### ISSUE TITLE
FDR adjusted p-values

### ISSUE THREAD

**Issue by motroy** [ChiLiubio/microeco#1]
Hi @ChiLiubio ,

Thanks for the nice R package! 
Just a quick question regarding the p-values obtained from the different analyses, are they FDR adjusted? Sorry if this has been mentioned in your documentation and I have missed it.

Regards,
Yair

**Comment by ChiLiubio** [comment]
Hi, @motroy , 
Currently, the p-values in trans_diff class are not adjusted for method lefse and random forest to get more prescreened taxa as many as possible. Thus, this setting without adjustment may help find some indicators which are not very significant but important in lefse or rf. We will consider to add the p adjustment as a parameter in trans_diff class. Thanks for your question!

Regards,
Chi
