### ISSUE TITLE
Write table from data$cal_spe_func(fungi_database = "FungalTraits")

### ISSUE THREAD

**Issue by vmcgimpsey** [ChiLiubio/microeco#101]
Hi,

I was trying to extract the data to share with colleagues using the following code: 
write.table(data$cal_spe_func(fungi_database = "FungalTraits"), file = "~path//soils microeco.csv")

A csv is created but it contains none of the functional information that is in the microtable, is there an alternative way to create a .csv with this data?

**Comment by ChiLiubio** [comment]
Hi,
Please use `data$res_spe_func`  to get the result. So the command should be:
```
data$cal_spe_func(fungi_database = "FungalTraits")
write.csv(data$res_spe_func, file = "soils_microeco.csv")
```
Please also see https://chiliubio.github.io/microeco_tutorial/intro.html#framework  for the data structure

**Comment by vmcgimpsey** [comment]
thanks, really great package!
