### ISSUE TITLE
cal_tax4fun: SILVA123

### ISSUE THREAD

**Issue by byjediaz** [ChiLiubio/microeco#102]
Hello Dear Chi Liu,

Please would kindly help me with this issue, working on R 4.1.3 I had the next issue when loading the SILVA 123 for  tax4fun analysis: 

t1$cal_tax4fun(folderReferenceData = "./SILVA123")

Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
In addition: Warning message:
In write.table(otu_file, file = output, append = TRUE, quote = FALSE,  :
  appending column names to file

Thanks in advance!

**Comment by ChiLiubio** [comment]
Hi,
Could you please save your t1 object and paste it here? See tutorial for saving data (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function). I am not sure where this error happened. So I need to repeat this error.

Chi

**Comment by byjediaz** [comment]
> Hi, Could you please save your t1 object and paste it here? See tutorial for saving data (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function). I am not sure where this error happened. So I need to repeat this error.
> 
> Chi

Hello Chi,
Once I read your reply pointing T1 object, it occurs to me something was wrong in the object, as I was doing an entire analysis using microeco, so I tried redoing the T1 and this time showed a different message and everything work out fine. 

> t1$cal_tax4fun(folderReferenceData = "./SILVA123")
The KO abundance result is stored in object$tax4fun_KO ...
The pathway abundance result is stored in object$tax4fun_path ...
Warning message:
In write.table(otu_file, file = output, append = TRUE, quote = FALSE,  :
  appending column names to file

*** Just one additional quick question, where do I get representative sequences for tax4fun 2 analysis?

Thanks for your help!
