### ISSUE TITLE
The function of cal_sum_links() does not exist

### ISSUE THREAD

**Issue by BelongChan** [ChiLiubio/microeco#107]
I cant use this function , the console showed that, "attemt to apply non-funcion". I checked the package, this function was not exist in the trans_network function.

**Comment by ChiLiubio** [comment]
Hi @BelongChan 
This function has been moved to package mecodev (https://github.com/ChiLiubio/mecodev) trans_netchord class. I think this part is not the core content for network analysis. If you do not think so, please feel free to tell me your idea or suggestion.

Chi
