### ISSUE TITLE
Error in tans_beta$new

### ISSUE THREAD

**Issue by JBL05** [ChiLiubio/microeco#108]
Can anyone help, plz?

> t1 <- trans_beta$new(dataset = dataset, group = "Reach", measure = "bray")
Error in initialize(...) : 
  Input measure should be one of beta_diversity distance in dataset !

**Comment by JBL05** [comment]
Problem fixed by calculate bet_diversity distance matrix before using function trans_beta, sorry!

**Comment by FreitasAndy** [comment]
Hi all.

I had the same problem here, but did not found the function to calculate the beta diversity matrix as you showed. 

Can anyone help me, please?

**Comment by FreitasAndy** [comment]
Just found here.

dataset$cal_betadiv(method = "bray")

**Comment by spencerlong1** [comment]
Hi, I am a little stuck on this point as well and was wondering if you had a bit more detail on how to prevent the error. After you use dataset$cal_betadiv(method = "bray") how do you then use the output, so that you then get to the point where trans_beta$new(dataset = dataset, group = "Reach", measure = "bray") will work?

**Comment by ChiLiubio** [comment]
Good question! trans_beta can use dataset$beta_diversity$bray matrix. So current logic is 1) `dataset$cal_betadiv(method = "bray")` can generate dataset$beta_diversity$bray 2) `t1 <- trans_beta$new(dataset = dataset, group = "Reach", measure = "bray")` can generate a t1 with bray in t1 in order for other operations calling bray matrix. To make the step simple, I will add a checking step in the function to automatically calculate bray if a microtable object is found without beta diversity matrix.

**Comment by spencerlong1** [comment]
Thanks Chi!
