### ISSUE TITLE
plot_bar with no "others"

### ISSUE THREAD

**Issue by Debora6991** [ChiLiubio/microeco#109]
I would like to use the plot_bar function in order to obtain a bar plot of my species. 
I created a microeco object in which I already have grouped In "others" some species And I will have something like:
Species1
Species 2
......
Species 12
Other_species

I tried to plot all my Species, 12 + Other_species (13 in total) , using this code

colourCount = length(row.names(mydata))  **#used to count how many different species are in my list, in order to obtain the number of colours I need if they are more than 12**
getPalette = colorRampPalette(brewer.pal(12, "Paired"))

t1_c <- trans_abund$new(dataset = dataset, taxrank = "Species", ntaxa=13)  
g1 <- t1_c$plot_bar(others_color = "grey70", legend_text_italic = FALSE, color_values=getPalette(colourCount))
g1 + theme_classic() + theme(axis.title.y = element_text(size = 18), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 

When plotting I obtain this
![image](https://user-images.githubusercontent.com/50614431/169836551-db6870ec-374b-4af7-9f7c-e11573ce675e.png)

How can I obtain a graph without "Others" being automatically created by the plot_bar function? Moreover I asked with the "ntaxa=13" to plot at least 13 Species, why the maximum of taxa plotted seems to be 10+ Others? 

Thanks for your help

**Comment by ChiLiubio** [comment]
Hi. If you wan to remove 'Others', please use parameter bar_type = "notfull". Because the default y axis is 100%, no Others will cause the inaccuracy in the total range. bar_type = "notfull" means only use the stacked taxa.

**Comment by ChiLiubio** [comment]
The taxa in the legend in too long to see. It is better to use tidy_taxonomy function to standarize the taxonomy table and rerun the cal_abund and trans_abund to get brief one.

**Comment by Debora6991** [comment]
I added bar_type = "notfull" and "Others" did disappear, but I always have in my plot one less species than expected. 
Here, for example, I should have 12 Species but I only have 11 in the plot (third and fourth bars are missing that 12th Species). 
![image](https://user-images.githubusercontent.com/50614431/169968895-486262c9-075a-473a-a8c7-8ee5a3d2cdd3.png)

Here's the code and the fact that the Species are indeed 12
![image](https://user-images.githubusercontent.com/50614431/169969356-5b988808-6251-4907-86b1-07845b0b35b7.png)
If the species are 17, the plot have 16, and so on.
![image](https://user-images.githubusercontent.com/50614431/169969717-0f0a46e9-ccf4-482a-893b-ab7eab86710e.png)

Another question: how can I add black borders to my bars? I tried with geom_bar() but I did not succeed.

**Comment by ChiLiubio** [comment]
Please first check t1_c$data_abund to see whether there are 12 taxa. If it is still not be solved, please save your C data object and send it to me to have a  try. The save usage is here (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function). Please paste the compressed zip file as the tutorial shows.

**Comment by Debora6991** [comment]
[dataset.zip](https://github.com/ChiLiubio/microeco/files/8762647/dataset.zip)
Here's the dataset.

**Comment by ChiLiubio** [comment]
The reason is there is a species with only "s__". It is filtered automaticlly in the analysis as no effective info in it.

**Comment by Debora6991** [comment]
How did I miss this?! Thanks for your help.
