### ISSUE TITLE
t1$cal_eigen() not working

### ISSUE THREAD

**Issue by ire1990** [ChiLiubio/microeco#11]
Hi,
first of all, thanks a lot for your work with this package!
I did the tutorial and now I am using my own dataset containing the abundance of 253 OTUs and I want to compare the networks between different forest types. Unfortunately, I only have 14 samples per forest type but anyway I managed to correctly create and visualize the networks in Gephi. 
However, when I try to do the correlation between the  eigengene of a module and the environmental variables, I only get two modules while in gephi I correclty see 9 modules.
I am pasting here the reproducible example:
`t1 <- trans_network$new(dataset = dataset, cal_cor = "base", taxa_level = "OTU", filter_thres = 0.0001, cor_method = "spearman")
t1$cal_eigen()
t2 <- trans_env$new(dataset = dataset, add_data = env_data_16S[, 4:11])
# calculate correlations
t2$cal_cor(add_abund_table = t1$res_eigen)
# plot the correlation heatmap
t2$plot_corr()`
do you know what could be the problem?

**Comment by ChiLiubio** [comment]
Hi,
I suggest you first check the res_eigen file in your trans_network object, like the operation t1$res_eigen. Please see the help document. The eigengene calculation can automatically filter the modules with nodes number < 3, as the operation of modules with too less nodes are meanlingless.
