### ISSUE TITLE
 trans_netchord

### ISSUE THREAD

**Issue by Hobgoblin8** [ChiLiubio/microeco#110]
Excuse me. I run the code and an error occurs:
data(sample_info_16S)
data(otu_table_16S)
data(taxonomy_table_16S)
dataset <- microtable$new(sample_table = sample_info_16S, otu_table = otu_table_16S, tax_table = taxonomy_table_16S)
dataset$tidy_dataset()
t1 <- trans_network$new(dataset = dataset, cal_cor = "WGCNA", taxa_level = "OTU", filter_thres = 0.0001, cor_method = "spearman")
t1$cal_network(p_thres = 0.01, COR_cut = 0.7)
test1 <- trans_netchord$new(dataset = t1, taxa_level = "Phylum")
Error in names(x) <- value : 
  'names' attribute [2] must be the same length as the vector [1]
How can I solve the problem? 
Look forward to your reply. Thank you very much.

**Comment by Hobgoblin8** [comment]
Thank you. How can I save it as " .pdf " or a vector graphic？

**Comment by ChiLiubio** [comment]
Sorry. I donot know the exact answer. Actually, I kown little about the javascript. So could you move this question to the chorddiag or D3 library github Issues? The maintainers of those projects should be more familiar on this issue. Thanks.

**Comment by Hobgoblin8** [comment]
Ok. Thank you very much.
Best regards!
