### ISSUE TITLE
Simpson Index and Inverse Simpson Index

### ISSUE THREAD

**Issue by alberjo296** [ChiLiubio/microeco#112]
Hi Chi,

I have a doubt about the trans_alpha function. I thought the Inverse of Simpson was calculated as 1/Simpson Index but the values don't show that. Isn't it?
Another doubt I have is: the Simpson Index shows higher diversity when is higher or lower? I have messed up.

Thank you so much in advance

**Comment by alberjo296** [comment]
I'm not sure what this index is calculating is the Simpson's diversity index or the Gini-Simpson index. Could you clarify it, please?

**Comment by ChiLiubio** [comment]
Hi @alberjo296 

The simpson and invsimpson are calculated based on the vegan::diversity function.
So you can find the details in the function help document:
![图片](https://user-images.githubusercontent.com/20815519/170636036-cf1cf653-63c9-47e7-a4de-b72e560dad14.png)
I will also add some descriptions in the cal_alphadiv function.
Thanks for your question.

Best,
Chi
