### ISSUE TITLE
Upload to bioconda?

### ISSUE THREAD

**Issue by wangzhichao1990** [ChiLiubio/microeco#113]
Hi, 
Do you have any plans to upload the microeco package to bioconda? I think it is convenient to use CONDA to manage the related dependent packages. What do you think?

**Comment by ChiLiubio** [comment]
Hi @wangzhichao1990 

Thank you for the great suggestion! I will think about it. There are at least two reasons I have not used conda to date. 1. I do not have enough time to manage this project. Actually, it is a challange now to maintain the microeco and file2meco packages with the increasing of functions :)  2. Based on the first reason, I think more users use PC to do those analysis. So I reduce the dependencies in the installation as many as possible. This is also one of design principles. After all, few can use all the functions. So I think it is better to install something for users when it is time to use it.
What is your email? I will talk with you in the future when it is time to do this.
Thanks.

Best,
Chi
