### ISSUE TITLE
Mantel tests

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#117]
Hello,
Thanks for all the last additions to the package!
I have three questions about the Mantel test in Microeco.
1) Doing this:
dataset_16S_bioenv$cal_mantel(use_measure = "bray")
dataset_16S_bioenv$res_mantel
I get the correlation of each variable with the community. But I also need the "global" Mantel statistic and its corresponding P-value (as explained in the Vegan help). How can I get these two values?
2) Are the environemntal variables normalized before the analysis? (I think this is important). In case that this is not done by default, can I do it within Microeco?
3) What taxa level is used by default? I need OTU/ASV. Just to confirm I am doing this OK.
Thanks!
Best regards,
jose

**Comment by ChiLiubio** [comment]
Hi @jamorillo 

1. I am not sure the meaning of 'global' Mantel statistic you said. So could you take a toy example?
2. Yes. All the factors have been scaled in the function.
3. The required format in Mantel is distance matrix, i.e. 'Bray-Curtis' in your microtable$beta_diversity. So I think it should comes from your OTU/ASV depending on your otu_table.

Best,
Chi

**Comment by jamorillo** [comment]
Hello, 
OK, perfect.
About the point 1, sometimes I have seen Mantel tests grouing all env variables in a single distance matrix. If I am not wrong, this is well explained in this web, in the last section "Mantel test output for all environmental parameters":
https://jkzorz.github.io/2019/07/08/mantel-test.html
But I can do that specific operation outside Microeco, it is not a problem.
Thanks!!
Best, 
jose
