### ISSUE TITLE
trans_venn

### ISSUE THREAD

**Issue by Hobgoblin8** [ChiLiubio/microeco#118]
Excuse me.

I run the code and an error occurs:
data(sample_info_16S)
data(otu_table_16S)
data(taxonomy_table_16S)
dataset <- microtable$new(sample_table = sample_info_16S, otu_table = otu_table_16S, tax_table = taxonomy_table_16S)
dataset1 <- dataset$merge_samples(use_group = "Group")
t1 <- trans_venn$new(dataset1, ratio = NULL)
t1$plot_venn()
tmp <- dataset$merge_samples(use_group = "Type")
tmp
t1 <- trans_venn$new(dataset = tmp)
t1$data_summary %<>% .[.[, 1] > 20, ]
t1$plot_bar()
Error: attempt to apply non-function

How can I solve the problem?
Look forward to your reply. Thank you very much.

**Comment by ChiLiubio** [comment]
Hi. Please update the package. This function is developed from v0.11.0.

**Comment by Hobgoblin8** [comment]
Thank you.
