### ISSUE TITLE
The results change when executing the code again

### ISSUE THREAD

**Issue by bfalco** [ChiLiubio/microeco#119]
Hi Chi,

I wanted to ask you again about the change that arises in the results when applying tests such as the MANOVA (the p-values change after each execution of the code) and the LDA scores in LEfSE (there are taxa that are reordered after executing the entire code again).

I have seen that the problem continues with the latest updates. I would like to know if you have found out what could be causing it and if you will be able to adjust the test to correctly execute each analysis.

Thank you very much.

**Comment by ChiLiubio** [comment]
Hi @bfalco 

Thanks. Those changeable p values and LDA scores come from the permutations, i.e. resampling in the analysis. It is also closely related with the data characteristics, such as sample size and feature variations. So it hard to say how to fix it. For MANOVA, trans_beta class call adonis2 function in vegan. Even you try to use the adonis2 function for MANOVA in vegan package, there will be a similar result. For lefse, it is pratical to use parameter nresam = 1 and boots = 1 to fix the trouble, meaning no resampling performed.

**Comment by bfalco** [comment]
Okay, thank you very much for the explanation. In some cases, it is curious to see how the p-values “dance” below and above alpha in the MANOVA.

Until next time.
