### ISSUE TITLE
feature request: cladogram, select different groups to show

### ISSUE THREAD

**Issue by nweerasu** [ChiLiubio/microeco#122]
Hello Chi,

Do you have an easy way to have the trans_func cladogram to load the full lefse analysis results but to select which groups to show on the tree? At the moment I have 8 group comparisons that are all important to show, but creates a crowded cladogram. My solution would be to add a parameter that filters in or out which groups to show on the cladogram, so I can do specific comparisons based off the full lefse result. 

If you'd like images or a dataset to detail my example, please let me know.

Thanks!
Nimalka

**Comment by ChiLiubio** [comment]
Hi Nimalka

An easy way is to change the Return file `res_diff` inside the object. Here is my toy example:
```
library(magrittr)
library(microeco)
data(dataset)
t1 <- trans_diff$new(dataset = dataset, method = "lefse", group = "Group")
# copy t1 for comparison
t2 <- clone(t1)
# delete 'IW' group in t2 result
t2$res_diff %<>% .[.$Group != "IW", ]
t2$plot_diff_cladogram(use_taxa_num = 100, use_feature_num = 30, select_show_labels = NULL)
t1$plot_diff_cladogram(use_taxa_num = 100, use_feature_num = 30, select_show_labels = NULL)
```
Is this what you need?

Chi

**Comment by nweerasu** [comment]
Hello!

Yes, I see how you are manipulating the res_diff table to select the group comparisons! Thank you!
I have attempted with my t2 object but now get the error:

t2$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 35,
                       alpha = 0.15,  clade_label_size = 1)

>Error in `[[<-.data.frame`(`*tmp*`, i, value = c("#1B9E77", "#D95F02",  : 
>  replacement has 8 rows, data has 3
>In addition: Warning message:
>Removed 6 rows containing missing values (geom_rect). 

Using the packages default 'dataset' does give me the right output, however, so I wonder if it is my dataset.
[dataset.rs.zip](https://github.com/ChiLiubio/microeco/files/9097494/dataset.rs.zip)


Thank you for your help!

**Comment by ChiLiubio** [comment]
Hi. Could you paste all your codes? Thus, I can repeat the error totally.

**Comment by nweerasu** [comment]
```
library(magrittr)
library(microeco)

t1 <- trans_diff$new(dataset.rs, method = "lefse", group = "Group", alpha = 0.05, lefse_subgroup = NULL)
# see t1$res_diff for the result

# copy t1 for comparison
t2 <- clone(t1) # <9 CEC

# delete unwanted comparisons
t2$res_diff %<>% .[.$Group == "<9_Low" | .$Group == "<9_Optimum", ]

# then use parameter select_show_labels to show
t2$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 35,
                       alpha = 0.15,
                       clade_label_size = 1)
```

**Comment by ChiLiubio** [comment]
Hi @nweerasu 

The error comes from the groups difference between changed res_diff$Group and the raw group inside the object, which is mainly designed to order groups with factor levels. Two ways can be used to sovle this. 
One is provide the group_order parameter to tell the program to select groups like this:
```
t2$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 30, alpha = 0.15, clade_label_size = 1, group_order = c("<9_Low", "<9_Optimum"))
```
The other is to update the package from github. I fix this by searching the groups in new res_diff to find whether they are same between this and the raw group order.

Chi

**Comment by nweerasu** [comment]
Hello @ChiLiubio 

Thank you! That solved the issue I was getting when modifying from res_diff. 
I notice now that after updating to 0.11.1, I still have a legend graphics error with the cladogram when I use all the samples in the t1 object. 

```
library(magrittr)
library(microeco)
library(RColorBrewer)

t1 <- trans_diff$new(dataset.rs, method = "lefse", group = "Group", alpha = 0.05, lefse_subgroup = NULL)
# see t1$res_diff for the result

# palette
pal <- brewer.pal(8, "Dark2")

# plot whole thing first
t1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 50,
                       alpha = 0.15, color = pal[c(1:6,8)],
                       clade_label_size = 1)
```
![clado_test](https://user-images.githubusercontent.com/18601221/179019876-336c852b-ede3-4234-9c01-27254ff22a50.png)


Interestingly, if I use a fewer number of features, e.g.

```
t1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 35,
                       alpha = 0.15, color = pal[c(1:6,8)],
                       clade_label_size = 1)
```

I get
>Error in `[[<-.data.frame`(`*tmp*`, i, value = c("#1B9E77", "#D95F02",  : 
>  replacement has 8 rows, data has 6
>In addition: Warning message:
>Removed 3 rows containing missing values (geom_rect).

Thank you again!

**Comment by nweerasu** [comment]
Ah, interesting. If I remove "10-13_Low" from the group_order, the figure comes out correctly.

```
t1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 50,
                       alpha = 0.15, color = pal[c(1:8)],
                       clade_label_size = 1, 
                       group_order = c("<9_Low", "<9_Optimum", 
                         "10-13_Optimum", "14-17_Low", "14-17_Optimum", 
                         ">18_Low", ">18_Optimum"))
``
![clado_test2](https://user-images.githubusercontent.com/18601221/179021621-49c5939f-117d-46ae-9184-7dc191a72788.png)
`

**Comment by ChiLiubio** [comment]
Sorry @nweerasu. I found I ignored the group filtering in the function, leading to the weird legend in the plot. In terms of the experience, the group without enriched feature in res_diff should not appear in the legend as it is meaningless. Now the group_order parameter in updated package can also be used to select part of groups instead of changing the res_diff.
Please update the package from github and try again.
```
# those commands have same outputs
t1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 50,
                       alpha = 0.15, color = pal[c(1:6,8)], clade_label_size = 1)
t1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 50,
                       alpha = 0.15, color = pal[c(1:8)], clade_label_size = 1, 
                       group_order = c("<9_Low", "<9_Optimum",  "10-13_Optimum", "14-17_Low", "14-17_Optimum", 
                         ">18_Low", ">18_Optimum"))
# use_feature_num = 35; only five groups are found in top LDA 35 features and are shown in the legend
t1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 35,
                       alpha = 0.15, color = pal[c(1:8)], clade_label_size = 1)
# to select groups to show, use group_order
t1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 50,
                       alpha = 0.15, color = pal[c(1:8)],
                       clade_label_size = 1, 
                       group_order = c("<9_Low", "<9_Optimum", "10-13_Optimum"))
```
Thanks very much for pointing out this bug.

Chi

**Comment by nweerasu** [comment]
Thanks very much for your work and responses, Chi!!
