### ISSUE TITLE
Genus names are keeping the full taxonomy in plots

### ISSUE THREAD

**Issue by FreitasAndy** [ChiLiubio/microeco#123]
I'm plotting heatmaps for genera in my dataset. The tutorial shows plots when it only appears the genera name (i.e. Azotobacter, Moraxella, etc.) but when I do it for my data the plots show the full taxonomy (Bacteria|Firmicutes|Bacilli|Bacillales|Bacillaceae...). How can I fix it to the plots show only the genera name?

My code:

#Heatmap of genera
t1 <- trans_abund$new(dataset = dataset, taxrank = "Genus", ntaxa = 20)
t1$plot_heatmap(facet = "Substrate", xtext_keep = FALSE, withmargin = FALSE)

**Comment by ChiLiubio** [comment]
Hi. I guess your taxonomic info is not standard (without prefix). Please try to run `tidy_taxonomy` like the following example. I remember there have been two similar issues. So you can also check them for more details.

```
library(magrittr)
library(microeco)
data(dataset)
dataset$tax_table %<>% tidy_taxonomy
# then rerun cal_abund
dataset$cal_abund()
# then rerun trans_abund
```
