### ISSUE TITLE
cal_autocor funtion

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#124]
Hello!
I am using cal_autocor(). What correlation method is using this function? Spearman, Pearson or other?
In the "help" of that function it is not specified, If I am not wrong.
Would be possible to use Spearman? (better for my data)
thanks!! 
PD: of course, I can use the external package if that optoin is not easy

**Comment by ChiLiubio** [comment]
Hi @jamorillo 
The function cal_autocor call GGally::ggpairs function to plot paired results. So you can pass parameters to GGally::ggpairs.
The following is an example to use Spearman with wrap function in GGally.
```
library(microeco)
data(dataset)
data(env_data_16S)
t1 <- trans_env$new(dataset = dataset, add_data = env_data_16S[, 4:8])
# correlation value use spearman in upper triangle
# for more info, see help in ?GGally::ggpairs
t1$cal_autocor(upper = list(continuous = wrap("cor", method= "spearman")))
```

**Comment by jamorillo** [comment]
Great, thank you!!
Regards,
Jose
