### ISSUE TITLE
Differential analysis on tax4fun2 results 

### ISSUE THREAD

**Issue by cdeschamps63** [ChiLiubio/microeco#127]
Hello, 

I have just performed differential analysis on my previous tax4fun2 results (not generated with microeco) and I obtained this : 
<img width="794" alt="Capture d’écran 2022-07-26 à 16 34 32" src="https://user-images.githubusercontent.com/101580346/181034600-303c4c58-99c7-4130-bbf8-6edf7971ce98.png">

Is it normal that for Metabolism or Carbohydrate metabolism there is three bars corresponding to the three group ? What does it means ? 

For me, a green bar can be described as "Starch and sucrose" is differentially more expressed in the Small group than in the other groups, am I wrong ? 

Thank you very much for your help,

Charlotte

**Comment by ChiLiubio** [comment]
Hi, @cdeschamps63 

Sorry for the delay. Could you provide the data and steps that generate this figure? I am not sure how this issue happens. Please upload the compressed data (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) or send it to me via email.

Chi

**Comment by cdeschamps63** [comment]
Thanks @ChiLiubio 

Here is my code: 
pathway <- read.csv("/Tax4Fun2/pathway_prediction.csv", sep=";")
ptw_desc <- read.csv("/Tax4Fun2_ReferenceData_v1/KEGG/ptw.txt", sep="\t")

func2 <- microtable$new(otu_table = pathway, 
                        tax_table = ptw_desc,
                        sample_table = t1$sample_table)
func2$tidy_dataset()
func2$tax_table %<>% tidy_taxonomy
func2$cal_abund()
print(func2)
diffab2 <- trans_abund$new(func2, taxrank = "level2", 
                           ntaxa=50, groupmean = "size")

plot1b <- trans_diff$new(dataset = func2,
                        method = "lefse", group = "size", 
                        alpha = 0.05, lefse_subgroup = NULL)

plotA <- plot1b$plot_diff_bar(threshold = 3, width = 0.8, use_number = 1:20,
                    group_order = c("Small", "Medium", "Large"), 
                    color_values = sizecolor, keep_prefix = FALSE )
plotA

I've send you the data via email. 

Thanks a lot,
Charlotte

**Comment by cdeschamps63** [comment]
Dear @ChiLiubio,

You can find attached my file. Thanks a lot for your support,

Regards,
Charlotte

**Comment by ChiLiubio** [comment]
Hi @cdeschamps63 
I did not find any attached data in the email. Maybe something goes wrong. Please try to send the data again to my email (liuchi0426@126.com).

**Comment by ChiLiubio** [comment]
The issue comes from the reverse levels in tax_table. The default levels used by cal_abund function is from high to low, i.e. from left of tax_table to the right. But the level1 in your tax_table is the lowest lineage level. So the final name of lineage in level2 and level3 will be wired (level1|level2) and incorrectly used in the following operations. The solution is to reverse the direction of calculation like `func2$cal_abund(select_cols = 3:1)`. Full steps I checked:
```
library(microeco)
library(magrittr)
load("dataset_func2.RData")
func2$tidy_dataset()
func2$cal_abund(select_cols = 3:1)

plot1b <- trans_diff$new(dataset = func2, method = "lefse", group = "size", alpha = 0.05, lefse_subgroup = NULL)
plot1b$plot_diff_bar(threshold = 3, width = 0.8, use_number = 1:20, group_order = c("Small", "Medium", "Large"), keep_prefix = FALSE )
```

Best,
Chi

**Comment by cdeschamps63** [comment]
Thank you so much @ChiLiubio this have solved my problem !
