### ISSUE TITLE
ytext_size isn't working

### ISSUE THREAD

**Issue by RafaelAngelakopoulos** [ChiLiubio/microeco#128]
Hello all,

I'm trying to increase the size of the yaxis but it isn't working. While  xtext_size is working fine.

Here is the code that i'm using:

t1$plot_bar(others_color = "grey70",facet = "Day",facet2="Method", xtext_keep = T,legend_text_italic = T,
            xtext_size = 22, strip_text = 20,xtext_type_hor = '45',ytitle_size = 40, ytext_size=22)+
  theme(plot.margin = unit(c(0.1, 0, 0, 5), "cm"))+theme(legend.key.size = unit(1, 'cm'))+
  theme(legend.text = element_text(size = 16, face = "bold"))

Thank you,
Rafael

**Comment by ChiLiubio** [comment]
Hi @RafaelAngelakopoulos 

Currently, the size of the yaxis text is not considered in the parameter. So you can change it with theme additionally like:
```
t1$plot_bar(others_color = "grey70",facet = "Day",facet2="Method", xtext_keep = T,legend_text_italic = T,
xtext_size = 22, strip_text = 20,xtext_type_hor = '45',ytitle_size = 40)+
theme(plot.margin = unit(c(0.1, 0, 0, 5), "cm"))+theme(legend.key.size = unit(1, 'cm'))+
theme(legend.text = element_text(size = 16, face = "bold")) +
theme(axis.text.y = element_text(size = 22))
```

Chi

**Comment by RafaelAngelakopoulos** [comment]
Thank you very mych for your reply!!

Have a nice day
