### ISSUE TITLE
How to update FAPROTAX dataset? 

### ISSUE THREAD

**Issue by milanvarsadiya** [ChiLiubio/microeco#13]
I would like to update the database of FAPROTAX, by default microeco package use FAPROTAX 1.2.1 but a more recent version is also available (FAPROTAX 1.2.4). I would like to have results from a newer version of FAPROTAX, how am I suppose to do that? 

And I have another issue when I use bacteria and fungi OTU tables together (merged both OTU tables), I am able to assign an only bacterial function to OTU level but not the fungal one. Using individually, I am able to assign functions to each kingdom but not together. 

Thanks for creating such a wonderful and really really excellent pacakge.

**Comment by ChiLiubio** [comment]
Hi.
Do you mean the FAPROTAX database in the function trans_func$cal_spe_func() ? If yes, I think the best way is we parse the current FAPROTAX 1.2.4 version and update the underlying database inside the package. Because this function invoke a transformed database for the assignment, not the raw FAPROTAX database. It is a litter tricky to do this step for users who are not familar with the chunk of code.

Generally, the OTU/ASV table are for either prokaryotes or fungi. So to make this analysis simple, our initial idea is to judge the type of data into prokaryotes or fungi automatically according to the Kingdom data in taxonomy table. This is reasonable in terms of the databse call and results management. The best solution I think is to run the analysis individually as you did with the change of "for_what" object in trans_func object. Please see the 'Return' in the trans_func$new help document and try to change your_trans_func_object$for_what for the analysis. Then merge two result tables together manually.

Thanks for your appreciation.
Chi

**Comment by milanvarsadiya** [comment]
Since I have several questions, I am replying via email.

Thanks, Chi for getting back so promptly. And yes, I meant the FAPROTAX
database in the the function trans_func$cal_spe_func(). I would really
appreciate it if you can update this new version (FAPROTAX 1.2.4) in your
package.

I can completely understand using kingdom-level taxonomy to identified the
function individually. I will try according to your suggestion though I
have a question regarding fungal functional annotation. Are you using the
latest updated database for this annotation? Here this article is just
published (https://doi.org/10.1007/s13225-020-00466-2) about the fungal
lifestyle. I am wondering if it is possible to use this database for fungal
lifestyle annotation.

I am also having a problem when subsetting the taxonomy or mapping file
from the R6 object. Whenever I use "%<>%", as per suggestion, I am not able
to subset anything. Is this function part of another package?

How to use trans_network to plot graphs via graph package. Is there a way
to extract the network object and plot/visualize it through Igraph?

Is there any way to change the correlation method used for network
construction? There is an option for "base", "WGCNA" and "SparCC", but I
would like to use another method from a package like Hmisc. If not then, is
it possible to convert network objects created via Igraph (separately) and
convert to tans-network for further use in microeco package?

Excuse me for all these queries. I have spent the whole last week working
with microeco, your package is really intuitive.

I really appreciate your time and suggestions.

Thank you

Sincerely
Milan

**Comment by ChiLiubio** [comment]
Hi, @milanvarsadiya 

thanks for providing the new valuable fungi database. I will update the prokaryotes and fungi databases in recent days. 

The pipe operator "%<>%" is in magrittr package. Please install and load the package and try again.

Please see the help document of trans_network class. In the 'Return' part of cal_network(), you can see 'res_network'. You can use this your_trans_network_object$res_network to do anything you want with igraph and other packages.

You can use other method to get the correlation matrix and p value matrix and assign them in the res_cor_p list in trans_network object to do further analysis. Please check the help document of trans_network$new. This is a very interesting operation I think. Indeed, the flexibility we said in the design of this package partly comes from this type of operation.

Please feel free to tell me if you think what I write is not clear.

Best
Chi

**Comment by milanvarsadiya** [comment]
Thank you, Chi,

It's indeed helpful and now everything is clear. I will write you in case I
will have any problems, but for now everything is clear to me.

Best regards,
Milan

**Comment by milanvarsadiya** [comment]
Hello Chi,

Sorry to bother you again, but I found some strange results for the Zi-Pi
plot. I have been using the following to get Z and P value from the network
which is totally different when I calculate Z and P values by the
cal_node_type () function via the microeco package. The code I am using is
based on this article (
https://www.nature.com/articles/s41598-018-27172-z#Sec16).

Am I making any mistake here?

*network1=network_object*






























*seqdeg=degree(network1)Nnodes=length(seqdeg)Z=seqdegZ[]=0P=ZWtc=fastgreedy.community(network1)Membership=membership(Wtc)Seq=seq(1:Nnodes)for(i
in 1:Nnodes){  L=Membership==Membership[i]
neighbs=neighbors(network1,i)                 Kis=sum(L[neighbs])  SUM=0
SUMsq=0   SUMP=0  Miv=Seq[L]  for(j in 1:sum(L)){
neighbsj=neighbors(network1,Miv[j])    Kjs=sum(L[neighbsj])    SUM=SUM+Kjs
  SUMsq=SUMsq+Kjs^2  }
Z[i]=(Kis-SUM/sum(L))/sqrt(SUMsq/sum(L)-(SUM/sum(L))^2)
if(Kis-SUM/sum(L)==0){Z[i]=0}  for(k in 1:max(Membership)){
Lp=Membership==k    Kisp=sum(Lp[neighbs])    SUMP=SUMP+(Kisp/seqdeg[i])^2}
P[i]=1-SUMP}*

*attribute_table=data.frame(cbind(degree=seqdeg,module=Membership,Pi=P,Zi=Z))*

Thank you once again.

Best,
Milan

**Comment by ChiLiubio** [comment]
Hi, Milan

Did you use the same network to calculate Pi and Zi? I suggest you check some details, including network construction parameters and modules classification. It is not easy to find out which step affects the final results.

Chi

**Comment by milanvarsadiya** [comment]
Hello Chi,

Thanks, I have been using the same network parameters to calculate zipi
plot.

Best,
Milan

**Comment by ChiLiubio** [comment]
Hi, @milanvarsadiya 

Now in the github, the FAPROTAX  database has been updated to V1.2.4. The FungalTraits database has also been added in the package. Please see the parameter of cal_spe_func function in trans_func. Now, FUNGuild and FungalTraits are both available. Feel free to tell me if this part is not clear.

Chi

**Comment by milanvarsadiya** [comment]
Thank you, Chi,

It's really helpful. I will surely let you know in case I will have any
doubt.

And thank you again for updating the dataset.

Best,
Milan
