### ISSUE TITLE
dbRDA not plotting?

### ISSUE THREAD

**Issue by NataliHB** [ChiLiubio/microeco#130]
Hi Chi,

I hope you are okay! I am trying to re-run some analyses after I updated microeco and I am struggling with the dbRDA graph (which I was able to get before), as it doesn't display the samples. 

> t1$cal_ordination(method = "dbRDA", use_measure = "bray")
Use bray in dataset$beta_diversity for dbRDA ...
The original ordination result is stored in object$res_ordination ...
The R2 is stored in object$res_ordination_R2 ...
The terms anova result is stored in object$res_ordination_terms ...
The axis anova result is stored in object$res_ordination_axis ...
> t1$trans_ordination(adjust_arrow_length = TRUE)
The result list is stored in object$res_ordination_trans ...
Warning messages:
1: In scrs$biplot <- scores(res_ordination, choices = c(1, 2), "bp",  :
  Coercing LHS to a list
2: In Ops.factor(ref[, 1], 2) : ‘^’ not meaningful for factors
3: In Ops.factor(ref[, 2], 2) : ‘^’ not meaningful for factors
> t1$plot_ordination(plot_color = "Well")
Warning messages:
1: Removed 11 rows containing missing values (geom_segment). 
2: Removed 11 rows containing missing values (geom_text_repel). 

<img width="651" alt="Screenshot 2022-08-04 at 00 52 07" src="https://user-images.githubusercontent.com/50379650/182733570-b5d6b0b3-12b7-47d9-af24-7bc54366e3df.png">

This is what I get, have you encountered this issue before? Any help is hugely appreciated!

Cheers,
Natali

**Comment by ChiLiubio** [comment]
Hi Natali,

Could you please send me your data to reproduce the plot? I need to check how this happened step by step. Please both save your microtable object and t1 object and compress them (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function). You can paste the data here or send to me via email (liuchi0426@126.com).

Chi

**Comment by jarioksa** [comment]
Please note that `dbRDA` only finds one kind of scores: those for which you have calculated dissimilarities. Normally these are row scores that correspond to sites, but in your graph you seem to have variables. Is that `dbRDA` or normal `RDA`? In **vegan** you can add the missing scores (usually columns and corresponding species) with function `sppscores<-`, but I have no idea how to do that in **microeco**. Anyway, if you have `dbRDA`, it is expected to have just one kind of scores.
