### ISSUE TITLE
problem with alpha diversity calculation

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#133]
Hi, I have error while doing alpa diversity calculation,

> t1$cal_diff(method = "anova", anova_set = "Host_taxa")
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels

I use the latest version of microeco. I know the factor is having more than two levels. It is working for beta diversity calculation. 

please let me know if you have idea on it.

**Comment by apoosakkannu** [comment]
I just found out the problem occur while calculating alpha with PD=TRUE.

**Comment by apoosakkannu** [comment]
The problem is not only with anova. It is also happening when i use KW method.

**Comment by ChiLiubio** [comment]
Could you please save your microtable data using this way (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and compress and paste it here? Also please paste your scripts that I can use to reproduce your issue. I am not sure how this problem happened.

**Comment by apoosakkannu** [comment]
Thanks, please find the attached files as mentioned. 
[bird_bat.rmd.zip](https://github.com/ChiLiubio/microeco/files/9358329/bird_bat.rmd.zip)
[dataset.rdata.zip](https://github.com/ChiLiubio/microeco/files/9358330/dataset.rdata.zip)

I have also attached my scripts as rmd file in which you can see the last script for subsample "Mallard" samples end up in error.

**Comment by apoosakkannu** [comment]
Hi, this one also small problem with space in the sample name resulted.
