### ISSUE TITLE
error_Microeco : # plot the functional redundancy of network modules

### ISSUE THREAD

**Issue by lepiotaproceta** [ChiLiubio/microeco#134]
Dear all, 
I have an issue when i am using the Funguild features in the updated "microeco" package. Which is generally amazing. Regardsless, up until this point i havent had any problems. I run into the error specifically when i try to use plot_spe_func_perc. I dont deviate from the tutorial, beside changing the micro_table to my own data. Both the function is in t2 and and the res_spe_func_perc exist in the data frame. I worry that the script somehow overwrites the sample_table and thereby cant recognise the sample id creating the following error:

# plot the functional redundancy of network modules
> t2$plot_spe_func_perc(select_samples = paste0("M", 1:10))

**Error in t2$plot_spe_func_perc(select_samples = paste0("M", 1:10)) : 
  unused argument (select_samples = paste0("M", 1:10))**

**Comment by ChiLiubio** [comment]
Hi. 

The new version deprecated the parameter select_samples as the whole workflow is restructured to reduce the redundancy. Please see the trans_comm function of trans_network class to understand how the module info is converted to a sample-like table and used in the trans_func class.

Chi

**Comment by lepiotaproceta** [comment]
Hej, 

Yes i do understand! However i still run into the same bug, without using the select_sample function ;s. to me it looks like the script up until the plotting point, all the data, functions, modules have been created. Do you have an idea/script that could solve this issue?

thanks,

**Comment by ChiLiubio** [comment]
Could you provide a complete example to me to reproduce your issue? Thus, I can check it step by step. I am not sure what is the detailed problem and how this happened.

**Comment by lepiotaproceta** [comment]
hej, the problem arises when i follow the tutorial exactly step by step, as described. 

You can see the image attached: 
![problem_funguild_1](https://user-images.githubusercontent.com/111376283/187250170-77648b4d-34d8-476e-a037-ad9cfb3e73c3.PNG)

all objects have been created successfully.

**Comment by ChiLiubio** [comment]
Sorry. In v0.11.0, the parameter select_samples was replaced by parameter order_x. I forgot this before. I will update it soon. Please try this command:
```
t2$plot_spe_func_perc(order_x = paste0("M", 1:10))
```
Thanks very much for your issue!

Chi

**Comment by lepiotaproceta** [comment]
Hej Chi, 
Thank you so much, i finally was able to plot the modules using the function you provided ! 
I noticed that when using a microtable it somehow overwrites the sample table already provided. 
In my case: 

![image](https://user-images.githubusercontent.com/111376283/187534587-bd18c125-29ec-40f5-acdd-15d20fe8fac4.png)

However, i do have a sample_table in the microtable used, and it consist of 126 samples, so im a bit confused why it overwrites it and gives me : 
![image](https://user-images.githubusercontent.com/111376283/187534811-7119c5a3-08b8-432e-9f21-49a1f638e4b1.png)

Thanks for all your hard work, and fast replies,
cheers!

**Comment by ChiLiubio** [comment]
Hi. The sample names are Network Modules, not the names in sample_table that have been used. They are totally different. It is impossible to use sample names as module names. So the function create a simple one automatically.
