### ISSUE TITLE
saving files from an object

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#136]
Hi, I wonder could it be possible to save OTU, Taxanomy and meta files from an object. I could not find any tutorial on it! Please let me know if it is possible!

**Comment by ChiLiubio** [comment]
Hi. Do you mean save microtable$otu_table, microtable$tax_table and microtable$sample_table like this:
```
library(microeco)
data(dataset)
write.csv(dataset$otu_table, "otu_table.csv")
write.csv(dataset$tax_table, "tax_table.csv")
write.csv(dataset$sample_table, "sample_table.csv")
```

**Comment by apoosakkannu** [comment]
Yes it is!

**Comment by ChiLiubio** [comment]
Please use write.tree function from ape package.

**Comment by apoosakkannu** [comment]
Hi, i tried following,
write.tree(dataset$OTU_tree, file= "tree_decontam_all.tre", append= FALSE, digits = 10, tree.names = FALSE)

it says phy has no tree. any correction pls?
