### ISSUE TITLE
plot_alpha

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#138]
Hi, I am following  your tutorial for the plotting. 

t1 <- trans_alpha$new(dataset = dataset, group = "Host_taxa")
t1$cal_diff(method = "anova", anova_set = "Host_taxa")

t1$plot_alpha(pair_compare = TRUE, measure = "Chao1", shape = "Host_taxa")

The above plotting just give the plot with out any significant code. 

![image](https://user-images.githubusercontent.com/50707302/186128790-66fec17e-305c-4956-b6d6-40f826fca442.png)

**Comment by ChiLiubio** [comment]
Hi.
Which version of the microeco package are you using? The parameter "pair_compare" is deprecated in the current version.
Please see the tutorial (https://chiliubio.github.io/microeco_tutorial/) and help document with command `?trans_alpha`

**Comment by apoosakkannu** [comment]
Thanks. i am using the latest version 0.11.0.

**Comment by apoosakkannu** [comment]
Hi, when i plot the alpha diversity indices for a specific factor, i get extended line for the significant code. Please check the attached picture. I am getting this for only a specific factor. Good you give me a pointer where it is gong wrong?

#creat the trans alpha object for the gender analysis
t4 <- trans_alpha$new(dataset = age, group = "Age")
t4$cal_diff(method = "KW")


#plot the gender alpha results
g3 <- t4$plot_alpha(measure = "Chao1", xtext_size = 15)
g4 <- t4$plot_alpha(measure = "Shannon", xtext_size = 15)

print(g3)
print(g4)



![image](https://user-images.githubusercontent.com/50707302/190478773-7f630c98-2212-44dc-ad94-22e5c053fc6e.png)

![image](https://user-images.githubusercontent.com/50707302/190478809-9ace861a-1b00-4ee2-b2ef-af98ea733cf0.png)
