### ISSUE TITLE
cal_cor use_data error

### ISSUE THREAD

**Issue by spencerlong1** [ChiLiubio/microeco#139]
Hi!

I am having some problems with cal_cor with environmental data. I have a simple micro-table object with normalised (VST transformed) count data, and am following the tutorial, but every time I try and perform the following commands I get an error:

I have simple microtable class object created like this, as with for all other analysis:
microtable_16S_all <- microtable$new(sample_table = sample_info_16S, otu_table = count_tab_16S, tax_table = tax_tab_16S)
microtable_16S_all$tidy_dataset()

Then I perform this:

env_microtable_16S_all <- trans_env$new(dataset = microtable_16S_all, env_cols = 15:20)
env_microtable_16S_all$cal_cor(use_data = "family", p_adjust_method = "fdr")

and get the following:
Error in env_microtable_16S_all$cal_cor(use_data = "family", p_adjust_method = "fdr") : 
  Unknown use_data parameter provided!

It is worth noting that my taxa levels are (not capitalised): domain, phylum, class, order, family, genus, species. 

Preferably I would like to do this at the "family" level, but "Genus", "genus" or any of the above names aren't working either.

Do you know why this may be? all the other trans_env functions on the tutorial have been fine with the same data, including specifically at family level. this also happens when I don't use VST transformed count data, but I don't think that should matter anyway. 

Thanks :)

Spencer

**Comment by ChiLiubio** [comment]
Hi.
Please try to run cal_abund function to get the taxa abundance at each level:
```
microtable_16S_all$cal_abund()
env_microtable_16S_all <- trans_env$new(dataset = microtable_16S_all, env_cols = 15:20)
env_microtable_16S_all$cal_cor(use_data = "family", p_adjust_method = "fdr")
```
Otherwise, the function can not find the abundance at your 'family' level.

Chi

**Comment by ChiLiubio** [comment]
In the next update, I will add a step to automatically calculate abundance in cal_cor function if taxonomic abundance is not found in the object.

**Comment by spencerlong1** [comment]
Great, that works perfectly now. I did forget about the cal_abund step. Thanks Chi!
