### ISSUE TITLE
importing QIIME2 data to Microeco

### ISSUE THREAD

**Issue by mvtejesvi** [ChiLiubio/microeco#141]
hi,

I have tried your package and seems very good. I would like to try my own data analyzed using qiime2. How can I do that? I could not find any useful information to import the data. 

Thanks in advance for your valuable help!

Best wishes

TJ

**Comment by ChiLiubio** [comment]
Hi.

You can import your data according to the required data format in microtable object. Please see the help document with `?microtable`. You can also import data with file2meco package (https://chiliubio.github.io/microeco_tutorial/file2meco-package.html) if the data comes from some specific tools.

Best,
Chi
