### ISSUE TITLE
trans_diff$new - all taxa problem

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#144]
Hi, I am getting the following error for all taxa, but it is working for single taxa level,
> t4 <- trans_diff$new(dataset = dataset, method = "KW_dunn", group = "Host_taxa", taxa_level = "all")
Error in if (z < 0) { : missing value where TRUE/FALSE needed

any possible to overcome this problem?

**Comment by ChiLiubio** [comment]
Hi. I am not sure where this error happend. Could you please send me your data to check it? Please save the data using this way (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function).

**Comment by apoosakkannu** [comment]
[
[dataset.rdata.zip](https://github.com/ChiLiubio/microeco/files/9563166/dataset.rdata.zip)

**Comment by ChiLiubio** [comment]
Hi. The reason is the same abundance of all the samples in the Kingdom level. I will fix the bug. To solve this temporarily, please try this.
```
dataset$taxa_abund$Kingdom <- NULL
t4 <- trans_diff$new(dataset = dataset, method = "KW_dunn", group = "Host_taxa", taxa_level = "all")
```
