### ISSUE TITLE
Lefse plot_diff_abund() tidy taxa order

### ISSUE THREAD

**Issue by Debora6991** [ChiLiubio/microeco#145]
Hello,
I have obtained a plot of the abundance of biomarkers detected by LEfSe.

![image](https://user-images.githubusercontent.com/50614431/189843263-86829888-9525-4e8e-b57c-ecfbb27c061b.png)

Do you think it is possible to order the y-axis following a taxonomic order? 
I would like to have all taxonomic orders of the same Phylum close to each other and in the canonical order: Phylum, class, order, family ecc... The only solution I was able to think of is that of extrapolating the res_diff and res_abund matrices and create a new plot with those. Is there a more direct way to obtain the ordered plot?

**Comment by ChiLiubio** [comment]
Hi. Yes. Your solution is feasible. Currently, there is no parameter to control the orders by the taxonomic levels. The current orders are sorted by the LDA scores to keep in line with the LDA bar plot.
