### ISSUE TITLE
FungalTraits

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#146]
Hello!
I am trying to use FungalTraits through the package Microeco. Thanks for implementing this. I have 3 (I hope) simple questions:
1) Based on the tutorial, I don’t know how to obtain the specific trait for each ASV. Would it be possible to generate a table (or data frame) containing that information? For example: ASVs vs primary life style, etc.
2) In the FungalTraits paper they mentioned two methods to operate in order to get the traits: a) using taxonomy at genus level, b) Species Hypothesis level (UNITE´s SH). What way is using Microeco?
3) What version of FungalTraits is in the current version of Microeco?
Thanks!
jose

**Comment by ChiLiubio** [comment]
Hi.
1. The return res_spe_func in your trans_func object is the result. 
2. At Genus level
3. FungalTraits_1.2_ver_16Dec_2020V.1.2. If you find a update, please feel free to tell me. Thanks.

Chi

**Comment by jamorillo** [comment]
Hello, 
Thanks, very useful! 
I can´t find a newer version, I will let you know in case.
cheers,
jose
