### ISSUE TITLE
question

### ISSUE THREAD

**Issue by sheyong111** [ChiLiubio/microeco#147]
With a sample size of 89, Microeco kept running crashes

**Comment by ChiLiubio** [comment]
Could you please provide more information?

**Comment by sheyong111** [comment]
I want a 16s data about 89 sample, it was wrong when we calculated relative abundance using microeco,R crashed
,it recover nomal after I use 16s data for a 50 sample

**Comment by sheyong111** [comment]
I have a 16s data about 89 sample, it was wrong when we calculated relative abundance using microeco,R crashed
,it recover nomal after I use 16s data for a 50 sample

**Comment by sheyong111** [comment]
this is dataset
















At 2022-09-22 10:09:40, "Chi Liu" ***@***.***> wrote:

Could you please provide more information?

**Comment by sheyong111** [comment]
There was a problem with the sample data name yesterday,I resend the dataset.












At 2022-09-22 18:23:51, "Chi Liu" ***@***.***> wrote:

So could you send me your dataset to have a look?

**Comment by sheyong111** [comment]
Forgot to add an attachment










At 2022-09-22 18:23:51, "Chi Liu" ***@***.***> wrote:

So could you send me your dataset to have a look?

**Comment by sheyong111** [comment]
How did you see it?

**Comment by ChiLiubio** [comment]
I cannot find the data. Please upload the compressed zip format data.

**Comment by sheyong111** [comment]
Could you see the dataset?












At 2022-09-24 07:15:19, "Chi Liu" ***@***.***> wrote:

I cannot find the data. Please upload the compressed zip format data.

**Comment by ChiLiubio** [comment]
No. Can you send the data to my email (liuchi0426@126.com)?

**Comment by ChiLiubio** [comment]
Please provide the R steps that I can use to totally reproduce your issue.

**Comment by ChiLiubio** [comment]
I have got the data. Please provide the R steps that I can use to totally reproduce your issue.

**Comment by ChiLiubio** [comment]
I run all the codes successfuly and donot find any question. I also checked all the samples.

**Comment by ChiLiubio** [comment]
Yes. It is also ok to check the new steps. Could you provide more infomation about how your running goes wrong?

**Comment by sheyong111** [comment]
I found the script didn't work in server, but it was normal to be local to my computer
















在 2022-10-05 16:37:48，"Chi Liu" ***@***.***> 写道：

Closed #147 as completed.
