### ISSUE TITLE
issue in alpha diversity plot significance 

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#148]
Hi, i have a problem when plotting the alpha diversity with extended significance line beyond the two levels. 

![image](https://user-images.githubusercontent.com/50707302/191698707-4e4038a0-d817-4d23-85de-687187bbdd5d.png)

i have used the following dataset and code,

#creat the trans alpha object for the age analysis
t4 <- trans_alpha$new(dataset = age, group = "Age")
t4$cal_diff(method = "KW")

#plot the age alpha results
g3 <- t4$plot_alpha(measure = "Chao1", xtext_size = 15)
g4 <- t4$plot_alpha(measure = "Shannon", xtext_size = 15)

print(g3)
print(g4)

[age.rdata.zip](https://github.com/ChiLiubio/microeco/files/9623961/age.rdata.zip)

**Comment by ChiLiubio** [comment]
Hi. The Age in sample_table is factor type with three levels, but only have two elements. Please check it with `unique(age$sample_table$Age)`. Reassign factors can solve the issue.

```
library(microeco)
library(magrittr)
age$sample_table$Age %<>% as.character %>% as.factor

#creat the trans alpha object for the age analysis
t4 <- trans_alpha$new(dataset = age, group = "Age")
t4$cal_diff(method = "KW")

#plot the age alpha results
g3 <- t4$plot_alpha(measure = "Chao1", xtext_size = 15)
g4 <- t4$plot_alpha(measure = "Shannon", xtext_size = 15)

g3
g4
```

**Comment by apoosakkannu** [comment]
thanks, it worked!
