### ISSUE TITLE
problem with alpha diversity calculation

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#149]
Hi, I have problem when i do alpha diversity analysis with PD=True. but no PD calculated. 

#calculate alpha diversity
dataset1$cal_alphadiv(PD = TRUE)

  
#calculate beta diversity
dataset1$cal_betadiv(unifrac = TRUE)

#calculate the abundance
dataset1$cal_abund()

I have attached the dataset for your reference. 

[dataset1.rdata.zip](https://github.com/ChiLiubio/microeco/files/9632077/dataset1.rdata.zip)

**Comment by ChiLiubio** [comment]
Hi. This is the first time I run into this type of issue. I have checked your data and the steps, but not found how this issue generated. I will spend more time on it. So could you provide more information on this to help me check the data, such as how your phylogenetic tree is made?

**Comment by apoosakkannu** [comment]
Thanks. I used phylogenetic tree in mothur using representative sequences.
The following is the code for mother.


mothur > dist.seqs(fasta=final.fasta, output=lt)
mothur > clearcut(phylip=final.phylip.dist)



Actually same phylogenetic tree working for when I do subset.

**Comment by ChiLiubio** [comment]
Sorry. I am still confused about how this happened.

**Comment by apoosakkannu** [comment]
Thanks. I wonder if there is any other way i could do weighted and
unweighted unifrac distances for this dataset?

**Comment by ChiLiubio** [comment]
Could you please try to do those in QIIME or QIIME2? Or just use representative sequences to make a phylogenetic tree in QIIME or QIIME2 instead of mothur and try again to use above R codes to run these metrics?

**Comment by apoosakkannu** [comment]
I found that edge.length in phylo tree has a "NaN". I think it should be zero? I am not sure if that is a problem here? if so any possibility to overcome?
[dataset1.rdata.zip](https://github.com/ChiLiubio/microeco/files/9632077/dataset1.rdata.zip)

**Comment by apoosakkannu** [comment]
I created the tree with qiime2 and it worked now. Thanks.
