### ISSUE TITLE
trans_abund class, entire taxonomy string being applied to plot labels

### ISSUE THREAD

**Issue by benedil** [ChiLiubio/microeco#15]
Hi, I'm really enjoying working with your package, thanks for all your work.

All my plots generated with trans_abund are including ALL tax info for each species in the plot labels, in the format "Bacteria|Proteobacteria|Zetaproteobacteria|Mariprofundales|Mariprofundaceae|Mariprofundus", for example.  I can not find any way to affect this output.

My data were generated by mothur so my tax_table does not have the prefixes associated with each taxon (c__, p__, etc).  Other than the prefixes, my table follows the format of the example data (cols are taxlevels, rows are OTUs).

Am I going to need to convert my mothur outputs to QIIME to make this work?

**Comment by ChiLiubio** [comment]
Hi, thanks for your appreciation.

It is easy to convert your tax_table to a standard format with prefix which is generally necessary in many methods of the package. The input file formats have no matter with the bioinformatic tools. The inconsistency  of taxonomic format is common. You can also see the Issues-"Error: id variables not found in data: Taxonomy". Now I also paste the simplified codes to add prefix.

Solution:
test <- dataset$tax_table
for(i in 1:ncol(test)){
prefix <- paste0(tolower(substr(colnames(test)[i], 1, 1)), "__")
test[, i] <- gsub(prefix, "", test[, i])
test[,i] <- paste0(prefix, test[, i])
}
dataset$tax_table <- test

If not work, feel free to tell me.

Chi

**Comment by benedil** [comment]
Thank you for your reply. This solution worked and my plot labels are fixed!
