### ISSUE TITLE
block desings (random effects) in PERMANOVAs

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#156]
Hello, 
I am working in an experiment with several experimental blocks (different soil plots were we replicate the same treatments). 
I therefore need to include the term “block” in the PERMANOVA models (like a random effect, not like fix factor). Following the help command of adonis2 function in R, it seems the term “strata” is what I need. 
What about Microeco, is the term “group” in trans_beta$cal_manova passed to "strata" in adonis2?
I tried but apparently the function trans_beta$cal_manova is ignoring whatever I specify in “group”.
What is the best way to consider these blocks design in permanovas?
Thanks!!
jose

**Comment by jamorillo** [comment]
Hello again, 
I think I found the solution myself, just want to confirm this is not wrong. 
Apparently, I can pass adonis2 parameters to the function cal_manova (microeco). For example:

beta_Bray_16S$cal_manova(
  manova_set = "Site*N*P",
  by = "terms",
  strata = dataset_16S$sample_table$Block,
  permutations = 999
)
where:
"beta_Bray_16S" is a microeco object
"by" and "strata" are parameters of vegan::adonis2 function
and "dataset_16S$sample_table$Block" is the metadata column of my microeco object that contains the block factor.

Correct? Thanks, your suggestions are very appreciated.
jose

**Comment by ChiLiubio** [comment]
Hi jose,

Yes. You are right. All the parameters not found by cal_manova function will pass to adonis2 function. Please use `beta_Bray_16S$res_manova` to check your result.

Best,
Chi

**Comment by jamorillo** [comment]
Hello Chi, 
Thanks for implementing the function in this way. It is very flexible. Great.
Best, 
jose
