### ISSUE TITLE
trans_alpha$plot_alpha

### ISSUE THREAD

**Issue by yezi0721** [ChiLiubio/microeco#158]
no significance show on the figure.
I use the following code:
t_alpha_CL$cal_diff(method = "anova")
t_alpha_CL$plot_alpha(measure = "Simpson")
t_alpha_CL$plot_alpha(measure = "Simpson", order_x_mean = TRUE)

t_alpha_CL$plot_alpha( measure = "Simpson", shape = "SARS_Concentration_Level", pair_compare = TRUE)

it seems like the pair_compare doesn't work. the version of microeco is 0.12.1
<img width="859" alt="WeChate24eb4fff7ab82fd5441aa5e1fdaf7e7" src="https://user-images.githubusercontent.com/65677763/199504793-9a87a025-fa1b-4534-8194-beb5469d3dfd.png">

**Comment by ChiLiubio** [comment]
Hi,
Sorry. We forget to correct this line in the tutorial. Now there is no pair_compare parameter in plot_alpha function. All the statistics are performed in the cal_diff function. Please select other paired comparison method instead of anova. Thanks very much!

Best,
Chi
