### ISSUE TITLE
Percentages for trans_venn are incorrect

### ISSUE THREAD

**Issue by ignorantiam** [ChiLiubio/microeco#16]
Hello,

Thanks for creating this package! It is saving me time. 

I'd like to use the venn diagrams for shared ASVs, but the percentages are appear to be incorrect. As an example, you tutorial (https://chiliubio.github.io/microeco/) middle percentage should be around 49% by my calculation. 

Best,

Bo

**Comment by ChiLiubio** [comment]
Hi,

The percentage type you mean should be the ASVs number percentage. Thus, the 'ratio' parameter in trans_venn$new should be 'numratio'. Please see the help document. The 'ratio' in tutorial used is 'seqratio', in which the sequences percentage is calculated in those taxa, not the OTUs/ASVs number percentage. This can correspond to your 49%.

Best
Chi

**Comment by ChiLiubio** [comment]
Hi, @benedil 

The seqratio you mean in the petal plot may only include the central intersection and particular parts, in which the part intersections of groups are missing. In another words, the petal plot only shows a part of the results, a little different from the venn plot.

Chi

**Comment by benedil** [comment]
Oh my goodness, I completely missed that difference!  Thank you!  Everything makes sense again.
LB

**Comment by pkmnsandy** [comment]
Hi, I would like to understand what does sequence ratio mean?
