### ISSUE TITLE
Faprotax and Funguild percentage of assignment

### ISSUE THREAD

**Issue by SusanaRE2** [ChiLiubio/microeco#161]
Hi

Is there a way to get the percentage of OTUs/ASVs that get a function assigned when using trans_func? 
Thanks for your help!
I love the microeco package!

**Comment by SusanaRE2** [comment]
Hi!

It is not possible to assign functions to all bacteria or fungal OTUs/ASVs
because 1) assignment is done to a certain taxonomic level, so for example
OTUs that did not get identified up to genus level won't be used for the
functional profiling, and 2) some taxa are not present in the functional
databases. I would like to know if it is possible to know which percentage
of total OTUs gets a function assigned. For example I have used funguild on
its own before and you have the total number of OTUs that got assigned to a
function, and usually for soil fungi is around 60% of the obtained OTUs.
In the meantime I think I figured it out. I can see the assignment to
individual OTUs using object$res_spe_func_raw_funguild and so get the
number of OTUs that did get a functional assignment.

Thanks for your reply anyway!




Susana Rodríguez Echeverría

CENTRE FOR FUNCTIONAL ECOLOGY - Science for People & the Planet

Department of Life Sciences • University of Coimbra

Calçada Martim de Freitas • 3000-456 COIMBRA • PORTUGAL

Tel. |Phone: +351239240767 ext. 262367

E-mail: ***@***.***  or ***@***.***
***@***.***>*

Official page: http://cfe.uc.pt/profile/members/1707 <http://cfe.uc.pt/sre>
<http://cfe.uc.pt/sre>
Investigadora Responsável do Grupo de Trabalho em Ecologia de Montanha e
Diversidade (Rede para a Ciência e Educação para a Sustentabilidade do
Estrela Geopark)
Follow my current research project at https://www.facebook.com/ecolabestrela
and Instagram @ecolab_estrela

**Comment by ChiLiubio** [comment]
Hi,

I think `trans_func$cal_spe_func_perc(abundance_weighted = FALSE)` is just what you may need. `abundance_weighted = FALSE` means return percentage is the `number of OTUs assigned/total OTUs number in a sample * 100`.

Best,
Chi

**Comment by SusanaRE2** [comment]
Thanks!



Susana Rodríguez Echeverría

CENTRE FOR FUNCTIONAL ECOLOGY - Science for People & the Planet

Department of Life Sciences • University of Coimbra

Calçada Martim de Freitas • 3000-456 COIMBRA • PORTUGAL

Tel. |Phone: +351239240767 ext. 262367

E-mail: ***@***.***  or ***@***.***
***@***.***>*

Official page: http://cfe.uc.pt/profile/members/1707 <http://cfe.uc.pt/sre>
<http://cfe.uc.pt/sre>
Investigadora Responsável do Grupo de Trabalho em Ecologia de Montanha e
Diversidade (Rede para a Ciência e Educação para a Sustentabilidade do
Estrela Geopark)
Follow my current research project at https://www.facebook.com/ecolabestrela
and Instagram @ecolab_estrela
