### ISSUE TITLE
trans_network

### ISSUE THREAD

**Issue by Hobgoblin8** [ChiLiubio/microeco#162]
Excuse me.  I was wondering how to make the color of the edge represents positive and negative correlation?

**Comment by ChiLiubio** [comment]
For which method or software?

**Comment by Hobgoblin8** [comment]
I use t1 <- trans_network$new(dataset = dataset, cor_method = "spearman", use_WGCNA_pearson_spearman = TRUE, filter_thres = 0.0001)…,  and then view network in Gephi.

> For which method or software?

I use t1$cal_network(p_thres = 0.01,COR_optimization = TRUE, COR_cut = 0.7,add_taxa_name = "Family")……,  and then view network in Gephi.

**Comment by ChiLiubio** [comment]
You can find the edge color assignment in the upper left part of the panel.
![图片](https://user-images.githubusercontent.com/20815519/200721194-87589f18-df81-40a0-9227-9f0724829fde.png)

**Comment by Hobgoblin8** [comment]
> You can find the edge color assignment in the upper left part of the panel. ![图片](https://user-images.githubusercontent.com/20815519/200721194-87589f18-df81-40a0-9227-9f0724829fde.png)

I want to use color of edge represents correlation coefficient, just as red represents"+", green represent"-", I can't find this column about correlation coefficient.

**Comment by ChiLiubio** [comment]
The correlation coefficient was used as the weight of edges, not the label.
