### ISSUE TITLE
count otus classified at different taxa level

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#163]
Hi, I would like get the details of number or percentage of otus classifed at each taxonomy level. Is there any way to do it in microeco object? Please let me know!

**Comment by ChiLiubio** [comment]
Hi. I think you can directly manipulate tax_table.
```
library(microeco)
data(dataset)
table(dataset$tax_table$Phylum)
```

**Comment by apoosakkannu** [comment]
Thanks. I tried a couple of things, but was not able to get exactly my
wish. I need to get something like in following,
https://rdrr.io/cran/RAM/man/percent.classified.html. Could you pls give me
any pointers?
