### ISSUE TITLE
Problema with paired MANOVA

### ISSUE THREAD

**Issue by alberjo0296** [ChiLiubio/microeco#167]
Hi Chi,

a few weeks ago with this library the differences among groups by beta diversity could be calculated with paired PERMANOVA like this:

t1 <- trans_beta$new(dataset = dataset, group = "Treatment", measure = "bray")
t1$cal_manova(cal_manova_paired = TRUE)
t1$res_manova

Now, this has changed and the new tutorial says that I can do paiwise comparison with the function:

t1$cal_manova(manova_all = FALSE)
t1$res_manova

but it is not working, the result is the same as the one I obtained with manova_all = TRUE and it don't display the pairwise comparisons. I don't understand the reasons for the changes that have been made in the writing of this code if the library was already well-developed for the users who used it regularly. The same happens for alpha diversity which now also displays an extra column called "Group" that doesn't really add anything of value.
Honestly, I really liked Microeco, but I think these changes only make it more difficult for users who have already adapted to it to run analyzes. The library was already very good and the language was understandable for everyone with the previous tutorials; the changes make no sense. I hope that it is solved as soon as possible and that we will be able to perform the paired MANOVA between the studied groups again.

Alberto

**Comment by alberjo0296** [comment]
Apparently, the reason is that this library does not allow to do paired PERMANOVA for six groups. Solved

**Comment by ChiLiubio** [comment]
Hi. I have tested this function again and donot find such issue with my another data, which has a 'treatment' column in sample metadata with six groups. Actually, the group numbers have no limitation in this function. So which version of the package are your using?
