### ISSUE TITLE
not able to create micro table

### ISSUE THREAD

**Issue by mvtejesvi** [ChiLiubio/microeco#171]
Hi, When I run the command, I get the following errors. What could be the problem? 

> qiime2meco(feature_table = "table_decontam_filt.qza")
No sample_table provided, automatically use colnames in otu_table to create one ...
microtable-class object:
sample_table have 80 rows and 2 columns
otu_table have 2947 rows and 80 columns
> sample_data = "metadata.txt"
> taxonomy_data = "taxonomy.qza"
> test1 <- qiime2meco("table_decontam_filt.qza", "metadata.txt", "taxonomy.qza")
Error in type.convert.default(data[[i]], [as.is](http://as.is/) = [as.is](http://as.is/)[i], dec = dec,  :
  invalid multibyte string at '<b8>d<b4>z<12>אi<d9>e<cf><f7><cc><e4><da><e6><e4><b1><da><f3><e8><ce><da>r[&<88><b9><cc>; <c7>Dֺ<d4>@+2<d1><e6>X<b6><b9>e<f7>&ө<e4> q <e9><98>w߻<d5>9W<9b>;J-<a3>T<80>j-<db>g<b3>2<ec> <d2>o<d0>D<b5><8e><aa><e0>YJ<ac>.+{<e7>m<b9><e4>͹ <d3> <b8><82>ޖtkOudN&<a6>iֲd<ef>]<8a><8e>w<9a> <d7>i<fe>(<84><ae><8f> <88>*<de>ˈ<dd>b<b8><dc><c1>8<d2>$;<97>ѫ<a0>[<gG dt<aa><ad>dsnDw<90><8e>4<d9)<a5><a0>K<e8><d1>] <ad>EiZwG<cb>̒<ef> <bd><90>&<c8>S<89><b9><93><f5>j<a9>*[<9a>cP<da>3<e7><d6> <a3><94><bf>wS <b7><ce>2 <89><8b>F݊L<8d> <91>A<a8><a7>ɻ<82>q<a4>i<ec><d9>jCi<a2><c6><d7>FY<b0>j <f3> <83>d <be><83>t<a4>I<b2>͚<9b>q<99><b9><93>w<a3>mܛW<b5><92><bb><f7>;H<af><a3><89>k1<9a> };<8d>R%<ca>i<c8>ք\<84><e4>R<aa>q~<a7><a9>/<aa> :BὍU<a9><9a>lD<84>р3<ad><dd><c1>8<d2><e4><b9><d1>Щ<b4>LG<de><a0>#
Ҥ<cc>E<e3>,y<97><90><8e>4AD <ef>Ae<cd><cc><e2><9b>r<e0><8f><c8>h<90> E<94>w<90>^GS<95>R<b3><ae><96><96><e5><96><ea>j<92>zG<f3>vU2)C<f3><f2>w<9a>H<fb>RׂK9<f
In addition: Warning messages:
1: In read.table(match_table, stringsAsFactors = FALSE, sep = "\t") :
  line 1 appears to contain embedded nulls
2: In read.table(match_table, stringsAsFactors = FALSE, sep = "\t") :
  line 2 appears to contain embedded nulls
3: In read.table(match_table, stringsAsFactors = FALSE, sep = "\t") :
  line 3 appears to contain embedded nulls
4: In read.table(match_table, stringsAsFactors = FALSE, sep = "\t") :
  line 4 appears to contain embedded nulls
5: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
6: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  embedded nul(s) found in input

Best Wishes

Tj

**Comment by ChiLiubio** [comment]
Hi @mvtejesvi 
Please also send me "metadata.txt" and "taxonomy.qza" to have a try. I am not sure how this happened. You can directly drag the compressed file or data here as you can see under the dialog box.
![图片](https://user-images.githubusercontent.com/20815519/206066114-6c3f14cd-0a4f-4802-a9d2-1cfd1fb93ce3.png)

Chi

**Comment by mvtejesvi** [comment]
[metadata.txt](https://github.com/ChiLiubio/microeco/files/10173306/metadata.txt)
I am not able to attach taxonomy.qza file, it says it can not attached.

**Comment by ChiLiubio** [comment]
Please first compress it.

**Comment by ChiLiubio** [comment]
Hi,
My test is fine with file2meco v0.5.0
![图片](https://user-images.githubusercontent.com/20815519/206128446-620a8c4c-3a18-49aa-99ef-78079270dc0b.png)
You should add the parameter name in order to make the function knows what the provided file are as your provided files are not consistent with the parameter orders.

**Comment by mvtejesvi** [comment]
[taxonomy.qza.zip](https://github.com/ChiLiubio/microeco/files/10174181/taxonomy.qza.zip)

Here is the file. Please let me know what is the problem? 

Thank you

Best, 
Tj

**Comment by ChiLiubio** [comment]
Please try again with the command
```
qiime2meco("table_decontam_filt.qza", sample_table = "metadata.txt", taxonomy_table = "taxonomy.qza")
```
