### ISSUE TITLE
FunGuild with my samples instead of modules in trans_comm function

### ISSUE THREAD

**Issue by guilhermeluciomartins** [ChiLiubio/microeco#173]
Hi Chi,

I would like to use FUNGuild's function to identify the trophic level and guilds of my samples. Instead of plotting the figure with modules, the same way you do in the tutorial, I want to use my samples.

I was able to change the figure by changing the object "meco_module" to "meco_fungi", but the final figure has 3 repetitions instead of just 1. Is there any way to change the "meco_module" function to display my samples?

[funguild2.pdf](https://github.com/ChiLiubio/microeco/files/10418436/funguild2.pdf)

[funguild_script.txt](https://github.com/ChiLiubio/microeco/files/10418441/funguild_script.txt)

**Comment by ChiLiubio** [comment]
Hi @guilhermeluciomartins 

I check through your script and think it is ok in terms of the operations. Do you mean that the figure you send showed the groups with 3 repetitions? You need only one mean value for each group? If yes, it is easy to do like this.
```
meco_fungi_mean <- meco_fungi$merge_samples(use_group = "Group") # please use your group name instead of "Group"
# then it is same to do others
t2 <- trans_func$new(meco_fungi_mean)
```
I may donot fully get your point. The "meco_module" is only a converted microtable object in which each module is just viewed as a sample to make it feasible to do other analysis.

Best regards,
Chi

**Comment by guilhermeluciomartins** [comment]
Your recommendation worked perfectly! Thanks!

I was not understanding the results of the "meco_module" object, that's why I was trying to change it for my samples. In this case, it's possible to change the name of the labels from "M1, M2, ..." to the name of my samples?

**Comment by ChiLiubio** [comment]
The "meco_module" object has no matter with your samples. It represents the composition of each module in the constructed network. So the example in the tutorial is only used to show the network analysis and use the funguild functions as the extension of the network modules. If you are studying the functional composition in samples, please ignore the whole network part like this do `t2 <- trans_func$new(meco_fungi_mean)`. Please feel free to tell me if it is still unclear.

**Comment by guilhermeluciomartins** [comment]
Chi, thank you for your explanation, it was very clear. Yes, in fact, I am studying the functional composition of my samples. I have tried to go directly with the "meco_fungi" object instead of the "meco_module" object, but I wasn't sure if I was doing it correctly.

**Comment by ChiLiubio** [comment]
Yes. What you have done is totally correct!
