### ISSUE TITLE
plot alpha error 

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#177]
Hi, i try to plot the alpha diversity by_group and found problem with significant code. 

Please check the following code. 

#calculate and plot the alpha diversity
t_country <- trans_alpha$new(dataset = dataset2, group = "Country", by_group = "Host_taxa")
t_country$cal_diff(method = "wilcox")
t_country$plot_alpha(measure = "Chao1")
t_country$plot_alpha(measure = "Shannon")

![image](https://user-images.githubusercontent.com/50707302/215739111-108300b0-0ac6-4131-8fa6-908083481b52.png)
![image](https://user-images.githubusercontent.com/50707302/215739144-5e40177c-664e-485e-ac2e-74073522d227.png)

**Comment by ChiLiubio** [comment]
Hi. Could you please send me your `dataset2` to check it? Please use `save` function to save the data (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function). I am not sure how it hapened now.

**Comment by apoosakkannu** [comment]
dataset.rdata.zip
<https://drive.google.com/file/d/1QI_OcO4Q8TtJXMrQaSEiVhutseYKfaW3/view?usp=drive_web>

pls find the dataset attached!

**Comment by ChiLiubio** [comment]
Please drag the data in the Github issue page. I can not open the upper link via the email.

**Comment by apoosakkannu** [comment]
Large file size. Not able to upload it. Any email I’d I could send?

**Comment by apoosakkannu** [comment]
https://drive.google.com/file/d/1QI_OcO4Q8TtJXMrQaSEiVhutseYKfaW3/view?usp=drive_web

**Comment by ChiLiubio** [comment]
It can not be opened for me. Please directly send the data to my email (liuchi0426@126.com). Thanks.

**Comment by ChiLiubio** [comment]
Hi. I found the weird result comes from the incorrect factor assignment in the 'Host_taxa ' of sample_table. If you print `dataset2$sample_table$Host_taxa`, you can find there are 5 factors, not 4. Removing the factors can solve this issue.
```
library(magrittr)
dataset2$sample_table$Host_taxa %<>% as.character
t_country <- trans_alpha$new(dataset = dataset2, group = "Country", by_group = "Host_taxa")
t_country$cal_diff(method = "wilcox")
t_country$plot_alpha(measure = "Chao1")
```

**Comment by apoosakkannu** [comment]
Thanks, it worked. It seems that when I do the subset, a factor still
remains even after tidying the dataset.

**Comment by milyzhou** [comment]
dataset <- mpa2meco("buglist_clean.tsv", sample_table =metadata1)
test <- dataset$merge_taxa(taxa = "Genus")
test$cal_alphadiv(PD = FALSE)
t2 <- trans_alpha$new(dataset = test, group = "group",by_group="time")
t2$cal_diff(method = "wilcox")
I also check the "group" and "time" as.character
but  Error in wilcox.test.formula(formu, data = table_compare, ...) : 
 grouping factor must have exactly 2 levels
[KW_genus_leveL_TIME.pdf](https://github.com/ChiLiubio/microeco/files/14475950/KW_genus_leveL_TIME.pdf)

**Comment by ChiLiubio** [comment]
Hi. 
Could you please attach your `dataset` or `test` object so that I can reproduce your issue? To save it, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by ChiLiubio** [comment]
Hi. 
Could you please attach your `dataset` or `test` object so that I can reproduce your issue? To save it, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by milyzhou** [comment]
[test_data.zip](https://github.com/ChiLiubio/microeco/files/14488779/test_data.zip)
Thank you!
