### ISSUE TITLE
FAPROTAX v1.2.6 is available

### ISSUE THREAD

**Issue by paytonyau** [ChiLiubio/microeco#179]
Hi,

There is a update for FAPROTAX from v1.2.4, could you please consider update the [prok_func_FAPROTAX.RData](https://github.com/ChiLiubio/microeco/blob/master/data/prok_func_FAPROTAX.RData) data?
Thank you for your consideration. 

Best regards,
Payton

**Comment by ChiLiubio** [comment]
Hi,

Thanks very much. It will be updated in the next release of microeco package. The github version will be first updated in the next two days.

Best,
Chi
