### ISSUE TITLE
How to sort the x-axis(sampleid) in taxa bar plot made by trans_abund$plot_bar

### ISSUE THREAD

**Issue by zhonglinma** [ChiLiubio/microeco#18]
Hi, I'd like to know how to sort my x-axis(sample-id) in taxa bar plot in the way I want, cause I didn't find any parameters in trans_abund$plot_bar() that can do it, thank you a lot!

**Comment by ChiLiubio** [comment]
Hi, @zhonglinma 

The best way I think is to set the order_x parameter in trans_abund object creating. Please see the trans_abund$new part in help document. However I found a bug today in this part and updated the code in github. Please reinstall the package from github, not CRAN, and try again. Thanks.

Chi

**Comment by Jin-1106** [comment]
@ChiLiubio 

I also have a order problem here, I would like to reorder my samples with a protein concentration. Here I just find in following: 

>  trans_abund <- R6Class(classname = "trans_abund",
@param order_x default NULL; character vector; if x xais is ordered, input the samples or group vector or the column name in sample table.

Then I tried `t1a <- trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 10, order_x = X119_Order )` 
As X119_Order is a column of concentration data in meta_table, but it cannot work. I then tried the thing like `est1 <- dplyr:: arrange (dataset, X119_Order)`, R told me this cannot be applied in R6 class. As I am new in R, could you give me a example for order samples, I would adopt it into my alluvial and heatmap plot. Thank you.

**Comment by ChiLiubio** [comment]
Hi, @Jin-1106 

Please install the lateset version in github or CRAN. There is a bug in the previous version. The code is ok when I debug recently.
Is X119_Order same with your sample names? This will be used as the factor levels for samples. The following is the raw code:

if(!is.null(order_x)){
  if(length(order_x) == 1){
	  abund_data$Sample %<>% factor(., levels = unique(self$sample_table[, order_x]))
  } else {
	  abund_data$Sample %<>% factor(., levels = order_x)
  }
}

**Comment by Jin-1106** [comment]
Yes!!!@ChiLiubio 

You remind me that I just add a new column to put ordered sample ID. Then get the plots. Thank you.

**Comment by ChiLiubio** [comment]
Hi, @Jin-1106 

I just update the trans_abund code in github to make the names and order adjustment of x axis more flexible. Now it is better than the previous version, especially, two parameters: x_axis_name and order_x in plot_bar() or plot_heatmap().
