### ISSUE TITLE
heat map plotting 

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#181]
Hi, I am getting a weird couple of white spaces in my heat map. I used the following code and attached the picture .

# show 38 taxa at phylum level
t_phyla_heat <- trans_abund$new(dataset = dataset2, taxrank = "Phylum", ntaxa = 38)
t_phyla_heat$plot_heatmap(facet = "Host_taxa", xtext_keep = FALSE, withmargin = FALSE)

![image](https://user-images.githubusercontent.com/50707302/218312532-3058a6d3-676a-433a-baa7-d415b33f8f3a.png)

Actually the dataset is same as in the issue, https://github.com/ChiLiubio/microeco/issues/177 which i sent to your email few days back.

**Comment by ChiLiubio** [comment]
Hi. I have checked it. No such issue was found. Please try to save the picure with more widths. Here is what I run.
```
t_phyla_heat <- trans_abund$new(dataset = dataset2, taxrank = "Phylum", ntaxa = 38)
g1 <- t_phyla_heat$plot_heatmap(facet = "Host_taxa", xtext_keep = FALSE, withmargin = FALSE)
ggplot2::ggsave("test.pdf", g1, width = 15, height= 8)
```
