### ISSUE TITLE
Problems in p-adjustment with FDR

### ISSUE THREAD

**Issue by alberjo296** [ChiLiubio/microeco#189]
I think the adjustment with FDR is wrong. The adjusted p-values that I obtain are different than when using other libraries and softwares...

Regards,

Alberto

**Comment by ChiLiubio** [comment]
Could you please give me an example that I can use to reproduce your result and check it? For example, which function are you using. It would be best if you can use the dataset inside the package to show the question.

Best,
Chi

**Comment by alberjo296** [comment]
Here:

t4 <- trans_diff$new(dataset = dataset, method = "wilcox", group = "Group", taxa_level = "Phylum", p_adjust_method = "fdr", filter_thres = 0.005)
t5 <- t4$res_diff
t5

**Comment by ChiLiubio** [comment]
Hi.
The column P.unadj in t5 is the raw P values.
```
p.adjust(t5$P.unadj, method = "fdr")
```
I found the result is same with P.adj column. Which way are you using?
If you want to check the raw P value, it is easy to use the following way
```
abund_table <- dataset$taxa_abund[["Phylum"]]
wilcox.test(unlist(abund_table["k__Bacteria|p__Proteobacteria", rownames(tmp_dataset$sample_table[tmp_dataset$sample_table$Group == "IW", ])]),
unlist(abund_table["k__Bacteria|p__Proteobacteria", rownames(tmp_dataset$sample_table[tmp_dataset$sample_table$Group == "CW", ])]))
```
