### ISSUE TITLE
Tax4Fun R version Issue

### ISSUE THREAD

**Issue by calla404** [ChiLiubio/microeco#19]
First off I want to say thank you for making this package, it seems like it will turn a weeks worth of work into a days worth of work. I am running into an issue using the tax4fun package though... it seems like microeco uses Tax4Fun, but I cannot install it on the most current version of R (v4.04). I can, however, install Tax4Fun2, which doesn't seem compatible with microeco. Are there plans to switch microeco over to Tax4Fun2, or is there a way to force the install of the original Tax4Fun?
Thank you so much!

**Comment by ChiLiubio** [comment]
Hi, @calla404 

I have try to reinstall R 4.0.4 and Tax4Fun using the steps in README of microeco (Tax4Fun part). Everything seems to be ok. So it is not the issue of compatibility. I recommend you using the steps in README to install Tax4Fun.
Thanks for your valuable link to Tax4Fun2. I am also considering integrating Tax4Fun2 into microeco package. The new ideas of Tax4Fun2 are very interesting.

Chi

**Comment by calla404** [comment]
Thank you very much for your reply. I had previously tried to install the package following the instructions on the readme without it working- this time I restarted R and it worked like a charm. It's not the first time something like this has happened. 
I look forward to seeing you implement new ideas into microeco!
Cheers
Jake
