### ISSUE TITLE
Error with tidy_dataset

### ISSUE THREAD

**Issue by sqqsjc** [ChiLiubio/microeco#190]
Hello,
I read the paper on microeco and used it to create many of the figures. But when executing the tidy_dataset() command to make the OTU and sample information consistent across all files in the dataset object, I found that the number of samples is one less, from 110 to 109. I want to know the reason for this issue.
The command I used:
library(microeco)
library(tidyverse)
library(ggplot2)
otu_table_16S <- read.delim('otu_table.tsv', row.name = 1, check.names = FALSE)
sample_info_16S<-read.delim('metadata.tsv', row.name = 1, check.names = FALSE, fileEncoding="GBK")
taxonomy_table_16S<-read.delim('taxonomy_table_16S(raw).txt', row.name = 1, check.names = FALSE)
library(seqinr)
rep_fasta<-read.fasta("rep-seqs.fasta")
library(ape)
phylo_tree_16S <-read.tree("rooted_tree.nwk")
library(magrittr)
set.seed(123)
library(ggplot2)
theme_set(theme_bw())
taxonomy_table_16S %<>% tidy_taxonomy
dataset <- microtable$new(sample_table = sample_info_16S, otu_table = otu_table_16S, tax_table = taxonomy_table_16S, phylo_tree = phylo_tree_16S, auto_tidy = TRUE)
dataset
dataset$tax_table %<>% base::subset(Kingdom == "k__Archaea" | Kingdom == "k__Bacteria")
dataset
dataset$filter_pollution(taxa = c("mitochondria", "chloroplast"))
dataset
dataset$tidy_dataset()
print(dataset)

My microtable object data: 
[microtable object data.zip](https://github.com/ChiLiubio/microeco/files/10822187/microtable.object.data.zip)
Any help you can provide on this would be much appreciated!

**Comment by ChiLiubio** [comment]
Hi. Please see the `rownames(sample_info_16S)`. There is a blank spacing in "S2.7 ". In otu table, it is "S2.7". It is not same recognized by the function. Then there are filtered by the function.

**Comment by sqqsjc** [comment]
Hi. Thank you! The issue had been solved.
