### ISSUE TITLE
No alpha diversity after normalization

### ISSUE THREAD

**Issue by alberjo296** [ChiLiubio/microeco#191]
Hi Chi,

it gives me the following error when I write:

dataset$cal_alphadiv(PD = TRUE)
dataset$save_alphadiv(dirpath = "alpha_diversity")

>Error in estimateR.default(newX[, i], ...) : 
  function accepts only integers (counts)

so what if I want to work with normalize data (with decimals)?

Best,

Alberto

**Comment by ChiLiubio** [comment]
Hi. Yes. Some indexes need integers. How about convert your otu_table to integers or use other indexes instead of it, such as Shannon.

**Comment by ChiLiubio** [comment]
Hi. Yes. Some indexes need integers. How about convert your otu_table to integers or use other indexes instead of it, such as Shannon.

**Comment by alberjo296** [comment]
How can I convert my otu_table to integers after rarefying?
The thing is I can not obtain any alpha diversity index values because of this error

Alberto

**Comment by ChiLiubio** [comment]
Hi. To calculate Shannon, please try:
```
dataset$cal_alphadiv(measures = "Shannon")
```
Which normalization way are you using? I mean if you use some methods like CSS ..., there may be decimal. Actually, I think it is not a good way to convert the decimal to integer arbitrarily. Because the error probably comes from the index like Chao1 or other, which is used to estimate the species number. The decimal means the data has been converted and is not a classical format to estime species.

Chi

**Comment by alberjo296** [comment]
The thing is you can not store the object alpha_diversity because you have normalized by TSS or CSS and you have decimals so it doesn't save any object/file with the alpha diversity, so you can not apply functions like that at all:

dataset$cal_alphadiv(measures = "Shannon")

It should be allowed to use decimals.

Regards,

Alberto

**Comment by ChiLiubio** [comment]
Hi. Shannon index has no matter with the decimals.  I have tried again with the example dataset.
```
library(microeco)
library(mecodev)
data("dataset")
t1 <- trans_norm$new(dataset = dataset)
d1 <- t1$norm("CCS")
d1$cal_alphadiv(measures = "Shannon")
View(d1$alpha_diversity)
```
All values are decimals in `d1$otu_table`.

Best,
Chi

**Comment by alberjo296** [comment]
Okay thank you :) and is it possible to do it with ACE and PD?

**Comment by ChiLiubio** [comment]
PD is ok with `d1$cal_alphadiv(measures = "Shannon", PD = TRUE); View(d1$alpha_diversity)`
ACE only accept integers if you run `d1$cal_alphadiv(measures = c("Shannon", "ACE"), PD = TRUE)`
