### ISSUE TITLE
ISSUE to plot the results of Trans$null model class

### ISSUE THREAD

**Issue by CYBERBOY1210** [ChiLiubio/microeco#192]
Hi there. I am trying to  add betaNRI matrix to my beta_diversity list, and plot the results. However when I try to run this part of the code:
g1 <- t2$plot_group_distance(distance_pair_stat = TRUE), I'm getting the following message: "The ordered groups are Disturbed Undisturbed ...
Error in `[.data.frame`(use_data, , group) : undefined columns selected"
I have been dealing with this issue for several days and have been trying to run the code with different datasets...but I get the same error.
This is the complete code I ran:

 dataset$beta_diversity[["betaNRI"]] <- t1$res_ses_betampd
 # create trans_beta class, use measure "betaNRI"
 t2 <- trans_beta$new(dataset = dataset, group = "Type", measure = "betaNRI")
 # transform the distance for each group
 t2$cal_group_distance()
 # plot the results
 g1 <- t2$plot_group_distance(distance_pair_stat = TRUE)
 g1 + geom_hline(yintercept = -2, linetype = 2) + geom_hline(yintercept = 2, linetype = 2)

I'm not an expert in R...Any ideas?

**Comment by ChiLiubio** [comment]
Hi. Which version are you using? The distance_pair_stat parameter in plot_group_distance has been deprecated. The function in the current package v0.14.1 is very different from older usage. Please first update the package. Then check this part in the tutorial again (https://chiliubio.github.io/microeco_tutorial/diversity-based-class.html#trans_beta-class) or see the help document with the command `?trans_beta`.

**Comment by CYBERBOY1210** [comment]
Hi. Thank you for getting back to me.
 I though there was a sort of bug with the code. I was using an older version but I updated it recently to  v0.14.1. Aditionally to the issue I mentioned before,  when I ran the code: t1$cal_ses_betampd(runs=500, abundance.weighted = TRUE), I'm getting this error:  "Error in array(r, dim = d, dimnames = if (!(is.null(n1 <- names(x[[1L]])) &  : 
  length of 'dimnames' [1] not equal to array extent"   I get the same error when using the sample dataset"Dataset". I will go over the ?trans_beta command,following your suggestion

**Comment by ChiLiubio** [comment]
Hi. The parameter `distance_pair_stat` has been deprecated. Please delete it in your code. If there is still an issue, please paste your script with the example dataset so that I can reproduce your issue.

**Comment by CYBERBOY1210** [comment]
Hi, I did that, but when I get rid of the "distance_pair_stat", the code is not working either. I have been using the code from the Microeco tutorial version v0.14.1. Below is the chunk of code I used with the sample "dataset"

 # generate trans_nullmodel object
 # as an example, we only use high abundance OTU with mean relative abundance > 0.0005
 t1 <- trans_nullmodel$new(dataset, filter_thres = 0.0005, add_data = sample_info_16S)

 
 # see null.model parameter for other null models
 # null model run 500 times for the example
 t1$cal_ses_betampd(runs=500, abundance.weighted = TRUE)
 # return t1$res_ses_betampd
 
 
 # add betaNRI matrix to beta_diversity list
 dataset$beta_diversity[["betaNRI"]] <- t1$res_ses_betampd
 # create trans_beta class, use measure "betaNRI"
 t2 <- trans_beta$new(dataset = dataset, group = "Type", measure = "betaNRI")
 # transform the distance for each group
 t2$cal_group_distance()
 # plot the results
 g1 <- t2$plot_group_distance(distance_pair_stat = TRUE)
 g1 + geom_hline(yintercept = -2, linetype = 2) + geom_hline(yintercept = 2, linetype = 2)

**Comment by ChiLiubio** [comment]
Hi. Sorry. It is a bug. The reason is plot_group_distance can not recognize the group parameter passing when cal_group_distance_diff function is not used. To temporarily resolve this, please use this:
```
library(ggplot2)
library(microeco)
t1 <- trans_nullmodel$new(dataset, filter_thres = 0.0005, add_data = sample_info_16S)
t1$cal_ses_betampd(runs=500, abundance.weighted = TRUE)
dataset$beta_diversity[["betaNRI"]] <- t1$res_ses_betampd
t2 <- trans_beta$new(dataset = dataset, group = "Type", measure = "betaNRI")
t2$cal_group_distance()
t2$cal_group_distance_diff(method = "anova")
g1 <- t2$plot_group_distance(distance_pair_stat = TRUE)
g1 + geom_hline(yintercept = -2, linetype = 2) + geom_hline(yintercept = 2, linetype = 2)
```
I have fixed this and updated the package in github. If you do not want to change your code, you can reinstall the package from github and try again. The CRAN version will be later updated till the next release.

Best,
Chi

**Comment by ChiLiubio** [comment]
Also thank you for letting me know the tutorial is a little behind for the current package version.

**Comment by CYBERBOY1210** [comment]
Hi, Chi.
I used the modified code and it works! Thank you so much for your help and disposition.

Julian
