### ISSUE TITLE
Error creating network - sparcc

### ISSUE THREAD

**Issue by tpellegrinetti** [ChiLiubio/microeco#193]
Hello, I'm having trouble running the 'sparcc' association in R. When I run the code, I get the following error message:

Calculate 'sparcc' associations ... Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Execution halted
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Fatal error: error during cleanup

I'm not sure what's causing this issue. I'm running R version 4.2.2 on Ubuntu 22.04. Any help would be greatly appreciated. Thank you!

**Comment by ChiLiubio** [comment]
Hi. Could you please provide your steps that I can reproduce in PC? Now I am not sure how it happened.
