### ISSUE TITLE
observed ASV for selective taxa

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#196]
Hi, I wonder could it be possible to subset observed ASVs for the selected taxa? Please let me know if there is any possibility! Thanks in advance!

**Comment by ChiLiubio** [comment]
Hi. Please directly manipulate the tax_table in your microtable like this.
```
library(microeco)
library(magrittr)
data(dataset)
dataset
dataset$tax_table %<>% .[.$Phylum == "p__Proteobacteria", ]
dataset$tidy_dataset()
dataset
```
you can see feature number change from 404 to 138. All come from Proteobacteria.

Chi
