### ISSUE TITLE
how to split specific taxa hierarchy from otu data or dataset

### ISSUE THREAD

**Issue by hansir8** [ChiLiubio/microeco#199]
Now, i extract the dataset$otu_table to a new file, and used for next analysis. I didn't know that how to  split the specific taxa hierarchy from otu data. For example, I want to extract the data from otu data at family hierarchy level. Isn't it a function in the Microeco package?  Thanks!

Zhenzhi

**Comment by ChiLiubio** [comment]
Hi. Why not extract the data by tax_table. Something like this (https://chiliubio.github.io/microeco_tutorial/other-examples-1.html#mantel-test-correlation-heatmap):
![图片](https://user-images.githubusercontent.com/20815519/226078369-0991cb58-c88f-4f3c-aba0-3ceb00e4a5e8.png)
Please use Family to replace Phylum.

Chi

**Comment by hansir8** [comment]
Thanks for your reply! I have successfully extracted a specific tatanomy, e.g., f__Poxviridae, and it only included the data under this family ( f__Poxviridae) level. I meet another problem about the taxa. Could it split all taxa hierarchy from otu data? For example, I want to extract the whole taxa data of family level (including all data of family level, e.g., f__Poxviridae, f__Picornaviridae, f__Tristromaviridae, f__Herpesviridae and others), and it also included the data under  taxa hierarchy. Like this, other taxa level, e.g., Order, Phylum or Genus, could be extracted in this way. 

Thanks

**Comment by ChiLiubio** [comment]
Sorry. I donot totally understand your question. Could you give me a toy example with a diagram? Theorectically, all the subset operations can be finished with the manipulation of `tax_table` in your microtable object and following `tidy_dataset` function.

**Comment by ChiLiubio** [comment]
Please use `merge_taxa` function.
```
library(microeco)
data(dataset)
d1 <- dataset$merge_taxa(taxa = "Family")
rownames(d1$otu_table) <- apply(d1$tax_table, 1, paste, collapse = ";")
```
`d1$otu_table` is the final result.

**Comment by hansir8** [comment]
Thanks for your help! The problem has been ideally solved.
