### ISSUE TITLE
plot_group_distance statistical method

### ISSUE THREAD

**Issue by motroy** [ChiLiubio/microeco#2]
Hi @ChiLiubio,

Thanks for your prompt response to my previous issue! Just wanted to clarify what statistical method/s were used for the group comparisons (both within and between groups) in the trans_beta class part of the tutorial (https://chiliubio.github.io/microeco/#trans_beta-class)? I apologize if it's stated there and I overlooked it.

thanks,
Yair

**Comment by ChiLiubio** [comment]
Hi,
The default method for paired comparison in plot_group_distance function of trans_beta class is wilcox.test. You can also change the method. The details can be found in the parameter of the function in help document. Try ?trans_beta .

Chi
