### ISSUE TITLE
Small problem for legend mismatching in Lefse analysis

### ISSUE THREAD

**Issue by ZejinZhang** [ChiLiubio/microeco#20]
First of all, thank you very much for developing this efficient R package, which is really helpful for our amplicon analysis.
A small problem appeared in the process of use: in the **Lefse analysis**, the legends of LDA-score bar plot and cladogram graph did not correspond. There seems to be a little BUG in **labels matching**.

**Comment by ZejinZhang** [comment]
As follows:
![{4~LB~YH(5_VHAZV)DLDF L](https://user-images.githubusercontent.com/74855921/111863201-07449680-8995-11eb-968b-20839150c432.png)
![D3~$5{8Y$E Z24E6(I)5BIV](https://user-images.githubusercontent.com/74855921/111863203-0b70b400-8995-11eb-89b1-b9fe6a423d06.png)

**Comment by ChiLiubio** [comment]
Hi, @ZejinZhang 

I carefully checked this part of code and found that it is a bug coming from the group disorder and color matchment in the factor generation. I have fixed this and updated the code in github. Please reinstall the package from github and try again. Thanks.

Chi
