### ISSUE TITLE
Some columns in otu_table are not numeric vector! Please check the otu_table!

### ISSUE THREAD

**Issue by tboonf** [ChiLiubio/microeco#203]
Hi, 

I have been trying to import a data frame but have not been successful.
I first imported the data as such: abc<-read.csv("sample_data.xls", sep="\t", header=TRUE)
After which, I tried to convert it to microeco format as such: dataset <- microtable$new(otu_table = abc)

I have tried many different versions but it just doesnt work. Any help is appreciated. 
[sample_data.xls](https://github.com/ChiLiubio/microeco/files/11024683/sample_data.xls)

**Comment by ChiLiubio** [comment]
Hi. The input `abc` should have rownames and no any characteristic data in the table.
```
abc<-read.csv("sample_data.xls", sep="\t", header=TRUE, row.names = 1)
```

**Comment by tboonf** [comment]
Thank you. Now that has been resolved. I am now trying to create venn diagram using shared and unique taxa, i.e. genus ...however I am not able to do it following the tutorial:

# merge samples as one community for each group
dataset1 <- dataset$merge_samples(use_group = "Group")
# dataset1 is a new microtable object
# create trans_venn object
t1 <- trans_venn$new(dataset1, ratio = NULL)
t1$plot_venn()
