### ISSUE TITLE
Continuous value supplied to discrete scale error when using trans_beta$plot_ordination()

### ISSUE THREAD

**Issue by zhonglinma** [ChiLiubio/microeco#21]
Hi, I got a Continuous value supplied to discrete scale Error when plotting NMDS with **trans_beta$plot_ordination()**, I think it's because I used the **plot_color**parameter, I do have some group in my **sample_table** whose value is number, but it's just a classified group, the value itself makes no sense,  I think the parameters like **plot_color** and **plot_shape** could accept Continuous value but I don't know how to set, is there any resolutions? or just transfer the numeric value to character?

**Comment by ChiLiubio** [comment]
Hi, what is the data type of your classified group in sample_table? numeric or character?

**Comment by zhonglinma** [comment]
`lapply(dataset010101$sample_table,mode)`
$SampleID
[1] "numeric"

$CTD
[1] "numeric"

$year
[1] "numeric"

$`CTD-BW`
[1] "numeric"

$Depth
[1] "numeric"

$`Depth-3`
[1] "numeric"
It's numeric

**Comment by ChiLiubio** [comment]
Hi, @zhonglinma 

That is the problem. Currently, the group should be discrete variable. Could you please change the numeric type to character and try again?

Chi

**Comment by susheelbhanu** [comment]
Hi, I'm running into the same issue, despite my variable being a character. 

Any thoughts on how to get around it?

Thank you!

```bash
t1 <- trans_beta$new(dataset = dataset_filter, group = "STAGE", measure = "bray")
t1$sample_table$`Date Filtered` <- as.character(t1$sample_table$`Date Filtered`)

t1$cal_ordination(ordination = "PCoA")
# t1$res_ordination is the ordination result list
class(t1$res_ordination)

pca <- t1$plot_ordination(plot_color = "STAGE", plot_shape = "`Date Filtered`", plot_type = c("point", "ellipse"))
pca

#> mode(t1$sample_table$`Date Filtered`)
#[1] "character"
```

**Comment by ChiLiubio** [comment]
Hi. 
Could you please attach your `dataset_filter` so that I can reproduce your issue? To save the `dataset_filter`, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by susheelbhanu** [comment]
Here you go - thank you for your prompt help.
[test_data.zip](https://github.com/ChiLiubio/microeco/files/14786041/test_data.zip)

**Comment by ChiLiubio** [comment]
Hi. The class type should be changed before creating the object.
```
library(microeco)
load("dataset_filter.RData")

dataset_filter$sample_table$`Date Filtered` <- as.character(dataset_filter$sample_table$`Date Filtered`)

t1 <- trans_beta$new(dataset = dataset_filter, group = "STAGE", measure = "bray")

t1$cal_ordination(ordination = "PCoA")
# t1$res_ordination is the ordination result list
class(t1$res_ordination)

pca <- t1$plot_ordination(plot_color = "STAGE", plot_shape = "`Date Filtered`", plot_type = c("point", "ellipse"))
pca
```

**Comment by susheelbhanu** [comment]
Thank you - that worked beautifully. Can I ask another question though? Is there a way to order the facets on a barplot?

For example, I'm running the following:
```bash
t1 <- trans_abund$new(dataset = dataset_filter, taxrank = "Phylum", ntaxa = 15, use_percentage = FALSE)
t1$plot_bar(others_color = "grey70", facet = c("STAGE", "`Date Filtered`"), xtext_keep = FALSE, 
            legend_text_italic = FALSE, order_x = c("2023-02-22", "2023-09-26", "2023-09-27", "2023-09-28","2023-12-21"))
```

While this orders the `Date Filtered`, I also want to order the 'STAGE' variable, in the following order: RAW, RPTSH, FINAL, FPTSH.

Thanks for your help!

**Comment by ChiLiubio** [comment]
Please use factor for the variable in dataset_filter like the tutorial shows (https://chiliubio.github.io/microeco_tutorial/notes.html#group-order)

**Comment by susheelbhanu** [comment]
Perfect, thank you very much! Appreciate your help!
