### ISSUE TITLE
Error in `[.data.frame`(., , apply(., 2, sum) != 0) : 选择了未定义的列

### ISSUE THREAD

**Issue by JBL05** [ChiLiubio/microeco#211]
Hi Prof. Liu, I ran t2$cal_spe_fun(prok_database ="FAPROTAX") with no problem, but there was an error when I ran t2$cal_spe_fun_perc(abunance_weighted = FALSE), could you please help me out

**Comment by ChiLiubio** [comment]
Could you please send me your data to reproduce this error? See this to save and paste your data (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function).

**Comment by JBL05** [comment]
Here is my dataset. Thank you very much!
[dataset.zip](https://github.com/ChiLiubio/microeco/files/11099519/dataset.zip)

**Comment by ChiLiubio** [comment]
Hi. It probably comes from NA in the taxonomic match. I have fixed this issue in the newest version. Please update the package to v0.15.0 from CRAN or github. Then run again. It is ok in my test.

**Comment by JBL05** [comment]
> Hi. It probably comes from NA in the taxonomic match. I have fixed this issue in the newest version. Please update the package to v0.15.0 from CRAN or github. Then run again. It is ok in my test.

Hi, Prof. Liu. Yes, it comes from the NA, and got fixed after update to v0.15.0. Many thanks!
