### ISSUE TITLE
Median and IQR for trans_abund

### ISSUE THREAD

**Issue by motroy** [ChiLiubio/microeco#213]
Hi @ChiLiubio ,

Thank you for this great package. Would it be possible to add an option to the trans_abund class that would allow the user to easily obtain median and IQR values per taxa, while also allowing to plot such values (as in the plot_box function)?

Thanks again for all your time and effort, this package is very very useful,
Yair

**Comment by ChiLiubio** [comment]
Hi. Thanks for your suggestion.  I will have a try.

Chi

**Comment by motroy** [comment]
Thank you @ChiLiubio, will test it out soon

**Comment by motroy** [comment]
Thank you @ChiLiubio, have tested this function and the results look valid
keep up the great work on this package!
regards,
Yair
