### ISSUE TITLE
Error in tapply(LD, group_vec_lda, mean) : arguments must have same length in "trans_diff"

### ISSUE THREAD

**Issue by marwa38** [ChiLiubio/microeco#215]
Hey

I am getting the following error but not sure why:
`t5 <- trans_diff$new(dataset = dataset.intes.VMV, method = "lefse", group = "Region", alpha = 0.05, lefse_subgroup = NULL)`
`Error in tapply(LD, group_vec_lda, mean) : arguments must have same length`
![image](https://user-images.githubusercontent.com/68851733/229716839-a998cd5f-84a7-4ca2-b680-7372fd9cb2ce.png)
[dataset.intes.VMV.zip](https://github.com/ChiLiubio/microeco/files/11145678/dataset.intes.VMV.zip)

Thanks

**Comment by ChiLiubio** [comment]
Hi. The issue comes from only one significant feature found by the default method, triggering unexpected error. This is generally caused by the weak significances of features, which would be almost non-significant after p value adjustment. It is ok if you disable the p value adjustment with the parameter `p_adjust_method`.
```
t5 <- trans_diff$new(dataset = dataset.intes.VMV, method = "lefse", group = "Region", alpha = 0.05, p_adjust_method = "none", lefse_subgroup = NULL)
```
Actually, the way without p adjustment is totally same with the lefse original python version, such as that in the galaxy server. This has been discussed in a previous Issue.
Yes. 0.05 is less strict as the threshold.

**Comment by ChiLiubio** [comment]
Thanks for your issue. I will add a message output in the function for this case that only one or no significant feature got in the process. The message can guide user to disable the p value adjustment.

**Comment by marwa38** [comment]
Thanks, Chi for turning in errors into more clarifications and enhancements that are positive and helpful. 
I tried `alpha = 0.01` with and without  `p_adjust_method = NULL`
![image](https://user-images.githubusercontent.com/68851733/229757474-595babda-94d4-46d9-83c9-35f9e245e7ff.png)
![image](https://user-images.githubusercontent.com/68851733/229757409-86183fee-3d4e-4040-ac44-b86d57e39609.png)

Do you think that removing fdr for multiple comparisons allowed the number of feature from one to more than one?

Thanks again 
Marwa

**Comment by ChiLiubio** [comment]
Yes. The effect is especially apparent when most p values are close to the threshold.

**Comment by ChiLiubio** [comment]
In my viewpoint, though this operation can increase the possibility of type I error, it is acceptable to get some important features in the first time for the subsequent analysis.

**Comment by marwa38** [comment]
Thanks Chi. 
Do you think that we can select a specific feature separately to do the subsequent analysis?
Can we select the colors of the groups while visualizing differential abundances?

**Comment by ChiLiubio** [comment]
What do you mean about "select a specific feature separately"?
Please try to use `color_values` parameter.

**Comment by marwa38** [comment]
Select only one taxa to avoid type one error when I use NULL for multiple comparisons? for the subsequent analysis on each taxa separately. Hope that clarify. Thanks

**Comment by ChiLiubio** [comment]
One feature is not enough for the following classifier training. So the process will stop.

**Comment by marwa38** [comment]
>  Can we select the colors of the groups while visualizing differential abundances?

I tried different things but can't figure out how to select a specific color for a certain group (I have 6), the color are produced according to the order of the group while I need to fix a color for each group. Knowing that I plot each 2 groups separately.

**Comment by ChiLiubio** [comment]
Do you mean that `color_values` parameter can not exactly control your colors because of part of groups is not there? Could you please show an example that I can reproduce?
