### ISSUE TITLE
Reorder x-axis in trans_beta$plot_group_distance issue (version 0.15.0)

### ISSUE THREAD

**Issue by calla404** [ChiLiubio/microeco#219]
Hi Chi, 

I am happy to see that you keep adding useful features to microeco! I have, however, run into a small issue on the latest release (microeco version 0.15.0). When trying to plot group distances from the trans_beta class I cannot get the groups to reorder along the x-axis, below is a snippet of the code used:

```
DS_beta$cal_group_distance()
DS_beta$cal_group_distance_diff(method = "KW_dunn")
DS_beta$res_group_distance_diff %<>% base::subset(Significance != "ns") # subset out non-significant values
DS_beta$plot_group_distance(plot_group_order = c("Carrie", "Peltier", "Portage", "Hill", "White Iron", "Tait"))
```

This results in a very nice boxplot, but the group order does not change by adding 'plot_group_order' (there are no error codes, it just makes a plot with the default group order). I also tried factoring the levels of the table after subsetting the significant results, but it still didn't change the order. 

```
DS_beta$res_group_distance_diff$Group %<>% factor(levels = c("Carrie", "Peltier", "Portage", "Hill", "White Iron", "Tait"))
DS_beta$plot_group_distance(plot_group_order = c("Carrie", "Peltier", "Portage", "Hill", "White Iron", "Tait"))
```

I would appreciate any insight into what I may be doing wrong and potential solutions to this problem. 

Thank you so much for all your hard work on this R package!

Cheers,
Jake

**Comment by ChiLiubio** [comment]
Hi Jake,

Sorry. It is bug coming from the last update on the whole structure of these three functions. I forgot to test this parameter. 
Two ways are available to fix it.
1 The first one is a temporary solution. You donot need to reinstall the package from github.
Here is what you can run. Ignore the message.
```
DS_beta$res_group_distance_diff_tmp$data_alpha[, DS_beta$group] %<>% factor(levels = c("Carrie", "Peltier", "Portage", "Hill", "White Iron", "Tait"))
DS_beta$plot_group_distance()
```
This is my test. 
```
library(microeco)
t1 <- trans_beta$new(dataset = dataset, group = "Type", measure = "bray")
library(magrittr)
t1$cal_group_distance(within_group = TRUE)
t1$cal_group_distance_diff(method = "wilcox")
t1$res_group_distance_diff %<>% .[.$Significance != "ns", ]
t1$plot_group_distance()
# temporary solution
t1$res_group_distance_diff_tmp$data_alpha[, t1$group] %<>% factor(levels = c("NE", "NW", "NC", "YML", "SC", "QTP"))
t1$plot_group_distance()
```
2 The second one is to update the package. I have fixed the bug and updated the package in github. You can reinstall it from github (pre release v0.16.0) and have a try. Remember to recreate your trans_beta object. Here is my test.
```
library(microeco)
t1 <- trans_beta$new(dataset = dataset, group = "Type", measure = "bray")
library(magrittr)
t1$cal_group_distance(within_group = TRUE)
t1$cal_group_distance_diff(method = "wilcox")
t1$res_group_distance_diff %<>% .[.$Significance != "ns", ]
t1$plot_group_distance()
t1$plot_group_distance(plot_group_order = c("NE", "NW", "NC", "YML", "SC", "QTP"))
t1$plot_group_distance(plot_group_order = c("SC", "NC", "YML", "NE", "NW", "QTP"))
```
Thanks very much for your finding.

Best,
Chi
