### ISSUE TITLE
saving permanova and beta dispersion results

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#220]
Hi, I would like to save permanova and beta dispersion results in csv format. I have trouble saving especiallu beta dispersion results.  Error in as.data.frame.default(tmp_beta$res_betadisper) : 
  cannot coerce class '"permutest.betadisper"' to a data.frame

Could you please help me out? Thanks in advance!

**Comment by ChiLiubio** [comment]
The result of betadisper is a list. You can only save them by accessing each data like this.
```
# save overall significance
write.csv(tmp_beta$res_betadisper$tab, "1.csv")
# append observed paired
write.table(as.data.frame(tmp_beta$res_betadisper$pairwise$observed), "1.csv", append = TRUE, sep = ",")
# append permuted paired
write.table(as.data.frame(tmp_beta$res_betadisper$pairwise$permuted), "1.csv", append = TRUE, sep = ",")
``
