### ISSUE TITLE
Specific color for each treatment (n=6) in plot_diff

### ISSUE THREAD

**Issue by marwa38** [ChiLiubio/microeco#222]
Do you mean that `color_values` parameter can not exactly control your colors because of part of groups is not there? Could you please show an example that I can reproduce?

_Originally posted by @ChiLiubio in https://github.com/ChiLiubio/microeco/issues/215#issuecomment-1506826036_

Code and data kindly attached below 
The figure produced for metastat for example V-VM comparison color the VM with green although I want it to be brownish orange as V is already green.

```{r}
# V vs VM
t25$plot_diff_bar(select_group = "V - VM", group_order = c("M", "V", "MM", "VM", "MMV", "VMV"))
ggsave("figures/metastat_intes.V.VM.tiff", width = 6, height = 5.5,
       units = "in", dpi = 300, compression = "lzw")

t25$plot_diff_abund(select_group = "V - VM", group_order = c("M", "V", "MM", "VM", "MMV", "VMV"),
                    select_taxa = t25$plot_diff_bar_taxa)
ggsave("figures/metastat_intes.V.VM_RA.tiff", width = 6, height = 5,
       units = "in", dpi = 300, compression = "lzw")
```

M-V comparison  (V is green)
![image](https://user-images.githubusercontent.com/68851733/232008462-01744b5a-8d1e-4392-9bb4-80e48f58c5ef.png)
V-VM comparison (VM is green)
![image](https://user-images.githubusercontent.com/68851733/232008745-78e65208-2efd-4fac-b2cb-fe661bc8107a.png)

**Comment by marwa38** [comment]
Just to keep a record of previous comments in case needed
@marwa38 
> > Can we select the colors of the groups while visualizing differential abundances?
> 
> I tried different things but can't figure out how to select a specific color for a certain group (I have 6), the color are produced according to the order of the group while I need to fix a color for each group. Knowing that I plot each 2 groups separately.

**Comment by marwa38** [comment]
I got an idea now but haven't tried that I just could change the group order? will check and come later

**Comment by marwa38** [comment]
I tried the rearrangement (`t25$plot_diff_bar(select_group = "V - VM", group_order = c("VM", "V"))`) BUT it didn't change the color.

**Comment by ChiLiubio** [comment]
I think you should try to change `color_values` parameter according to your groups order. The default colors order is fixed. If you change group order, you should also change colors input.

**Comment by marwa38** [comment]
as an update on the colors; I first assigned colors
`colors <- c("#1E90FF","lightgreen", "#4169E1", "#87CEEB", "#008080", "#2E8B57")`
![image](https://github.com/ChiLiubio/microeco/assets/68851733/8c0a3f31-baae-40c0-acf6-730be2610867)

[t1.zip](https://github.com/ChiLiubio/microeco/files/11518237/t1.zip)
```
t1 <- trans_diff$new(dataset = dataset.intes, method = "lefse", group = "Regime", alpha = 0.01,
                     lefse_subgroup = NULL)
# see t1$res_diff for the result
# From v0.8.0, threshold is used for the LDA score selection.
t1$plot_diff_bar(threshold = 4, color_values = colors)
```
It seems that I need to change the color ordering from the assignment stage
![image](https://github.com/ChiLiubio/microeco/assets/68851733/8c0a3f31-baae-40c0-acf6-730be2610867) to make sure it appears for each group in order as some don't show differential abundance features/taxa so the order of the group will be different due to absence/presence of a group. Not sure if there is a possibility to change an argument in code plot_diff to assign a color for each group? So   #1E90FF" for M,"lightgreen" for V, "#4169E1" for MM, "#87CEEB" for VM, "#008080" for MMV, "#2E8B57" for VMV
![image](https://github.com/ChiLiubio/microeco/assets/68851733/d94707b8-f05f-49bf-9efa-e09f66144711)

**Comment by ChiLiubio** [comment]
Ok. I will have a try.

**Comment by ChiLiubio** [comment]
Hi.  I got it. I add a parameter color_group_map in plot_diff_bar to automatically match the groups to colors.
```
rm(list = ls())
library(microeco)
data(dataset)
t2 <- trans_diff$new(dataset = dataset, method = "lefse", group = "Type", alpha = 0.01, lefse_subgroup = NULL)
g1 <- t2$plot_diff_bar(use_number = 1:10)
ggplot2::ggsave("F_10.png", g1, width = 10, height= 8)
g1 <- t2$plot_diff_bar(use_number = 1:30)
ggplot2::ggsave("F_30.png", g1, width = 10, height= 8)
g1 <- t2$plot_diff_bar(color_group_map = TRUE, use_number = 1:10)
ggplot2::ggsave("T_10.png", g1, width = 10, height= 8)
g1 <- t2$plot_diff_bar(color_group_map = TRUE, use_number = 1:30)
ggplot2::ggsave("T_30.png", g1, width = 10, height= 8)
g1 <- t2$plot_diff_bar(color_group_map = TRUE, use_number = 1:10, group_order = c("NC", "YML", "SC", "NE"))
ggplot2::ggsave("T_10_order.png", g1, width = 10, height= 8)
```
You can find that in F_10 and F_30 figures, colors in groups are not regular. When use color_group_map = TRUE, you can find all the colors in T_10 are same with those in T_30 thought T_30 have more groups. Even though we rearrange the orders in T_10_order, the colors in T10 and T_10_order are same. 
Total groups used to match the orders come from the original sample_table in your microtable object, either the factor levels of groups or the group orders in the table when it is not factor. So If you want to change color_values, you should assign all the colors to all the groups in the sample_table. Now I take an example.
```
# I use factor to determine raw orders
dataset$sample_table$Type <- factor(dataset$sample_table$Type, levels = c("NE", "QTP", "NW", "NC", "YML", "SC"))
# Now I want to make NE black and SC yellow
newcolor <- RColorBrewer::brewer.pal(8, "Dark2")
# NE is the first; SC is sixth
newcolor[1] <- "black"
newcolor[6] <- "yellow"
t2 <- trans_diff$new(dataset = dataset, method = "lefse", group = "Type", alpha = 0.01, lefse_subgroup = NULL)
g1 <- t2$plot_diff_bar(color_group_map = TRUE, use_number = 1:10, group_order = c("NC", "YML", "SC", "NE"), color_values = newcolor)
ggplot2::ggsave("T_10_order_newcolor.png", g1, width = 10, height= 8)
```
Very good and useful suggestion I have to say! Many thanks. Sorry for the delay.

Chi

**Comment by marwa38** [comment]
thanks so much
