### ISSUE TITLE
number of phylum or class or order in dataset

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#229]
Hi, I wonder could it be possible to get the number of phyla or class or ... in any dataset? please let me know. Thanks in advance!

**Comment by ChiLiubio** [comment]
Do you mean just get the unique number of taxa at each level. Please try this:
```
library(microeco)
data(dataset)
apply(dataset$tax_table, 2, function(x){length(unique(x))})
```

**Comment by apoosakkannu** [comment]
Thanks. This is exactly what I want. Just perfect and simple.
