### ISSUE TITLE
Error when running cal_abund for a Tax4Fun2 object 

### ISSUE THREAD

**Issue by lemv24** [ChiLiubio/microeco#234]
Hello! I am running into an error when executing the Tax4Fun steps.

1) When executing the following line:
# filter rownames, only keep ko+number
rownames(pathway_file) %<>% gsub("(^.*);\\s.*", "\\1", .)

I get an error indicating that the function %<>% doesn't exist. I ran the code removing the  "<" and got the ko+number as expected. I dont know if this is a typo or I am lacking a dependency that recognizes that function.

2) I followed the pipeline and built a microtable with this composition

print(funcMSPD3)

microtable-class object:
sample_table have 6 rows and 10 columns
otu_table have 266 rows and 6 columns
tax_table have 444 rows and 3 columns

When I try to run the tidy dataset function I get the following error message:
funcMSPD3$tidy_dataset()

**Error in funcMSPD3$tidy_dataset() : 
  No same feature names found between rownames of otu_table and rownames of tax_table! Please check rownames of those tables !**

I can see how the tax and otu tables have different names but dont know how to fix this issue. I tried to assign the rownames of one to the other but it didn't work.

I appreciate your time and help solving this problem! Have a great day!

Luis

**Comment by ChiLiubio** [comment]
Hi Luis,
To solve the first issue that  the function %<>% doesn't exist, please just load the package magrittr: `library(magrittr)`
Then run again. I think the following steps will be fine.

Chi

**Comment by lemv24** [comment]
Thank you very much! it all ran smoothly after loading that lib.

Have a great day,


Luis
