### ISSUE TITLE
threshold shared ASV Venn diagramm

### ISSUE THREAD

**Issue by cdeschamps63** [ChiLiubio/microeco#236]
Hello, 

I run the following code : 
dataset1 <- dataset$merge_samples(use_group = "Size")
t5 <- trans_venn$new(dataset1, ratio = "seqratio")
t5$plot_venn()

I obtained 23 ASV shared between "size" groups. However I do not know how are they selected ? 
What is the threshold to consider that an ASV is present in the group (present in at least one sample ? In 10% of the samples of the group …?)

Thank you for your help !

**Comment by ChiLiubio** [comment]
Hi,

In trans_venn, no threshold can be applied to filter features. This class is only responsible for the shared feature analysis with the input microtable object. If you want to filter features, you should manipulate the microtable object with `filter_taxa` function before performing trans_venn. In the first step generating dataset1, all the samples in each Size group have been merged into one sample in dataset1. Then each group is treated as one sample in the venn analysis. So in this example, an ASV is classified once it occures in one sample (i.e. merged group).

Best,
Chi
