### ISSUE TITLE
trans_env class issue

### ISSUE THREAD

**Issue by HCB-M2RG** [ChiLiubio/microeco#24]
Hello I received this error when working with the trans_env class when running this command:
t1 <- trans_env$new(dataset = dataset, add_data = env_data_16S[, 4:11])

Error in initialize(...) : No sample names of sample_table found in env_data! Please chech the names of env_data!

At first I got it with my own data set but then went back to the example data provided (https://chiliubio.github.io/microeco/#trans_env_class) and received the same error with the data provided.

Can you give an explination on how the sample_table works?

**Comment by ChiLiubio** [comment]
Hi, @HCB-M2RG 
In your own data set, you can use env_cols  parameter to select the required environmental factors in sample_table, or use a single table, e.g. env_data_16S in the example, to pass to add_data parameter. If you use a single table, you must make sure the rownames of the table is sample names, as the code will use the names to match other tables. Feel free to tell me if this not works.

**Comment by HCB-M2RG** [comment]
Yes, setting the row names to match what I had assigned as sampleID fixed the problem. Thanks for the quick reply.
