### ISSUE TITLE
trans_norm adding a new method?

### ISSUE THREAD

**Issue by marwa38** [ChiLiubio/microeco#241]
Hi Chi 
[SRS  ](https://github.com/vitorheidrich/SRS) is a method of normalization that is being used instead of rarefaction (which got huge debate against). Any possibility to add as an option? it also produces a curve as rarefaction 
"_Analysis of species count data in ecology often requires normalization to an identical sample size. Rarefying (random subsampling without replacement), which is the current standard method for normalization, has been widely criticized for its poor reproducibility and potential distortion of the community structure. In the context of microbiome count data, researchers explicitly advised against the use of rarefying. Here we introduce a normalization method for species count data called scaling with ranked subsampling (SRS) and demonstrate its suitability for the analysis of microbial communities._" from https://peerj.com/articles/9593/
It also has the shinyGo option: [scripts](https://github.com/vitorheidrich/SRS/tree/main/R)
Thanks 
Marwa

**Comment by ChiLiubio** [comment]
Thanks. The SRS method has been implemented in the `rarefy_samples` function of `microtable` class.
```
# first install SRS package
install.packages("SRS")
# example
library(microeco)
data(sample_info_16S)
data(otu_table_16S)
d1 <- microtable$new(sample_table = sample_info_16S, otu_table = otu_table_16S)
# rarefaction; default method
d2 <- clone(d1)
d2$rarefy_samples(sample.size = 10000)
View(d2$otu_table)
# SRS when method = "SRS"
d3 <- clone(d1)
d3$rarefy_samples(method = "SRS", sample.size = 10000)
View(d3$otu_table)
d3$sample_sums()
```

**Comment by ChiLiubio** [comment]
Sorry. A minor bug is found. I have fixed it in github.

**Comment by marwa38** [comment]
Many thanks, Chi, it worked fine. 
I tried to plot a rarefaction curve using the following from the tutorial but it didn't work and it give an error (below). 
`t1$plot_rarefy(color_values = rep("grey", 100), show_point = TRUE, add_fitting = FALSE, show_legend = FALSE)`
![image](https://github.com/ChiLiubio/microeco/assets/68851733/117bf1ea-9569-4c0a-b8e5-956556822d9d)

**Comment by ChiLiubio** [comment]
The plot_rarefy is in trans_rarefy class of mecodev package (https://chiliubio.github.io/microeco_tutorial/mecodev-package.html#trans_rarefy), not microtable class. Please check your steps.

**Comment by ChiLiubio** [comment]
Please try to use `meco2phyloseq` function of file2meco package (https://chiliubio.github.io/microeco_tutorial/file2meco-package.html#phyloseq).

**Comment by marwa38** [comment]
Thank you so much, Chi.

**Comment by wangcxv** [comment]
Hi Chi,
I am using the v1.5.0, but an error showed "Error in meco2phyloseq(dataset) : could not find function "meco2phyloseq"", I can not fix it, could you tell me how to deal with it?
P.s. : similar errors as "Error: object 'trans_norm' not found".
Thanks!

**Comment by wangcxv** [comment]
@ChiLiubio 
Hi Chi,
I am using the v1.5.0, but an error showed "Error in meco2phyloseq(dataset) : could not find function "meco2phyloseq"", I can not fix it, could you tell me how to deal with it?
P.s. : similar errors as "Error: object 'trans_norm' not found".
Thanks!

**Comment by milyzhou** [comment]
Hi chi,
I want to use 'trans_norm' normalize data, a similar error as  "Error: object 'trans_norm' not found". Can you check  the function is working correctly? Thanks

**Comment by ChiLiubio** [comment]
Hi. Please use `?trans_norm` to find the document.

**Comment by milyzhou** [comment]
![1](https://github.com/ChiLiubio/microeco/assets/154502566/4c49dfe5-1570-4b66-84b1-e5272a48d98e)

**Comment by ChiLiubio** [comment]
Hi. `trans_norm` class is now in microeco package, not the mecodev.  https://chiliubio.github.io/microeco_tutorial/other-examples-1.html#trans_norm
