### ISSUE TITLE
i meet issue during network analysis

### ISSUE THREAD

**Issue by Seoki0903** [ChiLiubio/microeco#242]
Thank you for this awesome package!

Now I analyze microbiome metadata.

In network-analysis, I have a problem.

First, almost edge were + interaction... i guess it is something wrong.
Second, how can I choose the value of "filter_thres" for trans_network$new?
Third, I want to analyze this like Molecular Ecological Network Analaysis Pipeline. Can you advise on the code?

this is my code

df$otu_table <- df$otu_table[rowSums(df$otu_table != 0) >= 14, ] # Only keep the OTUs with 14 in total 29 samples 
df$tidy_dataset()
t1 <- trans_network$new(dataset = df, 
                        cor_method = "pearson", 
                        use_WGCNA_pearson_spearman = TRUE, 
                        filter_thres = 0)
t1$cal_network(COR_p_thres = 0.05, COR_optimization = TRUE)
t1$cal_module(method = "cluster_fast_greedy")
t1$save_network(filepath = "network.gexf")

**Comment by ChiLiubio** [comment]
As you can see in the help document `?trans_network`, `filter_thres` parameter control the feature filtering via the relative abundance. So `filter_thres = 0.0001` means removing features with relative abund < 0.0001.
Based on my experience, it is normal that the edges of correlation networks focus on the positive links. This case can vary accoding to the studies system and many factors. So it depends. It is also good to use other method or data to try to reproduce the result as a double check.
