### ISSUE TITLE
taxonomic composition by highest abundace?

### ISSUE THREAD

**Issue by marwa38** [ChiLiubio/microeco#247]
Hi Chi 
Hope you are doing well. 
I was wondering if it is possible to order the samples by the highest in relative abundance? to make the visualization much better for taxonomic abundance especially when we have many samples and many taxa.
Example from https://www.nature.com/articles/ncomms5500
![image](https://github.com/ChiLiubio/microeco/assets/68851733/1f3189f3-dd20-4df7-a1ca-ac62e141f600)
Thanks in advance 
Marwa

**Comment by ChiLiubio** [comment]
Hi.
You can use the `order_x` parameter. Here is an example.
```
library(microeco)
data(dataset)
t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 8)
t1$plot_bar(order_x = names(sort(unlist(dataset$taxa_abund$Phylum["k__Bacteria|p__Proteobacteria", ]))))
```
The whole part of `names(sort(unlist(dataset$taxa_abund$Phylum["k__Bacteria|p__Proteobacteria", ])))` means we take out the p__Proteobacteria abundance from `dataset$taxa_abund$Phylum` table and sort them by the abundance. Then the sample names are passed to order_x.

Chi

**Comment by marwa38** [comment]
Many thanks Chi 

If I selected a column for a group I can't facet according to 

![image](https://github.com/ChiLiubio/microeco/assets/68851733/a9faac59-2543-4fe8-ba79-db6e37737dcc)
I want to have the facet = c("Group", "Type") option to produce these titles 
on the top of the figure
![image](https://github.com/ChiLiubio/microeco/assets/68851733/6f88ec5f-618d-462a-b666-c10e04d2c385)

here is the full figure
![image](https://github.com/ChiLiubio/microeco/assets/68851733/1d0d25a5-4939-40ca-95b4-efe3f06ec254)

Any way to do that?

My codes
```
t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum")
t1$plot_bar(facet = c("Region", "Regime"),
  order_x = names(sort(unlist(dataset$taxa_abund$Phylum["k__Bacteria|p__Firmicutes", ])))) + 
  theme(axis.text.x = element_blank())

t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum", groupmean = "Regime")
t1$plot_bar() 
t1$plot_bar(facet = c("Region", "Regime"))
```

**Comment by marwa38** [comment]
the other available option is to make a column combining two columns before using plot_bar but the problem is that it produces repetitive words (two pyloric, middle, etc)

![image](https://github.com/ChiLiubio/microeco/assets/68851733/d159543c-65de-458b-a26f-7bdb213b0193)

**Comment by marwa38** [comment]
For genus level, any control through microeco allows the genus to be named by family name if it is NA? (for example Ruminococcacae NA) Ruminococcacae is the family and NA refers that the genus level is not identified.

**Comment by marwa38** [comment]
Because it is only two samples in water.MMV, MMV is not clearly shown as a facet name on the top
![image](https://github.com/ChiLiubio/microeco/assets/68851733/b4602627-8bb9-4e9f-afdb-18c8c505348e)
the solution is either change the width of the bar (which is not preferable as it might imply more importance or emphasis on this group) or 
overwrite it on the facet grey area (how to do this?)

**Comment by ChiLiubio** [comment]
Hi. it is actually hard to show the full text as there are too few samples in those groups relative to others. I think the simplest way is to reduce the facet text size and increase the width of the figure.

**Comment by ChiLiubio** [comment]
For the case that genus of 16S rRNA gene have NAs, how about assigning the family taxonmy to the genus manually in your tax_table of your phyloseq object or microtable object. Then you can do anything like we usually do.
I see it. I think it should work!

**Comment by marwa38** [comment]
> Many thanks Chi
> 
> If I selected a column for a group I can't facet according to c("Group", "Type")
> 
> ![image](https://user-images.githubusercontent.com/68851733/249453046-a9faac59-2543-4fe8-ba79-db6e37737dcc.png) I want to have the facet = c("Group", "Type") option to produce these titles on the top of the figure ![image](https://user-images.githubusercontent.com/68851733/249453380-6f88ec5f-618d-462a-b666-c10e04d2c385.png)
> 
> here is the full figure ![image](https://user-images.githubusercontent.com/68851733/249453289-1d0d25a5-4939-40ca-95b4-efe3f06ec254.png)
> 
> Any way to do that?
> 
> My codes
> 
> ```
> t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum")
> t1$plot_bar(facet = c("Region", "Regime"),
>   order_x = names(sort(unlist(dataset$taxa_abund$Phylum["k__Bacteria|p__Firmicutes", ])))) + 
>   theme(axis.text.x = element_blank())
> 
> t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum", groupmean = "Regime")
> t1$plot_bar() 
> t1$plot_bar(facet = c("Region", "Regime"))
> ```

thanks Chi 
Any suggestion/help regarding this? I think there is away.

**Comment by ChiLiubio** [comment]
I may get what you want. How your dataset is generated? If you are using group-mean instead of individual samples, you may have calculated the mean values across each group. So the generated dataset metadata may not include group and type. Thus, you should create those columns in your `sample_table` and use them like the normal case. If it is not clear, please attach your dataset. I will try to show the whole operations.

**Comment by marwa38** [comment]
[dataset.zip](https://github.com/ChiLiubio/microeco/files/11912040/dataset.zip)
Thanks, Chi 
Please find attached
unzip them
dataset <- readRDS("dataset.rds")

**Comment by ChiLiubio** [comment]
Hi. I fould an issue. When you use groupmean for "Regime", all the taxonomic abundances are means for each group of "Regime". So there are only 4 samples for the result. These 4 names can not be further classified for "Regime" and "Region", as they can not be grouped from the original info.
![图片](https://github.com/ChiLiubio/microeco/assets/20815519/b06d93dc-4644-4f6a-b127-d2dd9afbce56)

**Comment by ChiLiubio** [comment]
```
t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum", groupmean = "Regime")
t1$plot_bar(facet = c("Region", "Regime"))
```
So the error from this line is there are no any metadata inside the t1 object. Because abundances have been transformed by the `groupmean`, there are no original metadata for the plot.

**Comment by marwa38** [comment]
so there is no solution?

**Comment by ChiLiubio** [comment]
Hi. I think there is no need to add facets for this case as there are a few samples to show. Facets are usually used to compare groups.

**Comment by marwa38** [comment]
Many thanks Chi
