### ISSUE TITLE
No sample_table provided,

### ISSUE THREAD

**Issue by Geize** [ChiLiubio/microeco#249]
Hi there, 
I have received the following messages.

```
ASV_data <- "table-dada2.qza"
metadata_file<-"sample-metadata.txt"
taxa_file <-"taxa.qza"

tree_data <- "root-tree.qza"
rep_data <- "rep-seqs-dada2.qza"
qiime2meco(ASV_data)

```

**Message**
No sample_table provided, automatically use colnames in otu_table to create one ...
microtable-class object:
sample_table have 10 rows and 2 columns
otu_table have 2032 rows and 10 columns

```
Taxa_dataset <-qiime2meco(ASV_data, 
                          sample_table =metadata_file, 
                          taxonomy_table = taxa_file,
                          phylo_tree = tree_data, 
                          rep_fasta =rep_data, 
                          auto_tidy = TRUE)

  

Taxa_dataset
Taxa_dataset$tidy_dataset

```
**Message**

function (main_data = FALSE) 
{
    self$otu_table <- private$check_abund_table(self$otu_table)
    sample_names <- intersect(rownames(self$sample_table), colnames(self$otu_table))
    if (length(sample_names) == 0) {
        stop("No same sample name found between rownames of sample_table and colnames of otu_table! Please check whether the rownames of sample_table are sample names!")
    }
    sample_names <- rownames(self$sample_table) %>% .[. %in% 
        sample_names]
    self$sample_table %<>% .[sample_names, , drop = FALSE]
    self$otu_table %<>% .[, sample_names, drop = FALSE]
    self$otu_table %<>% {
        .[apply(., 1, sum) > 0, , drop = FALSE]
    }
    taxa_list <- list(rownames(self$otu_table), rownames(self$tax_table), 
        self$phylo_tree$tip.label) %>% .[!unlist(lapply(., is.null))]
    taxa_names <- Reduce(intersect, taxa_list)
    if (length(taxa_names) == 0) {
        if (is.null(self$phylo_tree)) {
            stop("No same feature names found between rownames of otu_table and rownames of tax_table! Please check rownames of those tables!")
        }
        else {
            stop("No same feature name found among otu_table, tax_table and phylo_tree! Please check feature names in those objects!")
        }
    }
    self$otu_table %<>% .[taxa_names, , drop = FALSE]
    if (!is.null(self$tax_table)) {
        self$tax_table %<>% .[taxa_names, , drop = FALSE]
    }
    if (!is.null(self$phylo_tree)) {
        self$phylo_tree %<>% ape::drop.tip(., base::setdiff(.$tip.label, 
            taxa_names))
    }
    if (!is.null(self$rep_fasta)) {
        if (!all(taxa_names %in% names(self$rep_fasta))) {
            stop("Some feature names are not found in the names of rep_fasta! Please provide a complete fasta file or manually check the names!")
        }
        self$rep_fasta %<>% .[taxa_names]
    }
    if (main_data == F) {
        if (!is.null(self$taxa_abund)) {
            self$taxa_abund %<>% lapply(., function(x) x[, sample_names, 
                drop = FALSE])
        }
        if (!is.null(self$alpha_diversity)) {
            self$alpha_diversity %<>% .[sample_names, , drop = FALSE]
        }
        if (!is.null(self$beta_diversity)) {
            self$beta_diversity %<>% lapply(., function(x) x[sample_names, 
                sample_names, drop = FALSE])
        }
    }
}
<environment: 0x7fdb1389afa0>

**Comment by ChiLiubio** [comment]
Hi. It seems like the function can not find the metadata_file, i.e. "sample-metadata.txt". Could you please attach all the files to let me reproduce the whole results?

**Comment by ChiLiubio** [comment]
I forget to say that, to temporarily sovle that, you can manually assigan your metadata table to the microtable object like the following pseudo codes.
```
Taxa_dataset <-qiime2meco(ASV_data, 
                          sample_table =metadata_file, 
                          taxonomy_table = taxa_file,
                          phylo_tree = tree_data, 
                          rep_fasta =rep_data, 
                          auto_tidy = TRUE)
Taxa_dataset
# manually assign sample table, first please try to read your "sample-metadata.txt" to R
tmp_sample_table <- read.delim("sample-metadata.txt", row.names = 1) # maybe other similar operations
Taxa_dataset$sample_table <- tmp_sample_table
# use tidy_dataset to check all the files again
Taxa_dataset$tidy_dataset
```
Again, please attach all the files with a compressed zip file if possible. I will find why it happened. Thanks.

**Comment by Geize** [comment]
Hi there, 

Thanks for your reply. 

Please, I've attached the files..
[MicroEco.zip](https://github.com/ChiLiubio/microeco/files/11858123/MicroEco.zip)

**Comment by ChiLiubio** [comment]
Hi.

I run all the steps without any issue under my new created R project.

```
library(microeco)
library(file2meco)

ASV_data <- "table-dada2.qza"
metadata_file<-"sample-metadata.txt"
taxa_file <-"taxonomy.qza"
tree_data <- "root-tree.qza"
rep_data <- "rep-seqs-dada2.qza"

Taxa_dataset <-qiime2meco(ASV_data, 
                          sample_table = metadata_file, 
                          taxonomy_table = taxa_file,
                          phylo_tree = tree_data, 
                          rep_fasta =rep_data, 
                          auto_tidy = TRUE)


Taxa_dataset
# actually, tidy_dataset() is only needed after you modify the files inside the microtable object. So you can see they are same (Taxa_dataset).
Taxa_dataset$tidy_dataset()
Taxa_dataset
```
I am using file2meco package version 0.6.0.

Chi

**Comment by Geize** [comment]
Hi Chi, 

I appreciate your messages. 
R and Rstudio were removed. I reinstalled everything again, and it worked. However, after running for  some time, again it stopped working once more. 

The software was also installed in Ubuntu Virtual machine. And in both case, I received this message: 
```

> # add phylogenetic tree and fasta for more demonstrations
> # please download tree from https://docs.qiime2.org/2022.2/data/tutorials/pd-mice/tree.qza
> # the file name is 'tree.qza'; put it into the R working directory
> tree_data <- "tree.qza"
> # please download fasta from https://docs.qiime2.org/2022.2/data/tutorials/pd-mice/dada2_rep_set.qza
> # the file name is 'dada2_rep_set.qza'; put it into the R working directory
> rep_data <- "dada2_rep_set.qza"
> test1 <- qiime2meco(abund_file_path, sample_table = sample_file_path, taxonomy_table = taxonomy_file_path, phylo_tree = tree_data, rep_fasta = rep_data, auto_tidy = TRUE)
Error in read_qza(phylo_tree) : 
  Input artifact (tree.qza) not found. Please check path and/or use list.files() to see files in current working directory.
> test1
Error: object 'test1' not found
```


It does not even recognize your files. Any suggestion?

**Comment by ChiLiubio** [comment]
Hi. Do you download the tree.qza and dada2_rep_set.qza files? These two files are not inside the package as the package size is limited. If no, please donot provide the file path like this:
```
test1 <- qiime2meco(abund_file_path, sample_table = sample_file_path, taxonomy_table = taxonomy_file_path, auto_tidy = TRUE)
```
