### ISSUE TITLE
Is it possible to use "trans_diff" function to select environmental variables instead of taxa?

### ISSUE THREAD

**Issue by ignerocha-f** [ChiLiubio/microeco#25]
Hi, Chi! 
Thank you so much for this amazing R package! Really interesting, handy, and useful!

I'm struggling with the topic of variable selection, then I was wondering if is it possible to use some adjusted "trans_diff" function to pick the most relevant environmental variable to explain the microbial community structure, instead of differential abundance, such as RandonForest. I've been trying different methods such as 'ordiR2step', "foward.sel', 'envdist', and 'correlation + Mantel test', but different results are displayed depending on the method, which is not good in my perception.

Any advice?

Thank you so much in advance!

**Comment by ChiLiubio** [comment]
Hi, @ignerocha-f 

Thanks for getting in touch. Currently, the RF method in trans_diff is only designed for the classification, not regression.  However, I think it is not hard to change this part of code to realize. Please have a try. As you said, the variable selection depends on the method. It is not easy to compare the results of different methods. Anyway, the explainable methods (such as rda and other methods on regression) is more credible if the causal relationship is relatively clear. You have said "pick the most relevant environmental variable to explain the microbial community structure", meaning that you are trying to parse the community structure, not one or some taxa you are interested in. This is important I think for you to select the better method.

Chi
