### ISSUE TITLE
Error in plot_diff_cladogram

### ISSUE THREAD

**Issue by diego00012138** [ChiLiubio/microeco#254]
when i ran this code：l1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 50, clade_label_level = 5)
i got the result 
![adabacaf914000e9ca671c1f3058840](https://github.com/ChiLiubio/microeco/assets/101499808/2ef8c1a5-0401-4f80-abf0-0631b6910477)
it seems that all the circles and the dots are squeezed together

**Comment by diego00012138** [comment]
with the warning:
1: In stat_cladeText(node = node, label = label, offset = offset +  ... :
  Ignoring unknown parameters: `level`
2: In stat_cladeBar(node = node, offset = offset, align = align,  ... :
  Ignoring unknown parameters: `level`

**Comment by ChiLiubio** [comment]
Hi. Could you attach the data and scripts to let me reproduce the result? Please follow this (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) to save and compress your microtable object. Thanks.

**Comment by diego00012138** [comment]
data$sample_table$grazing %<>% factor(., levels = c("TEP","TEPfree-WATER"))
l1 <- trans_diff$new(
  dataset = data, 
  method = "lefse", 
  group = "grazing", 
  taxa_level = "all",
  alpha = 0.05,
  p_adjust_method = "fdr",
  lefse_norm = 1000000,
  nresam = 0.6667,
  boots = 100,
)
clad <- l1$plot_diff_cladogram(
  filter_taxa = 0.0001,
  use_taxa_num = 200,
  use_feature_num = 50,
  clade_label_level = 5, 
  only_select_show = FALSE,
#group_order = c("TEP","TEPfree-WATER"), 
  group_order =NULL,
  node_size_offset = 1.5,
  annotation_shape = 21,
  annotation_shape_size = 4.5,
  clade_label_size =1,
  alpha = 0.2
)

[data.zip](https://github.com/ChiLiubio/microeco/files/11933372/data.zip)

And if i run ’group_order = c("TEP", "TEPfree-WATER")‘ ，i get the same result but with different warnings like
1: The following aesthetics were dropped during statistical transformation:
node, parent
ℹ This can happen when ggplot fails to infer the correct grouping structure
  in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
  variable into a factor?
but i have already done "data$sample_table$grazing %<>% factor(., levels = c("TEP","TEPfree-WATER"))"

**Comment by ChiLiubio** [comment]
Hi. Adding one step with `tidy_taxonomy` function can temporarily solve this issue.
```
library(microeco)
library(magrittr)
load("data.RData")
data$sample_table$grazing %<>% factor(., levels = c("TEP","TEPfree-WATER"))

data$tax_table %<>% tidy_taxonomy
data$cal_abund()

l1 <- trans_diff$new(
dataset = data,
method = "lefse",
group = "grazing",
taxa_level = "all",
alpha = 0.05,
p_adjust_method = "fdr",
lefse_norm = 1000000,
nresam = 0.6667,
boots = 100,
)

clad <- l1$plot_diff_cladogram(
filter_taxa = 0.0001,
use_taxa_num = 200,
use_feature_num = 50,
clade_label_level = 5,
only_select_show = FALSE,
#group_order = c("TEP","TEPfree-WATER"),
group_order =NULL,
node_size_offset = 1.5,
annotation_shape = 21,
annotation_shape_size = 4.5,
clade_label_size =1,
alpha = 0.2
)
ggplot2::ggsave("test1.png", clad, width = 10, height = 8)
```
Using tidy_taxonomy function can add prefix in each taxonomy level. This can make the taxonomies with same names in different levels to be classified correctly in the function.
