### ISSUE TITLE
Error in trans_diff ancombc2

### ISSUE THREAD

**Issue by zhaohanshuang** [ChiLiubio/microeco#256]
Hi!
    I've been running “t1 <- trans_diff$new(dataset = dataset, method = "ancombc2", group = "Group", taxa_level = "Family")” with the following error, but I've checked my input files and the input file names and numbers are consistent with each other, how can I solve this problem?
  Error in names(x) <- value : 
  'names' attribute [5] must be the same length as the vector [4].
  Thanks!

**Comment by ChiLiubio** [comment]
Hi. 
Could you please attach your dataset so that I can reproduce your error? To save your data, please follow the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function), which is the simplest way. 
Thanks.

**Comment by zhaohanshuang** [comment]
[test_data_diff.zip](https://github.com/ChiLiubio/microeco/files/12023373/test_data_diff.zip)

**Comment by zhaohanshuang** [comment]
Hi,
   I have submitted my data, could you please check it and give a resolution?
   Thanks!

**Comment by ChiLiubio** [comment]
Hi. I have run the steps successfully with your data in a new created project. Version: microeco v0.20.0; ANCOMBC  v2.2.0. Could you please try again in a new project by loading your saved dataset and running the same step? I am still not sure how this error happened exactly.
This is the trans_diff object that I got.
[test_t1.zip](https://github.com/ChiLiubio/microeco/files/12034407/test_t1.zip)
To check the result, please see `t1$res_diff`
