### ISSUE TITLE
Taxa4Fun2: Predicting functions for 18S amplicon data

### ISSUE THREAD

**Issue by rgn06** [ChiLiubio/microeco#257]
Hi Chi,
I am trying to run Taxa4Fun2 for predicting functions for my 18S amplicon data. 
I get error by running:
t1 = trans_func$new(dataset12)

" No Bacteria, Archaea or Fungi found in the Kingdom of tax_table!"

Can you help me with this!
 
Girish

**Comment by ChiLiubio** [comment]
Hi Girish,
I remember Tax4Fun2 is used for 16S gene data. Please check it again.
The reason showing this message " No ..."  is the program does not find bacteria, archaea or fungi infomations in your dataset. Though it is not crutial, it may affect the trait prediction when you use cal_spe_func function. If you make sure your tax_table of dataset12 has good taxonomic assignments, please ignore this message.

Chi

**Comment by rgn06** [comment]
Hi Chi,

Thanks for the help! I will check that again.

Girish
