### ISSUE TITLE
cal_manova error

### ISSUE THREAD

**Issue by DrMaestre** [ChiLiubio/microeco#26]
Hi,

I am trying:

> trans_beta$cal_manova(
+   cal_manova_all = FALSE,
+   cal_manova_paired = FALSE,
+   cal_manova_set = NULL,
+   permutations = 999
+ )

But it says:
Error: attempt to apply non-function

Any idea why it would not be working? Thanks1

**Comment by ChiLiubio** [comment]
Hi,
Could you please show the full code you are running?  Thus, I can repeat the error. Now I can only make sure that this error definitely comes from an incorrect object in which the function cal_manova does not exist.

**Comment by DrMaestre** [comment]
> Hi,
> Could you please show the full code you are running? Thus, I can repeat the error. Now I can only make sure that this error definitely comes from an incorrect object in which the function cal_manova does not exist.

I am converting a phyloseq object to meco and then running that code (I found that adonis has changed to adonis2 and I could make work other pieces of code, but not this one). What could I post here regarding the phyloseq object I start with?

**Comment by DrMaestre** [comment]
Are there packages I should install for this function that are not included in the microeco? Also, when I install microeco from CRAN, even though it does not provide errors, most functions are not present and I have to run the functions code on the side to have them. Maybe that is the problem? Maybe I am not running all of them?

**Comment by DrMaestre** [comment]
Reinstalled from github. Still the same problem. I created a RData to attach it here, but it does not allow me. How can I share it with you?

Thanks!

**Comment by DrMaestre** [comment]
Or if you give me your email, I can email it to you. Thanks so much for your patience.

**Comment by ChiLiubio** [comment]
Hi,
1. Generally,  transfrom your phyloseq object to microtable using function in file2meco, see https://github.com/ChiLiubio/file2meco
2. Please check this part about the use of trans_beta in tutorial of microeco, it is easy to use cal_manova.
3. You can just paste your running code. I guess this is the question of usage, not other issue.

**Comment by DrMaestre** [comment]
Thanks for your help. I do constuct a phyloseq object that works. Then I convert to meco.

meco_hud= phyloseq2meco(RDEF_1000_hud_samples)

dataset=meco_hud

> t1 <- trans_beta$new(dataset = dataset, group = "Code1_recoded", measure = "bray", ordination = "PCoA")
The ordination result is stored in object$res_ordination !
> trans_beta$cal_manova(
+   cal_manova_all = FALSE,
+   cal_manova_paired = FALSE,
+   cal_manova_set = NULL,
+   permutations = 999
+ )
Error: attempt to apply non-function

Do you need anything else?

PS: when I install from Cran or from GitHub, some functions are not included and I had to run them manually. So there may be functions I am not including just because I do not know. 
RStudio Version 1.1.383
Macintosh; Intel Mac OS X 10_11_6 El capitan
I have r version 3.6.2

Thanks!

**Comment by ChiLiubio** [comment]
Hi,
It should be t1$cal_manova  , not trans_beta$cal_manova().  trans_beta is a  class name.

**Comment by DrMaestre** [comment]
Hi,

When I do t1$cal_manova I get this: 

t1$cal_manova
function (cal_manova_all = FALSE, cal_manova_paired = FALSE, 
    cal_manova_set = NULL, permutations = 999) 
{
    use_matrix <- self$use_matrix
    if (!is.null(cal_manova_set)) {
        self$res_manova <- adonis(reformulate(cal_manova_set, 
            substitute(as.dist(use_matrix))), data = self$sample_table, 
            permutations = permutations)
    }
    if (cal_manova_all == T) {
        self$res_manova <- adonis(reformulate(self$group, substitute(as.dist(use_matrix))), 
            data = self$sample_table, permutations = permutations)
    }
    if (cal_manova_paired == T) {
        self$res_manova <- private$paired_group_manova(sample_info_use = self$sample_table, 
            use_matrix = use_matrix, group = self$group, measure = self$measure, 
            permutations = permutations)
    }
    message("The result is stored in object$res_manova !")
}
<environment: 0x12412c580>

What do you think is wrong?

**Comment by DrMaestre** [comment]
I am still having the problem, here the code:

> t1$cal_manova(
+   cal_manova_all = FALSE,
+   cal_manova_paired = FALSE,
+   cal_manova_set = NULL,
+   permutations = 999
+ )
The result is stored in object$res_manova !
> t1$res_manova$aov.tab
NULL

What do you think is happening? Thanks a lot for your help and patience.

**Comment by ChiLiubio** [comment]
Hi,
please see the help document using help(trans_beta). Now, no manova was calculated, as cal_manova_all, cal_manova_paired and cal_manova_set are all not assigned. You should use, at least, one of those three parameters to select the running method. Wish it helps.
