### ISSUE TITLE
Two questions about RDA analysis

### ISSUE THREAD

**Issue by lizhaojie1025** [ChiLiubio/microeco#265]
Hello.
 I have recently been using microeco for full flow analysis of microbiological data and microeco has greatly improved my efficiency. But I am facing several problems with RDA analysis, can you provide some help 
1)`t1$cal_ordination(method = "RDA", taxa_level = "Genus", feature_sel = TRUE)` 
This line of code selects the environment variables by feature_sel = TRUE, I would like to select variables artificially in the environment, for example only pH, TOC and TN, do you have a good solution for this?
2) `t1$cal_ordination(method = "RDA", taxa_level = "Genus", feature_sel = TRUE)` 
`t1$cal_ordination_ envfit() `
I'm trying to calculate the contribution of my filtered environmental variables to the microbial community. t1$cal_ordination_envfit() This line of code is still defaulting all environmental variables to the microbial community. Do you have a good solution for this? 
Thank you very much for taking the time to read my question 
Thanks 
zhaojie

**Comment by ChiLiubio** [comment]
Hi zhaojie,
The easiest way is to select those variables in the object creating step, i.e. something like `trans_env$new(dataset = dataset, add_data = env_data_16S[, c("pH", "TOC")])`. Then you can close the auto feature slection, i.e. `feature_sel = FALSE` in cal_ordination function.

Best,
Chi

**Comment by lizhaojie1025** [comment]
Okay, I got it. Thank you very much. Also, I have a new question that isn't about RDA.
Multi-omics research is an approach to explore the interactions between multiple substances in a biological system. For example, microbiomics is combined with transcriptomics, proteomics，metabolomics and ARGs, etc... Is it possible to build in some multi-omics analysis methods in microeco, such as Procrustes analysis, etc.? 
Thank you very much for taking the time to read my question 
Thanks 
zhaojie

**Comment by ChiLiubio** [comment]
Thanks very much for your suggestion! I will use and evaluate such methods including Procrustes.

Chi
