### ISSUE TITLE
Error running FlashWeave

### ISSUE THREAD

**Issue by eperezv** [ChiLiubio/microeco#266]
Hello,
I am having an issue when running FlashWeave through microeco (latest version) in R.
I am able to run FlashWeave in the command line but not in R, as it gives this error:
```
> t1$cal_network(network_method = "FlashWeave", FlashWeave_other_para = "alpha=0.01,sensitive=true,heterogeneous=false")
Loading required package: igraph

Attaching package: igraph

The following objects are masked from package:stats:

    decompose, spectrum

The following object is masked from package:base:

    union

---------------- 2023-08-06 16:58:15 : Start ----------------
The temporary files are in /tmp/Rtmp6ifMRT ...
Check Julia ...
Run the FlashWeave ...
ERROR: LoadError: InitError: could not load library "/home/eduardo/.julia/artifacts/fe9a6a7b5ad3d5e88aeb1b50e123320f834a19ed/lib/libhdf5.so"
/usr/lib/x86_64-linux-gnu/libcurl.so: version CURL_4 not found (required by /home/eduardo/.julia/artifacts/fe9a6a7b5ad3d5e88aeb1b50e123320f834a19ed/lib/libhdf5.so)
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:114
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:114
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
  [4] __init__()
    @ HDF5_jll ~/.julia/packages/HDF5_jll/rRmEU/src/wrappers/x86_64-linux-gnu-libgfortran4-cxx11-mpi+mpich.jl:15
  [5] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:696
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:782
  [7] _tryrequire_from_serialized(modkey::Base.PkgId, build_id::UInt64, modpath::String)
    @ Base ./loading.jl:711
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:771
  [9] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1020
 [10] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:936
 [11] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:923
during initialization of module HDF5_jll
in expression starting at /tmp/Rtmp6ifMRT/calculate_network.jl:1
Error in read.graph.gml(file, ...) : 
  At rinterface_extra.c:5424 : Cannot read GML file, File operation error
```
I am not sure why it is complaining about /usr/lib/x86_64-linux-gnu/libcurl.so.4 which exists and looks correct in my computer.
Thank you.

**Comment by ChiLiubio** [comment]
Hi. I think the first thing now is to test whether FlashWeave is correctly installed again with your data. It is easy. Please find "/tmp/Rtmp6ifMRT", in which there is a file named "calculate_network.jl". Then enter into this directory and run "julia calculate_network.jl" in the comand line. This file has all the steps of FlashWeave.

**Comment by eperezv** [comment]
Hi. I have tried and it works. This is the output:

`eduardo@eduardo-PC:/tmp/Rtmp9q14QS$ julia calculate_network.jl 

### Loading data ###

### Normalizing ###

Removing variables with 0 variance (or equivalently 1 level) and samples with 0 reads
        -> no samples or variables discarded

Normalization

### Learning interactions ###

Inferring network with FlashWeave - sensitive (conditional)

        Run information:
        sensitive - true
        heterogeneous - false
        max_k - 3
        alpha - 0.01
        sparse - false
        workers - 1
        OTUs - 5501
        MVs - 0

Automatically setting 'n_obs_min' to 20 for enhanced reliability
Computing univariate associations

Univariate degree stats:
Summary Stats:
Length:         5501
Missing Count:  0
Mean:           110.100709
Minimum:        0.000000
1st Quartile:   60.000000
Median:         96.000000
3rd Quartile:   146.000000
Maximum:        453.000000



Starting conditioning search

Preparing workers..

Done. Starting inference..
Starting convergence checks at 8746 edges.
Latest convergence step change: 0.40559
Latest convergence step change: 0.34771
Latest convergence step change: 0.29167
Latest convergence step change: 0.19744

Postprocessing
Complete

Finished inference. Total time taken: 15.982s
`

**Comment by ChiLiubio** [comment]
Hi. It is so strange. The file "calculate_network.jl" is what the program invokes and works. I am still not sure how this happened. If it is still there and you need to use trans_network class for other operations, you can use a tempararilly solution.
```
library(igraph)
# find the result file
network <- read_graph("network_FlashWeave.gml", format = "gml")
network <- set_vertex_attr(network, "name", value = V(network)$label)
V(network)$RelativeAbundance <- t1$data_relabund[V(network)$name]
# then assign network back to your t1 object
t1$res_network <- network
```

Chi

**Comment by eperezv** [comment]
Thanks, I will try that.
