### ISSUE TITLE
font size is small

### ISSUE THREAD

**Issue by mvtejesvi** [ChiLiubio/microeco#268]
Hi,

I am using the bar plots for phyla using the commands below. How can I increase the font size of the legends and taxa names?  what is the command to increase the font size? Font's seems to be too small when we make a panel diagram. 

t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 10)

# t1 object now include the transformed abundance data t1$abund_data and other elements for the following plotting

t1$plot_bar(others_color = "grey70", facet = "Cancer_type", xtext_keep = FALSE, legend_text_italic = FALSE)

Thank you!

Best wishes

Tejesvi

**Comment by ChiLiubio** [comment]
Hi. Please see the help document of ggplot2 theme function, i.e. `help(theme)`. `axis.text` term may be what you need.
