### ISSUE TITLE
Subsetting by Phylum

### ISSUE THREAD

**Issue by calla404** [ChiLiubio/microeco#27]
Hello,

Thank you for making this awesome R package- I am enjoying working with it a lot. I am running into an issue: I would like to subset out the phylum Cyanobacteria after I calculate the total relative abundances and filter out chloroplasts, etc. This is what I have tried:

testDS <- clone(dataset_ASV)
testDS$tax_table %<>% base::subset(Phylum == "Cyanobacteria")
testDS$tidy_dataset()

This doesn't seem to work, however. Any insight into how to subset by Phylum would be greatly appreciated. 
Thank you!

**Comment by ChiLiubio** [comment]
Hi, @calla404 
You can use View(testDS$tax_table) to see whether the content of "Cyanobacteria" in Phylum column is "Cyanobacteria", maybe it is "p__Cyanobacteria". In other words, make sure the command is right: testDS$tax_table %<>% base::subset(Phylum == "Cyanobacteria")
The tax_table in testDS is a data.frame. So you can use any method to subset the table, such as more flexible function grepl().
It is general useful to see the print result line by line in such operations as those steps is important and not complicated to check. If ok, then use tidy_dataset.
like the following steps:

testDS <- clone(dataset_ASV)
testDS
testDS$tax_table %<>% base::subset(Phylum == "p__Cyanobacteria")
testDS
testDS$tidy_dataset()

**Comment by calla404** [comment]
Hello, thank you very much for your response. I followed your suggestion and when I look at the table using View(testDS$tax_table) after subsetting I only have Cyanobacteria in the table. Additionally, just entering "testDS" shows the correct numbers in the tax table and OTU table.

However, when I make a stacked bar graph I get all of the other phyla that should have been removed. Here is how I made the graphs. 

testDS_plot <-trans_abund$new(dataset = testDS, taxrank = "Order", ntaxa = 7)
testDS_plot$plot_bar(others_color = "grey70", facet = "WaterLocation", xtext_keep = TRUE, xtext_type_hor = FALSE, legend_text_italic = FALSE)

Thanks again for your help!

**Comment by ChiLiubio** [comment]
Hi,
Do you use testDS$cal_abund() to recalculate the taxonomic abundance after using testDS$tidy_dataset()? The trans_abund class invoke the taxa_abund stored in microtable object. I guess this is the point in that problem.

**Comment by calla404** [comment]
Hello,
When I recalculate using cal_abund() my stacked bar graph shows the relative abundance of cyanobacteria to be 100%, but I was hoping to use the relative abundances of cyanobacteria in the total population to make the graphs and do statistical analyses on. If there's not a way to subset out taxa like this I can just do it by hand and import the relative abundance info into microeco for analysis, no big deal. 
Thank you!

**Comment by ChiLiubio** [comment]
Hi,
If so, it is easy to manipulate the taxa_abund stored in your microtable object directly. You can delete the taxa that you donnot need. Another way is to manipulate the intermediate file after generating your trans_abund object. All the plotting functions in trans_abund class depend on this intermediate taxa table. Wish it helps.

**Comment by calla404** [comment]
Hello, 
Would you mind giving me an example of how to delete the taxa I don't need in the microtable object? I'm unfamiliar with the microtable class and am not having luck figuring it out. 
Thank you!

**Comment by ChiLiubio** [comment]
Hi,

library(microeco)
data("dataset")
View(dataset$taxa_abund$Order)

dataset$taxa_abund$Order is a data.frame table. You can reassign this table like the following pseudo code:

dataset$taxa_abund$Order <- dataset$taxa_abund$Order[grepl("p__Cyanobacteria"", rownames(dataset$taxa_abund$Order)),  ]

Wish it helps.
Chi

**Comment by calla404** [comment]
This works perfectly. I really appreciate the time and effort you put in to help me with this. Thanks again!
