### ISSUE TITLE
Change the name of the axes and the name of the variables from English to Spanish in the graphs

### ISSUE THREAD

**Issue by jimena18-O** [ChiLiubio/microeco#270]
Hi. I appreciate if you can help me with the following.

I want to change the name of the y-axis "relative abundance (%)" to "Abundancia relativa (%)"

# select top 8 abundant Phyla.
t1 <- trans_abund$new(dataset = meco_dataset, taxrank = "Phylum", ntaxa = 8)

abundanciarelativa<-t1$plot_bar(others_color = "grey70", facet = "trat", xtext_keep = FALSE, legend_text_italic = FALSE)
# return a ggplot2 object

Thanks!

**Comment by ChiLiubio** [comment]
Please try:
```
abundanciarelativa  <- abundanciarelativa + ylab("Abundancia relativa (%)")
```
