### ISSUE TITLE
cal_cor. Environmental factors and some important taxa

### ISSUE THREAD

**Issue by jimena18-O** [ChiLiubio/microeco#271]
I want to do the correlation analysis between the environmental factors and some important taxa detected in the biomarker analysis. 

The first error I had was the following:

> t1 <- trans_env$new(dataset = meco_dataset, add_data = filtered_add_data)
Error in initialize(...) : 
  No valid rowname in add_data! Rownames must be sample names in the input add_data!

and then:

> t1$cal_cor(use_data = "other", p_adjust_method = "fdr", other_taxa = t2$res_diff$Taxa[1:40])
Find non-numeric columns in the object$data_env: winter ID_trat Sample trat.1 zona ...
Remove non-numeric columns ...
Error in cor.test.default(abund_table[groups == x[1], x[2]], env_data[groups ==  : 
  not enough finite observations

I started from a phyloseq object.

meco_dataset <- phyloseq2meco(psd4)
meco_dataset

The variables to be correlated were not in the metadata because they were later added.

I appreciate if you can help me. 
From already thank you very much

**Comment by ChiLiubio** [comment]
Hi.
The message shows 'No valid rowname in add_data! Rownames must be sample names in the input add_data!'. The rownames of your provided `filtered_add_data` must be sample names same with the `sample_table` of `meco_dataset`. Please use `View(meco_dataset$sample_table)` to see the correct sample names.

**Comment by jimena18-O** [comment]
thanks!

I was able to fix it with the following script:

new_test <- clone(meco_dataset)
new_test$sample_table <- data.frame(new_test$sample_table, env_adddata_barrow[rownames(new_test$sample_table), ])
# now new_test$sample_table has the whole data
new_test

**Comment by jimena18-O** [comment]
and now It doesn't work the next:

> t2 <- trans_diff$new(dataset = new_test, method = "lefse", group = "trat", taxa_level = "Genus")
Start Kruskal-Wallis rank sum test for trat ...
25 taxa found significant ...
After P value adjustment, 8 taxa found significant ...
Minimum LDA score: 2.87740430083684 maximum LDA score: 3.88294676223486
Taxa abundance table is stored in object$res_abund ...
lefse analysis result is stored in object$res_diff ...

> t1$cal_cor(use_data = "other", p_adjust_method = "fdr", other_taxa = t2$res_diff$Taxa[1:40])
Error in cor.test.default(abund_table[groups == x[1], x[2]], env_data[groups ==  : 
  not enough finite observations

Thanks

**Comment by ChiLiubio** [comment]
Hi. Could you attach your data so that I can reproduce your issue? To save your dataset, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object. Both the `new_test` and `filtered_add_data` are needed.

**Comment by jimena18-O** [comment]
[env_adddata_barrow.xlsx](https://github.com/ChiLiubio/microeco/files/12430235/env_adddata_barrow.xlsx)
[new_tet.zip](https://github.com/ChiLiubio/microeco/files/12430309/new_tet.zip)
[meco_dataset.zip](https://github.com/ChiLiubio/microeco/files/12430310/meco_dataset.zip)
