### ISSUE TITLE
Cal_cor: Not all variable in the correlation matrix

### ISSUE THREAD

**Issue by RoyDibakar** [ChiLiubio/microeco#272]
I want to analyze the correlation between environmental variables and each marker species.

I noticed that each group is not correlating with each variable.
I did - 
dataset1 <- microtable$new(sample_table = sam_data, otu_table = otu_data, tax_table = tax_data)
variable = read.csv("corr_variable.csv", header = TRUE, sep = ",", row.names = 1)
new_test <- clone(dataset1)
new_test$sample_table <- data.frame(new_test$sample_table, variable[rownames(new_test$sample_table), ])
View(new_test$sample_table)
t1 <- trans_env$new(dataset = new_test, env_cols = 24:34)
t2 <- trans_diff$new(dataset = new_test, method = "lefse", group = "Group", taxa_level = "Species", p_adjust_method = "none")
t1$cal_cor(by_group = "Group", use_data = "other", p_adjust_method = "fdr", p_adjust_type = "Env", other_taxa = t2$res_diff$Taxa[1:50])
t1$plot_cor()

**Comment by ChiLiubio** [comment]
Hi. Could you provide more details on the results? If it is complicated to show, is it fine to attach your data so that I can reproduce your issue? To save your dataset, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by RoyDibakar** [comment]
Hi,
I did t1$cal_cor() function to obtain the correlation between the environmental variables. The result matrix (t1$res_cor()) doesnot contain all the variables such as gender, therapeutics (they are in the t1$data_env()).. I am attaching the Rdata file and the codes. 
[Microeco.zip](https://github.com/ChiLiubio/microeco/files/12474878/Microeco.zip)

**Comment by ChiLiubio** [comment]
Hi. When we use `View(new_test$sample_table)` to check the metadata, we find that in three columns, all the values are same, i.e. all are 1. The Warning message in the cal_cor process all show this. Same values cannot be used to get covariances.

**Comment by RoyDibakar** [comment]
Hi,
Thank you very much for your reply.
Then, how should I represent the sample_data on the basis of gender (e.g. male) or therapeutics (e.g. yes)?

**Comment by ChiLiubio** [comment]
Maybe the data preparation is good, and no more operation is need. So more samples with different values?

**Comment by RoyDibakar** [comment]
Thank you for your response and suggestion.
I will try to do that.
