### ISSUE TITLE
About trans_diff$plot_diff_abund function: reorder taxa according to P.adj

### ISSUE THREAD

**Issue by kestlermai** [ChiLiubio/microeco#273]
Hi,  

The trans_diff$plot_diff_abund function by default sorts the species based on p-values in ascending order. Currently, I would like to change this sorting method, for example, to sort based on the total abundance.

I appreciate if you can help me solve this problem

**Comment by ChiLiubio** [comment]
Hi.

Good question! The parameter `select_taxa` can do that. Provided features by the param select_taxa will be used to select the taxa from the result and resort the result by the provided order. Here is an example.

```
library(microeco)
library(magrittr)
data(dataset)
t1 <- trans_diff$new(dataset = dataset, method = "KW", group = "Group", taxa_level = "Genus", filter_thres = 0.001)
# filter those non-significant
diff_table <- t1$res_diff %>% .[grepl("*", .$Significance, fixed = TRUE), ]
# select 20 to show
diff_taxa <- diff_table$Taxa[1:20] %>% gsub(".*\\|", "", .)
# the raw abundane table has been sorted by the mean abundance (similar to total abundance), so we can directly use them
raw_order <- rownames(dataset$taxa_abund$Genus) %>% gsub(".*\\|", "", .)
raw_order %<>% .[. %in% diff_taxa]
# use select_taxa
t1$plot_diff_abund(select_taxa = raw_order, add_sig = T)
```

**Comment by kestlermai** [comment]
It works very well, thank you very much for your assistance.

**Comment by bioinfo17** [comment]
Hi,
A similar question when I run anova/kw and the results are in the order below:

"Taxa","Method","Group","Letter","Significance"
"k__Eukaryota|p__Basidiomycota|c__Microbotryomycetes|f__Sporidiobolales|o__Sporidiobolaceae|g__Sporobolomyces","anova","asymptomatic","a","a"
"k__Eukaryota|p__Basidiomycota|c__Microbotryomycetes|f__Sporidiobolales|o__Sporidiobolaceae|g__Sporobolomyces","anova","symptomatic","a","a"
"k__Eukaryota|p__Ascomycota|c__Dothideomycetes|f__Pleosporales|o__Didymellaceae|g__Didymella","anova","asymptomatic","a","a"
"k__Eukaryota|p__Ascomycota|c__Dothideomycetes|f__Pleosporales|o__Didymellaceae|g__Didymella","anova","symptomatic","a","a"
"k__Eukaryota|p__Ascomycota|c__Dothideomycetes|f__Dothideales|o__Saccotheciaceae|g__Aureobasidium","anova","symptomatic","a","a"
"k__Eukaryota|p__Ascomycota|c__Dothideomycetes|f__Dothideales|o__Saccotheciaceae|g__Aureobasidium","anova","asymptomatic","a","a"
"k__Eukaryota|p__Basidiomycota|c__Microbotryomycetes|f__Sporidiobolales|o__Sporidiobolaceae|g__Rhodotorula","anova","asymptomatic","a","a"
"k__Eukaryota|p__Basidiomycota|c__Microbotryomycetes|f__Sporidiobolales|o__Sporidiobolaceae|g__Rhodotorula","anova","symptomatic","b","b"
"k__Eukaryota|p__Ascomycota|c__Dothideomycetes|f__Pleosporales|o__Pleosporaceae|g__Alternaria","anova","symptomatic","a","a"
"k__Eukaryota|p__Ascomycota|c__Dothideomycetes|f__Pleosporales|o__Pleosporaceae|g__Alternaria","anova","asymptomatic","a","a"

How can I plot only the significant ones and not the top 10 ones in the order above?

Code:
t1 <- trans_diff$new(dataset = mt1, method = "KW", group = "Health", taxa_level = "Genus", filter_thres = 0.0001)
t1$plot_diff_abund(use_number = 1:10, add_sig = T, coord_flip = F)

Thanks
