### ISSUE TITLE
trans_network

### ISSUE THREAD

**Issue by Hobgoblin8** [ChiLiubio/microeco#275]
Excuse me,
What code is used to calculate these  node-level topological features (degree, betweenness, closeness, and eigenvector centrality) for each node?
thank you.

**Comment by ChiLiubio** [comment]
Hi. Please try to use `get_node_table` function in `trans_network` class.

**Comment by Hobgoblin8** [comment]
Sorry. I didn't get closeness and eigenvector centrality using 'get_node_table' function.

**Comment by ChiLiubio** [comment]
Hi. 
Sorry.  I forgot to add these two centrality indexes in the function yesterday. I have updated the package in the github. Please reinstall it from github and try again. Thanks.

Best,
Chi
