### ISSUE TITLE
order_x_mean in plot_alpha not working

### ISSUE THREAD

**Issue by benedil** [ChiLiubio/microeco#28]
Hello, 
I'm having a problem plotting alpha diversity metrics using the order_x_mean parameter.  After looking at the other issues involving ordering the x axis labels, I just updated the package and reran my code but the problem is still there.  The x axis labels continue to be ordered the way they are listed in my sample info object.  This happens with all the metrics, but here is an example:

> talpha_Uni0Am_mergeLocation <- trans_alpha$new(dataset = Uni0Am, group = "Location")

![TransAlphaChao1ScreenGrab](https://user-images.githubusercontent.com/51459375/117378650-b62c2b80-ae8a-11eb-9b8b-d699c9c22011.png)

> talpha_Uni0Am_mergeLocation$plot_alpha(add_letter = F, measure = "Chao1", order_x_mean = TRUE)

![Chao1_Disordered](https://user-images.githubusercontent.com/51459375/117378672-bf1cfd00-ae8a-11eb-82d0-ff093a90a1cd.png)

Am I doing something wrong?

Thank you,
LSmith

**Comment by ChiLiubio** [comment]
Hi,
Currently, I can not make sure the reasons according to your descriptions. It is strange. Could you save and paste your 'Uni0Am' dataset? Then, I can repeat and debug your issue.

Chi

**Comment by benedil** [comment]
Chi -- I'm sorry, I'm new to both github and R and don't know how to do that.  I'm not sure which format to save the microtable object as so that it will paste here and will open properly.  Googling has not been helpful so far.

LSmith

**Comment by ChiLiubio** [comment]
Hi,
Please save your microtable dataset using the command: 
save(Uni0Am, file = "Uni0Am.RData")
Send Uni0Am.RData to my email  liuchi0426@126.com

**Comment by benedil** [comment]
The email has been sent--thank you!

**Comment by benedil** [comment]
Thank you!  I had only updated to the latest release in CRAN, getting the v0.4.0 from github fixed the issue.
