### ISSUE TITLE
The metagenomics code

### ISSUE THREAD

**Issue by CYBERBOY1210** [ChiLiubio/microeco#280]
Hi there, I need to use the metagenomic code of the package to compare the functional variation between two soil types. Could you please tell me the format and kind of data used as input in the code? (e.g. EXDATA,example_metagenome_sample_info.tsv, )

**Comment by ChiLiubio** [comment]
Hi. Please first install file2meco package (https://github.com/ChiLiubio/file2meco). Then use `?file2meco` to get each help document link of functions.  There is a detailed description on the sample_table parameter.
