### ISSUE TITLE
Merge two otu tables

### ISSUE THREAD

**Issue by MiaCoco** [ChiLiubio/microeco#283]
I have 30 microbiomes from sampling in summer and they are all sequenced in same run and have same OTU table, and there is antoher sampling done in winter also with 30 samples that share same OTU table. Is there a way to combined those two OTU tables as well as other files in one microeco object (R6) or maybe to make two R6 object for each OTU table, but then how to compare them and make statistical tests to show differences between summer and winter regarding multiple analysis? Is there options where I can call in same function some samples from first R6 object and some samples from second R6 object for further analysis ?

**Comment by ChiLiubio** [comment]
So two OTU tables are generated by two sepearte sequencing experiments and analysis?

**Comment by MiaCoco** [comment]
Yes, they were done by separate sequencing experiments but on same device and same quality of raw data and same depth of sequencing

**Comment by ChiLiubio** [comment]
May you perform bioinformatic analysis for all the samples to generate only one OTU/ASV table?

**Comment by MiaCoco** [comment]
So I should start from raw sequences to do that. That is possibility in case that there is no way to analysed one OTU table against other OTU table in your programm, and I was hoping that could be done, because we are short on time :/
