### ISSUE TITLE
Taxonomic rank names 

### ISSUE THREAD

**Issue by alecbiom** [ChiLiubio/microeco#284]
Hello, 

First of all, I loved the way this package makes microbiome analysis more easy and beautiful to interpret.

But I am now getting this plot bars with all taxonomic rank names, and I only want the name of the rank that i am choosing. Don't want all the higher names.

![dcbd792f-5fd8-4fbb-9660-095f290debe4](https://github.com/ChiLiubio/microeco/assets/97246443/2907be8d-bd94-4e8b-9359-946f3b52493e)

![f98db50c-9e74-40ab-ad36-4d5677a33766](https://github.com/ChiLiubio/microeco/assets/97246443/1c2dfa77-7a66-43bd-9dcd-7fa1c557e567)

How do I remove all higher taxonomic rank names?

Thank you so much!

**Comment by ChiLiubio** [comment]
Hi,

Please read this part (https://chiliubio.github.io/microeco_tutorial/other-examples-1.html#tidy_taxonomy-function) to understand the mechanism by which the higher tax names can be deleted or remained. To solve the issue, please follow the steps in the second one (https://github.com/ChiLiubio/microeco/issues/22) as I copy and paste here:
```
your_microtable$tax_table %<>% tidy_taxonomy
your_microtable$tidy_dataset()
your_microtable$cal_abund()
# then run trans_abund
```

Best,
Chi

**Comment by alecbiom** [comment]
Hello,

Thank you so much! 
It all went well!!

Best,
Alec
