### ISSUE TITLE
dbRDA flipping vector directions

### ISSUE THREAD

**Issue by spencerlong1** [ChiLiubio/microeco#285]
Hi Chi,

I have noticed an issue with plotting of dbRDA outputs in trans_env. I am finding that a lot of the time, the outputted plot is flipping the vectors across the axis, so that they are pointing in the wrong direction. For instance, my envfit can be like so: 
![image](https://github.com/ChiLiubio/microeco/assets/75384881/2f08355e-84e5-4269-a632-eb04f482a7b3)

but the graph out put will look like this: 
![image](https://github.com/ChiLiubio/microeco/assets/75384881/58b62877-55d2-4f27-96fa-2d4a406ce374)

where e.g. salinity has been flipped on RDA2, and so has temperature and nitrite. I have a few examples of this and can provide more, if needed, but I think the function is losing the - sign in some cases? or using the negative values incorrectly? the magnitude seems to be correct, and RDA1 always seems to be correct, but RDA2 fitted vectors sometimes flip.

here is my code, it doesnt deviate too much from the tutorial: 
#18S Tam
env_microtable_18S_tam <- trans_env$new(dataset = trans_microtable_18S_tam, env_cols = c(15:18,20), complete_na = TRUE)
env_microtable_18S_tam$cal_ordination(method = "dbRDA", use_measure = "bray", taxa_level = "genus")
env_microtable_18S_tam$trans_ordination(show_taxa = 10, adjust_arrow_length = TRUE)
env_microtable_18S_tam$res_ordination_R2

tam_dbRDA_asv_plot_18S <- env_microtable_18S_tam$plot_ordination(plot_color = "sample", 
                                                                 plot_shape = "sample", 
                                                                 color_values = c("green4","orchid4", "red1", "darkorange1"),
                                                                 shape_values = c(16, 18, 15, 17), 
                                                                 point_size = 4, 
                                                                 plot_type = c("point"), 
                                                                 add_sample_label = "salinity", 
                                                                 env_text_color = "blue", 
                                                                 env_arrow_color = "blue") + 
  ggtitle("Eukaryotes: Tamar Estuary")
tam_dbRDA_asv_plot_18S
env_microtable_18S_tam$cal_ordination_anova()
dbrda_anova_18S_tam <- env_microtable_18S_tam$res_ordination_terms
env_microtable_18S_tam$cal_ordination_envfit()
env_microtable_18S_tam$res_ordination_envfit

**Comment by ChiLiubio** [comment]
Sorry for the delay. This issue has been fixed from v1.3.0. Now v1.4.0 in CRAN is also released. Thanks.
