### ISSUE TITLE
网络分析中无法成功运行CPU多线程

### ISSUE THREAD

**Issue by purplesoil** [ChiLiubio/microeco#286]
作者您好，microeco包是一个非常优秀的包。
但是我在运行该包的trans_network时候，遇到了一个问题。
我的CPU是14700K，最高支持28个线程。但是在运行下面这行代码时，CPU占用很低，仅有2-3个线程在工作。
t1 <- trans_network$new(dataset = dataset, cor_method = "sparcc", use_sparcc_method = "SpiecEasi", taxa_level = "OTU", 
                        filter_thres = 0.0001, nThreads = 28, SparCC_simu_num = 100)
After filtering, 1276 features are remained ...
到目前为止已经运行将近9个小时了，依旧没有结果。所以想请问一下作者，能否提供一些建议。非常感谢。

**Comment by ChiLiubio** [comment]
您好，这个方法确实慢，特别是数据集较大的时候，估计还是底层优化的不够好。
