### ISSUE TITLE
extracting p-values and correlation from cal_spe_func result

### ISSUE THREAD

**Issue by galud27** [ChiLiubio/microeco#288]
Hi! 
I'm working on this tutorial on fungi/ funguild network plot https://chiliubio.github.io/microeco_tutorial/other-dataset.html#fungi-data and I wanted to see if there's a way to extract the correlation value and p-value of the module associated to different guilds and trophic mode. 
If I do: 
t2$res_spe_func_perc  I get the modules and guilds is there a way to get the correlation value and p value if using WGCNA when making the network. 

Thank you!

**Comment by ChiLiubio** [comment]
Hi. This method is used to get the percentage or abundance of guilds in each module. So there is no correlation here.

**Comment by galud27** [comment]
Thank you!
