### ISSUE TITLE
Tax4Fun2 is not assigning functions to half of my samples 

### ISSUE THREAD

**Issue by ignerocha-f** [ChiLiubio/microeco#29]
Hi Chi!
I've been having some issue with the tax4fun2, since half of my samples did not got any functional annotation, which is observed using the previous tax4fun.

This is my workflow:

cattle_core_dataset
microtable class:
sample_table have 27 rows and 4 columns
otu_table have 20 rows and 27 columns
tax_table have 20 rows and 7 columns
Taxa abundance: calculated for Kingdom,Phylum,Class,Order,Family,Genus,Species 

t1_func_cattle <- trans_func$new(cattle_core_dataset)
dir.create("test_prediction_cattle_core")

t1_func_cattle$cal_tax4fun2(
  blast_tool_path = "C:\\Users\\ferna\\Documents\\Tax4Fun2\\ncbi-blast-2.11.0+\\bin", 
  path_to_reference_data = "C:\\Users\\ferna\\Documents\\Tax4Fun2",
  path_to_temp_folder = "test_prediction_cattle_core", 
  database_mode = "Ref99NR")

trans_func class:
An object for prok analysis.
sample_table is available.
otu_table is available.
tax_table is available.
rep_fasta is available.

pathway_file <- t1_func_cattle$res_tax4fun2_pathway 
pathway_file2 = pathway_file[ -c(29,30,31)] #this columns are the level1, 2, and 3
rownames(pathway_file2) <- pathway_file2[,1]
pathway_file3 <- pathway_file2[,-1]
#
ko_map_tax = pathway_file %>% select(pathway,level1,level2, level3)
rownames(ko_map_tax) <- ko_map_tax[,1]
ko_map_tax2 = ko_map_tax[ -c(1)]
#
func_cattle_core1 <- microtable$new(otu_table = pathway_file3, tax_table = ko_map_tax2, sample_table = t1_func_cattle$sample_table)
print(func_cattle_core1)

After that I got a incorrect number of samples (9):
microtable class:
sample_table have 27 rows and 4 columns
otu_table have 226 rows and 9 columns
tax_table have 341 rows and 3 columns
--
For some reason the tax4fun2 did not annotated functions for half of my samples, all of then from the same group of samples (low disease). However, when I performed the previous tax4fun, it runs correctly, covering all my samples.
Am I making a mistake in some of the steps?

Thank you!

**Comment by ChiLiubio** [comment]
Hi, @ignerocha-f 
The tax_table of cattle_core_dataset only have 20 rows? only 20 OTU/ASV ?
The key method of tax4fun2 depend on the finding of close relatives with the alignment threshold. So less taxa can probably affect the performance of this method. In addition, in this case, using "Ref100NR" may also help improve the results. In the intermediate log files, you can see how many taxa are mapped to the effective species (close relative). This can also help evaluate the performance.

**Comment by ignerocha-f** [comment]
Hi, @ChiLiubio 
Thanks for your prompt response!

Yes, it is only 20 ASVs because is a core microbiota (65% prevalence of my row data).

I'll try to use the "Ref100NR" to check if something change.

Best,

**Comment by ignerocha-f** [comment]
In your opinion is there any huge difference between tax4fun and tax4fun2 in terms of accuracy?
