### ISSUE TITLE
change color

### ISSUE THREAD

**Issue by jimena18-O** [ChiLiubio/microeco#292]
Hi, I can change the color of my treatments; for example, Treat AE1, AE2, AE3, and CV. I want them to be in the colors 'aquamarine4,' 'aquamarine3,' 'aquamarine2,' and 'coral3,' respectively. 

Thanks

Best regard

**Comment by ChiLiubio** [comment]
In which function? Do you have a problem in the color assignment of the parameter?

**Comment by jimena18-O** [comment]
in this three functions:

t1$plot_alpha(measure = "Chao1", add_sig_text_size = 6, boxplot_add = "jitter", order_x_mean = TRUE)

t1$plot_ordination(plot_color = "Group", plot_shape = "Group", plot_type = c("point", "ellipse"))

t1$plot_group_distance(boxplot_add = "mean")

**Comment by ChiLiubio** [comment]
Please check the help document to find the parameter. For example, in plot alpha, it is `color_values` parameter.
