### ISSUE TITLE
Error: Input colors are not enough to use 

### ISSUE THREAD

**Issue by bingheer** [ChiLiubio/microeco#293]
Hi! Thanks for your resource, I benefit greatly from your contribution. I am in trouble when I draw figures using “plot_bar, plot_box, polt_donut, plot_line, plot_pie, plot_radar“, and I always get an error as is showed in the figure below. When drawing the first 10 OUTs, the color is not enough and the picture label is missing. Is there any method to solve this problem?

Best regards!
![question1](https://github.com/ChiLiubio/microeco/assets/152047380/8f6e3968-3e47-4e08-bceb-49ece04b8b39)
![question](https://github.com/ChiLiubio/microeco/assets/152047380/13184c40-cb33-4130-9ff4-4733a57c2ed5)

**Comment by ChiLiubio** [comment]
Sorry. I cannot open the picture with some unknown reasons. Could you please provide a complete step to let us to reproduce your issue, including the code, data and your pckages version?

**Comment by bingheer** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChiLiubio/microeco"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月26日(星期天) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChiLiubio/microeco] Error: Input colors are not enough to use  (Issue #293)





 
Sorry. I cannot open the picture with some unknown reasons. Could you please provide a complete step to let us to reproduce your issue, including the code, data and your pckages version?

**Comment by bingheer** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ChiLiubio/microeco" ***@***.***&gt;; 发送时间:&nbsp;2023年11月26日(星期天) 下午3:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ChiLiubio/microeco] Error: Input colors are not enough to use (Issue #293) Sorry. I cannot open the picture with some unknown reasons. Could you please provide a complete step to let us to reproduce your issue, including the code, data and your pckages version? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

We use R 4.1.0 to do this work. The code and data are attached to the upload.
[code_and_data.zip](https://github.com/ChiLiubio/microeco/files/13476489/code_and_data.zip)

**Comment by ChiLiubio** [comment]
Hi. If you run `unique(dataset$tax_table$Phylum)`, you can find there is a "" in the result. The solution is to use `tidy_taxonomy` function as we show in the tutorial (https://chiliubio.github.io/microeco_tutorial/other-examples-1.html#tidy_taxonomy-function). The following is the full steps.
```

library(microeco)
library(ggplot2)
library(magrittr)

dataset$tax_table %<>% tidy_taxonomy
dataset$cal_abund()

t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 10)
t1$plot_bar(others_color = "grey70", facet = "Group", xtext_keep = FALSE, legend_text_italic = FALSE)
```
The message of colors means you select 10 taxa, but default color_values parameter has only 8. To complete the plot, the function automatically add the colors.

**Comment by bingheer** [comment]
Thanks for the quick reply！

It's very useful to use tidy_taxonomy() to clean taxonomy table and make a uniform taxonomy information. Then solve this problem.

Thank you very much.
