### ISSUE TITLE
Distance attenuation relationship

### ISSUE THREAD

**Issue by makerer5** [ChiLiubio/microeco#296]
Hi Chi!
Distance decay of community composition heterogeneity is one of the fundamental patterns in biogeography, but I don't seem to find the relevant calculation process in the trans_env class, and I have to use other R codes to complete the relevant calculations.
If you could tell me how to accomplish "Distance decay relationship" in microeco, I would be very grateful!
Thank you very much
Mark

**Comment by ChiLiubio** [comment]
Hi Mark,
Thanks. The `plot_scatterfit` function in trans_env can help do the distance decay analysis. As its help document shows, the input x or y can be symmetric matrix. The tutorial also has some demonstrations about that. As to the geographic distance matrix, please prepare one for the input.

Best,
Chi

**Comment by makerer5** [comment]
I'm sorry if I didn't express my thoughts clearly
In my idea, I want to use the plot_scatterfit function to plot the relationship between latitude and longitude and Bray-Curtis Dissimilarity. I went back and carefully watched the tutorials and examples of the plot_scatterfit function, and I didn’t find anything related to “geo <- data.frame(df$Longitude, df$Latitude)
d.geo <- distm(geo, fun = distHaversine)" similar function. 
In addition, I also want to know, y_axis "Euclidean distance of pH", is pH calculated based on the Euclidean distance?

**Comment by ChiLiubio** [comment]
Hi. The function needs a prepared matrix for the input, so there is no such function to transform geo distance for longi and lati currently. We will consider implementing one. Thanks. Yes it is Euclidean.
