### ISSUE TITLE
cal_mantel_corr()

### ISSUE THREAD

**Issue by chrissy005** [ChiLiubio/microeco#297]
Hi @ChiLiubio,

I was following your  tutorial on the null models https://chiliubio.github.io/microeco_tutorial/model-based-class.html#trans_nullmodel-class and have a few questions.

Apart from the manual, do you have a detailed description of the functions in the microeco package?

1) If t1$cal_mantel_corr(use_env = NULL), then how exactly is the correlogram plotted and what matrices are used? In this case would it be the community matrix and all the environmental variables? How is the phylogenetic distance calulated in this case?

**Comment by chrissy005** [comment]
Thank you for the clarification. I was not aware that this function internally generates a tree.

Sorry I did not phrase my question properly. What I meant is that if no particular environmental variable is provided to the function such as :
t1$cal_mantel_corr() instead of t1$cal_mantel_corr(use_env = "pH")
Does it mean that the all the variables in the dataset will be used as the niche dissimilarity matrix and will correlate with the phylo matrix?

**Comment by ChiLiubio** [comment]
Yes. As the help document shows, if it is NULL, the function will use PCA to generate representative dimension for the further dissimilarity matrix.
