### ISSUE TITLE
More than 1 or 2 environmental data in microtable

### ISSUE THREAD

**Issue by biazen123** [ChiLiubio/microeco#301]
Dears
Hello

I want to use microeco package and then go through its tutorial dataset to check the functionality of all required packages including its possibility for microbial downstream analysis.

I know it is possible to make a microtable including sample information, ASV/OTU data, Taxa data, environmental, phylogenetic tree, and its generated alpha and beta diversities. In my case, I have plant abundance matrix data (separated as shrub and tree layers) and soil prokaryotic and fungi datasets and practice correlating the microbial diversities with that of the plants at different layers using this package.  My second or additional plant data (for shrub and tree layers) is a matrix and may be managed as that of the microbial data.

Can you please suggest some information or indicate a possible function for the following issues?
1. how is the vegetation matrix data included with others in the micro table?
2. how to run both vegetation matrix and environmental data as environmental factors? 
3. Indicator genus or species and its correlation with specific factor, for example, soil pH, as in the tutorial
4. finally, how to multivariate correlations (shrub, tree, soil microbial diversities, and environmental data).

Regards.

**Comment by ChiLiubio** [comment]
Hi. 
1 & 2. How about including vegetation matrix data with environmental factors for the analysis. In my viewpoint, vegetation seems like to be a table like env factors. If you require further suggestion, kindly provide a more specified description.
3. In the tutorial, there has been some examples about that, e.g. the rf and correlation heatmap example part in trans_env class. Please check it again. 
4. correlation heatmap or masslin2? Both can be used for the multivariate analysis and are available in cal_cor of trans_env class. 

Best.

**Comment by biazen123** [comment]
> Hi. 1 & 2. How about including vegetation matrix data with environmental factors for the analysis. In my viewpoint, vegetation seems like to be a table like env factors. If you require further suggestion, kindly provide a more specified description. 3. In the tutorial, there has been some examples about that, e.g. the rf and correlation heatmap example part in trans_env class. Please check it again. 4. correlation heatmap or masslin2? Both can be used for the multivariate analysis and are available in cal_cor of trans_env class.
> 
> Best.

Dears
Thank you very much for your suggestion.
For vegetation taxa data, I have matrix abundance data (shrub and tree taxa abundance matrix) like that of the microbial abundance matrix.

Can I make a dataset in a microtable containing both tree taxa matrix, shrub taxa matrix, and soil bacterial ASV and taxa matrix as dataframe or process separately and then correlate? the sample information is similar.

Many thanks!

**Comment by ChiLiubio** [comment]
Sure. You can. For correlation analysis, it is also fine to treat tree and shrub taxa matrix as environmental factors to do correlation with ASV.

**Comment by biazen123** [comment]
> Sure. You can. For correlation analysis, it is also fine to treat tree and shrub taxa matrix as environmental factors to do correlation with ASV.

Hi Chi
Thanks for your suggestions. I am practicing microeco, a new experience for me as far as I am a beginner in bioinformatics.

I am trying to illustrate the influences of biotic (plant metrics) and abiotic (soil physicochemical properties) factors on a Diversity of fungal and bacterial communities using partial Mantel tests. 

In addition, I want to plot or overlay it with the pairwise comparisons between biotic and abiotic factors (eg. Pearson's correlation) in the Microeco package. 

Can you please share or suggest to me some scripts/functions to run and plot them if applicable?

Best Regards!

**Comment by ChiLiubio** [comment]
Hi. It is easy for partial mantel test by setting the parameter `partial_mantel = TRUE` in `cal_mantel` function in `trans_env` class. Please have a try. Could you please explain more about 'pairwise comparisons between biotic and abiotic factors'?

**Comment by biazen123** [comment]
> Hi. It is easy for partial mantel test by setting the parameter `partial_mantel = TRUE` in `cal_mantel` function in `trans_env` class. Please have a try. Could you please explain more about 'pairwise comparisons between biotic and abiotic factors'?

Dears
Thank you very much for your suggestions.
What I want to mean by "A pairwise comparison between biotic and abiotic factors" is to display both the partial mantel test (factors on soil bacterial and fungal diversities) and the correlation analysis (between biotic and abiotic factors) results in one plot.

Best regards.

**Comment by ChiLiubio** [comment]
Hi. For this goal, there is no ready-made method for drawing. I think you can use ggplot2 to have a try.
