### ISSUE TITLE
plot_bar yields different scale for relative abundance when using high_level

### ISSUE THREAD

**Issue by lixiaopi1985** [ChiLiubio/microeco#304]
Hi,

Thank you for this great package!

When I tried to plot the abundance in bars, I got the wrong scale of the relative abundance. See the picture below:

```
guild.abund.epi = trans_abund$new(meco.epi, taxrank = "Guild", ntaxa = 10, groupmean = "Season", high_level = "Trophic_mode")
season.plot.epi = guild.abund.epi$plot_bar()
```

![image](https://github.com/ChiLiubio/microeco/assets/37941906/5d1defe2-6c32-4c04-bd4a-14b0d2faa033)

Tried to plot with ggnested, the scale also changed but still wrong:

`season.plot.epi = guild.abund.epi$plot_bar(ggnested = T)`

![image](https://github.com/ChiLiubio/microeco/assets/37941906/5d286e99-c9b0-45b8-9eef-2620ff7c0280)

Do you know how could I fix this?

And, if there is a way to reorder the legend label so that "others" can be placed in the last for the first plot?

Thank you

**Comment by ChiLiubio** [comment]
Hi. I guess the abundance data (taxa_abund list) in your meco.epi is not so-called standard relative abund. It probably has been the relative abundance * 100. If so, please add the parameter `use_percentage = FASLE` in your `trans_abund$new` and adjust the y axis title text. For more examples, please follow the metagenome data part of tutorial (https://chiliubio.github.io/microeco_tutorial/other-dataset.html#metagenomic-data), in which the abundance is RPK, not the relative abund. In the amplicon data, we generally use relative abundance ranging from 0 to 1. So the default function in trans_abund will first multiply the abund by 100 to be the percentage.

For the "others" in the legend lable, do you mean only moving the label to the bottom and do not change any plot contents? If so, the legend order will be opposite with the order in the plot?

For the second plot, ggnested method is currently only designed and tested for the amplicon data with standard taxonomic lineages. I have not tested this methd for the guild data. I will add it in the to-do list. Thanks.
