### ISSUE TITLE
trans_env class CCA module title error

### ISSUE THREAD

**Issue by makerer5** [ChiLiubio/microeco#305]
Hi！
Chi
I found that when calculating CCA using "t1$cal_ordination(method = "CCA", taxa_level = "Genus")" in trans_env class CCA module, t1$plot_ordination(plot_color = "Group", plot_shape = "Group", plot_type = c ("point", "ellipse")) will only show RDA and not CCA, can this be corrected
Your friend
Maker

**Comment by ChiLiubio** [comment]
Hi Maker,
Thanks very much! I have fixed it in github. New CRAN version will be released in the coming days.

Best,
Chi

**Comment by ChiLiubio** [comment]
Thanks. V1.4.0 in CRAN is released.
