### ISSUE TITLE
significance letter in plot_diff

### ISSUE THREAD

**Issue by DpennaS** [ChiLiubio/microeco#309]
Dear Dr. Chi,
I want to align the significance letter in the plot_diff function and just the position in the plot, but i am not being able to find a way inside the microeco package. I think that could have a parameter in the function similar to add_sig_text_size. But being add_sig_xposition =, and add_sig_yposition.

Thanks for the attention!

**Comment by ChiLiubio** [comment]
Hi. 
Please use the `y_start` and `y_increase` parameters to control the position of significance labels. Sorry for that these two params have a different prefix with others. `y_start` is for start y position of asterisk label. `y_increase` can be used for the letter of anova and kw_dunn. Please feel free to tell me if you have better suggestions for the parameters. Thanks.

Best,
Chi

**Comment by DpennaS** [comment]
Oh now i understood

Thanks for the response!

Best,
Penna
