### ISSUE TITLE
cal_Tax4Fun2 stuck at "filtering otu_table"

### ISSUE THREAD

**Issue by benedil** [ChiLiubio/microeco#31]
Hello,
I'm trying to get the functional annotation to work using Tax4Fun2 and have gotten stuck about halfway through (I think around line 548 of the source code in trans_func.R).  Here are the relevant lines from my code and the log returns:

tf_Uni0AmTax <- trans_func$new(Uni0Am)
dir.create("Tax4Fun2_prediction")
tf_Uni0AmTax$cal_tax4fun2(blast_tool_path = "ncbi-blast-2.11.0+/bin", 
                          path_to_reference_data = "Tax4Fun2_ReferenceData_v2", 
                          path_to_temp_folder = "Tax4Fun2_prediction",
                          database_mode = "Ref99NR", normalize_by_copy_number = T, 
                          min_identity_to_reference = 97, num_threads = 2)

the last command returns:

 database_mode is stored in object$res_tax4fun2_database_mode!
 Generate blast reference database.
 Reference database finished.
 Blast start.
 Blast finished
 Cleanup finished
 Using minimum idenity cutoff of 97% to nearest neighbor
 Error in aggregate.data.frame(x = otu_table_reduced[, -1, drop = FALSE],  : 
                                 no rows to aggregate

I'm not sure why I have no rows to aggregate or where I should be looking in my dataset to try and fix this.  Please let me know if there is more information or files I can provide.

Thank you again for your help--learning this package has been a fun adventure so far!

LSmith

**Comment by ChiLiubio** [comment]
Hi
Please first check the log file in "Tax4Fun2_prediction" to see whether the prediction is normal. Also check the balst result file content. I guess this issue come from the less effective mapping result. If failed, tell me. I will check your dataset and codes line by line.

**Comment by benedil** [comment]
Here's the log:
[logfile.txt](https://github.com/ChiLiubio/microeco/files/6470006/logfile.txt)

(I think) ref_blast shows 246 of my OTUs were identified in the db.  That is roughly 1% of my total OTUs, but that's not unexpected for environmental samples. 
[ref_blast.txt](https://github.com/ChiLiubio/microeco/files/6470058/ref_blast.txt)

I don't honestly know if these things indicate success or failure of the commands up to this point.

**Comment by ChiLiubio** [comment]
Hi,
Currently, I am not sure where this issue comes from. I need the data to check it. Could you save and paste your Uni0Am dataset like the last time? The dataset you send me last me donot have fasta seqs.

**Comment by ChiLiubio** [comment]
Hi,
Your otu_table have 218374 rows. Why do you only have 246 representative sequences?

**Comment by benedil** [comment]
Because I followed the instructions in the README exactly and misunderstood the purpose of the representative fasta.  .fna is not a file format I'm familiar with and did not recognize that file name as something I needed to replace with a file specific to my dataset.  I run my pipeline through mothur, which does not generate .fna files as far as I know.  Will filetomeco accept .fasta format in the rep_fasta file location, or do I need to convert it?

**Comment by ChiLiubio** [comment]
Hi,
I mean that so few fasta sequences are strange. Generally, the representative sequence number should be larger than the final OTU number, as the following filtering can reduce effective OTU number. No matter what platform is used, OTU must be generated based on the representative sequences. So please first check the file. I have not used mothur for a long time and can not remember the details. This is just a fasta file. No convertion should be made.

**Comment by benedil** [comment]
Yes, I just tried reading in the fasta file using seqinr, but the file is 1.9GiB and I run out of space for it.  The command just errored out: cannot allocate vector of size 15Kb.  My workspace is completely empty, so I'm not sure what to do to try and make it work.

**Comment by ChiLiubio** [comment]
Oh, yes. I miss that you have a large number of taxa. In the example dataset, there is about 4Mb for about 10 thousand sequences. This is an unavoidable issue using tax4fun2 method. Is it possible to reduce the effective OTU number with some filtering thresholds?

**Comment by benedil** [comment]
Hi Chi,
Yes, I think I can further filter my input files to reduce the file sizes.  Thank you for your help!
LSmith

**Comment by zina-R** [comment]
Hi Chi, 
I am tring to run this Tax4Fun2 test  for mu data set also. it looks that the this package is no more available on github. 
i have an error can you help me to solve it plz.
While running this code 
```
makeFunctionalPrediction(path_to_otu_table = "E:\\cc\\Desktop\\Tax4Fun\\SWARM_table_curated.tsv", 
                         path_to_reference_data = "E:\\cc\\Desktop\\Tax4Fun\\Tax4Fun2_ReferenceData_v2/", 
                         path_to_temp_folder = "E:\\cc\\Desktop\\Tax4Fun\\prediction/", 
                         database_mode = "Ref100NR", min_identity_to_reference = 0.97, normalize_by_copy_number = T, normalize_pathways = F)
```
> Using minimum idenity cutoff of 97% to nearest neighbor
> Erreur dans FUN(X[[i]], ...) : 'type' (character) de l'argument incorrect

I get this error and i dont konw how to fix it 
Thank you

**Comment by juanmluque** [comment]
Hi Chi,
I also am trying to run the next function of Tax4Fun2 with **Windows**, but the output gives me error (**using otu_table.tsv or otu_table.txt):**

> makeFunctionalPrediction(path_to_otu_table = "D:/Users/Usuario/Documents/Ejercicio_otu_table.tsv",  path_to_reference_data = "D:/Users/Usuario/Documents/Tax4Fun2_ReferenceData_v2/", path_to_temp_folder = "D:/Users/Usuario/Documents/Tax4Fun2_ReferenceData_v2/temp_folder", database_mode = "Ref100NR", normalize_by_copy_number = T, min_identity_to_reference = 0.97, normalize_pathways = F) 

Using minimum idenity cutoff of 97% to nearest neighbor
Error in aggregate.data.frame(x = otu_table_reduced[, -1], by = list(otu_table_reduced[,  : 
  no rows to aggregate

>  makeFunctionalPrediction(path_to_otu_table = "D:/Users/Usuario/Documents/Ejercicio_otu_table.txt",  path_to_reference_data = "D:/Users/Usuario/Documents/Tax4Fun2_ReferenceData_v2/", path_to_temp_folder = "D:/Users/Usuario/Documents/Tax4Fun2_ReferenceData_v2/temp_folder", database_mode = "Ref100NR", normalize_by_copy_number = T, min_identity_to_reference = 0.97, normalize_pathways = F) 

Using minimum idenity cutoff of 97% to nearest neighbor
Error in aggregate.data.frame(x = otu_table_reduced[, -1], by = list(otu_table_reduced[,  : 
  no rows to aggregate

I don´t know if my problem is the kind of otu_table file (txt or tsv file):

> write.table(t(foo), sep = "\t", "D:/Users/Usuario/Documents/Ejercicio_otu_table.txt", quote = F)
> t(foo)
       AshokSample1 AshokSample10 AshokSample11 AshokSample12 AshokSample13 AshokSample2 AshokSample3 AshokSample4 AshokSample5 AshokSample6 AshokSample7 AshokSample8 AshokSample9
ASV_1             1             7             0             7             1            0            0            2            0            3            9            1            0
ASV_2             2             2             0             0             0            0            0            0            2            0            0            1            0
ASV_3             0             0             0             0             1            0            0            0            1            0            0            1            0
ASV_4             0             2             0             0             0            0            0            0            0            0            0            0            0
ASV_5             0             1             1             0             0            0            0            0            0            0            0            0            0
ASV_6             0             0             2             0             0            0            0            0            0            0            0            0            0
ASV_7             0             0             0             0             1            0            0            0            0            1            0            0            0
ASV_8             0             0             0             0             0            2            0            0            0            0            0            0            0
ASV_9             0             0             0             0             0            2            0            0            0            0            0            0            0
ASV_10            0             0             0             0             0            2            0            0            0            0            0            0            0
ASV_11            0             0             0             0             0            1            0            0            1            0            0            0            0
ASV_12            0             0             0             0             0            0            1            0            0            0            0            0            1
ASV_13            0             0             0             0             0            0            0            0            2            0            0            0            0
ASV_14            0             0             0             0             0            0            0            0            0            0            0            0            2
ASV_15            0             1             0             0             0            0            0            0            0            0            0            0            0
ASV_16            0             0             1             0             0            0            0            0            0            0            0            0            0
ASV_17            0             0             0             0             1            0            0            0            0            0            0            0            0
ASV_18            0             0             0             0             0            0            1            0            0            0            0            0            0
ASV_19            0             0             0             0             0            0            0            0            0            1            0            0            0
ASV_20            0             0             0             0             0            0            0            0            0            1            0            0            0
ASV_21            0             0             0             0             0            0            0            0            0            0            1            0            0
ASV_22            0             0             0             0             0            0            0            0            0            0            1            0            0
ASV_23            0             0             0             0             0            0            0            0            0            0            0            1            0
ASV_24            0             0             0             0             0            0            0            0            0            0            0            1            0

The otu_table.txt is :

      AshokSample1	AshokSample10	AshokSample11	AshokSample12	AshokSample13	AshokSample2	AshokSample3	AshokSample4	AshokSample5	AshokSample6	AshokSample7	AshokSample8	AshokSample9
ASV_1	1	7	0	7	1	0	0	2	0	3	9	1	0
ASV_2	2	2	0	0	0	0	0	0	2	0	0	1	0
ASV_3	0	0	0	0	1	0	0	0	1	0	0	1	0
ASV_4	0	2	0	0	0	0	0	0	0	0	0	0	0
ASV_5	0	1	1	0	0	0	0	0	0	0	0	0	0
ASV_6	0	0	2	0	0	0	0	0	0	0	0	0	0
ASV_7	0	0	0	0	1	0	0	0	0	1	0	0	0
ASV_8	0	0	0	0	0	2	0	0	0	0	0	0	0
ASV_9	0	0	0	0	0	2	0	0	0	0	0	0	0
ASV_10	0	0	0	0	0	2	0	0	0	0	0	0	0
ASV_11	0	0	0	0	0	1	0	0	1	0	0	0	0
ASV_12	0	0	0	0	0	0	1	0	0	0	0	0	1
ASV_13	0	0	0	0	0	0	0	0	2	0	0	0	0
ASV_14	0	0	0	0	0	0	0	0	0	0	0	0	2
ASV_15	0	1	0	0	0	0	0	0	0	0	0	0	0
ASV_16	0	0	1	0	0	0	0	0	0	0	0	0	0
ASV_17	0	0	0	0	1	0	0	0	0	0	0	0	0
ASV_18	0	0	0	0	0	0	1	0	0	0	0	0	0
ASV_19	0	0	0	0	0	0	0	0	0	1	0	0	0
ASV_20	0	0	0	0	0	0	0	0	0	1	0	0	0
ASV_21	0	0	0	0	0	0	0	0	0	0	1	0	0
ASV_22	0	0	0	0	0	0	0	0	0	0	1	0	0
ASV_23	0	0	0	0	0	0	0	0	0	0	0	1	0
ASV_24	0	0	0	0	0	0	0	0	0	0	0	1	0
[Ejercicio_otu_table.txt](https://github.com/ChiLiubio/microeco/files/9495843/Ejercicio_otu_table.txt)

 Could you help me, please, to solve this error?.

Thank you very much.
