### ISSUE TITLE
Taxonomic names in LeFSe plot

### ISSUE THREAD

**Issue by DpennaS** [ChiLiubio/microeco#316]
Hi!

I am doing a barplot with LeFSe results. I am using all taxa levels, and I have as results, for example, Comamonadaceae as a family and Comamonadaceae Family as a Genus. There is a parameter inside the function to prevent ploting both of them?

Best,
Penna

**Comment by ChiLiubio** [comment]
Hi. You can delete those taxa by manipulating the data `res_diff` like this.
```
tmp <- your_object$res_diff 
# filter some
tmp <- tmp[tmp$Taxa != ".............something.............", ]
your_object$res_diff <- tmp
# then plot
```

Best,
Chi

**Comment by DpennaS** [comment]
Got it, 
Thanks,
Penna
