### ISSUE TITLE
 trans_env plot_scatterfit #Error in private$check_scatterfit_input(y, "y") :    #The input y is neither a vector nor a matrix !

### ISSUE THREAD

**Issue by xinguo1236** [ChiLiubio/microeco#317]
when I run t1$plot_scatterfit(
    x = "Oxygen", 
    y = dataset$beta_diversity$bray[rownames(t1$data_env), rownames(t1$data_env)], 
    type = "cor",
    point_size = 3, point_alpha = 0.1, 
    label.x.npc = "center", label.y.npc = "bottom", 
    x_axis_title = "Euclidean distance of pH", 
    y_axis_title = "Bray-Curtis distance"
    )
Error in private$check_scatterfit_input(y, "y") :    #The input y is neither a vector nor a matrix !

Is anything I can do to solve the problem? Many thanks if anyone can help.

**Comment by ChiLiubio** [comment]
Hi. As you donot send me `dataset`, I cannot repeat it. It seems like your `dataset$beta_diversity$bray[rownames(t1$data_env), rownames(t1$data_env)]` is not a matrix. Please check it. If it is still there, please also send me `dataset` to have a try.

**Comment by xinguo1236** [comment]
Hi, dataset have sent to your email yesterday. Could&nbsp; you help me? Thanks a lot.



---Original---
From: "Chi ***@***.***&gt;
Date: Sun, Feb 4, 2024 12:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ChiLiubio/microeco]  trans_env plot_scatterfit #Error inprivate$check_scatterfit_input(y, "y") :    #The input y is neither a vectornor a matrix ! (Issue #317)




 
Hi. As you donot send me dataset, I cannot repeat it. It seems like your dataset$beta_diversity$bray[rownames(t1$data_env), rownames(t1$data_env)] is not a matrix. Please check it. If it is still there, please also send me dataset to have a try.

**Comment by ChiLiubio** [comment]
Hi. It is ok after I use `t1$dataset` to replace `dataset`, which is the data that I say.
```
t1$plot_scatterfit(
    x = "Oxygen", 
    y = t1$dataset$beta_diversity$bray[rownames(t1$data_env), rownames(t1$data_env)], 
    type = "cor",
    point_size = 3, point_alpha = 0.1, 
    label.x.npc = "center", label.y.npc = "bottom", 
    x_axis_title = "Euclidean distance of pH", 
    y_axis_title = "Bray-Curtis distance"
    )
```
