### ISSUE TITLE
  missing value where TRUE/FALSE needed with cal_diff(method = "anova")

### ISSUE THREAD

**Issue by MarwaElnaiem** [ChiLiubio/microeco#319]
Dear all, 

I would like to conduct an ANOVA test (one-way) on my alpha diversity data using the following code:
  <alpha_all_w <- trans_alpha$new(dataset = alpha_all_w, group = "Land_use", by_group = "Site")>
  <alpha_all_w$cal_diff(method = "anova")>

I received the following error message:

Error in if (pvalue[k] <= 0.001) sig[k] <- "***" else if (pvalue[k] <=  : 
  missing value where TRUE/FALSE needed
I received this error only with anova, but when I chose KW for example it worked.

Would you please help? 

herein is my data that stored in object$data_stat ...
 Land_use    Measure N        Mean          SD           SE
1  Bare Land   Observed 6  98.0000000 21.80825532  8.903182951
2  Bare Land      Chao1 6  98.0000000 21.80825532  8.903182951
3  Bare Land        ACE 6  98.0000000 21.80825532  8.903182951
4  Bare Land    Shannon 6   3.3480186  0.33172712  0.135427030
5  Bare Land    Simpson 6   0.9258425  0.02588890  0.010569100
6  Bare Land InvSimpson 6  15.8187103  8.28732655  3.383286895
7  Bare Land     Fisher 6  14.1272708  3.53602641  1.443576739
8  Bare Land   Coverage 6   1.0000000  0.00000000  0.000000000
9      Mango   Observed 6 187.5000000 64.31096330 26.254840823
10     Mango      Chao1 6 187.5000000 64.31096330 26.254840823
11     Mango        ACE 6 187.5000000 64.31096330 26.254840823
12     Mango    Shannon 6   4.2211353  0.76516089  0.312375627
13     Mango    Simpson 6   0.9582465  0.05045097  0.020596523
14     Mango InvSimpson 6  45.4471125 27.45852344 11.209895255
15     Mango     Fisher 6  29.7054617 11.90347213  4.859572147
16     Mango   Coverage 6   1.0000000  0.00000000  0.000000000
17   Sorghum   Observed 6 117.0000000 28.38309356 11.587349424
18   Sorghum      Chao1 6 117.0000000 28.38309356 11.587349424
19   Sorghum        ACE 6 117.0000000 28.38309356 11.587349424
20   Sorghum    Shannon 6   3.9427693  0.26374207  0.107672250
21   Sorghum    Simpson 6   0.9630763  0.01352859  0.005523024
22   Sorghum InvSimpson 6  29.6153724  8.54690227  3.489258241
23   Sorghum     Fisher 6  17.3657294  4.42202369  1.805283612
24   Sorghum   Coverage 6   1.0000000  0.00000000  0.000000000

Regards

**Comment by ChiLiubio** [comment]
Hi. 
It seems like same with one topic (https://github.com/ChiLiubio/microeco/issues/311) a few days ago. I have fixed it by skiping the failed comparison. To solve it temporarily, please try to update the package from github.

Best,
Chi

**Comment by MarwaElnaiem** [comment]
Thanks very much.
