### ISSUE TITLE
'No significant taxa' error message with trans_diff

### ISSUE THREAD

**Issue by AmalHmaiss** [ChiLiubio/microeco#322]
Hello, thank you for the package, it's really a good tool for begginers with R.
I would like to create a correlation matrix between taxa abundance numbers and environmental conditions. For that, I'm using trans_diff, trans_env and cal_cor.
The problem is when I try to create a trans_diff object with my data
I get this error message:
![Capture d’écran 2024-02-16 121312](https://github.com/ChiLiubio/microeco/assets/132219694/f15728cb-941e-48e9-a6bc-44fbb485b81a)

Thank you in advance for your help,

**Comment by ChiLiubio** [comment]
Hi. It show that no significant feature is found under current parameters setting. Please try to use `alpha = 0.05`.

**Comment by AmalHmaiss** [comment]
Thank you for your reply, I still receive the same error message : 
<img width="716" alt="Capture d’écran 2" src="https://github.com/ChiLiubio/microeco/assets/132219694/c5811011-1abb-4a6e-901d-30336f7a0632">

**Comment by ChiLiubio** [comment]
This means there is actually no significantly differential taxa among the groups in "Origin".

**Comment by AmalHmaiss** [comment]
Hello, thank you again for your reply, I changed the group to sample ID and I still receive the same error message. Does this mean that I can't generate a correlation matrix between sample characteristics and the relative abundance of taxa using the microeco package? The main reason why I waunt to create a trans_diff object is to generate the correlation matrix ?Is there another way to visualize it ?

<img width="484" alt="Capture d’écran 2024-02-17 222838" src="https://github.com/ChiLiubio/microeco/assets/132219694/bd7052ca-d583-44f7-ad3e-c6319ae3333f">

Thank you,

**Comment by ChiLiubio** [comment]
Hi. The trans_diff class and lefse method in it is used to find the differential features by lefse across all the taxonomic lineages. Given that no significant feature is found, the groups have no difference in terms of the taxa. You can also use other method in trans_diff class to try again.

**Comment by AmalHmaiss** [comment]
Thank you so much I changed the method to KW and it works now
