### ISSUE TITLE
how to creat trans_alpha and trans_beta in genus level 

### ISSUE THREAD

**Issue by milyzhou** [ChiLiubio/microeco#329]
Hi, LIU
I created taxonomic table by HUMAnN3， I want to know that which level dose the trans_alpha and trans_beta use to analyze?and is it possible to restrct the analysis to the genus level? 

Thank you

**Comment by ChiLiubio** [comment]
Hi @milyzhou,
Theoretically, I think it is feasible to do trans_alpha and trans_beta at each taxonomic level or pathway level for HUMAnN results, depending on the explained question. To restrict the analysis to genus, you can use `cal_abund` function and `rel = FALSE` parameter to get the RPK table at genus level and recreate a microtable object using this table.

**Comment by milyzhou** [comment]
Thank you!  
I tryed to builded it followed tutorial and it worked!
dataset <- mpa2meco("buglist_clean.tsv", sample_table =metadata)
test <- dataset$merge_taxa(taxa = "Genus")
and I will follow you suggesstion check my table again.
