### ISSUE TITLE
The problem in phylo_tree_16S

### ISSUE THREAD

**Issue by Yuhuan-Zou** [ChiLiubio/microeco#33]
Hi, Chi
    Firstly, thank you for your hard in this package which is an excellent platform to analyse our data.

I started by working through the example (https://chiliubio.github.io/microeco/#trans_nullmodel_class) but I can't understand the phylo_tree_16S and its format. Through the help(microeco), I only found it was created by ape package. I was in a dilemma how to create the similar format with my own 16S data. Could you help me?

**Comment by ChiLiubio** [comment]
Hi,
This phylo_tree_16S example data is the phylogenetic tree created by the software FastTree. It is the newick format. Actually, no mattter what software you use for the phylogenetic tree reconstruction, the default reading function can handle the format. So the point is you should first create the tree using representive sequences of OTU/ASV. There is complete description on how to do this in QIIME official manual. Please check it out. In addition, the phylogenetic tree is also necessary to calculate phylogenetic diversity, such as  Unifrac distance.

**Comment by Yuhuan-Zou** [comment]
Thank you for your pratical help!!
