### ISSUE TITLE
taxa_abund =null

### ISSUE THREAD

**Issue by Elixir0822** [ChiLiubio/microeco#330]
Hello，chi
I want to trans the phyloseq format to microeco and do Lefse analysis，but the taxa_abund is null
> dataset <- phyloseq2meco(ps)
> dataset
microtable-class object:
sample_table have 15 rows and 1 columns
otu_table have 274 rows and 15 columns
tax_table have 274 rows and 7 columns
phylo_tree have 274 tips
rep_fasta have 274 sequences
> dataset$taxa_abund
NULL
> lefse <- trans_diff$new(dataset = dataset, 
+                         method = "lefse", 
+                         group = "Group", 
+                         alpha = 0.01, 
+                         lefse_subgroup = NULL,
+                         p.adjust.methods=)
No taxa_abund list found. Calculate it with cal_abund function ...
The result is stored in object$taxa_abund ...
489 input features ...
442 features are remained after removing unknown features ...
Start Kruskal-Wallis rank sum test for Group ...
12 taxa found significant ...
After P value adjustment, 0 taxa found significant ...
Error in private$check_taxa_number(sel_taxa, p_adjust_method) : 
  No significant feature found! To disable p value adjustment, please use p_adjust_method = "none"!

**Comment by ChiLiubio** [comment]
Hi. The message shows there is no significant feature. Please use `alpha = 0.05` and try again. Donot worry abunt taxa_abund. The function can automatically calculate and get taxa_abund when it is NULL.
![图片](https://github.com/ChiLiubio/microeco/assets/20815519/89da5c59-a3d9-49b7-b844-4cf707ad75aa)

**Comment by Elixir0822** [comment]
Thank you so much！
