### ISSUE TITLE
Error in guides_train(scales = scales$non_position_scales(), theme = theme,  :    could not find function "guides_train"

### ISSUE THREAD

**Issue by PPpissar** [ChiLiubio/microeco#331]
Hello,

This error was introduced after the update of ggplot2 from version 3.4.0 to 3.5.0. Even  with the new update of microeco today this problem was not solve.

>t2$plot_tern()

Input colors are not enough to use. Add more colors automatically via color interpolation ...
Registered S3 methods overwritten by 'ggtern':
  method           from   
  grid.draw.ggplot ggplot2
  plot.ggplot      ggplot2
  print.ggplot     ggplot2

Error in guides_train(scales = scales$non_position_scales(), theme = theme,  : 
  could not find function "guides_train"

What can we do?

**Comment by ChiLiubio** [comment]
Hi. Yes. The ggplot2 3.5.0 has a new guide system (https://github.com/tidyverse/ggplot2/releases). The ggtern package in CRAN is built based on the previous ggplot2 version. It is not easy to solve by simply adding a function. How about installing a ggplot2 3.4 to do it temporarily.

**Comment by PPpissar** [comment]
Hi, I have already tried this but because of the many packages linked to ggplot2 I get this

 Error in unloadNamespace(package) : namespace ‘ggplot2’ is imported by ‘ggplotify’, ‘patchwork’, ‘microbiome’, ‘ggfun’, ‘phyloseq’, ‘ggpubr’, ‘ggtree’, ‘aplot’, ‘microeco’ so cannot be unloaded

**Comment by ChiLiubio** [comment]
Hi. The author of ggtern package has updated it in CRAN and solved the issue by forcing ggplot2 >= 3.5. Please reinstall the ggtern and try again.

**Comment by PPpissar** [comment]
Thank you very much! I have done the update and it's working fine!!!


Best,

Panayiota



Sent from my Galaxy



-------- Original message --------
From: Chi Liu ***@***.***>
Date: 30/03/2024 07:08 (GMT+02:00)
To: ChiLiubio/microeco ***@***.***>
Cc: Panayiota Pissaridou ***@***.***>, Author ***@***.***>
Subject: Re: [ChiLiubio/microeco] Error in guides_train(scales = scales$non_position_scales(), theme = theme, : could not find function "guides_train" (Issue #331)


Hi. The author of ggtern package has updated it in CRAN and solved the issue by forcing ggplot2 >= 3.5. Please reinstall the ggtern and try again.
