### ISSUE TITLE
d1 <- dataset$merge_taxa(taxa = "Genus") Error in check_tax_level(taxa, self) : 没有"check_tax_level"这个函数

### ISSUE THREAD

**Issue by xinguo1236** [ChiLiubio/microeco#333]
Hello,

d1 <- dataset$merge_taxa(taxa = "Genus")
Error in check_tax_level(taxa, self) : 没有"check_tax_level"这个函数

What can I do?

Thanks.

**Comment by ChiLiubio** [comment]
Hi. Do you load the package? Please try to run the following example with the data inside the package.
```
library(microeco)
dataset$merge_taxa(taxa = "Genus")
```

**Comment by xinguo1236** [comment]
I followed your instructions and ran the command, but I'm still getting an error. Can you help me with this?> library(microeco)
> dataset$merge_taxa(taxa = "Genus")
Error in check_tax_level(taxa, self) : 没有"check_tax_level"这个函数



***@***.***
 
发件人： Chi Liu
发送时间： 2024-03-07 21:37
收件人： ChiLiubio/microeco
抄送： xinguo1236; Author
主题： Re: [ChiLiubio/microeco] d1 <- dataset$merge_taxa(taxa = "Genus") Error in check_tax_level(taxa, self) : 没有"check_tax_level"这个函数 (Issue #333)
Hi. Do you load the package? Please try to run the following example with the data inside the package.
library(microeco)
dataset$merge_taxa(taxa = "Genus")

**Comment by ChiLiubio** [comment]
Please provide the microeco package version.

**Comment by xinguo1236** [comment]
v 1.5.0. I still meet the same error. Thank you. dataset$merge_taxa(taxa = "Genus")
Error in check_tax_level(taxa, self) : 没有"check_tax_level"这个函数.



***@***.***
 
发件人： Chi Liu
发送时间： 2024-03-08 15:37
收件人： ChiLiubio/microeco
抄送： xinguo1236; Author
主题： Re: [ChiLiubio/microeco] d1 <- dataset$merge_taxa(taxa = "Genus") Error in check_tax_level(taxa, self) : 没有"check_tax_level"这个函数 (Issue #333)
Please provide the microeco package version.

**Comment by wangcxv** [comment]
@ChiLiubio 

Hi Chi, 
I met the similar issues:
when using the v1.5.0, but an error showed "Error in meco2phyloseq(dataset) : could not find function "meco2phyloseq"", I can not fix it, could you tell me how to deal with it?
P.s. : similar errors as "Error: object 'trans_norm' not found".
Thanks!

**Comment by ChiLiubio** [comment]
@wangcxv  Do you install `file2meco` package? If not, please install it first. I suggest you update your microeco to v1.6 as trans_norm has been moved to microeco v1.6.0 from mecodev package. So all you need to do is to update microeco package and install file2meco package.

**Comment by wangcxv** [comment]
![image](https://github.com/ChiLiubio/microeco/assets/41507812/f59a9861-706e-41c6-ba16-d8283b6fd114)
Yes, I update microeco package (v1.6.1) and install file2meco package, but there are still some errors as: "Error: object 'trans_rarefy' not found"/"Error in meco2phyloseq(dataset) : could not find function "meco2phyloseq""

**Comment by wangcxv** [comment]
@ChiLiubio 
![image](https://github.com/ChiLiubio/microeco/assets/41507812/1c9dda81-f6a9-4175-a479-408d3d7af6d3)
yes, I updated microeco package and installed file2meco package, but there are still errors: "Error in meco2phyloseq(dataset) : could not find function "meco2phyloseq" " 、“Error: object 'trans_rarefy' not found”, etc.

**Comment by ChiLiubio** [comment]
Which class/function are you using? Please attach the codes.

**Comment by wangcxv** [comment]
I found the problem, i just installed and loaded the package "mecodev", it works well now. Thanks!
