### ISSUE TITLE
t1 <- trans_diff$new(dataset = dataset, method = "metagenomeSeq", group = "Group", taxa_level = "Genus") #Error in h(simpleError(msg, call)) : Error in evaluating 'x' argument for selecting a method for the 'unique' function: There is no function called "setkey". 

### ISSUE THREAD

**Issue by xinguo1236** [ChiLiubio/microeco#335]
t1 <- trans_diff$new(dataset = dataset, method = "metagenomeSeq", group = "Group", taxa_level = "Genus") #Error in h(simpleError(msg, call)) : Error in evaluating 'x' argument for selecting a method for the 'unique' function: There is no function called "setkey".

**Comment by ChiLiubio** [comment]
Hi. I suggest you reinstall metagenomeSeq package and run the examples in `vignette("metagenomeSeq")` to test the package.

**Comment by xinguo1236** [comment]
I have reinstalled the metagenomeSeq package as you suggested. Running vignette("metagenomeSeq") now automatically loads its documentation. However, executing t1 <- trans_diff$new(dataset = dataset, method = "metagenomeSeq", group = "Group", taxa_level = "Genus")
  still gives an error 522 input features ...
Total 6 paired group for calculation ...
Run 1 : A - B ...

Error in h(simpleError(msg, call)) : 
  在为'unique'函数选择方法时评估'x'参数出了错: 没有"setkey"这个函数. Can you help me with this issue?"



***@***.***
 
From: Chi Liu
Date: 2024-03-07 21:43
To: ChiLiubio/microeco
CC: xinguo1236; Author
Subject: Re: [ChiLiubio/microeco] t1 <- trans_diff$new(dataset = dataset, method = "metagenomeSeq", group = "Group", taxa_level = "Genus") #Error in h(simpleError(msg, call)) : Error in evaluating 'x' argument for selecting a method for the 'unique' function: There is no function called "setkey". (Issue #335)
Hi. I suggest you reinstall metagenomeSeq package and run the examples in vignette("metagenomeSeq") to test the package.

**Comment by ChiLiubio** [comment]
Can you run the examples in vignette successfully? Please also attach the dataset. I will have a try. To save the dataset, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by xinguo1236** [comment]
Yes，I can run vignette("metagenomeSeq") successfully. However, executing t1 <- trans_diff$new(dataset = dataset, method = "metagenomeSeq[", group = "Group", taxa_level = "Genus")
  still gives an error Error in h(simpleError(msg, call)) : 
  在为'unique'函数选择方法时评估'x'参数出了错: 没有"setkey"这个函数 .I have attached the dataset. Thank you.



***@***.***
 
From: Chi Liu
Date: 2024-03-08 15:41
To: ChiLiubio/microeco
CC: xinguo1236; Author
Subject: Re: [ChiLiubio/microeco] t1 <- trans_diff$new(dataset = dataset, method = "metagenomeSeq", group = "Group", taxa_level = "Genus") #Error in h(simpleError(msg, call)) : Error in evaluating 'x' argument for selecting a method for the 'unique' function: There is no function called "setkey". (Issue #335)
Can you run the examples in vignette successfully? Please also attach the dataset. I will have a try. To save the dataset, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by ChiLiubio** [comment]
Hi. I donot find the data in the atttachment. Please attach it in the github.
