### ISSUE TITLE
Error in rep(1, nrow(edges)) When running plot_diff_cladogram

### ISSUE THREAD

**Issue by Harr7y** [ChiLiubio/microeco#338]
Hi, when I am running **plot_diff_cladogram**, an strange error occured.

"""
Select 50 significant features ...
Provided use_taxa_num: 200 >=  total effective taxa number. Skip the selection ...
Error in rep(1, nrow(edges)) : invalid 'times' argument
"""

Can you help me to solve it? Besides,  it works when I run **plot_diff_bar**.

**Comment by ChiLiubio** [comment]
Hi. 
Could you please attach your data and steps so that I can reproduce your issue? To save your microtable object, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by Harr7y** [comment]
[dataset.zip](https://github.com/ChiLiubio/microeco/files/14570272/dataset.zip)
Thanks, attached is a part of my data, which has the same error.

The dataset is generated with:
`
dataset <- microtable$new(sample_table = sample_table,
                          otu_table = feature_table, 
                          tax_table = tax_table)
`

**Comment by ChiLiubio** [comment]
Hi. Please also attach all the steps. I need to reproduce your issue. The dataset you attached cannot be found! Please send it to me via email (liuchi0426@126.com).

**Comment by ChiLiubio** [comment]
For v1.7.0, when such error is coming, the function will return a stop message that "The parent and child nodes are not correctly recognized! Please try to use tidy_taxonomy function to tidy taxonomic table in your microtable object! Then rerun cal_abund function and trans_diff class!". This means you should use `tidy_taxonomy` function to clean up your taxonomic table which probably have non-standard classification information.

**Comment by Harr7y** [comment]
Thanks a lot~

**Comment by LiDianjia** [comment]
Hi，
lefse$plot_diff_cladogram(use_taxa_num=100,
+                           use_feature_num=10,
+                           clade_label_level=5,
+                           group_order=c("Low", "Medium", "High"))
Select 10 significant features ...
Part of groups in group_order, High, not found in the feature table ...
Error in private$plot_backgroud_tree(abund_table = abund_table, use_taxa_num = use_taxa_num,  : 
  After filtering out non-standard taxonomy information, the abundance table only has 1 feature(s)! Is there an issue with the taxonomy table? Please first use the tidy_taxonomy function to process the taxonomy information table before constructing the microtable object.

**Comment by ChiLiubio** [comment]
Hi. Please first try to run this shown in the tutorial (https://chiliubio.github.io/microeco_tutorial/other-examples-1.html#tidy_taxonomy-function). Remember to change the corresponding names.
```
meco_qiime2$tax_table %<>% tidy_taxonomy
meco_qiime2$tidy_dataset()
meco_qiime2$cal_abund()
lefse_diff <- trans_diff$new(dataset = meco_qiime2, method = "lefse", group = "Group")
```

**Comment by LiDianjia** [comment]
Thanks very much！My problem was solved using your method.

**Comment by eyff-0116** [comment]
Hi.          > lefse$plot_diff_cladogram(use_taxa_num = 200, 
+                        use_feature_num = 50, 
+                        clade_label_level = 5, 
+                        group_order = c("DT", "NTS", "SS"))
Select 50 significant features ...
Select 200 most abundant taxa as the background cladogram ...
Error in numeric(max(phy$edge)): vector size can't be an infinite value
In addition: Warning message.
In max(phy$edge) : all arguments in max do not exist; returns -Inf
