### ISSUE TITLE
Error in cal_tax4fun2 

### ISSUE THREAD

**Issue by byjediaz** [ChiLiubio/microeco#34]
Hello Chi, please I would like some help:
I was trying to use the tax4fun2 function "cal_tax4fun2", but i get the error saying:
" Error in private$blastTableReducer(path_to_blast_file = res_blast_path) : 
  Blast result file empty!"

I've already follow the guidelines and manage to keep the folders structure exactly as it says in the tutorial, but i cannot pass this error.

Thanks in advice.

**Comment by ChiLiubio** [comment]
Hi
Is this the example data or your data? This issue probably comes from the empty alignment between user sequences and references.

**Comment by byjediaz** [comment]
> Hi
> Is this the example data or your data? This issue probably comes from the empty alignment between user sequences and references.

**Comment by byjediaz** [comment]
> Hi
> Is this the example data or your data? This issue probably comes from the empty alignment between user sequences and references.

Hello Chi, thank you for your response. I'm using my own data, but in order to get the fasta file "rep_fasta_16S" as it says in the tutorial, i extracted the fasta file from "seqtab" from the dada2 tutorial, and with "uniquesToFasta" function. Then, I loaded this fasta file in the pipeline with "read.fasta" function and constructed the new microtable. Thanks in advance for you kind response.

**Comment by ChiLiubio** [comment]
Hi, the method of tax4fun2 depends on the alignments between your fasta and the reference sequences. It is strange that your Blast result file is empty. Could you check this step manually? This may be from unknown question or no similar sequences indeed in the database. What is your sample type? The example sample is wetland soil. There still have about 10-20% sequeces that can have closed references I remember.

**Comment by ChiLiubio** [comment]
@SEvisual Hi. Could you please attach the error details? The Ref100NR is unavailable now. Sorry. I also have no backup.
