### ISSUE TITLE
 t1$cal_group_distance_diff with two variables

### ISSUE THREAD

**Issue by milyzhou** [ChiLiubio/microeco#340]
Hi Chi,
Thanks for helping. I'd like to use microeco to analysis my data. now I have a problem. I have two variables, group and time. I can use
 [t2 <- trans_alpha$new(dataset = test, group = "group",by_group="time")
t2$cal_diff(method = "wilcox")]
to compare the different chao1 between groups at each timepoint.
my question is how to creat the same compare at t1$cal_group_distance_diff(method = "wilcox") or t1$cal_anosim(group = "Group", paired = TRUE)?
or can we use mantel test to compare the different distance with groups at each time point? here is my dataset.
[test_data.zip](https://github.com/ChiLiubio/microeco/files/14644987/test_data.zip)

Thanks a lot.

**Comment by ChiLiubio** [comment]
Hi. In `cal_group_distance_diff` function, there is also `by_group` parameter. For `cal_anosim`, there is no such parameter now. You can select each time point according to the sample_table, generate a microtable object and perform anosim for paired groups within the time point. For mantel test, `by_group` is also available.

**Comment by milyzhou** [comment]
thank for answer, but it didn't work.
metadata <- import("sample_table.csv",row.names=1,header=TRUE)
rownames(metadata) <- metadata$ID
metadata$group <- str_replace(metadata$group,"group","")
metadata$group <- factor(metadata$group,levels = c("N","F","B"))
dput(metadata$ID)
metadata$time <- factor(metadata$time,levels = c("T0","T6","T12", "T24", "T48"))
metadata1 <- metadata[c("B1_T0", "B1_T12", "B1_T24", "B1_T48", "B1_T6", "B2_T0", "B2_T12", 
                        "B2_T24", "B2_T48", "B2_T6", "B3_T0", "B3_T12", "B3_T24", "B3_T48", 
                        "B3_T6", "F1_T0", "F1_T12", "F1_T24", "F1_T48", "F1_T6", "F2_T0", 
                        "F2_T12", "F2_T24", "F2_T48", "F2_T6", "F3_T0", "F3_T12", "F3_T24", 
                        "F3_T48", "F3_T6", "N1_T0", "N1_T12", "N1_T24", "N1_T48", "N1_T6", 
                        "N2_T0", "N2_T12", "N2_T24", "N2_T48", "N2_T6", "N3_T0", "N3_T12", 
                        "N3_T24", "N3_T48", "N3_T6"),]
dataset <- mpa2meco("buglist_clean.tsv", sample_table =metadata1)
dataset$tax_table%<>%subset(Kingdom == "k__Archaea" | Kingdom == "k__Bacteria")
dataset$tidy_dataset()
print(dataset)
dataset$sample_sums()%>% range
dataset$rarefy_samples(sample.size = 1785861)
dataset$cal_abund()

test <- dataset$merge_taxa(taxa = "Species")
d1 <- clone(test)
d1$tax_table %<>% .[.$Species != "s__", ]
d1$tidy_dataset()
rownames(d1$otu_table) <- d1$tax_table[rownames(d1$otu_table), "Species"]
rownames(d1$tax_table) <- d1$tax_table[, "Species"]
t1 <- trans_beta$new(dataset = d1,group="group")
t1$cal_ordination(ordination = "PCA")
t1$cal_group_distance(method = "wilcox",grou="group",by_group="time")
Error in t1$cal_group_distance(method = "wilcox", grou = "group", by_group = "time") : 
  参数没有用(method = "wilcox", grou = "group")

**Comment by ChiLiubio** [comment]
Hi. The input parameter is broken.
![图片](https://github.com/ChiLiubio/microeco/assets/20815519/604fd378-73f3-494b-9502-a8af198e5dcd)

**Comment by ChiLiubio** [comment]
Hi. I have updated the package in github and added a parameter `by_group` for both cal_manova and cal_anosim functions in trans_beta class.

**Comment by milyzhou** [comment]
Thank you for your help. Thanks again. I hope I didn't bother you.O(∩_∩)O
