### ISSUE TITLE
R Session Aborted    R encountered a fatal error   The session was  terminated

### ISSUE THREAD

**Issue by makerer5** [ChiLiubio/microeco#345]
Hi Chi
When I updated 'microeco' to V 1.6.0, I used the following code to plot the microbial network: t1 <- trans_network$new(dataset = group_PR, cor_method = NULL, taxa_level = "OTU", filter_thres = 0.001); t1$ cal_network(network_method = "SpiecEasi", SpiecEasi_method = "mb").
I encountered Rstudio crashing situation when I ran other code without any problem. Does this code conflict with R?
Maker
![image 2024-04-05 233726](https://github.com/ChiLiubio/microeco/assets/125379133/4129799e-0b68-4341-b6dd-3bc1d5650315)

**Comment by ChiLiubio** [comment]
Hi Maker. Could you please attach your data `group_PR` so that I can use my PC to reproduce it? To save the data, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.Message ID: ***@***.***>

**Comment by makerer5** [comment]
[dataset.zip](https://github.com/ChiLiubio/microeco/files/14892049/dataset.zip)
Thanks, this is my data. I also ran into the following problem: t1$get_node_table(node_roles = TRUE)
The nodes (364) with NaN in z will be filtered ...
Error in private$assign_module_roles(zp) :
   No valid result obtained for this network!

**Comment by ChiLiubio** [comment]
Hi. Yes. I tested the steps using both windows and linux server and different microeco versions. All the sessions crashed. I am still not sure why it happened. 
If no available z value is found, please use `node_roles = FALSE` in get_node_table function.

**Comment by makerer5** [comment]
This is the case, but the good news is: I used "SpiecEasi" to build the co-occurrence network for other data without any errors. It seems that this data has a special structure. Maybe I should check the amplicon process.
Anyway, thank you for your help!
