### ISSUE TITLE
Problem with colors and number of groups

### ISSUE THREAD

**Issue by Felipe-rdv** [ChiLiubio/microeco#35]
Hi,

I'm having problems because my dataset has 31 groups, the samples are in triplicate so I have a total of 93 samples.
Because of this the plots don't show all the colors of the groups, it looks like it's limited. How could I extend? I tried to put it manually with "scale_colour_manual(values = Sample_Colors)" but with no success.

If I do:
```
t1$plot_ordination(plot_color = "Group", plot_shape = "Group", plot_group_ellipse = FALSE)+
    scale_colour_manual(values = Sample_Colors) 
```
I got the error:
```
Scale for 'colour' is already present. Adding another scale for 'colour', which will replace the existing scale.
Error: Insufficient values in manual scale. 31 needed but only 17 provided.
```
But my Sample_Colors vector has all 31 colors.
```
> Sample_Colors
        1         2         3         4         5         6         7         8         9        10        11 
"#E41A1C" "#B73344" "#8A4D6C" "#5E6794" "#377FB4" "#999999" "#43987B" "#48A55F" "#51A84F" "#658F66" "#78767D" 
       12        13        14        15        16        17        18        19        20        21        22 
"#8B5D94" "#A15293" "#BC5F69" "#D76C3F" "#F17815" "#FF8F06" "#FFB013" "#FFD120" "#FFF22E" "#F0E331" "#D9B82E" 
       23        24        25        26        27        28        29        30        31 
"#C28C2B" "#AB6028" "#B55E45" "#CA696C" "#DF7493" "#F47FBA" "#E186B6" "#C98CAC" "#B192A2" 
```
I also tried the vector with color specs for the 93 samples and still without success.

The color limiting problem happens in other functions.
If I specify a high ntaxa, the plots are without some colors:

`t1 <- trans_abund$new(dataset = dataset, taxrank = "Order", ntaxa = 20)`

plot:
![bug_microeco1](https://user-images.githubusercontent.com/83514158/122616140-359f4400-d060-11eb-83ae-8b41a97957cf.png)

Briefly, how can I specify my colors or increase the package colors?

Thank you very much,

**Comment by ChiLiubio** [comment]
Hi,
Please check the color parameters in the plotting functions, such as 'use_colors' in trans_abund$plot_bar or 'color_values' in trans_beta$plot_ordination. Actually, it is very easy to see those if you have a look on the help documents, such as help(trans_abund). This is also mentioned in the tutorial part. 
My pleasue.

**Comment by Felipe-rdv** [comment]
Dear Chi,
Sorry for my lack of attention, I hadn't seen the parameter. And really the help of the functions is very well done!
Congratulations on the great work on this package.

In case someone also has problems with a high number of groups, I share here my code that worked:

```
t1$plot_ordination(plot_color = "Group", plot_shape = "Group", plot_group_ellipse = FALSE,
                   color_values = Group_Colors) +
        geom_point(alpha = 0.9, size=5, stroke=1.4) +
        scale_shape_manual(values=rep(c(21:25), times=8))
```

result:
![image](https://user-images.githubusercontent.com/83514158/122650608-545a1500-d10a-11eb-8c87-846e403b7adb.png)

Thank you very much,
my best wishes,
