### ISSUE TITLE
unused argument error

### ISSUE THREAD

**Issue by tenguzame** [ChiLiubio/microeco#350]
Hello,
I am using the last version of Microeco on RStudio version 2023.12.1 Build 402, on a Windows 10-equipped laptop with R version 4.3.2. When I try to plot an abundance plot, I get the following error:
```
Error in setup_panel_guides(..., self = self) : 
  unused argument (list(~Taxonomy, ~Sample, ~Abundance))
```
I never experienced any similar issues. What could cause it?
Best regards

**Comment by ChiLiubio** [comment]
Hi. Although I am not sure how it happened, I think it should come from the ggplot2 package compatability. Please restart the Rstudio and rerun the whole steps. If it is still there, I suggest to first update ggplot2 pakcage to v3.5.

**Comment by ChiLiubio** [comment]
Hi. Although I am not sure how it happened, I think it should come from the ggplot2 package compatability. Please restart the Rstudio and rerun the whole steps. If it is still there, I suggest to first update ggplot2 pakcage to v3.5.

**Comment by ChiLiubio** [comment]
Hi. Although I am not sure how it happened, I think it should come from the ggplot2 package compatability. Please restart the Rstudio and rerun the whole steps. If it is still there, I suggest to first update ggplot2 pakcage to v3.5.
