### ISSUE TITLE
Error in method = cicrlize with plot_sum_links

### ISSUE THREAD

**Issue by chrissy005** [ChiLiubio/microeco#352]
Dear Chi Liu,

I am getting an error when using this code for plot_sum_links for my data ( t1$plot_sum_links(method = "circlize", transparency = 0.2, annotationTrackHeight = circlize::mm_h(c(5, 5))))

My exact code is:

microeco_transnetwork_spieceasi$plot_sum_links(plot_pos = FALSE, plot_num = 15, color_values = color_values_2 ,method = "circlize", transparency = 0.2, annotationTrackHeight = circlize::mm_h(c(5, 5)))

color_values_2 = c("#3B4D16","#950D3D", "#848F22", "#A7A3FE","#B2C9B2", "#8CCBD3", "#0DD7FD", "#99D584", "#0D8CA8","#DFC500","#2A7F72","#FEAB2E", "#4B00FD", "#26E0A9" ,"#CC003D")

Error message is 

"Extract the negative link information ...
Error in chorddiag::chorddiag(use_data, groupColors = color_values, ...) : 
  unused arguments (method = "circlize", transparency = 0.2, annotationTrackHeight = c(0.0741309, 0.0741309))
In addition: Warning message:
`convert_length()` only works when aspect of the coordinate is 1. "

I have installed the circlize package and the version  of my microeco package is 1.6.1

**Comment by ChiLiubio** [comment]
Hi. Please attach your data `t1` so that I can reproduce the issue. To save it, please follow the tutorial to use save function (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by chrissy005** [comment]
Dear Chi Liu,

I tried it again and seemed to have worked. 

However, I still cannot figure out how to save these plots from the plot_sum_links function. I am liking the original plot without the 'method=circlize'

**Comment by chrissy005** [comment]
Ok noted.

On a separate note, I am finding the plot_taxa_roles(use_type = 2) very useful. I accessed the data table to understand the variables and understand that the p and z scores are used to plot the data. Is there any documentation that explains how these 2 scores are derived? Are these based on node interactions?

**Comment by ChiLiubio** [comment]
Hi. Please refer to the paper (https://doi.org/10.1186/1471-2105-13-113). I will add more descriptions in the function `get_node_table`. Thanks for the reminder.

**Comment by chrissy005** [comment]
Dear Chi Liu,1) Thank you for sending the reference to paper. However, I am still struggling to find the information on how the P and Z scores were derived for the plot_taxa_roles function.I would be extremely grateful if you could provide some information2) Also, with regards to the same function, doea the ‘show_number’ parameter parae the top n taxa with the most interactions or highest abundance in the network?Regards ChristalineOn Apr 22, 2024, at 9:41 AM, Chi Liu ***@***.***> wrote:﻿
Hi. Please refer to the paper (https://doi.org/10.1186/1471-2105-13-113). I will add more descriptions in the function get_node_table. Thanks for the reminder.

**Comment by ChiLiubio** [comment]
Hi. The Pi and Zi scores come from the function `get_node_table` and are stored in its result `res_node_table` inside the object. The function plot_taxa_roles is only used for the visualization. For the second one, it is node number, please refer to the help document.

**Comment by chrissy005** [comment]
Dear Chi Liu,

Thank you for your response. this has clarified and your publication on https://doi.org/10.1016/j.geoderma.2022.115866 has the required description.
