### ISSUE TITLE
Sample ID in rarefactions curves

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#355]
Hi, 
Would be possible to show SampleIDs in the rarefaction curves plot? 
It seems from the available options that this might not be straightforward.
Many thanks, 
jose

something like this:
![rarefaction](https://github.com/ChiLiubio/microeco/assets/46994209/84ebdbd9-9c53-497c-8c63-fe7f1ff6d8dc)

**Comment by ChiLiubio** [comment]
Hi. I have updated the mecodev package and added several parameters. Please reinstall it from github and try again.
```
library(mecodev)
library(microeco)
data(dataset)
dataset$sample_table <- dataset$sample_table[1:10, ]
dataset$tidy_dataset()
t1 <- trans_rarefy$new(dataset = dataset, depth = c(0, 10, 50, 400, 800))
t1$plot_rarefy(show_samplename = TRUE, samplename_size = 5, samplename_color = "black")
t1$plot_rarefy(color_values = rep("grey50", 20), show_samplename = TRUE, show_legend = FALSE)
```

**Comment by jamorillo** [comment]
Hello, 
Sorry for the delay, I had a problem to reinstall the packages, now OK-
Thank you for the enhancement!
Regards,
jose
