### ISSUE TITLE
problem with downloading abundance table

### ISSUE THREAD

**Issue by guianrey** [ChiLiubio/microeco#357]
I am using the function to plot the abundance at phylum level (t1 <- trans_abund$new(dataset = meco_dataset, taxrank = "Phylum", ntaxa = 100, groupmean = "Organs")), could you help me to download the abundance as a percentage (clustered for each of my 4 groups) in an excel table please?, since the last update it does not allow me to do it anymore.

I would like it in this format:
Taxa | Abundance | Percentage
-- | -- | --
Proteobacteria | 243666 | 66,86
Firmicutes | 95074 | 26,09
Bacteroidota | 21037 | 5,77
Verrucomicrobiota | 2207 | 0,61

Best

Guillermo

**Comment by ChiLiubio** [comment]
Hi. Here is an example.
```
library(microeco)
t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 10, groupmean = "Group")
# data_abund may be what you need
write.csv(t1$data_abund, "test.csv")
```
The intermediate data name is shown in the Returns part of help document.
![图片](https://github.com/ChiLiubio/microeco/assets/20815519/a76322b0-af07-49e4-9cbb-0319fb2f7098)

**Comment by guianrey** [comment]
Thank you Chi for your time, it works
