### ISSUE TITLE
cal_cor() correlation between diversity metrics and env factors?

### ISSUE THREAD

**Issue by marwa38** [ChiLiubio/microeco#358]
Hi Chi 

Hope you are doing well. 

I was wondering if it is possible to include in `cal_cor()` correlation between environmental factors along with alpha or beta diversity rather than with microbial taxa?
I received nice and constructive comments on my first manuscript and one of the comments was to do correlation between alpha (Shannon) or beta diversity (Bray-Curtis) with some of the growth performance indices I have. Your package is cited and referenced already, thanks very much for always being helpful. 

Many thanks in advance 
Marwa

**Comment by ChiLiubio** [comment]
Hi Marwa,
Please open the trans_env part of tutorial (https://chiliubio.github.io/microeco_tutorial/explainable-class.html#trans_env-class) and search for the `add_abund_table`. You can find an example on the alpha diversity.
![图片](https://github.com/ChiLiubio/microeco/assets/20815519/85db60e3-df26-471a-873a-652b0e56802d)

Best,
Chi

**Comment by marwa38** [comment]
paper accepted thanks very much Chi 
It would be great if it can be also for beta diversity in the documentation.

**Comment by ChiLiubio** [comment]
Congratulations! 
Thanks. I will consider optimizing that.

**Comment by marwa38** [comment]
Thank you. Can't wait for having beta_div and taxa to be correlated to.

**Comment by marwa38** [comment]
Hi Chi 

I was wondering if there is an update regarding correlation to beta_div. 

Cheers
Marwa

**Comment by ChiLiubio** [comment]
Hi. 
For beta diversity, please use the `cal_mantel` function of `trans_env` class, which can perform mantel test to correlate beta diveristy distance (e.g. Bray-Curtis)  matrix to environmental variables (converted to matrix). 

Best,
Chi
