### ISSUE TITLE
Cal_alphadiv skips observed

### ISSUE THREAD

**Issue by Manso002** [ChiLiubio/microeco#359]
Hello all.
I have a problem when asking to calculate alpha diversities values. I run with this message:

Skip 'Chao1', 'ACE' and 'Observed' ...
Skip the index Fisher because of an error ...
The result is stored in object$alpha_diversity ...

I tried running the same function with several microtable objects and i get the same message in all of them.
Hope you can help me.

Thanks in advance!

**Comment by ChiLiubio** [comment]
Hi. 
Could you please attach your data so that I can reproduce and check the issue? To save the microtable object, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by Manso002** [comment]
Hello again.
I am sorry for the late response, I was away. I attach the data as you mentioned:
[dataset.zip](https://github.com/ChiLiubio/microeco/files/15376114/dataset.zip)
Thank you in advance and again, sorry.

**Comment by ChiLiubio** [comment]
The numbers in otu_table are not integer. That is the reason. Chao1 and ACE are both the index that estimate the species number and depend on the count data of species. I guess your data is not the traditional community data. So please ignore these indexes.
