### ISSUE TITLE
<!--Correlation network

### ISSUE THREAD

**Issue by alisr7** [ChiLiubio/microeco#36]
Hello,

Thank you for this great package, it is very well put together. I have  a couple of little issues  I appreciate your help:
1- in plotting unique and shared species barplots, I am getting a random order of samples, how to fix that and make it in the same order as you had in the manual.
2- in constructing the trans-network class it is still not clear for me the benefits of grouping taxa by modules, what are these modules and is there a way to cluster nodes by groups or other sample_info
3- Same thing in plot_spe_func_perc, is there a way to plot functionality by sample-info such Group, type..
4- I tried replicating the co-occurrence plot in the trans_network class, after creating gexf file what are the steps to reproduce the same plot in Gephi. I am unfamiliar with Gephi and I appeciate your help.

Sorry for bombarding with all these questions, your help is highly appreciated,

Best,
AS

**Comment by ChiLiubio** [comment]
Hi,
1. please see the order_x parameter in the plotting functions of trans_abund. Another plexible method is to assign factors to the data inside the object.
2. grouping nodes with modules is a way that have some self-evident benefits to explain the co-occurred relationships in the social properties. This depends on the algorithms of module classifications. Most of papers use this method. Of course, clustering nodes by other groups you want to use is also ok if you can explain the underlying meanings .
3. currently, there is no additional way in this function. but if you are familiar with architectural thinking of this package, you can extract the data frame inside and use other functions in other class to do it, such as the trans_abund class.
4. there is a detailed manual in the gephi official website. please first check it.

Please feel free to tell me if there is still problems. The core design idea in the package is the links among the functions in the class or between different classes to make the methods brief and clear. In another words, not redundant. So there is a certain degree of difficulty for some flexible operations.

Best
Chi

**Comment by alisr7** [comment]
Thank you Chi for your prompt response, I appreciate it!
