### ISSUE TITLE
dbRDA results

### ISSUE THREAD

**Issue by DimitraIoli** [ChiLiubio/microeco#360]
_Dear Chi,
I have been using it for the past two years with great success! Thank you for this amazing package!
However, I have an issue interpreting db-RDA statistic outputs in 'microeco'. I have run dbRDA using the bray-Curtis distance with the following function and version 1.6.0
t1$cal_ordination(method = "dbRDA", use_measure="bray")
I would like to know where to find the 'fitted' and 'total' variation percentages. I am not sure what the plotted percentage corresponds to.

I am attaching the results and plot here:
![image](https://github.com/ChiLiubio/microeco/assets/64790624/3d9afb5c-8a76-4458-8579-14a1b36d9a82)

Do values in brackets correspond to the fitted percentage?_ 

> t1[["res_ordination"]]
Call: dbrda(formula = use_data ~ Temp + S + N + PO4 + SiO4 +
Chla, data = env_data)

              Inertia Proportion Rank RealDims
Total         56.5137     1.0000              
Constrained   11.1648     0.1976    6        6
Unconstrained 45.3489     0.8024  225      161
Inertia is squared Unknown distance 

Eigenvalues for constrained axes:
dbRDA1 dbRDA2 dbRDA3 dbRDA4 dbRDA5 dbRDA6 
 6.754  2.541  0.671  0.554  0.424  0.220 

Eigenvalues for unconstrained axes:
 MDS1  MDS2  MDS3  MDS4  MDS5  MDS6  MDS7  MDS8 
7.946 3.191 2.691 2.190 2.057 1.828 1.575 1.420 
(Showing 8 of 225 unconstrained eigenvalues)

_Could you confirm if the total variation percentages for dbRDA1 and dbRDA2 axis are 11.9 % and 4.5%?_
Importance of components:
                      dbRDA1  dbRDA2  dbRDA3   dbRDA4   dbRDA5   dbRDA6   MDS1
Eigenvalue            6.7537 2.54144 0.67138 0.554092 0.424003 0.220209 7.9463
Proportion Explained  0.1195 0.04497 0.01188 0.009805 0.007503 0.003897 0.1406
Cumulative Proportion     NA      NA      NA       NA       NA       NA     NA

Thank you!
Best,
Ioli

**Comment by ChiLiubio** [comment]
Hi Ioli,
Thanks for your appreciation. You are right. For "the plotted percentage corresponds to", the percentage in the axis can be got from the Eigenvalues for constrained axes. For example, the first axis dbRDA1 is `6.754/(6.754 + 2.541 + 0.671 + 0.554 + 0.424 + 0.220) = 0.605`. So it is fitted variation percentage. As you show, the total variation percentages for dbRDA1 axis is 11.9 %. The total R2 should be 0.1976. So the plotted percentage  can also be obtained: `0.1195/0.1976 = 0.605`.

Best,
Chi

**Comment by DimitraIoli** [comment]
Hi Chi!
Perfect! That sounds great. 
Thank you!
Cheers,
Ioli
