### ISSUE TITLE
Error in x[[p]] : subscript out of bounds

### ISSUE THREAD

**Issue by yumiao222222** [ChiLiubio/microeco#361]
Hi
When I ran the code to calculate LEFSE, it showed error as below

> feature_table <- read.csv('feature_table.csv', row.names = 1)
> sample_table <- read.csv('sample_table.csv', row.names = 1)
> tax_table <- read.csv('tax_table.csv', row.names = 1)
> dataset <- microtable$new(sample_table = sample_table,
otu_table = feature_table, 
tax_table = tax_table)
> dataset
microtable-class object:
sample_table have 5 rows and 3 columns
otu_table have 2737 rows and 5 columns
tax_table have 2737 rows and 6 columns
> lefse <- trans_diff$new(dataset = dataset, 
 method = "lefse", 
p_adjust_method = "none",
group = "Group", 
alpha = 0.1, 
lefse_norm = 10000000,
lefse_subgroup = NULL)

No taxa_abund list found. Calculate it with cal_abund function ...
The result is stored in object$taxa_abund ...
622 input features ...
603 features are remained after removing unknown features ...
Start Kruskal-Wallis rank sum test for Group ...
161 taxa found significant ...
After P value adjustment, 161 taxa found significant ...
**Error in x[[p]] : subscript out of bounds**

Is there a way to solve this?

**Comment by ChiLiubio** [comment]
Could you please attach your dataset so that I can reproduce your issue? To save the dataset, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by yumiao222222** [comment]
Hi Chi,
Please see the attached file.
Thank you
Yu

Chi Liu ***@***.***> 于2024年5月13日周一 22:58写道：

**Comment by yumiao222222** [comment]
[test_data.zip](https://github.com/ChiLiubio/microeco/files/15310329/test_data.zip)

**Comment by ChiLiubio** [comment]
Hi. The result shows no significant taxa was found. I checked the sample_table in dataset and found that there is no repetition for each group. Such case is not suitable for the differential test.
![图片](https://github.com/ChiLiubio/microeco/assets/20815519/8bcc12e4-bbff-4731-9e72-d9b9090e9bd3)
