### ISSUE TITLE
What does the se.ACE in the microbial alpha diversity index indicate

### ISSUE THREAD

**Issue by makerer5** [ChiLiubio/microeco#362]
Hi Chi
I calculated the alpha diversity of microbial communities using microeco and I noticed that there is a se.ACE index, what is the meaning of this se.ACE and se.Chao1 index?

**Comment by ChiLiubio** [comment]
Hi. They are standard errors of ACE and Chao1 based on the estimateR function of vegan package. The document shows the calculation details are very complicated.
![图片](https://github.com/ChiLiubio/microeco/assets/20815519/11eb57c3-8a8c-444e-a759-a306baa97ff0)
