### ISSUE TITLE
Error in private$tidy_samples(self) 

### ISSUE THREAD

**Issue by fafuwjw** [ChiLiubio/microeco#364]
Hi,Chi
when I use the microeco package,It came up with this error：
No same sample name found between rownames of sample_table and colnames of otu_table! Please first check whether the rownames of sample_table are sample names! Then check through the sample names of each table!
I'm pretty sure the rownames of sample_table and the colnames of otu_table are the same and it worked successfully before, can you tell me how to do it?

**Comment by ChiLiubio** [comment]
Hi. Could you please provide more steps and data so that I can reproduce your issue? To save the microtable object, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by fafuwjw** [comment]
[Uploading test_data.zip…]()

**Comment by fafuwjw** [comment]
Thank you for your reply, and last information  is a compressed Rdata

**Comment by ChiLiubio** [comment]
Hi. I cannot open it. Please make sure it is correctly uploaded.

**Comment by awwwwwwwwwwwwww** [comment]
I made the same mistake after run this code "dataset$tidy_dataset()",please help me!

> dataset <- microtable$new(sample_table = sample_info, otu_table = asv_table, tax_table = taxonomy_table, phylo_tree = phylo_tree)
> rownames(dataset$sample_table)==colnames(dataset$otu_table)
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE T
[Uploading dataset.RData…]()
RUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[24] TRUE TRUE TRUE TRUE
> dataset$tidy_dataset()
Error in private$tidy_samples(self) : 
  No same sample name found between rownames of sample_table and colnames of otu_table! Please first check whether the rownames of sample_table are sample names! Then check through the sample names of each table!
> rownames(dataset$sample_table)==colnames(dataset$otu_table)
 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[20] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

**Comment by awwwwwwwwwwwwww** [comment]
the second link "dataset.zip" is correct

**Comment by ChiLiubio** [comment]
Hi. I find the class of sample_table in your dataset is not the traditional data.frame class. It is probably the reason. I recreate the microtable object like the following:

```
class(dataset$sample_table)
newsample <- as.data.frame(dataset$sample_table)
# now no rownames in it
rownames(newsample) <- newsample$Sample
d1 <- microtable$new(otu_table = dataset$otu_table, sample_table = newsample, tax_table = dataset$tax_table, phylo_tree = dataset$phylo_tree)
d1$tidy_dataset()
```

**Comment by fafuwjw** [comment]
Thank you for your help! I have solved the problem successfully.

**Comment by awwwwwwwwwwwwww** [comment]
Thank you vvvvvvery much!
