### ISSUE TITLE
Error in dataset$tidy_dataset()

### ISSUE THREAD

**Issue by Ye-Yonglian** [ChiLiubio/microeco#366]
I met a problem when using it, the code was under:
**> library(microeco)
> library(ape)
> setwd("/Users/Yeyonglian/Desktop/扩增子/R")
> tax <- read.csv("taxonomy.csv", header = TRUE, check.names = FALSE, row.names = NULL)
> asv <- read.csv("asv_table.csv", check.names = FALSE, row.names = 1)
> group <- read.csv("group.csv", check.names = FALSE, row.names = 1)
> tree <- read.tree("renamed_tree.nwk")
> library(magrittr)
> library(ggplot2)
> theme_set(theme_bw())

> dataset <- microtable$new(sample_table = group, otu_table = asv, tax_table = tax, phylo_tree = tree)
> class(dataset)
[1] "microtable" "R6"        
> print(dataset)
microtable-class object:
sample_table have 271 rows and 2 columns
otu_table have 92911 rows and 271 columns
tax_table have 267191 rows and 8 columns
phylo_tree have 92911 tips

> dataset$tax_table %<>% subset(Kingdom == "k__Archaea" | Kingdom == "k__Bacteria")
> print(dataset)
microtable-class object:
sample_table have 271 rows and 2 columns
otu_table have 92911 rows and 271 columns
tax_table have 266640 rows and 8 columns
phylo_tree have 92911 tips

> dataset$filter_pollution(taxa = c("mitochondria", "chloroplast"))
Total 0 features are removed from tax_table ...
> print(dataset)
microtable-class object:
sample_table have 271 rows and 2 columns
otu_table have 92911 rows and 271 columns
tax_table have 266640 rows and 8 columns
phylo_tree have 92911 tips

> dataset$tidy_dataset()
Error in dataset$tidy_dataset() : 
  No same feature name found among otu_table, tax_table and phylo_tree! Please check feature names in those objects!
> tree
Phylogenetic tree with 92911 tips and 92684 internal nodes.
Tip labels:
  ASV_8404, ASV_61917, ASV_79545, ASV_12029, ASV_37648, ASV_58841, ...
Node labels:
  root, 0.905, 0.577, 0.953, , 0.980, ...
Rooted; includes branch lengths.

> tax[1:5, 1:5]
  OTU_ID     Kingdom              Phylum                    Class                        Order
1 ASV_01 k__Bacteria   p__Proteobacteria   c__Gammaproteobacteria o__Enterobacterales_A_737866
2 ASV_02 k__Bacteria  p__Patescibacteria c__Gracilibacteria_12420                   o__UBA1369
3 ASV_03 k__Bacteria p__Actinobacteriota       c__Thermoleophilia                o__BMS3ABIN01
4 ASV_04 k__Bacteria   p__Proteobacteria   c__Gammaproteobacteria         o__Granulosicoccales
5 ASV_05 k__Bacteria   p__Proteobacteria   c__Alphaproteobacteria      o__Rhizobiales_A_500471
> asv[1:8, 1:10]
       0514.1.1 0514.1.2 0514.1.3 0515.1.1 0515.1.2 0515.1.3 0516.1.1 0516.1.2 0516.1.3 0516.2.1
ASV_01        0        0        0        0        0        0        0        0        0        0
ASV_02        0        0        0        0        0        0        0        0        0        0
ASV_03        0        0        0        0        0        0        0        0        0        0
ASV_04        0        0        0        0        0        0        0        0        0        0
ASV_05        0        0        0        0        0        0        0        0        0        0
ASV_06        0        0        0        0        0        0        0        0        0        0
ASV_07        0        0        0        0        0        0        0        0        0        0
ASV_08        0        0        0        0        0        0        0        0        0        0**
please tell me how to solve it

**Comment by ChiLiubio** [comment]
Hi. The OTU_ID in tax should be rownames. Otherwise the function can not recognize the rownames in tax_table.

**Comment by Ye-Yonglian** [comment]
Thanks！It worked！
