### ISSUE TITLE
ggcor needed for Mantel test + Correlation heatmap is no longer available

### ISSUE THREAD

**Issue by eperezv** [ChiLiubio/microeco#371]
Hi, I'm trying to use some functions described in the tutorial, especifically Mantel test + Correlation heatmap, which depend on the package ggcor. However, this package (and the repository by houyunhuang) is not available anymore on github or the internet. Do we have some alternative to install it or to perform the analyses?

**Comment by ChiLiubio** [comment]
Please install it according to the steps provided in the link (https://chiliubio.github.io/microeco_tutorial/other-examples-1.html#mantel-test-correlation-heatmap). You can find this package from downloaded 'microeco_dependence.zip'.

**Comment by eperezv** [comment]
Ok, I will. Thanks!
