### ISSUE TITLE
Adding exting network

### ISSUE THREAD

**Issue by DpennaS** [ChiLiubio/microeco#373]
Hi Chi!

I am working with co-ocurrence networks and I constructed my networks with python in a local server. 

However, I would like to use the microeco to do the node classification. Is there an easy way to import a preexisting network?

I have gephi and cytoscape files, but I also have the tables with correlations.

Best Regards,
Penna

**Comment by ChiLiubio** [comment]
Hi Penna,
I show an example. I have also updated the package in github to fix a minor issue about abundance. Please reinstall the package from github and run the following example.
```
# dataset NULL for customized correlation
library(microeco)
test1 <- trans_network$new(dataset = NULL)

# I generate a correlation data set to simulate your correlation results
t2 <- trans_network$new(dataset = dataset, cor_method = "pearson", use_WGCNA_pearson_spearman = TRUE, filter_thres = 0.0005)
# correlation coefficient matrix
class(t2$res_cor_p$cor)
# correlation coefficient significance matrix
class(t2$res_cor_p$p)

# what we need to do is to use list to add these two matrix objects to test1
test1$res_cor_p <- list(cor = t2$res_cor_p$cor, p = t2$res_cor_p$p)
# then calculate network
test1$cal_network(COR_p_thres = 0.05, COR_cut = 0.7)
test1$cal_module()
test1$cal_network_attr()
test1$get_node_table()
head(test1$res_node_table)
```
Please feel free to tell me if it is not clear or an error occures.

Best,
Chi

**Comment by ChiLiubio** [comment]
Hi. I provide a function to convert it. 
```
# convert long format to symmetrical matrix
# The first and second columns must be names
vec2mat <- function(datatable, value_var, value_NA = 0, value_diag = 0){
	library(magrittr)
	datatable[, value_var] %<>% as.numeric
	use_table <- datatable[, c(1:2)]
	use_table[, value_var] <- datatable[, value_var]
	colnames(use_table) <- c("t1", "t2", "value")
	res_table <- rbind.data.frame(
		use_table, 
		data.frame(t1 = use_table[, 2], t2 = use_table[, 1], value = use_table[, 3])
	)
	res_table <- reshape2::dcast(res_table, t1~t2, value.var = "value") %>% 
		`row.names<-`(.[,1]) %>% 
		.[, -1] %>% 
		as.matrix
	res_table[is.na(res_table)] <- value_NA
	diag(res_table) <- value_diag
	res_table
}

input <- read.csv("aracaju_cor.csv", sep = "\t")

cor_matrix <- vec2mat(input, value_var = "Weight", value_NA = 0, value_diag = 0)
p_matrix <- vec2mat(input, value_var = "pval", value_NA = 1, value_diag = 1)

# dataset NULL for customized correlation
library(microeco)
test1 <- trans_network$new(dataset = NULL)

# what we need to do is to use list to add these two matrix objects to test1
test1$res_cor_p <- list(cor = cor_matrix, p = p_matrix)
# then calculate network
test1$cal_network(COR_p_thres = 0.05, COR_cut = 0.7)
test1$cal_module()
test1$cal_network_attr()
test1$get_node_table()
head(test1$res_node_table)
test1$plot_taxa_roles()
```

**Comment by ChiLiubio** [comment]
Please reinstall the microeco package from github and try again.
```
# If devtools package is not installed, first install it
install.packages("devtools")
devtools::install_github("ChiLiubio/microeco")
```

**Comment by DpennaS** [comment]
Thanks a lot!

Now the first function worked!!

However, when I tried to use the plot_taxa_roles(type = 2) I got this error:

> aracaju_network$plot_taxa_roles(use_type = 2)
Error in `geom_point()`:
! Problem while computing aesthetics.
ℹ Error occurred in the 1st layer.
Caused by error:
! object 'Abundance' not found
Run `rlang::last_trace()` to see where the error occurred.

Besides that, I have a doubt, the cal_network function uses the SparCC correlation as well?

Thanks for answering so many answers and issues.

**Comment by ChiLiubio** [comment]
Hi. The parameter "use_type = 2" in plot_taxa_roles is used in a normal way, i.e. the case that dataset is provided when creating trans_network object (`test1 <- trans_network$new(dataset)`). Do you have a dataset, i.e. microtable object in R?

For the SparCC , please see the help document of trans_network$new. `cal_network` only construct network. All the correlations calculation is in `trans_network$new` part.

**Comment by DpennaS** [comment]
Oh I see, the cal_network only do the construction. 

Yes I have a microtable object in R, but what I do if the network is already built?

In this same example I have the dataset ps_aracaju.

**Comment by ChiLiubio** [comment]
If so, you can assign it when you create the object.
```
library(microeco)
test1 <- trans_network$new(dataset = ps_aracaju)
``
