### ISSUE TITLE
Taxa labels dont show up in plot_diff_cladogram

### ISSUE THREAD

**Issue by jackqio** [ChiLiubio/microeco#374]
Hi! The taxa labels in figure of plot_diff_cladogram was not shown after the code run. I try to update my R and package, but it didn't work. Here are the R scripe and the zip of microtable. Besides, the R points that there are many warnings saying like that 

1: Computation failed in `stat_clad_bar()`.
Caused by error in `offspring.tbl_tree_item()`:
! 没有"offspring.tbl_tree_item"这个函数.

My R version is 4.4. 

![image](https://github.com/ChiLiubio/microeco/assets/149867268/98f72ad3-713a-423f-869c-edc1161965c2)

[R script.txt](https://github.com/user-attachments/files/15798004/R.script.txt)
[dataset.zip](https://github.com/user-attachments/files/15798005/dataset.zip)

**Comment by ChiLiubio** [comment]
Hi. I tested your steps in R4.3.3 and R4.4.0, and both run well. I guess some dependent packages are broken. Could you please reinstall related packages, including ggtree and tidytree, and try again

![test](https://github.com/ChiLiubio/microeco/assets/20815519/c276a61d-8a04-4115-be86-d53562b46c01)

**Comment by jackqio** [comment]
I reinstall the ggtree and tidytree package and it has been worked out. Thank you very much!
