### ISSUE TITLE
Legend and facet

### ISSUE THREAD

**Issue by Geize** [ChiLiubio/microeco#38]
Hi there, 

I am trying to plot a graphic similar to 

"t1$plot_bar(others_color = "grey70", facet = "Group", xtext_keep = FALSE, legend_text_italic = FALSE)"

But in my graphic besides changed xtext_keep = FALSE  to "TRUE", I want to keep this information on the top. 

Something similar to this one

https://i.stack.imgur.com/Lkklm.jpg 

Could you give a hand with this?

Thanks.

**Comment by ChiLiubio** [comment]
Hi
Sorry. I am not sure what you actually need. Could you please describe the details again?

Best
Chi

**Comment by Geize** [comment]
We can plot a graphic  based on this command: 

```
t1$plot_bar(others_color = "grey70", facet = "Group", xtext_keep = FALSE, legend_text_italic = FALSE)
 return a ggplot2 object

``` 

<img width="452" alt="image" src="https://user-images.githubusercontent.com/7786478/125606291-064f995b-1ac0-421a-a21f-81b39169ae62.png">



However, I need to move the information from bottom to the top and keep what I already have. Take a look on this  (but this one was manually edited..)

![Apresentação1](https://user-images.githubusercontent.com/7786478/125607714-98994332-2cb5-48c1-b3ef-1fa3bc65d79f.jpg)

**Comment by ChiLiubio** [comment]
If without facets, It is easy to do like the following lines:
p1 <- t1$plot_bar(others_color = "grey70", facet = "Group", legend_text_italic = FALSE)
p1 + scale_x_discrete(position = "top") 

If keeping facets, I think the overall layout is hard to control, including the facet and text in it and x-axis text size and angles. I have not tried the plotting in this way. If there is no simple way, I feel it is maybe necessary to dip into the basic methods in ggplot2.

**Comment by Geize** [comment]
Hi, 


Yes, I agree with you. 
Anyway, thanks for your help. 

best,
