### ISSUE TITLE
Plot_diff_abund improvement

### ISSUE THREAD

**Issue by DpennaS** [ChiLiubio/microeco#380]
Hey there!

I am using the function plot_diff_abund from the trans_diff class. I think it would be cool to add the same parameter that is present in trans_alpha$plot_alpha() to change the size of the significant letter (add_sig_text_size). 

King regards,
Penna

**Comment by ChiLiubio** [comment]
Hi Penna,
Thanks very much! It is on the way as you think. Please reinstall the package from github and try again.

Best,
Chi
