### ISSUE TITLE
Error in lefse$plot_diff_cladogram

### ISSUE THREAD

**Issue by YP-Hao** [ChiLiubio/microeco#382]
hi!
I have some error of this function. Here is the code.
feature_table=read.xlsx("真菌丰度.xlsx",rowNames =T,sheet = 1)
sample_table=read.xlsx("sample.xlsx",rowNames =T,sheet = 1)
tax_table=read.xlsx("tax.xlsx",rowNames =T,sheet = 1)
dataset <- microtable$new(sample_table = sample_table,
                          otu_table = feature_table, 
                          tax_table = tax_table)
lefse <- trans_diff$new(dataset = dataset,  
                        method = "lefse", 
                        group = "Group",  
                        alpha = 0.05,
                        lefse_subgroup = NULL, 。
                        taxa_level = "Genus", 
                        #nresam = 0.9, 
                        lefse_min_subsam = 8
) 
lefse$plot_diff_cladogram(use_taxa_num = 200, 
                          use_feature_num = 50, 
                          clade_label_level = 5, 
                          group_order = c("Forest", "Park", "Street", "Residential area"))
Here is error.
**Error in lefse$plot_diff_cladogram(use_taxa_num = 150, use_feature_num = 50,  : 
  This function is available only when taxa_level = 'all' !**
This problem has troubled me for a long time, I don't know how to solve it, if I can get your help, I will be very grateful!

**Comment by YP-Hao** [comment]
and the figure of LDA score only has genus

**Comment by ChiLiubio** [comment]
Hi. Please set `taxa_level = "all"`. You only select "Genu
![图片](https://github.com/user-attachments/assets/d5d32d4b-1a22-430b-96b7-1021452bf5f7)
s" in the command.

**Comment by YP-Hao** [comment]
> Hi. Please set `taxa_level = "all"`. You only select "Genus" in the command. ![图片](https://private-user-images.githubusercontent.com/20815519/348285654-d5d32d4b-1a22-430b-96b7-1021452bf5f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjAwMTIsIm5iZiI6MTcyMDg1OTcxMiwicGF0aCI6Ii8yMDgxNTUxOS8zNDgyODU2NTQtZDVkMzJkNGItMWEyMi00MzBiLTk2YjctMTAyMTQ1MmJmNWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA4MzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZTM4YTlmNjA5ZDY5N2I5MWJmYmQwMTQ5MWMzOWIwZTRjZjc1OWE2ODJiZjAwYjllOTgzZDIzOTI5ZWFjZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RhBTRZrWNfjl-_B4dwwlF8jAuRVjkw9angzYTpSJn24)

Thank you very much
