### ISSUE TITLE
humann2meco  -Some (unclassified) entries in the meco OTU table are assigned with negative entries  

### ISSUE THREAD

**Issue by barnali-waugh** [ChiLiubio/microeco#388]
Dear Dr. Chi,

I have generated the pathabundance.tsv file (merged) using humann (Reads per kilo base units). 
I used the following command to import the pathabundance.tsv file in microeco.

me_pwy <- humann2meco('Four_pathabundance_mod.tsv', db = "MetaCyc", sample_table = in_meta)
in_meta <- read.csv("metadata.csv", row.names = 1, sep = "\t")
View(me_pwy$otu_table) 

Some entries in the OTU table are assigned with negative values (mostly unclassified taxa and a few classified ones). Please find attached a file showing some of the negative entries. 

Is this normal? If not, what should be done to avoid generating negative entries. 

Thank you.  

[Pathways.pdf](https://github.com/user-attachments/files/16311126/Pathways.pdf)

**Comment by ChiLiubio** [comment]
Hi. They are not negative. Just very small number.
![图片](https://github.com/user-attachments/assets/fc866a94-ac45-4edd-848b-aa5e284b9239)

**Comment by ChiLiubio** [comment]
If you want to check whether these numbers are correct, please open the raw file in text (or excel, maybe need to change the format in excel) to find one to compare.

**Comment by barnali-waugh** [comment]
Grateful for your timely feedback.
