### ISSUE TITLE
Plotting tax4fun2 results

### ISSUE THREAD

**Issue by alisr7** [ChiLiubio/microeco#39]
Hi Chi,

I am not sure how to plot my results after running tax4fun2, I appreciate it if you could guide us on how to plot pathway relative abundance and lefse differences.
Thanks,
Ali

**Comment by ChiLiubio** [comment]
Hi Ali,
The key and basic operation is to construct a microtable object as you can see in the tax4fun part of tutorial. Please see the tax4fun part of tutorial and try to use ko_map data as the tax_table and your tax4fun2 result table as the otu_table. Please also see the README part of file2meco package. There are several metagenomic examples there. I think those are useful to help you understand the basic logistics of microtable object and how to do lefse and other operations you need.
Please feel free to tell me if there are still stuck things.

Best
Chi

**Comment by alisr7** [comment]
Thank you Chi for your prompt response. One more question, apart from Unifrac distance and the null model analysis, which steps of the tutorial do require a phylogenetic tree? Specifically do the cladogram lefse differential analysis in "trans_diff class" and the co-occurrence plots in trans_network class require a phylo tree?
Thanks,
Ali

**Comment by ChiLiubio** [comment]
Another part is the phylogenetic alpha diversity i.e. PD in the alpha diversity measurements in microtable class. No other things seems to work with phylogenetic tree. The cladogram in lefse is taxonomic tree, not phylogenetic tree.

Chi

**Comment by alisr7** [comment]
Thanks Chi!
Ali
