### ISSUE TITLE
Clarity on the "use_group_list = TRUE" in trans_func functions

### ISSUE THREAD

**Issue by biazen123** [ChiLiubio/microeco#390]
Hi 
Why use_group_list = TRUE is not working in "trans_func$plot_spe_func_perc(use_group_list = TRUE)" in the recent versions of microeco?
Best

**Comment by ChiLiubio** [comment]
Hi. This parameter has been deprecated, as we have added a function `trans_spe_func_perc` for more easily manage the data. Please feel free to tell me if you have other specific needs.

Best,
Chi
