### ISSUE TITLE
Trans Gamma diversity, sample dots not seen within the confidence interval

### ISSUE THREAD

**Issue by CYBERBOY1210** [ChiLiubio/microeco#391]
Hi, and thank you so much for your awesome R-package!

I have two questions:

1). When I ran the correlation between Gamma diversity and beta diversity using Mecodev,  the sample points/dots that fall within the confidence intervals are not visible, is there any way to make them visible? Also,  the correlation generates a n R-value....is that an R2(R squared) value?

2). I know DbRDA is available in the package, but Is there any way of running a DbCCA as well?

**Comment by ChiLiubio** [comment]
Hi.
1) Please add a parameter `line_alpha = 0.2`. The parameter will be passed to plot_scatterfit function of trans_env class. R means the coefficient of correltion. R2 is for regression.
2) I have not seen the dbCCA method. If you have related paper or link, please send me to have a look. Thanks.

**Comment by CYBERBOY1210** [comment]
Thank you!

**Comment by CYBERBOY1210** [comment]
Thank you!
