### ISSUE TITLE
get correlation matrix from trans_network$new

### ISSUE THREAD

**Issue by scilexenko** [ChiLiubio/microeco#395]
Hi, 

I'm working with the network construction with microeco package. I would like to get the calculated correlation and p-values matrix. How can I get it ? 

Here is my code : 

```
tmp <- trans_network$new(dataset = tmp, cor_method = "spearman", use_sparcc_method = c("SpiecEasi"), 
                           #filter_thres = 0.0001,
                           taxa_level = "Genus",
                           SparCC_simu_num= 100,
                           nThreads = 10)
 
  tmp$cal_network(COR_p_thres = 0.05, COR_cut = 0.7,   COR_p_adjust = "fdr", COR_weight = T, add_taxa_name = c("Kingdom", "Phylum", "Family"))
```
  
Thank you.
Ivan

**Comment by ChiLiubio** [comment]
Hi. Please find it in the help document. For your object, it is `tmp$res_cor_p$cor` and `tmp$res_cor_p$p`
![图片](https://github.com/user-attachments/assets/00c5144a-d808-42d0-a83a-b5d8ccb4c921)

**Comment by scilexenko** [comment]
thank you
