### ISSUE TITLE
SpiecEasi::spiec.easi in cal_network doesn't seem to change a thing

### ISSUE THREAD

**Issue by scilexenko** [ChiLiubio/microeco#396]
Hello, 

I've been experimenting with the network construction using `cal_network` and `trans_network$new`
I've trying to change the parameters for the network calculation using ` SpiecEasi::spiec.easi` in cal_network like here : 
 
```
t1 <- trans_network$new(dataset = tmp_b, cor_method = NULL, taxa_level = "Genus", filter_thres = 0.0001)

pargs2 <- list(rep.num=1000, seed=10010, ncores=10)
t1$cal_network(network_method = "SpiecEasi", SpiecEasi_method = "mb", 
               SpiecEasi::spiec.easi(lambda.min.ratio=1e-3, nlambda=30, sel.criterion='bstars', pulsar.select=TRUE, pulsar.params=pargs2))
```

But it doesn't seem to change how the network computed, since I have the same result whatever parameters of `SpiecEasi::spiec.easi` I put. 

Can you clarify me on this, please ?

Thank you in advance, 
Ivan

**Comment by ChiLiubio** [comment]
Hi. Please directly provide required parameters for parameter passing.
![图片](https://github.com/user-attachments/assets/254971b5-075a-4e51-a9f1-614a3115e1e7)
So the correct format should be:
```
t1 <- trans_network$new(dataset = dataset, cor_method = NULL, taxa_level = "OTU", filter_thres = 0.0005)

pargs2 <- list(rep.num=1000, seed=10010, ncores=1)
t1$cal_network(network_method = "SpiecEasi", SpiecEasi_method = "mb",  lambda.min.ratio=1e-3, nlambda=30, sel.criterion='bstars', pulsar.select=TRUE, pulsar.params=pargs2)
```
Best,
Chi

**Comment by scilexenko** [comment]
It worked, thank you.
