### ISSUE TITLE
Malformed colour string `#1#D95F029E77`. Must contain either 6 or 8 hex values

### ISSUE THREAD

**Issue by wangzhichao1990** [ChiLiubio/microeco#4]
Hi @ChiLiubio ,
Thanks for your R package. It is helpful for me.
when I use the method `plot_lefse_cladogram`, I get an error. Could you help me ? Thanks in advance.
my code :
```{r}
dataset <- readRDS("microtable.RDS")
dataset$cal_abund()
dataset$tidy_dataset()
t1 <- trans_diff$new(dataset = dataset, method = "lefse", group = "group", alpha = 0.01, lefse_subgroup = NULL)
t1$plot_lefse_cladogram(use_taxa_num = 200, use_feature_num = 50, clade_label_level = 5)
```
error message:
```{r}
错误: Malformed colour string `#1#D95F029E77`. Must contain either 6 or 8 hex values
此外: There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by ChiLiubio** [comment]
Please provide more details on the package version and the dataset you used. The current example data in microeco v0.3.0 is different from the previous version. We will update the tutorial recently.

**Comment by wangzhichao1990** [comment]
> Please provide more details on the package version and the dataset you used. The current example data in microeco v0.3.0 is different from the previous version. We will update the tutorial recently.

The version of microeco is 0.3.0.
The data named "microtable.RDS" is here.
[microtable.zip](https://github.com/ChiLiubio/microeco/files/5579410/microtable.zip)

**Comment by ChiLiubio** [comment]
Thanks, we have fixed the bug in the current github version. We will update the CRAN version to v0.3.2 in the next few days.
