### ISSUE TITLE
About additional distance matrix

### ISSUE THREAD

**Issue by Felipe-rdv** [ChiLiubio/microeco#40]
Hi Chi,

I got good results (with phyloseq) using the distance matrix Jensen-Shannon Divergence.
with the code: 
`phyloseq::distance(mothur_merge, method = "jsd")
`

I tried to implement this distance matrix in the microeco package but I couldn't.

In "trans_env$cal_rda":
add_matrix: default NULL; additional distance matrix provided, if you do not want to use the beta diversity matrix within the dataset.

I tried:
```
t1$cal_rda(use_dbrda = TRUE, 
           #use_measure = "bray",
           add_matrix = as.matrix(
                   phyloseq::distance(mothur_merge, method = "jsd")),
           )
```
but it didn't work because the plot remains the same as when I use:
` use_measure = "bray"`

I also tried using this distance matrix in "trans_beta$new" and it wasn't possible. Is there any solution for this case?

Thank you, my best

**Comment by ChiLiubio** [comment]
Hi,
Another way is to add your distance matrix  to dataset$beta_diversity, such as dataset$beta_diversity$jsd <- your_distance_matrix
Then use t1$cal_rda(use_dbrda = TRUE, use_measure = "jsd")
I think this way is normative as you can also use jsd in other parts like the bray.

Best
Chi

**Comment by Felipe-rdv** [comment]
Hi Chi,
Thank you very much for the help, it worked perfectly!
Congratulations on this great package.
Thanks, my best
