### ISSUE TITLE
How to extract a subset based on the name of a node using subset_network？

### ISSUE THREAD

**Issue by Liuyuxinn** [ChiLiubio/microeco#404]
Hi，
I want to extract the nodes named otu118, otu158, otu136 and the edges associated with these nodes from my network, how should I proceed?

Here is my code:  
t1$subset_network(node=t1$res_node_table %>% base::subset(name=="otu118", "otu158", "otu136"%>% rownames, rm_single=TRUE)

But it reports error: Error in `[.data.frame`(x,r,vars,drop=drop): undefined columns selected

How do I change my code?

**Comment by ChiLiubio** [comment]
Hi. The names are enough for the node parameter.
```
new <- t1$subset_network(node=c("otu118", "otu158", "otu136"))
```

**Comment by Liuyuxinn** [comment]
> "
I actually need to pick out the subnetwork associated with 32 nodes, but when I use this code, it only shows type22 when there are actually 45 nodes associated with the subnetwork.

Where is the error?

**Comment by Liuyuxinn** [comment]
> Hi. The names are enough for the node parameter.
> 
> ```
> new <- t1$subset_network(node=c("otu118", "otu158", "otu136"))
> ```

According to this code you provided, the final extraction is the network consisting of otu118-otu158, otu158-otu136, otu118-otu136?
How to extract all the edges of the nodes otu118, otu158, otu136? And form a sub-network?

**Comment by ChiLiubio** [comment]
To do this, we should first extract all the required nodes based on the res_edge_table.
```
nodes_raw <- c("otu118", "otu158", "otu136")
edge_table_filter <- t1$res_edge_table %>% .[.[,1] %in% node_raw | .[,2] %in% nodes_raw, ]
nodes_required <- c(edge_table_filter[, 1], edge_table_filter[, 2]) %>% unique
new <- t1$subset_network(node = nodes_required)
```

**Comment by Liuyuxinn** [comment]
> To do this, we should first extract all the required nodes based on the res_edge_table.
> 
> ```
> nodes_raw <- c("otu118", "otu158", "otu136")
> edge_table_filter <- t1$res_edge_table %>% .[.[,1] %in% node_raw | .[,2] %in% nodes_raw, ]
> nodes_required <- c(edge_table_filter[, 1], edge_table_filter[, 2]) %>% unique
> new <- t1$subset_network(node = nodes_required)
> ```

How to save the extracted subnetwork?
Here is my code:
new$save_network("M1.gexf")
It shows error: 错误: 不适用于非函数

**Comment by Liuyuxinn** [comment]
Thank you very much for successfully solving my problem！

**Comment by Liuyuxinn** [comment]
> new is a network with igraph class, not the trans_network object. So we should convert it to trans_network object.
> 
> ```
> new_obj <- clone(t1)
> new_obj$res_network <- new
> new_obj$save_network("test.gexf")
> ```

 I have another question about the extracted sub-network: for this sub-network NEW, how do I extract all its edge information?
