### ISSUE TITLE
chorddiagram : cal_sum_links

### ISSUE THREAD

**Issue by Ananya1006** [ChiLiubio/microeco#406]
Hi Chi! It's a beautiful package you have created and it has been so much fun using it on my data.
I ran into some problem with the network analysis but couldn't find similar issues here.
I am interested in analysing co-occurence of microbes in networks. More specifically I want to check the patterns or interactions of microbes at Phylum/Class level:
1) within various modules of the network
2) across modules of network

I was able to create a chord diagram using plot_sum_links for my network (the trans_network object is g_net2) as a whole but couldn't incorporate the already calculated module information in my chord diagram. 
I want to be able to create a chord diagram with the outermost layer as modules, second layer should have phylum information. If that's too complex, then it would be enough to create plots for individual modules. 

Here is the chord diagram code which I was working with:
g_net2      
trans_network object:
res_network: 
IGRAPH 00c6074 UNW- 401 2889 -- 
+ attr: name (v/c), taxa (v/c), Phylum (v/c), RelativeAbundance (v/n), module (v/c), label (e/c), weight (e/n)
+ edges from 00c6074 (vertex names):
 [1] Shewanella--Clostridium_sensu_stricto_13 Shewanella--Bifidobacterium             
 [3] Shewanella--Aeromonas                    Shewanella--OPB41                       
 [5] Shewanella--Brevibacterium               Shewanella--DEV007                      
 [7] Shewanella--Psychrobacter                Shewanella--Lactobacillus               
 [9] Shewanella--Sedimenticola                Shewanella--Nocardioides                
[11] Shewanella--Lineage_IIb                  Shewanella--Haloferula                  
[13] Woeseia   --Bacteroidetes_BD2-2          Woeseia   --Woesearchaeales             
[15] Woeseia   --Latescibacterota             Woeseia   --Sva0081_sediment_group      
+ ... omitted several edges

g_net2$cal_sum_links(taxa_level = "Phylum")
The positive results are stored in object$res_sum_links_pos ...
No negative edges found ...
g_net2$plot_sum_links #works perfectly
dim(g_net2$res_sum_links_pos)
[1] 43 43

#to subset the first module
gnett <- clone(g_net2)
g1 <- gnett$subset_network(node = gnett$res_node_table %>% base::subset(module == "M1") %>% rownames, rm_single = TRUE)
G_1 <- clone(gnett)
G_1$res_network <- g1

G_1
trans_network object:
res_network: 
IGRAPH 663c4ca UNW- 98 556 -- 
+ attr: name (v/c), taxa (v/c), Phylum (v/c), RelativeAbundance (v/n), module (v/c), label (e/c), weight (e/n)
+ edges from 663c4ca (vertex names):
 [1] Shewanella   --Clostridium_sensu_stricto_13 Shewanella   --Bifidobacterium             
 [3] Shewanella   --Aeromonas                    Shewanella   --OPB41                       
 [5] Shewanella   --Brevibacterium               Shewanella   --DEV007                      
 [7] Shewanella   --Psychrobacter                Shewanella   --Lactobacillus               
 [9] Shewanella   --Sedimenticola                Shewanella   --Nocardioides                
[11] Shewanella   --Lineage_IIb                  Shewanella   --Haloferula                  
[13] Prevotella   --Faecalibacterium             Prevotella   --Escherichia-Shigella        
[15] Prevotella   --Alloprevotella               Prevotella   --Thalassospira               
+ ... omitted several edges

G_1$cal_sum_links(taxa_level = "Phylum")
Error in `.rowNamesDF<-`(x, value = value) : 
  missing values in 'row.names' are not allowed**

If I am not wrong, the function cal_sum_links checks the taxa table, res_node_table, and res_edge_table to create the input matrix for chord diagram. 

I checked the examples to create chord diagrams from scratch, adding additional layers, groups/labels (https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html#basic-usage-of-making-chord-diagram ) and wanted to know if I should extract the information from modules (igraph object), and proceed? How exactly are the weighted links summed, i.e. how is the final matrix created?

I mapped the taxa file from g1 to the edge table from G_1 which had genus as label of nodes. The next step would be to calculate the sum of weights for each unique phylum pair?
head(edges)
            from                to label    weight
1 Proteobacteria        Firmicutes     + 0.7733256
2 Proteobacteria  Actinobacteriota     + 0.6798732
3 Proteobacteria    Proteobacteria     + 0.6830428
4 Proteobacteria  Actinobacteriota     + 0.6798732
5 Proteobacteria  Actinobacteriota     + 0.8322054
6 Proteobacteria Verrucomicrobiota     + 0.6830428

If there is any other approach or analysis more suited to this goal, please let me know. Thanks in advance!

**Comment by ChiLiubio** [comment]
Hi. Could you please attach your data `g_net2` so that I can totally reproduce your issue? Please save and compress it following the steps here (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function).

**Comment by ChiLiubio** [comment]
I also find one step should be added before `G_1$cal_sum_links` as the res_edge_table in the object should be updated.
```
G_1$get_edge_table()
G_1$cal_sum_links(taxa_level = "Phylum")
```

**Comment by ChiLiubio** [comment]
Hi. I find it is fine when I add the step in the last reply.
```
library(microeco)
load("g_net2.RData")

g_net2$cal_sum_links(taxa_level = "Phylum")

G_1 <- clone(g_net2)
G_1$res_network <- g_net2$subset_network(node = g_net2$res_node_table %>% base::subset(module == "M1") %>% rownames, rm_single = TRUE)
G_1

G_1$get_edge_table()
G_1$cal_sum_links(taxa_level = "Phylum")
View(G_1$res_sum_links_pos)
```

**Comment by Ananya1006** [comment]
Yes, I can see the within-module links now.
Regarding the second goal, to check links between modules, could you suggest any solution?

Appreciate the prompt replies.

**Comment by ChiLiubio** [comment]
Here is an example. You should first install the microeco package v1.9.2 from github as there is some necessary parameters that I have added recently and are used in the example. Then you must rerun the whole trans_network class. I use the dataset in the package.
```
library(microeco)
data(dataset)
# generate a simple network first
test1 <- trans_network$new(dataset = dataset, cor_method = "bray", filter_thres = 0.003)
test1$cal_network(COR_p_thres = 0, COR_cut = 0.3)
test1$cal_module()
test1$get_node_table()
test1$get_edge_table()

# extract the node and edge tables
edge_table <- test1$res_edge_table
node_table <- test1$res_node_table
# replace nodes with the module names
edge_table[, 1] <- node_table[edge_table[, 1], "module"]
edge_table[, 2] <- node_table[edge_table[, 2], "module"]

# only remain those edges with different modules; also return trans_network object instead of igraph type
new_obj <- test1$subset_network(edge = which(edge_table[, 1] != edge_table[, 2]), return_igraph = FALSE)
new_obj$cal_sum_links()
new_obj$plot_sum_links()
```

**Comment by Ananya1006** [comment]
Hi! I'm getting the following error when I do the above with g_net2 trans_network object:

g_net2
trans_network object:
res_network: 
IGRAPH de81f97 UNW- 401 2889 -- 
+ attr: name (v/c), taxa (v/c), Phylum (v/c), RelativeAbundance (v/n), module (v/c), label (e/c),
| weight (e/n)
+ edges from de81f97 (vertex names):
 [1] Shewanella--Clostridium_sensu_stricto_13 Shewanella--Bifidobacterium             
 [3] Shewanella--Aeromonas                    Shewanella--OPB41                       
 [5] Shewanella--Brevibacterium               Shewanella--DEV007                      
 [7] Shewanella--Psychrobacter                Shewanella--Lactobacillus               
 [9] Shewanella--Sedimenticola                Shewanella--Nocardioides                
[11] Shewanella--Lineage_IIb                  Shewanella--Haloferula                  
[13] Woeseia   --Bacteroidetes_BD2-2          Woeseia   --Woesearchaeales             
+ ... omitted several edges

edge_table <- g_net2$res_edge_table
node_table <- g_net2$res_node_table
head(edge_table)
       node1                        node2 label    weight
1 Shewanella Clostridium_sensu_stricto_13     + 0.7733256
2 Shewanella              Bifidobacterium     + 0.6798732
3 Shewanella                    Aeromonas     + 0.6830428
4 Shewanella                        OPB41     + 0.6798732
5 Shewanella               Brevibacterium     + 0.8322054
6 Shewanella                       DEV007     + 0.6830428

edge_table[, 1] <- node_table[edge_table[, 1], "module"]
edge_table[, 2] <- node_table[edge_table[, 2], "module"]
head(edge_table)
  node1 node2 label    weight
1    M1    M1     + 0.7733256
2    M1    M1     + 0.6798732
3    M1    M1     + 0.6830428
4    M1    M1     + 0.6798732
5    M1    M1     + 0.8322054
6    M1    M1     + 0.6830428

new_obj <- g_net2$subset_network(edge = which(edge_table[, 1] != edge_table[, 2]))
Error in ends(input_network, x) : 
  At vendor/cigraph/src/graph/type_common.c:123 : Invalid edge ID when retrieving edge endpoints. Invalid value
In addition: Warning message:
In label_raw != edge :
  longer object length is not a multiple of shorter object length

**Comment by ChiLiubio** [comment]
Do you install the microeco package v1.9.2 from github and recreate g_net2 object? If you donnot want to recalculate the g_net2, you can do like this example. At least the microeco v1.9.2 from github should be installed.
```
library(microeco)

load("g_net2.RData")

g_net2_backup <- clone(g_net2)

data(dataset)
g_net2 <- trans_network$new(dataset = dataset, cor_method = "bray", filter_thres = 0.003)
g_net2$cal_network(COR_p_thres = 0, COR_cut = 0.3)
g_net2$res_network <- g_net2_backup$res_network
g_net2$tax_table <- g_net2_backup$tax_table
g_net2$taxa_level <- g_net2_backup$taxa_level
g_net2$sample_table <- g_net2_backup$sample_table
g_net2$data_abund <- g_net2_backup$data_abund
g_net2$data_relabund <- g_net2_backup$data_relabund



g_net2$get_node_table(node_roles = F)
g_net2$get_edge_table()

# extract the node and edge tables
edge_table <- g_net2$res_edge_table
node_table <- g_net2$res_node_table
# replace nodes with the module names
edge_table[, 1] <- node_table[edge_table[, 1], "module"]
edge_table[, 2] <- node_table[edge_table[, 2], "module"]

# only remain those edges with different modules; also return trans_network object instead of igraph type
new_obj <- g_net2$subset_network(edge = which(edge_table[, 1] != edge_table[, 2]), return_igraph = FALSE)
new_obj$cal_sum_links()
new_obj$plot_sum_links()

```

**Comment by Ananya1006** [comment]
It's solved now, the error was due to some other package dependencies. 

The obtained chord plot shows the phylum interactions belonging to different modules now but I couldn't find any argument to label the modules? I would like to see and trace which exact modules show any unique interactions at the phylum level, i.e. I want to be able to create a chord diagram with one layer having labels of module no., and another should have phylum information (based on colors) if that's possible.

**Comment by ChiLiubio** [comment]
I feel it is very complex to visualize such results with chord diagram. Each element (e.g. M1 - M2 or M1 - M3) will have a chord diagram. To merge all these (all combinations) into one is not an easy thing. I will tell you if I have related idea.
