### ISSUE TITLE
Error in `[.data.frame`(rres, , rownames(abund_table_sub_lda), drop = FALSE)

### ISSUE THREAD

**Issue by hlwCoBi** [ChiLiubio/microeco#408]
The following error occurs when I use the 'trans_diff' function for lefse analysis
![image](https://github.com/user-attachments/assets/6ce101b1-dbf0-43fa-bd03-b1c454ca95f0)
The colnames of sample_table is this:
![image](https://github.com/user-attachments/assets/07b691b1-63e2-4f39-bf38-ad62085b5194)
My sample_table is this:
![image](https://github.com/user-attachments/assets/d12a6b04-c4a3-4dee-bf51-e143851016ad)

**Comment by ChiLiubio** [comment]
Hi. Could you please attach your `dataset` so that I can reproduce your issue? To save the dataset, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object. Please also provide your microeco package version.

**Comment by hlwCoBi** [comment]
Thanks, my dataset is this:
[dataset.zip](https://github.com/user-attachments/files/16924629/dataset.zip)
and my microeco package version is 1.7.1

**Comment by ChiLiubio** [comment]
Hi. I find there is an abnormal taxonomic information in tax_table with "\t" and "\n" in it.
```
library(microeco)
load("dataset.RData")

dataset$tax_table$Species[grepl("s__Synechococcus_sp._JA-2-3Ba(2-13)", dataset$tax_table$Species, fixed = TRUE)]
dataset$tax_table$Species[grepl("s__Synechococcus_sp._JA-2-3Ba(2-13)", dataset$tax_table$Species, fixed = TRUE)] <- "s__Synechococcus_sp._JA-2-3Ba(2-13)"
dataset$cal_abund()

lefse <- trans_diff$new(dataset = dataset, method = "lefse", group = "Species_name", lefse_norm = 10000, alpha = 0.01, p_adjust_method = "none", lefse_subgroup = NULL)
```
The speed is very low because there are too many groups (22) for the LDA calculation of paired combinations.

**Comment by hlwCoBi** [comment]
> Hi. I find there is an abnormal taxonomic information in tax_table with "\t" and "\n" in it.
> 
> ```
> library(microeco)
> load("dataset.RData")
> 
> dataset$tax_table$Species[grepl("s__Synechococcus_sp._JA-2-3Ba(2-13)", dataset$tax_table$Species, fixed = TRUE)]
> dataset$tax_table$Species[grepl("s__Synechococcus_sp._JA-2-3Ba(2-13)", dataset$tax_table$Species, fixed = TRUE)] <- "s__Synechococcus_sp._JA-2-3Ba(2-13)"
> dataset$cal_abund()
> 
> lefse <- trans_diff$new(dataset = dataset, method = "lefse", group = "Species_name", lefse_norm = 10000, alpha = 0.01, p_adjust_method = "none", lefse_subgroup = NULL)
> ```
> 
> The speed is very low because there are too many groups (22) for the LDA calculation of paired combinations.

Thanks for your answer and I have solved the error so far.
