### ISSUE TITLE
Funguild

### ISSUE THREAD

**Issue by LMalard** [ChiLiubio/microeco#41]
Thank you for a very useful package. 
I'm wondering why there are so many different guilds in the output when the FUNGUILD paper only describes 12?

Thanks,
Lucie

**Comment by ChiLiubio** [comment]
Hi,
Please have a look on the FUNGUILD database by loading the data inside the package or find the data manually. It is a curated data frame. I guess what you mean on many guilds should be the detailed guilds under the upper classes which is also described in the paper.

Best
Chi
