### ISSUE TITLE
when run trans_alpha$new, Skip 'Chao1', 'ACE' and 'Observed' ...

### ISSUE THREAD

**Issue by wanjinhu** [ChiLiubio/microeco#410]
Hi

When I run `trans_alpha$new`, just like: `t1 <- trans_alpha$new(dataset = dataset,  group = "group")`

It showed the message:

`The alpha_diversity in dataset not found! Calculate it automatically ... Skip 'Chao1', 'ACE' and 'Observed' ...`

I am wonder to know why index Chao1 and ACE doesn't calculate? The data I used is obtained from metagenomes, and there is no problem with generating data in the previous step, which is `microtable$new`

Thanks

Wanjin Hu

**Comment by ChiLiubio** [comment]
Hi. These metrics require count data that are integers. So when the input data are not integers, these will be automatically skipped. There has been a very similar issue with this (https://github.com/ChiLiubio/microeco/issues/359).

**Comment by wanjinhu** [comment]
My bad, I entered the relative abundance table.

Thanks. I will close this issue.
