### ISSUE TITLE
LEFSE result inconsistent with taxa distribution among groups

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#415]
Dear Chi, 

I am having some trouble interpreting the LEfSe results from my dataset, and was wondering if there could be a calculation error when obtaining the LDA scores. The distribution of certain genera across the groups doesn't seem to match the LEfSe output. For example, take the genus *Tubulicium*, which is clearly associated with the FR group (virtually undetectable in the others), yet LEfSe assigns it to the BG group. I have seen similar questions raised in previous issues on microeco, and ypou said that it might have something to do with the use of the median or mean in LEfSe's calculations, but I dont know how to arrange that, in case is the cause. But looking to  *Tubulicium* diff bars, Iit seems a bug somewhere, perhaps my code?  

Thank you very much.

Dataset: 

> microecoITS_norm
microtable-class object:
sample_table have 156 rows and 18 columns
otu_table have 3128 rows and 156 columns
tax_table have 3128 rows and 8 columns
phylo_tree have 3128 tips
rep_fasta have 3128 sequences
Taxa abundance: calculated for Kingdom,Phylum,Class,Order,Family,Genus,Species,ASVs 

### LEFSE Genus ----

t1 <- trans_diff$new(dataset = microecoITS_norm, 
                     method = "lefse",
                     group = "Site", 
                     alpha = 0.05, 
                     lefse_subgroup = NULL,
                     taxa_level = "Genus",
                     p_adjust_method = "fdr",
                     remove_unknown = TRUE
                     )

str(t1$res_diff)

###  From v0.8.0, threshold is used for the LDA score selection.
Lefse_plot_genus <- t1$plot_diff_bar(use_number = 1:10,
                                     width = 0.8,
                                     color_values = color_vector,
                                     group_order  = order_x,
                                     keep_prefix = FALSE,
                                     threshold = 4,
)

Lefse_plot_genus

### plot the abundance 
Lefse_bar_taxa <- t1$plot_diff_abund(
                                     select_taxa = t1$plot_diff_bar_taxa,
                                     color_values = color_vector,
                                     keep_prefix = FALSE)

###  show part of the table
t1$res_diff[1:5, c(1, 4, 7)]
                                     
Lefse_bar_taxa

###  combined figure
Lefse_plot_genus <- Lefse_plot_genus + theme(legend.position = "none")
Lefse_bar_taxa <- Lefse_bar_taxa + theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
Lefse_plot_full <- gridExtra::grid.arrange(Lefse_plot_genus, Lefse_bar_taxa, ncol = 2, nrow = 1, widths = c(2, 1.7))

![image](https://github.com/user-attachments/assets/17d4fb2f-62dc-46c7-b043-a8ee66fcaad4)

PD: I did all the recommended tidy functions and did not change the results:
microecoITS_norm$tax_table %<>% tidy_taxonomy
microecoITS_norm$tidy_dataset()
microecoITS_norm$cal_abund()

**Comment by ChiLiubio** [comment]
Hi. Such case can be found occasionally when there are many 0 abundance in a group, which also has a higher mean (because a few values are specially high). Please first check whether there are many 0 in FR for Tubulicium (more than BG). The non-parameteric KW test is used in lefse, so the median instead of mean is arranged in the left LDA plot in the result.

**Comment by ChiLiubio** [comment]
Hi. It is hard to say which method is better for the taxa at high taxonomic levels, because most of the methods in this field are designed for ASV/OTU. For these data, I think it is practicable and robust to filter these features with low occurrence frequency.

**Comment by jamorillo** [comment]
Hello Chi; I agree, thanks for shearing your knowledge!
