### ISSUE TITLE
Question about plot_scatterfit 

### ISSUE THREAD

**Issue by meredithds** [ChiLiubio/microeco#417]
Hello, 

I used a mantel test on centered environmental data and the Bray-Curtis distances of the microbial community data. My first question is if the environmental data is used to create a Euclidean Distance matrix for the mantel test-- I could not identify where in the code this would take place. 

I then wanted to use plot_scatterfit to visualize the significant variables by treatment group. When the vector for the variable of interest is created using Euclidean distance and then correlated with the Bray-Curtis dissimilarities it creates an xy table. I have 40 samples, yet when this xy table is created, each treatment has 45 points. I was wondering why this might be. 

Thank you!
Meredith Snyder

**Comment by ChiLiubio** [comment]
Hi. Yes. The environmental data is used to create a Euclidean Distance matrix for the mantel test. For the second one, how many samples are there in your each treatment. If 45 points are there, 10 samples and 4 treatment? If you need me to help checking the  details, please provide more information or attach your data and steps (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function). Thanks.  

Chi

**Comment by ChiLiubio** [comment]
It should be fine, as the combination of 10 samples results in 45 points (C~10~^9^).
