### ISSUE TITLE
About trans_diff and test_mark function

### ISSUE THREAD

**Issue by Felipe-rdv** [ChiLiubio/microeco#42]
Hi Chi,

I'm working with randomforest and exploring the test_mark function.

When we have taxas with different normalities, we may have problems in a dataset with different normality taxas:
If the taxa is non-parametric, p.value is returned in list form:
`list(p_value = res1$p.value, med = med)`

However, when you do anova, the p.value is returned out of the list, just the raw value:
```
pvalue <- as.numeric(unlist(summary(res1))[9])
pvalue
```

This can give a problem when processing pvalues as all items are expected to be sub-list items:
`pvalue <- unlist(lapply(res_class, function(x) x$p_value))`

In this case too, when it is anova, I imagine that we should consider:
`rownames(d1)[1] <- "Abundance"`
for:
`colnames(d1)[1] <- "Abundance"`

Hope this helps,
thanks

**Comment by ChiLiubio** [comment]
Hi @Felipe-rdv 

Thanks so much for your careful checking. Yes, it should be: colnames(d1)[1] <- "Abundance"
and the returned value in anova should be also a list as you say.
The anova method has not been used in the class as the non-parametric tests can be more robust. I still place the anova there in case of other need. Anyway, thanks for your suggestion. I almost forget the anova method there.
Please feel free to tell me if you have other queries or ideas on the project. Joining us is also welcome if you are interested in the project.

Best
Chi

**Comment by Felipe-rdv** [comment]
Hi @ChiLiubio,
It's a pleasure to help, you did a great job. It was great that you put anova because in my case I have mixed normalities.
I have ideas and it will be great if I can collaborate on the project.
Can you send me your email or some form of contact so we can talk?
Thanks,
my best wishes

**Comment by ChiLiubio** [comment]
Hi,
My email:  liuchi0426@126.com
and yours?

Best
Chi

**Comment by Felipe-rdv** [comment]
Hi,
I just sent you an email,
my best
