### ISSUE TITLE
Filtering ASVs/OTUs based on FungalTraits

### ISSUE THREAD

**Issue by alejorojas2** [ChiLiubio/microeco#421]
Hi Chi,

This may be a naive question and tried a couple of things.  We are trying to subset the microtable after querying the FungalTraits database to a specific lifestyle: "plant_pathogens".  But in the process, the object gets reduced to a data frame instead of maintaining the S6 object format.

This is the code that we were using:

```
#Convert phyloseq into microtable object
mt_fungi <- phyloseq2meco(filter_fungi)
mt_fungi

#microtable-class object:
#sample_table have 203 rows and 11 columns
#otu_table have 1198 rows and 203 columns
#tax_table have 1198 rows and 7 columns


#use tidy_dataset() to make OTUs and samples information consistent across files
mt_fungi$tidy_dataset()

#Then, let’s perform the fungal trait prediction

t1 <- trans_func$new(mt_fungi)
t1$cal_spe_func(fungi_database = "FungalTraits")
t1$cal_spe_func_perc(abundance_weighted = TRUE)

#Extract OTU names based on lifestyle as vector
ASVs_PP <- rownames(t1$res_spe_func[t1$res_spe_func$`primary_lifestyle|plant_pathogen` > 0,])
```

I stopped there since I did not see a `prune_taxa` function like in phyloseq. So I checked the tutorial for subset methods and try this:

```
#Trying to subset based on lifestyle but not successful
t1$res_spe_func %<>% base::subset(`primary_lifestyle|plant_pathogen` == 1)
```
I get a table with 253 taxa (which corresponded to plant path), but it is a dataframe, losing all the associated data.

Any suggestions?
Thanks!

[fungi_data.Rdata.zip](https://github.com/user-attachments/files/17250226/fungi_data.Rdata.zip)

**Comment by ChiLiubio** [comment]
Hi. The subset operation is something like this:
```
library(magrittr)
# it is enough to manipulate the otu_table or tax_table
mt_fungi$otu_table %<>% .[ASVs_PP, ]
mt_fungi
mt_fungi$tidy_dataset()
mt_fungi
```
The data format within the R6 class is familiar to us. The format of data such as otu_table and tax_table are data.frame, which differs significantly from phyloseq. Thus, we can manipulate these data like a typical data.frame and then use tidy_dataset to tidy them. 57 samples have also been removed because they have no abundance in these ASVs.

Best
Chi
