### ISSUE TITLE
FAPROTAX 1.2.10 is available, polite request of update in the package

### ISSUE THREAD

**Issue by PeterPan0106** [ChiLiubio/microeco#422]
Hi, the FAPROTAX 1.2.10 is available now, would you please update it in your package? Thank you for offering and continuously developing the wonderful package "microeco".

**Comment by ChiLiubio** [comment]
Hi. Thank you. It will be updated in the coming days. 

Best
Chi

**Comment by ChiLiubio** [comment]
Hi. Thank you. It will be updated in the coming days. 

Best
Chi

**Comment by ChiLiubio** [comment]
Hi. Can you open the link (http://www.loucalab.com/archive/FAPROTAX/lib/php/index.php?section=Download)? It failed in my lab.

**Comment by PeterPan0106** [comment]
> Hi. Can you open the link (http://www.loucalab.com/archive/FAPROTAX/lib/php/index.php?section=Download)? It failed in my lab.

Yes, things worked fluently on my computer.

**Comment by ChiLiubio** [comment]
Thanks. The package in Github has been updated with the FAPROTAX 1.2.10.

**Comment by PeterPan0106** [comment]
Thank you!
Best regards
