### ISSUE TITLE
Issue with order_x

### ISSUE THREAD

**Issue by susheelbhanu** [ChiLiubio/microeco#424]
Hi, 

I'm trying to do a bar plot where I order the samples by date. When I use the `order_x` function with a vector, my samples seemed to be grouped instead of showing individual bars. 

My code is below with the respective figures

```bash 
t1 <- trans_abund$new(dataset = dataset_filter, taxrank = "Phylum", ntaxa = 15, use_percentage = FALSE)
t1$plot_bar(others_color = "grey70", facet = "group", xtext_keep = FALSE, legend_text_italic = FALSE)
```
![image](https://github.com/user-attachments/assets/4c9b1def-ed65-4367-9344-01f000248700)

```bash
# sorting by date
sorted_dates <- levels(unique(bathing_metadata$date))
t1$plot_bar(others_color = "grey70", facet = "group", xtext_keep = FALSE, legend_text_italic = FALSE,
            order_x = c("2023-05-31", "2023-06-06", "2023-06-15", "2023-06-25", "2023-06-26",
                        "2023-06-30", "2023-07-05", "2023-07-13", "2023-07-19", "2023-07-24",
                        "2023-08-03", "2023-08-11", "2023-08-16", "2023-09-03", "2023-09-11", 
                        "2023-09-21", "2023-09-25", "2023-10-03"))
```
![image](https://github.com/user-attachments/assets/a7c27084-5ba3-40d7-b110-53f6097814de)

Attached is the RData object. 
[dataset_filter_data.zip](https://github.com/user-attachments/files/17339823/dataset_filter_data.zip)

Thank you for your help!
Susheel

**Comment by ChiLiubio** [comment]
Hi. The `order_x` is used to sort the samples, not groups. So the input in order_x must be sample names, same with the rownames in `dataset_filter$sample_table`. So if you want to sort samples according to date, you can first sort them and extract the samples like the following steps.
```
tmp <- dataset_filter$sample_table
# order the table
tmp <- tmp[order(tmp$date), ]
# extract the ordered sample names
tmp_orderx <- rownames(tmp)
t1$plot_bar(others_color = "grey70", facet = "group", xtext_keep = FALSE, legend_text_italic = FALSE, order_x = tmp_orderx)
```

Best
Chi

**Comment by susheelbhanu** [comment]
Ah i see - thank you @ChiLiubio!

Would be nice to have the functionality to sort by groups in the future as well. 

Thanks for all your work!
