### ISSUE TITLE
trans_env$cal_autocor p values

### ISSUE THREAD

**Issue by alberjo296** [ChiLiubio/microeco#425]
Hi Chi,

I'm using the function trans_env$cal_autocor() in microeco, and I obtain the figures with the correlation coefficients and their significance based on the number of asterkis, but I am not able to see the p-values, and I would like to be able to incorporate them in the text. How can I obtain the p-values?

With trans_env$cal_autocor it gives me NULL

Thank you :)

**Comment by alberjo296** [comment]
I just found how:

# Spearman correlation and return results as data frame (ggpairs = FALSE)
cor_results <- t1$cal_autocor(
  upper = list(continuous = GGally::wrap("cor", method= "spearman")), 
  ggpairs = FALSE
)

# Print or examine the correlation results
print(cor_results)

Sorry for the incovenience and thank you for the package 👍💯

**Comment by ChiLiubio** [comment]
Hi. For the values, not the figure, please use parameter `ggpairs = FALSE`.
```
t1$cal_autocor(ggpairs = FALSE, cor_method = "spearman")
```

**Comment by ChiLiubio** [comment]
Hi. For the values, not the figure, please use parameter `ggpairs = FALSE`.
```
t1$cal_autocor(ggpairs = FALSE, cor_method = "spearman")
```
