### ISSUE TITLE
Polite enquiry about "trans_network class"

### ISSUE THREAD

**Issue by PeterPan0106** [ChiLiubio/microeco#426]
Hi and thank you again for your wonderful package and nice tutorial. I still have a few questions regarding the following issues.

1, for "t1 <- trans_network$new(dataset = mt, cor_method = "spearman", use_WGCNA_pearson_spearman = TRUE, filter_thres = 0.0001)", I would like to know, if I use WGCNA package to calculate, is the method still standard spearman, or is it modified by WGCNA? My result changed very much when using WGCNA and not, method are both spearman. I've checked their original publication and was not very sure, because they proposed some modified algorithm in the publication (https://doi.org/10.1186/1471-2105-9-559).

2, I'm new to research in this field, so this question might be a little silly, in "res_network_attr", is "Vertex" equal to "nodes", and "Edge" equal to "links"?

3, I've seen publications use the term "positive link percentage" (https://doi.org/10.1016/j.watres.2021.117428, Fig. 6e), I would like to know if it could be calculated using microeco package. I've sorted out through "t1$res_network_attr" and found related tables, but due to my worse code ability, I was not able to sum it and calculate the positive link percentage. Will you please provide some guide on how to sum all positive and negative links, and then calculate the percentage?

4, based on https://doi.org/10.1016/j.watres.2021.117428, Fig. 6e, is it possible in the future for you to add all 7 bar plots with grouping to a function for us to plot faster? The 7 plots including comparisons of number of nodes, number of links, positive link percentages, average degrees, average weighted degrees, number of modules, and modularity. Your current t1$res_network_attr already cover much of them.

Thank you very much for your kind reply.

Best regards,
Peter

**Comment by ChiLiubio** [comment]
Hi. Thanks for the appreciation!
1. The method comes from the corAndPvalue function of WGCNA pakcage. There are actually a few difference in some cases between it and that in base. So you can first create the network and then check whether two networks are very different. I have not found a large difference in my data. It depend largely on the data. If so, please attach your data and steps, I will reproduce it.
2. Yes. They are similar concepts.
3. Please search `cal_sum_links` function in the tutorial or the help document. It is also shown in the meconetcomp part (https://chiliubio.github.io/microeco_tutorial/meconetcomp-package.html).
4. I will consider it in the tutorial. Thanks.

Best,
Chi

**Comment by PeterPan0106** [comment]
Thank you for your reply, it is very helpful. I'll compare the two arguments again and see, if there are huge differences as they originally do, I will send my dataset and code to your email for your reference. Thank you again for all the help.

Best regards,
Peter
