### ISSUE TITLE
How to import external correlation matrix into res_cor_p?

### ISSUE THREAD

**Issue by Liuyuxinn** [ChiLiubio/microeco#427]
Hello, 
I have some questions when building a network:
I have obtained the correlation matrix table (cor_matrix) and P value matrix table (p_matrix) through other software, and I want to import them into res_cor_p. How can I do it?

Here is my code:
t1 <- trans_network$new(dataset = dataset)
t1$res_cor_p <- list(cor = cor_matrix, p = p_matrix)
t1$cal_network(COR_p_thres = 0.05, COR_cut = 0.01)

But it shows, Error in t1$cal_network(COR_p_thres = 0.05, COR_cut = 0.01) :
All the correlation coefficients larger than COR_cut parameter are not significant under current COR_p_thres parameter!

But in fact, there are relationship pairs in my list with p values ​​less than 0.05 and correlations greater than 0.01.

How can I solve this problem?

**Comment by ChiLiubio** [comment]
Hi. Please disable the p value adjustment with `COR_p_adjust = "none"` and try again. Maybe p value adjustment leads to non-significance.

**Comment by Liuyuxinn** [comment]
> COR_p_adjust

Thank you, it has been successfully solved
