### ISSUE TITLE
cant see high order taxa in heatmaps

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#432]
Hello, 
In this example of heatmap, I would like to indicate the phylum to which the genera belong too, but it does not work, why?
I re-installed microeco today
thanks!!

show 50 taxa at Genus level

str(microeco_16S_norm_clean$tax_table) # SILVA taxononomy

'data.frame':	6194 obs. of  8 variables:
 $ Kingdom: chr  "k__Bacteria" "k__Bacteria" "k__Bacteria" "k__Bacteria" ...
 $ Phylum : chr  "p__Chloroflexi" "p__Chloroflexi" "p__Chloroflexi" "p__Chloroflexi" ...
 $ Class  : chr  "c__Anaerolineae" "c__Anaerolineae" "c__Anaerolineae" "c__Anaerolineae" ...
 $ Order  : chr  "o__SBR1031" "o__SBR1031" "o__SBR1031" "o__SBR1031" ...
 $ Family : chr  "f__A4b" "f__A4b" "f__A4b" "f__A4b" ...
 $ Genus  : chr  "g__A4b" "g__A4b" "g__A4b" "g__A4b" ...
 $ Species: chr  "s__metagenome" "s__metagenome" "s__metagenome" "s__metagenome" ...
 $ ASVs   : chr  "a__ASV_95" "a__ASV_99" "a__ASV_101" "a__ASV_108" ...

taxa_phylum_16S <- trans_abund$new(dataset = microeco_16S_norm_clean,
                                   taxrank = "Genus", 
                                   delete_taxonomy_lineage = TRUE,
                                   delete_taxonomy_prefix = TRUE,
                                   high_level = "Phylum",
                                   ntaxa = 50)

genus_heatmap <- taxa_phylum_16S$plot_heatmap(
                                              facet = c("Field_area","Treatment"),
                                              withmargin = TRUE,
                                              xtext_angle = 90)

**Comment by jamorillo** [comment]
But how can I apply this, should I reinstall microeco?

**Comment by ChiLiubio** [comment]
Hi @jamorillo 
Here is an example with the example data in the package.
```
library(microeco)
data("dataset")
dataset$cal_abund(select_cols = c("Phylum", "Genus"))
taxa_phylum_16S <- trans_abund$new(dataset = dataset,
                                   taxrank = "Genus",
                                   delete_taxonomy_lineage = FALSE,
                                   delete_taxonomy_prefix = TRUE,
                                   ntaxa = 50)
taxa_phylum_16S$plot_heatmap()
```
The core step is you should use `cal_abund`  function to recalculate taxa_abund list with only Phylum and Genus. Thus, the taxonomic lineage in front of Genus only has Phylum.

**Comment by jamorillo** [comment]
OK!, I was distracted by the option "high_level". Great, thanks a lot :)
