### ISSUE TITLE
Error in plot_diff_cladogram

### ISSUE THREAD

**Issue by PpGrApee** [ChiLiubio/microeco#434]
Hello！
I have some problem about using plot_diff_cladogram. Here is my code:
t1 <- trans_diff$new(dataset = micro_object, method = "lefse", group = "Group", alpha = 0.01, lefse_subgroup = NULL, filter_thres = 0.001)
t1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 50, clade_label_level = 6, group_order = c("DJ3", "DJ4", "DJA", "XD3"))
When i ran this code, there were some warnings: "The following aesthetics were dropped during statistical transformation: node and parent. ℹ This can happen when ggplot fails to infer the correct grouping structure in the data. ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor? "
I have saw the issue#254, but it did not help me solve this problem.

**Comment by ChiLiubio** [comment]
Hi. Could you please attach your `micro_object` object so that I can reproduce your issue? To save it, please follow the steps in the tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and attach the compressed object.

**Comment by PpGrApee** [comment]
[data.zip](https://github.com/user-attachments/files/17800145/data.zip)
This is my data. Thank you for your help :)

**Comment by ChiLiubio** [comment]
Hi. I found that this is a warning and does not currently affect the function to produce results. I will carefully check this issue and attempt to fix it. Thanks.
```
library(microeco)
library(magrittr)
load("micro_object_raw.RData")
t1 <- trans_diff$new(dataset = micro_object_raw, method = "lefse", group = "Group", alpha = 0.01, lefse_subgroup = NULL, filter_thres = 0.001)
t1$plot_diff_cladogram(use_taxa_num = 200, use_feature_num = 50, clade_label_level = 6, group_order = c("DaJiang3", "DaJiang4", "djcne244", "XiaDu3"))
```

Best,
Chi

**Comment by PpGrApee** [comment]
ok, Thank you for your help!!!
