### ISSUE TITLE
Plotting the relative abundance of specific taxon (at phylum or genus level) with respect to total taxa.

### ISSUE THREAD

**Issue by anilchauhanhp9** [ChiLiubio/microeco#437]
Hi Chi Liu,

Thank you for developing this awesome pipeline.

I have one question. Is it possible to plot the relative abundance of a specific taxon at any level (e.g., I want to plot the relative abundance of all the organisms present in phylum proteobacteria, but the relative abundance should be for all the reads or all the phyla, not just between proteobacteria, i.e., it should show the actual relative abundance of proteobacterial reads or organisms with respect to all the phyla present in the dataset)?

Thank you in advance.

**Comment by ChiLiubio** [comment]
Hi. Here is an example with microeco v1.10.0.
```
library(microeco)
data(dataset)
# we should normalize otu_table with TSS (total sum scaling), then we can get the relative abundance of each OTU
tmp <- trans_norm$new(dataset)
proteo <- tmp$norm("TSS")
# now we get a TSS-normalized dataset, naming proteo, then we filter features not classified into proteobacteria
proteo$tax_table <- proteo$tax_table[proteo$tax_table$Phylum == "p__Proteobacteria", ]
proteo$tidy_dataset()
# then we should calculate abundance without total abundance normalization, as the abundance has been normalized with total sum scaling
proteo$cal_abund(rel = FALSE)
# plot
t1 <- trans_abund$new(dataset = proteo, taxrank = "Genus", ntaxa = 10)
t1$plot_bar()
```

Best,
Chi

**Comment by anilchauhanhp9** [comment]
Thank you for the quick response
