### ISSUE TITLE
tidy_taxonomy execution is taking forever

### ISSUE THREAD

**Issue by nirK24** [ChiLiubio/microeco#438]
the example in the tutorial does not work 

taxonomy_table %<>%tidy_taxonomy

and the command tidy_taxonomy (taxonomy_table_16S) is never ending 
thanks

**Comment by ChiLiubio** [comment]
Hi. Thanks. I tested it in the current microeco v1.10.0. It is normal in my test. The issue is only found in the tidy_taxonomy function? Could you please first reopen an R session and try again?

**Comment by ChiLiubio** [comment]
Hi. Thanks. I tested it in the current microeco v1.10.0. It is normal in my test. The issue is only found in the tidy_taxonomy function? Could you please first reopen an R session and try again?

**Comment by nirK24** [comment]
Thanks:
I tried more than once changing also the R version with older ones
This: taxonomy_table %<>%tidy_taxonomy
Gives: error unexpected input

And the tidy_taxonomy(taxonomy_table_16S)
after running all night long resulted in error due to  impossible allocate a vector of 60.4 Gb. 
My taxonomy table is just 203 obs. For eight variables.

Thanks

**Comment by nirK24** [comment]
Update: the microeco example works, so the problem is in my files

**Comment by ChiLiubio** [comment]
Hi. Could you please attach your file that I can use to reproduce your issue and test how it happened? Except attachment in github,  It will be also appreciated to send it to me via email ***@***.***).




















At 2024-11-27 19:11:15, "nirK24" ***@***.***> wrote:

Update: the microeco example works, so the problem is in my files

**Comment by ChiLiubio** [comment]
Hi. Could you please attach your file that I can use to reproduce your issue and test how it happened? If you donot want to attach it in github,  It will be also appreciated to send it to me via email (liuchi0426@126.com).

**Comment by nirK24** [comment]
Thank you, really. Now it works

Il Gio 28 Nov 2024, 13:43 Chi Liu ***@***.***> ha scritto:
