### ISSUE TITLE
plot_diff_bar and plot_diff_abund commands are showing boxplots instead of bar plots

### ISSUE THREAD

**Issue by guilhermeluciomartins** [ChiLiubio/microeco#439]
Hi Chi,

This week, I have been analyzing some data using the ALDEx2 and RF functions, and I noticed that the commands plot_diff_bar and plot_diff_abund display the results as boxplots instead of bar charts.

While there’s nothing wrong with this, I would prefer to use bar plots to show relative abundance, but I haven’t been able to make this change.

Do you have any idea why this might be happening or how I could modify it to display bar plots instead?

I really appreciate any suggestions.

Best regards,
Guilherme

**Comment by ChiLiubio** [comment]
Hi Guilherme
Yes. I have redesigned the `plot_diff_abund` function to enable the generation of a greater variety of graphics. If you wish to use the previous style of bar with error bars, please refer to the examples provided in the tutorial (https://chiliubio.github.io/microeco_tutorial/model-based-class.html#trans_diff-class), such as using the parameters `plot_type = "barerrorbar", add_sig = FALSE, errorbar_addpoint = FALSE, errorbar_color_black = TRUE`.

Best,
Chi

**Comment by guilhermeluciomartins** [comment]
Hi Chi,

Thanks for the explanation and thanks for always improving the package.

Best,
Guilherme

**Comment by jamorillo** [comment]
Hello, is possible to use SD instead, in these graphics? 
In the option "barerrorbar" , what type of error is used?
thanks!"

**Comment by ChiLiubio** [comment]
Yes. The default is standard error. Please use parameter `plot_SE = FALSE` in plot_diff_abund function for SD. The function plot_diff_abund use parameter passing as the help document shows. So the parameters in plot_alpha function of trans_alpha class can also be used in this function.
![图片](https://github.com/user-attachments/assets/7b71d99d-9d2a-4065-9ae1-e830c7b1bca6)

**Comment by jamorillo** [comment]
OK, I see. Thanks for the help!
