### ISSUE TITLE
Problem with the trans_comm function

### ISSUE THREAD

**Issue by felipezagatto** [ChiLiubio/microeco#440]
Dear microeco team,

Thanks for the amazing package! 

I'm trying to run some network analyses, and, generally, everything is going ok, However, I'm facing problems when using the trans_comm function. 

I want to export the results of the networks and modules to a new microtable, but when I try to use this function, I get the following error: No available sample! Please check the data!

The whole part of the testing code looks like this: 

**> test <- trans_network$new(dataset = meco_merged_field_sub, cor_method = NULL, taxa_level = "ASVs", filter_thres = 0.001)**
After filtering, 228 features are remained ...

**> test$cal_network(network_method = "SpiecEasi", SpiecEasi_method = "mb", nlambda=30, lambda.min.ratio=1e-2, pulsar.params = list(thresh = 0.05, rep.num = 5), sel.criterion='bstars')**
 ---------------- 2024-12-05 13:21:01.880781 : Start ----------------
Applying data transformations...
Selecting model with pulsar using bstars...
Fitting final estimate with mb...
done
---------------- 2024-12-05 13:21:14.730873 : Finish ----------------
The result network is stored in object$res_network ...

**> test$cal_module(method = "cluster_spinglass")**
Use cluster_spinglass function to partition modules ...
Totally, 23 modules are idenfified ...
Modules are assigned in network with attribute name -- module ...

**> tmp_test <- net_merged_field$trans_comm(use_col = "module", abundance = TRUE)**
228 taxa with 0 abundance are removed from the otu_table ...
23 samples with 0 abundance are removed from the otu_table ...
Error in private$check_abund_table(otu_table) : 
#No available sample! Please check the data!

I’ve verified that test$res_node_table and test$data_abund still contain abundance data after module calculation, so I don't know why all the samples and taxa are being removed. I’ve also tried running the code with a different dataset, but I get the same error.
Is there anything I can do to solve this issue? 

Thanks in advance! 
Best regards, 
Felipe

**Comment by ChiLiubio** [comment]
Hi Felipe,
Thanks. I noticed that the object name was initially "test" but later it changed to "net_merged_field". 
Please confirm which one it is, and I can try to reproduce the issue to see what the problem might be.
Could you please save both "test" (if it is) and "meco_merged_field_sub" objects separately, and then attach them?
Please refer to this step to save the data (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function).

Best,
Chi

**Comment by felipezagatto** [comment]
Dear Chi, 

Thanks for your response. 

Indeed, for this test I forgot to change the "net_merged_field" to "test". So, "test" is the correct version, in this case. But this change doesn't change the error I'm getting. Attached you'll find both files ("test" and "meco_merged_field_sub"). 

Thanks again!
Felipe

[trans_comm_issue.zip](https://github.com/user-attachments/files/18038722/trans_comm_issue.zip)

**Comment by ChiLiubio** [comment]
Hi Felipe,
This issue can be solved by removing the `taxa_level` parameter in trans_network$new step as the following steps show.
```
library(microeco)
load("meco_merged_field_sub.RData")

test <- trans_network$new(dataset = meco_merged_field_sub, cor_method = NULL, filter_thres = 0.001)
test$cal_network(network_method = "SpiecEasi", SpiecEasi_method = "mb")
test$cal_module(method = "cluster_spinglass")
tmp_test <- test$trans_comm(use_col = "module", abundance = TRUE)
```
The default value of taxa_level argument is "OTU", which means using the orginal abundance in otu_table. This parameter is set for higher level. In your step, it is not correctly recognized, leading to a wrong names in the network. I will fix it with more robust input check. Thanks!

Best,
Chi

**Comment by ChiLiubio** [comment]
I have updated the package in github. So you can also reinstall the package from github and try again.

**Comment by ChiLiubio** [comment]
I have updated the package in github. So you can also reinstall the package from github and try again.

**Comment by ChiLiubio** [comment]
I have updated the package in github. So you can also reinstall the package from github and try again.

**Comment by felipezagatto** [comment]
Hi Chi, 

Now it works! Thank you so much again!

Best,
Felipe
