### ISSUE TITLE
sample size in rarefaction?

### ISSUE THREAD

**Issue by marwa38** [ChiLiubio/microeco#443]
Hi 

I was using microeco with the following codes and it was working fine where the minimum sample size across all samples was default if I remember correctly. 

Now I am asked to provide sample size as I get the following error.
```
Error in d1$rarefy_samples(method = "SRS", rngseed = 123) : 
  argument "sample.size" is missing, with no default
```
Any code how to do that in microeco?
My previous code that I used and it was working fine:
```

d1 <- clone(dataset.silva)

d1$rarefy_samples(method = "SRS", rngseed = 123)
# View(d2$otu_table)
# d1$sample_sums()
# Use the minimum number across samples: 624
# 2023 features are removed because they are no longer present in any sample after random subsampling ...
# 2023 taxa are removed from the otu_table, as the abundance is 0 ...
ps.silva <- meco2phyloseq(d1)
```

Thanks 
Marwa

**Comment by ChiLiubio** [comment]
Hi Marwa,
In the previous version, when I updated this function, I considered not setting the sample.size parameter to NULL, but instead leaving it to the user to set. If you want to use the same as before, you can temporarily add a minimum value to sample.size as shown below:
```
d1$rarefy_samples(method = "SRS", rngseed = 123, sample.size = min(d1$sample_sums()))
```
After your reminder, I think it's better to provide a default NULL to avoid errors. This will be done in the next CRAN version. Thank you.

Best,
Chi

**Comment by marwa38** [comment]
Thanks so much dear Chi for your help, hope all is well.
