### ISSUE TITLE
metastat results plotting issue

### ISSUE THREAD

**Issue by Debora6991** [ChiLiubio/microeco#47]
Hi there,
thank you for this useful package.
I am running the metastat analysis on some of my data (I need to compare 3 different sample types) and I have issues on plotting the results. 
When plotting the results I obtain the same plot for all the comparisons. The legend changes correctly according to each chosen group, but the  genus and abundance values are always the same. 
I don't know if I am doing something wrong or if there is an actual bug. I have read through the microeco pdf and microeco tutorial but I wasn't able to find an answer
I have also checked the res_metastat matrix and the plotted results match for just the first paired groups, but not for the following ones.
[metastat.txt](https://github.com/ChiLiubio/microeco/files/6867954/metastat.txt)
![run 2](https://user-images.githubusercontent.com/50614431/126766255-90c5dcee-fc62-4ab0-87c0-8e5157282c3a.jpeg)
![run 3](https://user-images.githubusercontent.com/50614431/126766261-c241b3f4-a145-4a7d-84ee-826149f72e9c.jpeg)
![run1](https://user-images.githubusercontent.com/50614431/126766263-966fa3bd-cde1-45bd-b459-2be9b5b87212.jpeg)
 The plotted results and the metastat analyses result matrix are here attached.

Thanks in andvance for your help.

Debora

**Comment by ChiLiubio** [comment]
Hi @Debora6991 

Sorry for the delay. I am in a field trip these days. This is a bug. I have updated the package in github. Please try to reinstall the package via github. Then rerun the whole trans_diff part. Thanks for your finding.

Best
Chi
