### ISSUE TITLE
Error with cal_tax4fun

### ISSUE THREAD

**Issue by liaochenlanruo** [ChiLiubio/microeco#48]
t1$cal_tax4fun(folderReferenceData = "./SILVA123")
Loading required package: Tax4Fun
Error: package or namespace load failed for ‘Tax4Fun’:
 package ‘Tax4Fun’ was installed before R 4.0.0: please re-install it
Error in t1$cal_tax4fun(folderReferenceData = "./SILVA123") : 
  Tax4Fun package not installed! see http://tax4fun.gobics.de/ 

As you can see, whenever I run the command, the error happens. Tax4Fun2 had been already installed. How can I fix this error? Thanks!

**Comment by ChiLiubio** [comment]
Hi,
Please first try to load Tax4Fun to see whether it can be loaded sucessfuly:
library(Tax4Fun)

Chi

**Comment by liaochenlanruo** [comment]
Hi,
It works well now, thanks a lot!
