### ISSUE TITLE
Error with cal_abund() and tidy_dataset

### ISSUE THREAD

**Issue by dsgregoire** [ChiLiubio/microeco#5]
Hello,

I read the paper on microeco and was excited to see all of these functions lumped into one package. I have been using QIIME2R and ampvis2 to try and create many of the figures, but this seemed like the ideal option for my analyses.

I have unfortunately been running into issues with the cal_abund() function when applied to a dataset I have been able to analyze successfully in ampvis2. The error I am getting in R says: "Error in `[.data.frame`(abund2, order(apply(abund2, 1, mean), decreasing = TRUE), : undefined columns selected". I have double checked that my data is in the proper format and that my taxonomy file is tidied up properly using the commands outlined in the microeco tutorial. I don't run into this issue when using the example datasets provided, so I am confused as to what the issue is with my data formatting. Furthermore, I am able to overcome this issue when defining sample_data = NULL when creating the microeco environment, but this means I lose all of my sample metadata.

As an additional note, I have found that when executing the tidy_dataset() command on an OTU table and taxonomy table that already have the same number of rows, microeco erases all rows of my data. Due to this issue, I have been skipping this step. Again, I don't run into this issue in the practice data but I have made sure my data is formatted the exact same way.

Any help you can provide on this would be much appreciated because I am very keen to use this package to the fullest!

**Comment by ChiLiubio** [comment]
Hi,
I can not repreat your error without your microtable object data, especially the issue that microeco erases all rows of your data when using tidy_dataset(). I doubt that the issue comes from the sample names of sample table and abundance table.
