### ISSUE TITLE
stat_compare_means - hide "ns" bars

### ISSUE THREAD

**Issue by nweerasu** [ChiLiubio/microeco#52]
Hello!

I was looking through the trans_beta and stat_compare_means documentation to see if there was a way to filter the comparisons since I have a number of "ns" bars that show up in between the significant comparisons. 
See below for the current output, what I'd like is to remove the ns comparisons AO_Ash & AO-Orch, AO-Ash & ONA.
[grpdist_Presence_LSUA.pdf](https://github.com/ChiLiubio/microeco/files/7139377/grpdist_Presence_LSUA.pdf)

The pair_compare_filter seems to be for the removal of one item from the comparison set, but doesn't help when removing specific pairs of comparisons (grepl only pulls the first item in the pattern and gives a warning if you provide anything else) e.g.:

```
# making a manual comparisons list
groups <- c("ANO", "ONA","AO-Ash","AO-Orch") # sample groups
all_groups <- combn(unique(as.character(groups)), 2) # create full comparisons list
filter <- all_groups[,c(1,4)] # specific comparisons to keep
groups; filter

# pulling from a small chunk of your code:
comparisons_list <- unique(as.character(all_groups)) %>% # I replaced your group_distance[, group] with my all_groups for ease
  combn(., 2) %>% as.data.frame(.) %>% 
grepl(filter, .) # I get the below warning for each extra item in the filter
```

"Warning message:
In grepl(filter, .) :
  argument 'pattern' has length > 1 and only the first element will be used"

Which makes me wonder how you want us to format the list/df to feed into your pair_compare_filter option. There weren't any examples in the documentation or tutorial to follow.

Alternatively, if it is easy enough to implement, is there a way to add in a "remove_ns" T/F option in the plot_group_distance to be able to just remove anything non-significant from the plot? This was originally what I was trying to achieve with the filter option, but didn't get there. The above is a small groups comparison, but one of my variables has 6 levels, so the number of comparisons is 15 and gets to be tough to see with the non-significant bars.

Thanks again for making such a great package!

Nimalka

**Comment by nweerasu** [comment]
If it helps, I found this as a rough workaround in ggpubr using the rstatix package.
https://github.com/kassambara/ggpubr/issues/171

**Comment by ChiLiubio** [comment]
Hi, @nweerasu 

Thanks for your suggestion! I have updated the package in github. Now I add a new parameter 'pair_compare_filter_select' to be used for selecting the required group pairs and use the parameter 'pair_compare_filter_match' to replace the previous 'pair_compare_filter'. Please reinstall and try again. Please see the help document for the detailed description of the parameter. The following is my example steps:

library(microeco)
data(dataset)
t1 <- trans_beta$new(dataset = dataset, group = "Group", measure = "bray")
t1$cal_group_distance()
t1$plot_group_distance(distance_pair_stat = TRUE, pair_compare_filter_select = c(2, 3))
# Now, the messages can show the ordered groups and selected groups.

Please feel free to tell me if something is not clear or if you have other ideas/suggestions.

Chi

**Comment by nweerasu** [comment]
Very helpful -- thank you!

**Comment by ChiLiubio** [comment]
Hi, @jarrodscott 

Interesting!  I think the easiest way is to add a pre-filter to select the pairs in comparisons_list with marks via the function compare_means. Let me have a try.

**Comment by ChiLiubio** [comment]
Hi, @jarrodscott 

I add hide_ns parameter to automaticlly filter ns and hide_ns_more parameter for more filtering. Please reinstall the package from github and try again. This is my example:

library(microeco)
library(magrittr)
library(ggplot2)
data(dataset)
t1 <- trans_beta$new(dataset = dataset, group = "Group", measure = "bray")
t1$cal_group_distance()
t1$plot_group_distance(distance_pair_stat = TRUE)
t1$plot_group_distance(distance_pair_stat = TRUE, hide_ns = TRUE)
t1$plot_group_distance(distance_pair_stat = TRUE, hide_ns = TRUE, hide_ns_more = c("ns", "*"))
t1$plot_group_distance(distance_pair_stat = TRUE, pair_compare_filter_select = 3)

Please fell free to tell me if you have better solutions!

Chi

**Comment by jarrodscott** [comment]
Hi @ChiLiubio 

This is beautiful! Exactly what I was looking for :) I was able to get the code above to run perfectly, however when I set `group` to something else, like `Type` I get an error. 

This runs fine:

```
data(dataset)
dataset$sample_table
t1 <- trans_beta$new(dataset = dataset, group = "Type", measure = "bray")
t1$cal_group_distance()
t1$plot_group_distance(distance_pair_stat = TRUE)
```

However, both of these throw the error `Error: Can't extract columns that don't exist. x Column `Group` doesn't exist.`

```
t1$plot_group_distance(distance_pair_stat = TRUE, hide_ns = TRUE)
t1$plot_group_distance(distance_pair_stat = TRUE, hide_ns = TRUE, hide_ns_more = c("ns", "*"))
```

I tried changing the `Type` column in the sample table to `Group` like so...

```
dataset2 <- clone(dataset)
dataset2$sample_table$Group <- NULL
dataset2$sample_table
names(dataset2$sample_table)[names(dataset2$sample_table) == 'Type'] <- 'Group'
```

And then running

```
t1 <- trans_beta$new(dataset = dataset2, group = "Group", measure = "bray")
t1$cal_group_distance()
t1$plot_group_distance(distance_pair_stat = TRUE)
```

Which works fine, but 

```
t1$plot_group_distance(distance_pair_stat = TRUE, hide_ns = TRUE)
```

Gives an error: `Error in wilcox.test.default(xi, xj, paired = paired, ...) : 'x' and 'y' must have the same length`

I do want to thank you for gettin a solution in place so fast! I am happy to help any way I can
--Jarrod

**Comment by ChiLiubio** [comment]
Hi, @jarrodscott 

It is a bug! Thanks a lot. I have fixed it. Please reinstall the package and try again. I am so happy to see your enlightening issues!

Chi

**Comment by jarrodscott** [comment]
Hi @ChiLiubio 

Success!!! Thank you Chi!! Here are the before and after. Wonderful. 


![before](https://user-images.githubusercontent.com/16192182/144231951-aede1525-bffc-4af1-a0d0-3b6c8ac836aa.png)

![after](https://user-images.githubusercontent.com/16192182/144231957-cb7ad111-c76f-4cfb-9a8a-2d09337308cf.png)
