### ISSUE TITLE
Missing modules in cal_node_type()

### ISSUE THREAD

**Issue by nweerasu** [ChiLiubio/microeco#54]
Hello Chi,

I have made a network with 9 modules (louvain method), however, when I went to map module function with FUNGuild (cal_spe_func_perc), I only see 7 of the 9 modules.

I traced back as far as I could to cal_node_type:
```{r}
network <- t1$res_network
node_type <- t1[[".__enclos_env__"]][["private"]]$module_roles(network)
```

and the resulting node_type object is missing M8 and M9. 

Let me know if I need to supply any other information.

Thanks again so much for a great package and your help!
Nimalka

**Comment by ChiLiubio** [comment]
Hi, @nweerasu 

Could you please send me your data to have a check? I am not clear where it comes from.

Chi

**Comment by nweerasu** [comment]
Hello Chi,

I went back through and loaded the data from the beginning and everything seemed to work out…
Unsure why I was getting that strange error, but it’s gone. I can close the issue.

Thank you!
Nimalka
