### ISSUE TITLE
what does t2$cal_spe_func_perc? 

### ISSUE THREAD

**Issue by rotifer16** [ChiLiubio/microeco#55]
[](url
[toy.xlsx](https://github.com/ChiLiubio/microeco/files/7212197/toy.xlsx)
)

Dear Chi,
many thanks for developing microeco that helps me a lot. I would like to know how the calculations in t2$cal_func_perc are done with use_community=TRUE and use_community=FALSE
Please find attached my toy example; I understood that we multiply OTU abundance with the presence/absence of the trait but I do not know how to get then the percentage; what is the divisor? Please, would you be so kind and show me the calculation in the excel file? 
all the best from Italy,
Ulrike

**Comment by ChiLiubio** [comment]
Hi Ulrike,

Thanks for your appreciation. Let's talk about two conditions. 
If you use the default abundance_weighted = FALSE, cal_spe_func_perc function have no matter with the abundance. Thus, the result for func_1 in sample_1 is (1+1)/4 , i.e. 0.5, representing half of OTUs have func_1 trait. The divisor '4' means that total 4 OTUs are found in sample_1. Two '1' are OTU-1 and OTU-4.
If  abundance_weighted = TRUE, the result for func_1 in sample_1 should be (4625 + 43)/(4625 + 409 + 542 + 43), the divisor should be all individuals, here sequences in sample_1.  This means the percentage of individuals with func_1 in sample_1.
use_community=TRUE is used for calculating the percentages for communities, i.e. samples
use_community=FALSE can be used for any other your defined groups, such as the network modules in the tutorial. If the input is not network node table, just make it having same format (only module column is used) with the node table similar with that in the tutorial. This is one of the principles for flexibility in the package.
Please feel free to tell me if it is still not clear.

Best
Chi

**Comment by rotifer16** [comment]
Dear Chi,
many thanks for your explanation; just another question: in the toy example
no OTU/ASV had more than one trait and thus percentages add up to 100%. But
what happens when one OTU has more than one trait but 2 as in the example
below, then percentages do not add up to 100% again but are > 100%

[image: Screenshot 2021-09-28 at 21.06.25.png]

is this intended? or how do you proceed in such cases?
all the best from Italy,
Ulrike

Am Do., 23. Sept. 2021 um 11:22 Uhr schrieb Chi Liu <
***@***.***>:

**Comment by ChiLiubio** [comment]
Hi, Maybe an error from the image. I can not click and see the image. I guess  '> 100%' may be from multiple trait. The percentage is designed for each trait, though one species have two trait. So the denominator is larger than the sum of numerator all the time.

Chi

**Comment by rotifer16** [comment]
[](url
[toy.xlsx](https://github.com/ChiLiubio/microeco/files/7249500/toy.xlsx)
)

Dear Chi,
I again uploaded the toy example with one OTU having 2 traits (in fact, in FaProTax it can happen multiple times that an OTU has > 1 trait). How are the calculations done to get 100%?
I tried to add 2 times the abundance of OTU 2 in the denominator, but this does not solve the issue. Could you explain this in more detail,
many thanks for your kind help,
Ulrike

**Comment by ChiLiubio** [comment]
Hi. The multiple matching of OTU2 has no matter with the calculations done to get total 100%, because the calculations are performed for each trait seperately. So the 100% only refer to the case that all the OTUs have one trait in a sample. For example, for sample2 (your bottom example in excel), there are only OTU2 and OTU4 in the community. Both OTU2 and OTU4  have func_1. So the functional redundancy of func1 should be 100% for both unweighted ((1+1)/2) and weighted ((1000+50)/1500) method. I am not sure about the meaning of 'SUM' in the excel.

Chi

**Comment by rotifer16** [comment]
Hi Chi,
one last question or confirmation:
            func1.  func2                 sample1       sample2       
OTU1   1            0                          4625          0
OTU2  1             1                           409         1000
OTU3  0            0                            542         0
OTU4  1            0                            43          4619

gives for abundance = FALSE
                   func_1         func_2
sample1       3/4                1/4
sample2       3/2                1/2

gives for abundance = TRUE
                   func_1                                                                              func_2
sample1       (4625+409+43)/(4625+409+43+542)  = 0.90         409/(4625+409+43+542) = 0.73
sample2       (1000+4619)/(1000+4619) = 1                                    1000/ (1000+4619) = 0.18   

hopefully I got it right,
many thanks for your kind help,
Ulrike

**Comment by ChiLiubio** [comment]
Hi, Ulrike. You got it! Actually, this may be a very easy way to represent the so-called FR. This method does not refer to the species diversity and evenness or others in plant ecology, as the trait of microbes are often very sparse. So I think an easy way may be more robust. Please feel free to tell me if you have other idea or method in this area.

Chi

**Comment by ChiLiubio** [comment]
Hi, Ulrike. You got it! Actually, this may be a very easy way to represent the so-called FR. This method does not refer to the species diversity and evenness or others in plant ecology, as the trait of microbes are often very sparse. So I think an easy way may be more robust. Please feel free to tell me if you have other idea or method in this area.

Chi
