### ISSUE TITLE
request to allow for modifiable jitter widths for trans_network

### ISSUE THREAD

**Issue by nweerasu** [ChiLiubio/microeco#56]
Hello Chi,

Just suggesting an option to use geom_jitter for the trans_network plot_taxa_roles plot with an option to modify the widths parameter to allow for lower values for sparse data. I have single or double points that stray too far from the central axis.

Thanks very much!
Nimalka

**Comment by ChiLiubio** [comment]
Hi Nimalka,

Would you want to have a try to optimize this :)

Best
Chi
