### ISSUE TITLE
Venn diagrams at different taxonomic levels?

### ISSUE THREAD

**Issue by NataliHB** [ChiLiubio/microeco#57]
Hi Chi,

Many thanks for developing this amazing package! it is very useful, I was wondering if there is away to make Venn diagrams at different taxonomic levels?

my idea was to do something like:

dataset.m2<-trans_abund$new(dataset = meco_dataset2, taxrank = "Genus")

dataset.m3<-dataset.m2$merge_samples(use_group = "Location")

but I get this error:

Error: attempt to apply non-function

Any help would be very appreciated,

Best, 
Natali

**Comment by ChiLiubio** [comment]
Hi Natali,

Good idea! Here are my test solution:

data(dataset)
# use merge_taxa to generate new microtable object
test1 <- dataset$merge_taxa(taxa = "Genus")
# merge groups
test2 <- test1$merge_samples(use_group = "Group")
# Then other things

Is it what you need?

Best,
Chi

**Comment by NataliHB** [comment]
Hi Chi,

Oh wow thank you so much for the quick response. This works like a charm for the Venn diagrams.

Cheers,
Natali
