### ISSUE TITLE
cal_mantel_corr error

### ISSUE THREAD

**Issue by liaochenlanruo** [ChiLiubio/microeco#58]
```
t1 <- trans_nullmodel$new(meco_dataset, taxa_number = 1000, add_data = env_data)
t1$cal_mantel_corr(use_env = "TN")
```
when "taxa_number" was set to a big number, such as 5000, the following error happens:

---------------- 2021-11-02 21:42:54 : Start ----------------
Error in cor(as.vector(xdis), ydis, method = method, use = use) : 
  missing observations in cov/cor
In addition: There were 50 or more warnings (use warnings() to see the first 50)

However, while "taxa_number" was set to a small number, no error happens. I have a total of 20001 OTUs.

**Comment by ChiLiubio** [comment]
Hi, I am not sure how it happened now. According to my experience, when the input OTU number is large, the mantel correlogram (developed based on vegan) is very very slow. I suggest you first use filter_thres parameter to filter otus with very low abundance.
