### ISSUE TITLE
problem in SparCC netwok edge weight

### ISSUE THREAD

**Issue by LuoWen0507** [ChiLiubio/microeco#62]
Thanks for developing microeco. It is very useful! I would like to know the result of the SpiecEasi network about the edge weight. The edge weights in my results were 1. Howerver, the results of the base  correlation network were normal. I don't konw how to deal with it. So, please, would you be so kind and help me wiht the  problem?

t1 <- trans_network$new(dataset = dataset, cal_cor = "SparCC", taxa_level = "OTU", filter_thres = 0.001, SparCC_simu_num = 100,nThreads=20)
t1$cal_network(network_method ="SpiecEasi",COR_cut = 0.8)
E(t1$res_network)$weight

**Comment by ChiLiubio** [comment]
Hi, SpiecEasi network was directly calculated with SpiecEasi package (https://github.com/zdk123/SpiecEasi) in trans_network. So the parameters "cal_cor = "SparCC"" and "COR_cut = 0.8" have no relatedness with this method. The weight also directly comes from the network result. The weight of the other correlation-based network we use is the correlation coefficient. You can try to take some time on the SpiecEasi algorithms if you think the weight is very important in your flow and write your issue in SpiecEasi github page (https://github.com/zdk123/SpiecEasi).

**Comment by LuoWen0507** [comment]
OK! Thanks for your patience.
