### ISSUE TITLE
Issues with trans_diff RF when 1 biomarker is identified

### ISSUE THREAD

**Issue by pxtm** [ChiLiubio/microeco#63]
Hi!

I've been using microeco for a few days now and now I am stuck with this issue when running a random forest analysis. Apparently, when only 1 genus is found to be significant, there seems to be an error when constructing the output dataframe, specifically with the row.names (error message below). Since the only way to analyze the output of the RF analysis step is to store it in a new object and this is the step failing to run, I cannot proceed. Could you help me with that?

```
trans_diff$new(working2, method = 'rf', group = 'condicions', rf_taxa_level = 'Genus')
Start differential test for condicions ...
Total 1 biomarkers found ...
Error in `.rowNamesDF<-`(x, value = value) : missing values in 'row.names' are not allowed
```

thanks in advance!
Bests,
mrc

**Comment by ChiLiubio** [comment]
Hi, could you first try to use other taxa level to see whether is it ok? If still stuck, you can save your working2 data using save() function and send me the working2.RData to check it.

Chi

**Comment by pxtm** [comment]
Hey  @ChiLiubio, with higher tax levels I have the same issues when it comes down to only 1 biomarker identified. Where can I send the RDS file?

thanks in advance!

**Comment by ChiLiubio** [comment]
Hi, @pxtm , you can directly dragging your file here to attach file.

**Comment by pxtm** [comment]
there you go! thanks :)
[working2_microeco.zip](https://github.com/ChiLiubio/microeco/files/7561097/working2_microeco.zip)

**Comment by ChiLiubio** [comment]
Hi, @pxtm , this issue comes from only one significant genus found between two groups. Then the result can not be used in rf. Why not try to use rf_taxa_level = 'all'?  or use other method?
