### ISSUE TITLE
possible conflict with adespatial

### ISSUE THREAD

**Issue by m-urvoy** [ChiLiubio/microeco#65]
Hello,
I just wanted to let you know I encountered a conflict with adespatial when using cal_ses_betampd or cal_ses_betamntd.
When adespatial is not loaded, everything works fine. However, when it is loaded, it throws the following error (on the data attached with the microeco package):
![image](https://user-images.githubusercontent.com/95699395/145049976-f9d82930-a001-47c7-87a0-535b0253c07b.png)

Thank you,
Kind regards
Marion

**Comment by ChiLiubio** [comment]
Hi, Marion @m-urvoy 

Yes. I totally repeated this conflict. I checked this part step by step and surprisingly found the conflict only comes from sapply function when adespatial package was attached. I will update the code of this part.
Thanks.

Best
Chi

**Comment by ChiLiubio** [comment]
Hi, Marion

I have fixed this conflict and updated the package in github.
Thanks!

Best
Chi

**Comment by m-urvoy** [comment]
Thank you very much Chi!
Kind regards,
Marion
