### ISSUE TITLE
Heatmap with annotations?

### ISSUE THREAD

**Issue by NataliHB** [ChiLiubio/microeco#68]
Hi Chi,
Thank you so much for this helpful package! I was wondering if you had any ideas to annotate further a heatmap created with plot_heatmap. I am trying to include some environmental variables, is there something similar to "annotation_row"?

Any help is hugely appreciated!

Best,
Natali

**Comment by ChiLiubio** [comment]
Hi Natali, @NataliHB 

The heatmap from plot_heatmap is generated based on ggplot2. I guess you want to use pheatmap style to annotate something. So now I think the easiest way is to directly use pheatmap or ComplexHeatmap package to make it. You can extract required data frame from trans_abund$abund_data or from microtable$taxa_abund. How do you think about it? Any suggestion is appreciated.

Best
Chi
