### ISSUE TITLE
Error: id variables not found in data: Taxonomy

### ISSUE THREAD

**Issue by HCB-M2RG** [ChiLiubio/microeco#7]
Hello,
I have been test driving this package and feel positive about it. Thanks for producing it. 

I went through the material in the read_me and pulled the tutorial qiime2 data into many of the examples given in your detailed tutorial. No issues there.

I then pulled my own qiime2 .qza data outputs in and have started the journey. I run into an error using the trans_abund function given in your tutorial: 

t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 10)

Error: id variables not found in data: Taxonomy
6. stop("id variables not found in data: ", vars, call. = FALSE)
5. melt_check(data, id.vars, measure.vars, variable.name, value.name)
4. melt.data.frame(abund_data, id.vars = "Taxonomy")
3. reshape2::melt(abund_data, id.vars = "Taxonomy")
2. initialize(...)
1 . trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 10)

Any ideas to help me stay on this new microeco package journey?

**Comment by ChiLiubio** [comment]
Hi,
@HCB-M2RG Thanks. I cann't make sure the error point from the information you provided. Could you please provide the microtable object data (your dataset I see) using save function or other data that I can run and repeat your error?

**Comment by HCB-M2RG** [comment]
Thanks,
The meco_data set directory I created is attached.
-h

Hans C. Bernstein
Associate Professor
Microalgae & Microbiomes Research Group Leader
Arctic Centre for Sustainable Energy (ARC)
UiT - The Arctic University of Norway
Norwegian College of Fisheries Sciences
Faculty of Biosciences, Fisheries and Economics
Email: Hans.C.Bernstein@uit.no<mailto:Hans.C.Bernstein@uit.no>
URL: https://uit.no/research/micro
Twitter: @microbe_angler<https://twitter.com/microbe_angler?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>

**Comment by Geize** [comment]
Hi there, 

I am facing the same issues. 

Could you share the answer?

Thanks in advance.

**Comment by ChiLiubio** [comment]
Hi,
@Geize @HCB-M2RG  Could you send me the dataset.RData to my email (liuchi0426@126.com)? I suggest you save the dataset using command:  save(dataset, file = "dataset.RData")  .  Then I can completely repeat and check this issue. @HCB-M2RG sorry that I cannot open the url.

**Comment by ChiLiubio** [comment]
Hi, 
@HCB-M2RG I have carefully checked the dataset you provided, and found several issues. I provided the reasons and solutions.

There are three questions in the structure of the dataset and needed to be solved.

Q1: The prefix of taxonomy table.
There are many prefix (e.g. p__ and c__) missing in dataset$tax_table. This is not good and can lead to wrong data structure in the following abundance calculation and other related operations.

Solution:
test <- dataset$tax_table
for(i in 1:ncol(test)){
	prefix <- paste0(tolower(substr(colnames(test)[i], 1, 1)), "__")
	test[, i] <- gsub(prefix, "", test[, i])
	test[,i] <- paste0(prefix, test[, i])
}
dataset$tax_table <- test

 Q2:  The character attribute in dataset$otu_table
The data attribute in dataset$otu_table must be numeric for any operation in the package.

Solution:
for(i in 1:ncol(dataset$otu_table)){
	dataset$otu_table[, i] %<>% as.numeric
}

Q3：Abundance calculation
The taxonomic abundance must be first calculated in dataset before you make plots using trans_abund class.
This has been described in the tutorial (see README). Similarly, if you want use trans_alpha class, you also need to first calculate alpha diversity using command dataset$cal_alphadiv().

Solution:
dataset$cal_abund()
 
Finally, those are all the codes that I run:

library(microeco)
library(magrittr)
library(ggplot2)

# the data you provided
load("dataset.RData")
# standardize the taxonomic table
test <- dataset$tax_table
for(i in 1:ncol(test)){
	prefix <- paste0(tolower(substr(colnames(test)[i], 1, 1)), "__")
	test[, i] <- gsub(prefix, "", test[, i])
	test[,i] <- paste0(prefix, test[, i])
}
dataset$tax_table <- test
# ASV table: convert character to numeric
for(i in 1:ncol(dataset$otu_table)){
	dataset$otu_table[, i] %<>% as.numeric
}
# calculate taxonomic abundance
dataset$cal_abund()
# then use trans_abund class
t1 <- trans_abund$new(dataset = dataset, taxrank = "Phylum", ntaxa = 10)
t1$plot_bar(others_color = "grey70")

**Comment by HCB-M2RG** [comment]
thanks @ChiLiubio, these steps solved my issues.

**Comment by vicky662** [comment]
hello 
[sample_points.csv](https://github.com/ChiLiubio/microeco/files/8562335/sample_points.csv)
,im having an issue with this error id variables not found in data: Point_ID

**Comment by ChiLiubio** [comment]
So what is the error? Could you paste the steps that I can repeat? Generally, it is not a good choice to use the number as the sample id.
