### ISSUE TITLE
Regarding  RDA analysis in trans_env class

### ISSUE THREAD

**Issue by ShailNair** [ChiLiubio/microeco#70]
Hi,
I wanted to know why the group distance among the different groups in the beta diversity plot and RDA plot is different (in https://chiliubio.github.io/microeco_tutorial/)?. Both the plot uses the Bray-Curtis method for diversity calculation. Although PCoA ordination is used in beta diversity calculations, there is no mention of ordination for RDA analysis.

**Comment by ChiLiubio** [comment]
Hi, @ShailNair 

PCoA and RDA belong to two different types of ordination. Please see this article(DOI: 10.1111/j.1574-6941.2007.00375.x) for the details.

**Comment by ShailNair** [comment]
Thanks
