### ISSUE TITLE
error in cal_alphdiv

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#71]
Hi, I am getting following error in calculating alpha diversity of my dataset, 

> dataset$cal_alphadiv(PD = FALSE)
Error in uniroot(d1fun, c(1, 50), extendInt = "upX", S = S, N = N, ...) : 
  did not succeed extending the interval endpoints for f(lower) * f(upper) <= 0

pls let mw know, how to overcome this issue.

**Comment by ChiLiubio** [comment]
Hi. Could you send me your dataset to repeat this issue? Please save your dataset using this way (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function). Thanks. 

Chi

**Comment by apoosakkannu** [comment]
Hi, thanks for your kind reply. Please find the dataset. Actually i have also problem with OTU_tree at one point of making dataset for analysis.
[MapRunJune2019_complete.csv](https://github.com/ChiLiubio/microeco/files/7813743/MapRunJune2019_complete.csv)
[otu_norarefaction_abund.csv](https://github.com/ChiLiubio/microeco/files/7813745/otu_norarefaction_abund.csv)
[otu_norarefaction_taxa.csv](https://github.com/ChiLiubio/microeco/files/7813746/otu_norarefaction_taxa.csv)

**Comment by apoosakkannu** [comment]
pls find the dataset. thanks.

**Comment by ChiLiubio** [comment]
Hi, Please  use the step in tutorial (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) to save your dataset and send me "dataset.RData". Otherwise, I can not exactly repeat your issue. I guess this issue comes from your phylogenetic tree.

**Comment by apoosakkannu** [comment]
I am not able to attach dataset.RData here. How to send it?

**Comment by patrickDsal** [comment]
I just updated my packages and now have a similar issue, after working with the package for months without a problem. It seems like there is a problem with the "ape" package for loading the phylogenetic tree into R. 
It seems to me that all of a sudden there is an interference whilst tidying the dataset.
After tidying the dataset one gets a warning message : In ape::drop.tip(., base::setdiff(.$tip.label, taxa_names)) :
drop all tips of the tree: returning NULL, 
To me this basically means that it drops every tip and accordingly every OTU and taxa in the OTU table and taxonomy table.
It's very strange!

**Comment by patrickDsal** [comment]
Ok I solved it for me.
Try to deinstall the"ape" package and install an older version of it instead, that might fix your problem as well.

you can install older packages like this (I went back to version 5.4)
require(devtools)
install_version("ape", version = "5.4", repos = "http://cran.us.r-project.org")

**Comment by apoosakkannu** [comment]
Thanks Patrick. Even 5.5 worked for me.

**Comment by ChiLiubio** [comment]
@patrickDsal @apoosakkannu Hi, could you please send me your phylogenetic tree to repeat this issue? I have updated ape 5.6 and find it is ok with my tree. If the issue is caused by the tree format, I will update the package.

**Comment by apoosakkannu** [comment]
[Uploading oturep_qiime2_tree.nwk.zip…]()

**Comment by apoosakkannu** [comment]
[oturep_qiime2_tree.nwk.zip](https://github.com/ChiLiubio/microeco/files/7819980/oturep_qiime2_tree.nwk.zip)
