### ISSUE TITLE
subset_network error

### ISSUE THREAD

**Issue by apoosakkannu** [ChiLiubio/microeco#73]
Hi, I am doing network analysis, i found that subset_network is not working. 

> t16$subset_network(node = t16$res_node_type %>% .[.$module == "M2", ] %>% rownames, rm_single = TRUE)
Error: attempt to apply non-function
> subset_network
Error: object 'subset_network' not found

Could you give me some idea what i am doing wrong?

**Comment by ChiLiubio** [comment]
Hi, which version of microeco do you use? This tells us no subset_network function in your object. So it may be an old version. Please update the package, recreate t16 and try again.
