### ISSUE TITLE
cal_manova issue

### ISSUE THREAD

**Issue by mtva0001** [ChiLiubio/microeco#74]
Hi,

I try to run PERMANOVA but it doesn't work. I could easily make an NMDS, even calculate calculate and plot group distances and betadisper, but the function of cal_manova results in this error message:

> t1$cal_manova(cal_manova_all = TRUE)
Error in `colnames<-`(`*tmp*`, value = colnames(lhs)) : 
  attempt to set 'colnames' on an object with less than two dimensions

How could I fix this?

Thanks for your help in advance! 
(I'm using the newest version of your package)

**Comment by ChiLiubio** [comment]
Hi. Could you send me your t1 object? Thus, I can try to repeat this error.  It can be saved like this example (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function) and dragged here.

**Comment by ChiLiubio** [comment]
Hi, @mtva0001 

It is ok in my runing with the commands: 
`library(microeco)
load("t1.RData")
t1$cal_manova(cal_manova_all = TRUE)
t1$res_manova
`
As I directly use t1 object, so the function performed in t1 is totally same with you use. So it should not be the issue of package version.

**Comment by mtva0001** [comment]
Thanks for checking this! Unfortunately, it doesn't work for me :/ 

> library(microeco)
> load("/Users/matevass/t1.RData")
> t1$cal_manova(cal_manova_all = TRUE)
Error in `colnames<-`(`*tmp*`, value = colnames(lhs)) : 
  attempt to set 'colnames' on an object with less than two dimensions
> t1$res_manova
NULL
> (.packages())
 [1] "ggplot2"     "viridis"     "viridisLite" "microeco"    "grid"        "stats"       "graphics"   
 [8] "grDevices"   "utils"       "datasets"    "methods"     "base"
