### ISSUE TITLE
Results from trans_env$cal_rda_envsquare

### ISSUE THREAD

**Issue by NataliHB** [ChiLiubio/microeco#75]
Hi Chi,

I hope you are well. I'm trying to obtain the contribution of each variable that I used for and RDA, I am just not sure if I am looking at the right place. In the trans_env class objet I see in the res_rda_envsquare the following:

![image](https://user-images.githubusercontent.com/50379650/151282067-52f7e3f4-7972-46bb-ae5b-387adf0878a3.png)

I am just bit confused, since a don't see the percentage of variance explained by each variable. I was hoping you could give me some advise on this.

Cheers,
Natali

**Comment by ChiLiubio** [comment]
Hi @NataliHB,

You can directly show the res_rda_envsquare in the console like your_object$res_rda_envsquare . Then you can see the R2 column. But it is notable that each variable is analysed separately. So it is not the percentage like the output we get in VPA.

Best
Chi

**Comment by NataliHB** [comment]
Hi Chi,

Many thanks for your response. It makes sense now! thank you so much for explaining!

Best,
Natali
