### ISSUE TITLE
Not an issue but a question about the trans_beta class transformation

### ISSUE THREAD

**Issue by Fuad59** [ChiLiubio/microeco#76]
Hi,
I imported a dataset from phyloseq to do alpha, beta and functional trait analysis. May I know if I need to log transform or standardize my dataset before assigning trans_beta or not? If yes, then which function in microeco can be used?
Thanks.

**Comment by ChiLiubio** [comment]
Hi,
It depends. Generally, for alpha and beta diversity and functional analysis, no need to perform standardization if you have a rarified dataset (see rarefy_samples function in https://chiliubio.github.io/microeco_tutorial/basic-class.html#microtable-class). Though many debates occur on the rarefying, it is simple to solve the inhomogeneity.

**Comment by Fuad59** [comment]
Thanks for your quick response. I already checked my sequence depth. The min=2 and max=1433. So, I am afraid to rarify. I used phyloseq to standardize my dataset and then imported to microeco. But got errors while calling cal_alphadiv and so on. Wish, your package would add standardize transformation choices (i.e., log10) for NMDS or other analysis.

**Comment by Fuad59** [comment]
Please, check how many data was removed after using rarefy.

> dataset3$sample_sums() %>% range
[1]    2 2219
> dataset3
microtable class:
sample_table have 27 rows and 4 columns
otu_table have 1294 rows and 27 columns
tax_table have 1294 rows and 7 columns
phylo_tree have 1294 tips
> dataset3$rarefy_samples()
Use the minimum number across samples: 2
1250 OTUs were removed because they are no longer present in any sample after random subsampling ...
1250 taxa are removed from the otu_table, as the abundance is 0 ...
> dataset3
microtable class:
sample_table have 27 rows and 4 columns
otu_table have 44 rows and 27 columns
tax_table have 44 rows and 7 columns
phylo_tree have 44 tips

**Comment by ChiLiubio** [comment]
The lowest number of sequences is 2. It is too low. You can assign an appropriate value with the parameter sample.size to increase the number.

**Comment by ChiLiubio** [comment]
Please see the help document with the command:  help(microtable)
