### ISSUE TITLE
trans_diff q-value issue

### ISSUE THREAD

**Issue by alberjo296** [ChiLiubio/microeco#78]
Hi ChiLilubio,
thank you for the package! I have an issue. I've used the function:

t1 <- trans_diff$new(dataset=dataset, method="metastat", group ="SampleType", metastat_taxa_level= "Phylum")
write.csv2(t1$res_metastat, "trans_diff_phylum.csv")

but most of the q-value are negatives (though all of them are between -1 and 1). How is this possible?

Tanks.

**Comment by alberjo296** [comment]
(+) the p-values are all positives (0-1)

**Comment by alberjo296** [comment]
(+) and I am comparing 8 conditions between them

**Comment by ChiLiubio** [comment]
Hi @alberjo296 
I checked the example dataset and did not found any negative q value. Could you make sure whether there is something illogical in your runing process? Sure, you can also save and send me your microtable object and your trans_diff object using this way (https://chiliubio.github.io/microeco_tutorial/notes.html#save-function).

Chi

**Comment by alberjo296** [comment]
Hi Chi,
I didn't find anything weird in my script.
I send you both. I used the function:
dataset$cal_abund()
dataset$save_abund(dirpath = "taxa_abund")
t7 <- trans_diff$new(dataset=dataset, method="metastat", group ="SampleType", metastat_taxa_level= "Phylum")
write.csv2(t7$res_metastat, "trans_diff_phylum.csv")

Thank you :)


[dataset.zip](https://github.com/ChiLiubio/microeco/files/8067526/dataset.zip)
[trans_diff.zip](https://github.com/ChiLiubio/microeco/files/8067595/trans_diff.zip)

**Comment by ChiLiubio** [comment]
Hi. I found the negative values occurred only in several paired groups: such as "D1, A.I. vs D1, P.I." "D4, A.I. vs D1, P.I." "D4, P.I. vs D3, A.I." "D1, P.I. vs D2, P.I." "D2, A.I. vs D2, P.I."  . There is one same point in those q values among the groups, i.e. many same value in those q values. So I guess this q value method may be not suitable for these cases. Please also see the details in metastat paper (doi:10.1371/journal.pcbi.1000352). I think it is also ok to use other p adjusting methods.

**Comment by alberjo296** [comment]
Thank you, Chi.
It's very weird because I don't find any limitation on the paper related to that. Which other method do you recommend me to have two-to-two comparisons between groups?

Thank you.

**Comment by alberjo296** [comment]
btw, I have just remembered I did not come back to that issue topic. After a time using the metastats method, I think that was a problem of me using this methodology on wrong conditions. In the paper, it says that for estimating significance assessment:  "Our approach is specifically targeted at datasets comprising multiple subjects" (with a cut-off of 8); so if you don't have at least 8 individuals per treatment this method can fail (that's probably why I obtained negative q-values), but if you have more I found it's a very interesting method. I recommend reading its paper before using it:  https://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1000352&type=printable
An alternative (in case you have less than 8 individuals) could be using the Mann-Whitney-Wilcoxon test and adjusting the p-values with FDR, in case you also want to incorporate that method into your library :) Mann-Whitney-Wilcoxon (+FDR) test is very common for microbiota data. It will work for calculating significant differences in relative abundances

Thank you again,

Alberto

**Comment by ChiLiubio** [comment]
Hi @alberjo296 
Thanks for your detailed explanation on your data and great suggestion on the method selection. I am also considering adding those commonly used methods as options. I reopen this topic and will tell you after the updating.

Chi

**Comment by ChiLiubio** [comment]
Hi. I have add method option "KW" for  Kruskal-Wallis Rank Sum Test (groups > 2) or Wilcoxon Rank Sum Tests (groups = 2) and "KW_dunn" option for Dunn's Kruskal-Wallis Multiple Comparisons in trans_diff$new. The p value adjustment is also included. It may be useful for you. Thanks for your suggestion.
Chi

**Comment by alberjo296** [comment]
No, thank you Chi for all the settings! Can't wait to try them! :D

Best regards,

Alberto
