### ISSUE TITLE
Problem in trans_diff part

### ISSUE THREAD

**Issue by Jin-1106** [ChiLiubio/microeco#8]
Hi Chi,

Thank you for R package makes analysis easily. Yiwei recommended me to apply this package. I have some problems when analysing my data, but the one in trans_diff part is kind of hard, can you give me some suggestions?

It is ok to generate this t1
metastat analysis at Genus level

> `t1 <- trans_diff$new(dataset = dataset, method = "metastat", group = "Group", metastat_taxa_level = "Genus")`

However, when generating another t1 for LEfSe, there was a problem

> `t1 <- trans_diff$new(dataset = dataset, method = "lefse", group = "Group", alpha = 0.01, lefse_subgroup = NULL)`

And error showed below
![Screenshot from 2021-02-01 16-03-21](https://user-images.githubusercontent.com/77013101/106435226-906b4100-64ad-11eb-92c8-9df911fc7c1d.png)

**Comment by ChiLiubio** [comment]
@Jin-1106 Could you send me the dataset.RData to my email (liuchi0426@126.com)? Otherwise, I cannot repreat your error and find out the solutions. I suggest you save the dataset using command: save(dataset, file = "dataset.RData") . Then I can completely repeat and check this issue. Thanks.

**Comment by Jin-1106** [comment]
Sure, Thanks for great help.

**Comment by ChiLiubio** [comment]
@Jin-1106 Thanks，this is a bug coming from the automatically transformation of data.frame with only one column in dataset$sample_table when performing subsampling. I have fixed it and re-uploaded codes to github. You can reinstall the package from github. Alternatively, if you donnot want to update the package right now, you can add a column (e.g. sampleid) in sample_table of dataset to bypass the bug.

**Comment by Jin-1106** [comment]
@ChiLiubio Thanks for your prompt reply and help me fixing it. Firstly I tried to reinstall microeco, and run smoothly, then I find other tiny bugs in some parts of trans_  can be fixed with adding extra column. And I guess there is few people like me has the only column to do the analysis. 

I have ran through all parts of microeco, Yet, I still has one bug in trans_alpha class, at plot step, I cannot generate significant mark in the figure, see below
`t1$plot_alpha(pair_compare = TRUE, measure = "Chao1")`
![Screenshot from 2021-02-03 15-33-02](https://user-images.githubusercontent.com/77013101/106714911-7493a680-6637-11eb-8953-e6fe2cf1e966.png)

**Comment by ChiLiubio** [comment]
@Jin-1106 This is a weired bug.  I have fixed it and re-uploaded codes to github. It is ok now. You can reinstall the package from github.

**Comment by Jin-1106** [comment]
@ChiLiubio Thanks a lot, it works very well, especially for me as a fresh man to R, it's great help!!!

**Comment by Jin-1106** [comment]
Hi @ChiLiubio 

After you helped me to solve the problem about adding significant star, then another problem came out. Order of all alpha-diversity figures for KW test follows G2, G1, and G3. like following: 
![test](https://user-images.githubusercontent.com/77013101/114302736-ecc98d00-9afc-11eb-96ac-d3f5c72b42fd.png)

How could I reorder the X axis? T ^ T

**Comment by ChiLiubio** [comment]
Hi, @Jin-1106 

The best way I think is to assign factor levels to alpha_data in your trans_alpha object, like the following:
t1$alpha_data$Group %<>% factor(., levels = c("CW", "TW", "IW"))

**Comment by ChiLiubio** [comment]
I will also take into account a parameter in this function to adjust the group order easily.

**Comment by Jin-1106** [comment]
Hi @ChiLiubio 

Assignment works. Thank you. ^_^

Best,
JIN Jing

**Comment by yezi0721** [comment]
> @Jin-1106 This is a weired bug. I have fixed it and re-uploaded codes to github. It is ok now. You can reinstall the package from github.

I still can't make the figure with the significant thing on it. 
![image](https://user-images.githubusercontent.com/65677763/198677116-44658312-695d-41c7-ba2c-5f5becbf3712.png)

**Comment by yezi0721** [comment]
> Hi @ChiLiubio
> the plot_alpha, pair_compare didn't work for me. I don't know how to fix it.

**Comment by AmalHmaiss** [comment]
Hello, thank you for the package, it's really a good tool for begginers with R.
I would like to create a correlation matrix between taxa abundance numbers and environmental conditions. For that, I'm using trans_diff, trans_env and cal_cor. 
The problem is when I try to create a trans_diff object with my data
I get this error message: 
![Capture d’écran 2024-02-16 121312](https://github.com/ChiLiubio/microeco/assets/132219694/674ad152-7557-4b4b-b7d3-b1a0696f96d1)

I thank you in advance for your help,
