### ISSUE TITLE
remove rare taxa before RF

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#83]
Hello, 
I read the paper Jiaxing An et al. (Geoderma 2019). In mat/met section they say:" To avoid the effects of rare taxa, we removed less abundant genera (average abundance<0.01% in all samples)"
Do I need to create a new microtable?
I cant find a straightforward way to do that, would please help me?
thanks a lot for the package , it is very interesting
cheers,
jose

**Comment by ChiLiubio** [comment]
Hi @jamorillo 
Thanks for your good issue! I will add a parameter to control the filtering of rare taxa to make this operation simple in the next update. 
Now to solve this issue, I think you can filter the rare taxa by manipulating your_dataset$taxa_abund$Genus file like the following steps:

```
library(microeco)
library(magrittr)
data(dataset)
dataset$cal_abund()
# clone a new data for the test
d1 <- clone(dataset)
# Now filter the Genus use relative threshold 0.0001 if you want to use genera in rf of trans_diff
d1$taxa_abund$Genus %<>% .[apply(., 1, mean) > 0.0001, ]
# It is ok now to run trans_diff
t1 <- trans_diff$new(dataset = d1, method = "rf", group = "Group", rf_taxa_level = "Genus")
```

Chi

**Comment by jamorillo** [comment]
Dear Chi, 
Thanks a lot. It works very well!
I have a couple of questions related to these RF plots combined with heat maps.
I will open a new issue because it is a different one.
cheers
jose
