### ISSUE TITLE
KW test? 

### ISSUE THREAD

**Issue by alberjo296** [ChiLiubio/microeco#88]
Hi Chi, I have one question:

A significant Kruskal–Wallis test indicates that at least one sample stochastically dominates one other sample. The test does not identify where this stochastic dominance occurs or for how many pairs of groups stochastic dominance obtains. For analyzing the specific sample pairs for stochastic dominance, Dunn's test, pairwise Mann–Whitney tests with Bonferroni correction, or the  Conover–Iman test are sometimes used.

I know Microeco compares alpha diversity with KW but when finding differences which "post-hoc" test is used for multiple comparison/paired comparison?

Thank you,
Alberto

**Comment by ChiLiubio** [comment]
Hi, @alberjo296 
Please see method parameter in cal_diff function of trans_alpha class. I think "anova" may be your required option.

Chi

**Comment by ChiLiubio** [comment]
Hi @alberjo296 

Thanks for your good suggestion! I add a new option "KW_dunn" in method parameter of trans_alpha$cal_diff function for the Dunn's Kruskal-Wallis Multiple Comparisons with dunnTest function of FSA package. I have updated the package in github. If you think it is useful, you can reinstall the package from github and have a try. Please feel free to tell me if you have other issue or idea. Good luck!

Chi

**Comment by alberjo296** [comment]
Thank you very much for your involvement and making this package better every day Chi!!

Will keep in contact :)
