### ISSUE TITLE
trans_Nullmodel MPD, MNTD implementation

### ISSUE THREAD

**Issue by patrickDsal** [ChiLiubio/microeco#89]
Hello,
first of all I want to thank you for the great package and your tremendous effort.
I don't have an issue, rather a question!
I was wondering if there is a possibility to implement MPD/NRI and MNTD/NTI in addition to the beta versions. I have scenarios where I am only interested in plain values of one community. Switching to picante somehow makes my PC crumble, an issue I never had with this package...
Thanks for answering!

**Comment by ChiLiubio** [comment]
Hi @patrickDsal 
Could you give me a toy example to show what is the format or data structure you want to get? or I may donot get your point. The MPD/NRI and MNTD/NTI results are matrix in trans_nullmodel like the result from picante. Generally, they can be transformed to any format you want to use. Thanks.

Chi

**Comment by patrickDsal** [comment]
I apologize for the confusion!
I just wanted to ask if it is possible to implement the ses.mpd/ses.mntd functions from the picante package.
As example: In some of my questions, I am not interested in the comparison of two samples/communities (which defacto betaNRI/NTI calculates) but rather I am interested in specifically the NTI/NRI values of one sample/community.
So the resulting dataframe would not be a distance matrix but would look like this:
SampleID-- NTI-- NRI
S1--------- -0.4---0.6            
S2--------- -0.3---0.7
S3--------- -0.7---1.1
etc...

**Comment by ChiLiubio** [comment]
Good suggestion. I will add NTI/NRI metrics in trans_nullmodel and tell you when it is done.

Best
Chi

**Comment by ChiLiubio** [comment]
Hi @patrickDsal 
I have added cal_NTI and cal_NRI functions in trans_nullmodel. You can use them by reinstalling the package from github. Remember to recreate the trans_nullmodel object to use the new functions.

Chi

**Comment by patrickDsal** [comment]
You're amazing!
Thank you !

Patrick
