### ISSUE TITLE
RDA plot error Error: attempt to apply non-function

### ISSUE THREAD

**Issue by amrvx4** [ChiLiubio/microeco#92]
I was using this function a few days ago and it worked fine, but now its giving me error. I am not sure if its the error on my R only or is something changed with the package?

```
t1 <- trans_env$new(dataset = dataset, add_data = env_data_16S[, 4:11])
t1$cal_ordination(method = "dbRDA", use_measure = "bray")
```
Error: attempt to apply non-function
`t1$cal_ordination(method = "RDA", taxa_level = "Genus")`
Error: attempt to apply non-function

cal_ordination just don't work with RDA anymore. 
I can still plot by using $plot_rda but then I am not able to show Taxa names on the plot.

Any help would be appreciated.
Thanks,

**Comment by ChiLiubio** [comment]
Hi, @amrvx4  Which version of microeco are you using? Please also see the help document of trans_env and try to find the cal_ordination and plot_ordination function. If no those functions, please update your package to 0.7 from CRAN as the tutorial shows.

Best
Chi
