### ISSUE TITLE
Using minimum idenity cutoff of 97% to nearest neighbor - Erreur dans FUN(X[[i]], ...) : 'type' (character) de l'argument incorrect

### ISSUE THREAD

**Issue by zina-R** [ChiLiubio/microeco#93]
Hi Chi,
I am trying to run this Tax4Fun2 test for mu data set also. it looks that the this package is no more available on github. 
i have an error can you help me to solve it plz.
While running this code
```
makeFunctionalPrediction(path_to_otu_table = "E:\\cc\\Desktop\\Tax4Fun\\OTUs.txt", 
                         path_to_reference_data = "E:\\cc\\Desktop\\Tax4Fun\\Tax4Fun2_ReferenceData_v2/", 
                         path_to_temp_folder = "E:\\cc\\Desktop\\Tax4Fun\\prediction/", 
                         database_mode = "Ref100NR", min_identity_to_reference = 0.97, normalize_by_copy_number = T, normalize_pathways = F)

```

- Using minimum idenity cutoff of 97% to nearest neighbor
- Erreur dans FUN(X[[i]], ...) : 'type' (character) de l'argument incorrect

I get this error and i don't konw how to fix it
Thank you,

Zina

**Comment by ChiLiubio** [comment]
Hi, Zina

Why not try the Tax4Fun2 method implemented in trans_func class? It is easier to use and supports more fasta input (from Biostrings or seqinr).

Chi

**Comment by ChiLiubio** [comment]
Hi @zina-R 
I mean it is easier to use trans_func for tax4fun2. Especially, it is easy to repeat any error for me. The results are same according to my testing.

Chi

**Comment by zina-R** [comment]
Hi Chi, 
Can you include the last version of of Silva ( Sliva 138)? because the one used in Tax4Fun2 is the previous version.

Best, 
Zeina

**Comment by zina-R** [comment]
Yes, one of the reference data is Silva. 
with the function below
`buildReferenceData(path_to_working_directory = '', install_suggested_packages = T)`
we get as output blast, KEGG, Silva 132, Ref99NR, Ref100NR..

**Comment by ChiLiubio** [comment]
But the core functions do not refer to SILVA. I guess this is only related with the reference data building, such as reference sequences blast and species function identification.
