### ISSUE TITLE
cal_cor error 

### ISSUE THREAD

**Issue by emihoe** [ChiLiubio/microeco#95]
Hello,
I am trying to follow the tutorial to create a spearman's correlation heatmap of my metadata. I started with a phyloseq object which I converted with _phyloseq2meco_. I have the values I'd like to correlate in the metadata/sample_table already so didn't want to add any environmental data. I used the steps below after I had calculated the abundances.
`meco_dataset$cal_abund()`

# First create trans_diff object as a demonstration
`t2 <- trans_diff$new(dataset = meco_dataset, method = "rf", group = "IL6", rf_taxa_level = "Genus")`

# Then create trans_env object
`t1 <- trans_env$new(dataset = meco_dataset)`

#This step gave me an error message (see below)
```
t1$cal_cor(
  use_data = c("Genus"),
  cor_method = c("spearman"),
  p_adjust_method = "fdr",
  p_adjust_type = c("Type"),
  by_group = NULL,
  use_taxa_num = NULL,
  other_taxa = NULL,
  group_use = NULL,
  group_select = NULL,
  taxa_name_full = TRUE
)
```

**Error in rep("All", nrow(env_data)) : invalid 'times' argument**

Thanks

**Comment by ChiLiubio** [comment]
Hi. You did not select the data from sample table with env_cols parameter. Please use env_cols parameter when creating t1.
Like this:
```
t1 <- trans_env$new(dataset = meco_dataset, env_cols = 3:5)
```

**Comment by emihoe** [comment]
Thank you very much this solved my problem.

Another question will the asterisks for significance of the correlation be automatically added if I only use: `t1$plot_cor()` or do I need to add an extra parameter?

And if I use qualitative values how do I show these correlations as separate entries instead of grouping them under 1 heading?

example: Sex (males and females as the separate values being grouped under 1 entry in the spearman correlation) 

is the easiest solution to add a header for females and males separately to the sample table? 

Thank you, this is a great package!

**Comment by ChiLiubio** [comment]
Hi, @emihoe 
Do you mean do the correlations for different groups separately? twice like males and females? If so, by_group parameter is what you need. Please see the tutorial part (https://chiliubio.github.io/microeco_tutorial/explainable-class.html#trans_env-class) and search by_group. You can find it.

Chi
