### ISSUE TITLE
FlashWeave observations

### ISSUE THREAD

**Issue by tenguzame** [ChiLiubio/microeco#97]
Greetings,
Would it be feasible to add the possibility to set the minimum number of observations through the n_obs_min parameter? I have tried to manually add it to your function, but RStudio then throws off the following bug:
`unexpected '[['
584:             method_envs <- lapply(old_new_enclosing_pairs, [[`

**Comment by ChiLiubio** [comment]
Thanks. I will have a look.

**Comment by ChiLiubio** [comment]
Hi
I have updated the package in github. Please reinstall the package using `devtools::install_github("ChiLiubio/microeco")`
I optimized the parameters input. Please see the help document description. Now PGM_other_para  can accept all the customized parameters. The following is my testing code:
```
library(microeco)
data(dataset)
t1 <- trans_network$new(dataset = dataset, cal_cor = NA, taxa_level = "OTU", filter_thres = 0)
t1$cal_network(network_method = "PGM", PGM_other_para = "alpha=0.01,sensitive=true,heterogeneous=true, n_obs_min=50")
```
Thanks for your suggestion!

Best
Chi

**Comment by tenguzame** [comment]
Worked like a charm! Thank you!
