### ISSUE TITLE
correlations microbial functions vs environmental variables

### ISSUE THREAD

**Issue by jamorillo** [ChiLiubio/microeco#98]
Hello!
I am working a lot (trying to learn) with Microeco package. Thanks again for this great project and this forum!
I wrote the following code (in this case using the dataset example of the package) to obtain figures to visualize correlations of microbial functions vs environmental data. I managed to get those figures using FAPROTAX and TAXAforFUN2.  The two final outputs that I need are what I named in the script “func_corrplot_16S_FAPROTAX” and “func_corrplot_16S_TAXFORFUN2”. This scrip runs also OK with my own data!
But I have some questions about all this:
1)	First at all, the figures look OK, but is this a correct approach? (in case I am missing something).
2)	How can I know the fraction of OTUs/ASVs that has been used to assign a function in these methods?
3)	I see that “pearson” is the default cor_method by default. What is the reason, do you recommend in general Pearson for this kind of correlations over the other options? 
Thanks a lot for shedding light here,
Cheers
Jose

The R code:

rm(list = ls())
set.seed(789)
library(microeco)
library(magrittr)
library(tidyverse)

#################################
#################################

#### clone a new data for the test
dataset_16S_clone1 <- clone(dataset)

#### create trans_func object
dataset_16S_clone1_func <- trans_func$new(dataset_16S_clone1)

####  identify species traits, automatically select database for prokaryotes or fungi
dataset_16S_clone1_func$cal_spe_func(prok_database = "FAPROTAX")

####  calculate the percentages for communities
dataset_16S_clone1_func$cal_spe_func_perc(use_community = TRUE)

####  create trans_env object
transenv_16S <- trans_env$new(dataset = dataset_16S_clone1, 
                              add_data = env_data_16S[, 4:11])

####  correlate the res_spe_func_perc of communities to environmental variables
transenv_16S$cal_cor(add_abund_table = dataset_16S_clone1_func$res_spe_func_perc, 
                     cor_method = "pearson")
####  filter functions that do not have at least one ***
func_corrplot_16S_FAPROTAX <- transenv_16S$plot_cor(filter_feature = c("", "*", "**"),
                                                   pheatmap = TRUE)

#################################
#################################

####  reference files
rep_fasta_path <- system.file("extdata", 
                              "rep.fna", 
                              package="file2meco")
rep_fasta <- seqinr::read.fasta(rep_fasta_path)

####  clone a new data for the test
dataset_16S_clone2 <- clone(dataset)

####  create trans_func object
dataset_16S_clone2_func <- trans_func$new(dataset_16S_clone2)

####  create a directory for result and log files (trivial)
dir.create("R_tables/test_prediction_taxforfun2")

#### Functions 
dataset_16S_clone2_func$cal_tax4fun2(blast_tool_path = "./ncbi-blast-2.5.0+/bin", 
                                     path_to_reference_data = "./Tax4Fun2_ReferenceData_v2",
                                     database_mode = "Ref99NR", 
                                     path_to_temp_folder = "R_tables/test_prediction_taxforfun2",
                                     normalize_by_copy_number = T,
                                     min_identity_to_reference = 97,
                                     use_uproc = T,
                                     num_threads = 2,
                                     normalize_pathways = F
)

####  prepare feature table and metadata
data(Tax4Fun2_KEGG)

####  create a microtable object for pathways
func <- microtable$new(otu_table = dataset_16S_clone2_func$res_tax4fun2_pathway, 
                        tax_table = Tax4Fun2_KEGG$ptw_desc, 
                        sample_table = dataset_16S_clone2_func$sample_table)
func$tidy_dataset()
func$cal_abund()

####  bar plot at Level.2
taxforfun2_abund <- trans_abund$new(func, 
                                    taxrank = "Level.2", 
                                    groupmean = "Group")

taxforfun2_abund$plot_bar(legend_text_italic = FALSE)

####  env data:
trans_env <- trans_env$new(dataset = func, 
                           add_data = env_data_16S[, 4:11])

####  correlations
trans_env$cal_cor(use_data = "Level.2", 
                  cor_method = "pearson",
                  p_adjust_method = "fdr")

####  filter functions that do not have at least one ***
func_corrplot_16S_TAXFORFUN2 <- trans_env$plot_cor(filter_feature = c("", "*", "**"),
                   pheatmap = TRUE)

**Comment by ChiLiubio** [comment]
Hi
1. I found  rep_fasta was not assigned to dataset_16S_clone2, i.e. `dataset$rep_fasta <- rep_fasta`   . Tax4fun2 will use the fasta file inside microtable object.
2. Actually, the result of cal_spe_func_perc() function is the  fraction of OTUs/ASVs when the parameter abundance_weighted = FALSE
3. This is hard to say. Genenally it depends I think. I must say I did not recommend Pearson. I just put it there. I use spearman more in my studies. Sorry about that  :)
Do I miss something?

Best
Chi

**Comment by jamorillo** [comment]
Hello Chi, 
Thanks again for your feedback! Very useful.
Just to clarify:

1. The microtable of the tutorial already contains a rep_fasta. In R:
> dataset
microtable class:
sample_table have 90 rows and 4 columns
otu_table have 404 rows and 90 columns
tax_table have 404 rows and 7 columns
phylo_tree have 404 tips
**rep_fasta** have 404 sequences
So, why do I need to assign again a rep_fasta? I don´t understand this point, but I guess it is important.

2.  How ca I use cal_spe_func_perc() in the case of TaxforFun2? This function depends on the result of cal_spe_func(), that only allows "FAPROTAX" or "NJC19" databases in case or prokaryotic communities. 

3. OK, I understand that Pearson/Spearman depends on the specific dataset etc.
Cheers!
jose

**Comment by ChiLiubio** [comment]
Hi @jamorillo 
1. Tax4fun2 need your representative fasta sequences to find the closed reference species. Please see https://chiliubio.github.io/microeco_tutorial/intro.html#tax4fun2 . The 'dataset' is example data and has a rep_fasta in it for the demo pipeline. You can add your fasta when creating microtable object or give it like `your_microtable_object$rep_fasta <- your_fasta`.
2. Please first try to run the examples in tax4fun2 of  https://chiliubio.github.io/microeco_tutorial/explainable-class.html#trans_func-class . Then you can find each part is separate. cal_spe_func_perc() has nothing with tax4fun2.

Chi

**Comment by jamorillo** [comment]
Hi Chi, 
Thanks! 
Good to confirm that cal_spe_func_perc() has no matter with tax4fun2.
jose
