### ISSUE TITLE
# trans_abund class: can I draw the heatmap which has three facets?

### ISSUE THREAD

**Issue by yezi0721** [ChiLiubio/microeco#99]
Can I draw the heatmap which has three facets?

> t1$plot_bar(others_color = "grey70", facet = "SARS", facet2 = "Building",facet3 = "SARS_Level", xtext_keep = FALSE, legend_text_italic = FALSE, barwidth = 1)
Error in t1$plot_bar(others_color = "grey70", facet = "SARS", facet2 = "Building",  : 
  unused argument (facet3 = "SARS_Level")

**Comment by ChiLiubio** [comment]
Sorry for that the facet3 is not implemented in the current version. I will consider this. Thanks for your suggestion. I will also appreciate your contribution if you can develop this :)

**Comment by yezi0721** [comment]
Haha. I'm fresh in R. Hopefully to see the new version very soon. Thank
you.🤣🤣🤣

**Comment by ChiLiubio** [comment]
Hi. The new version v0.12.0 has been released several days ago. Please update the package and try again. Now You can find the `facet3` parameter in the plot_heatmap and plot_bar function of trans_abund.
